### ISSUE TITLE
Potential extension for assertions within Mock closures

### ISSUE THREAD

**Issue by mwhipple** [spockframework/spock#1001]
This is probably a better fit for the dev-forum but I can't seem to access it :(.

I threw together an extension awhile ago and one of my coworkers just asked if I looked into merging it upstream so I figured it was worth quickly gauging interest (it also seems fine to leave as an external extension).

https://gitlab.com/mwhipple/spock-thenclose-extension

The quick summary cribbed from the README is that it provides an extension `ThenCleanup` which allows definition of methods to be invoked at the end of a `then`: the primary use case of which is to add support into a Specification subclass to allow tests such as:

```groovy
class MySpec extends ThenkfulSpecification {
    def 'some work should call some stuff'() {
        when:
        myCode.doWork('foo')

        then:
        1 * worker.doSomething(*_) >> { args ->
            thenk { assert args[0].content == 'foo' }
            thenk { assert args[0].id }

            myReturnValue
         }
     }
 }
```
where assertions can be defined within the Mock closure but are not evaluated until control is handed back to Spock. More info is in the README (though the extension piece hasn't been doc'ed). Let me know if there's interest and I could look towards making whatever adjustments are needed to make it PR-worthy.

**Comment by leonard84** [comment]
Hi @mwhipple, have you looked at the new reporting features of Spock 1.3? In that version we improved unmatched invocation reporting a lot.

**Comment by leonard84** [comment]
Generally we like to have third-party maintained extensions, I've added yours here https://github.com/spockframework/spock/wiki/Third-Party-Extensions

**Comment by mwhipple** [comment]
👍 thanks, sorry for not responding earlier, I've been outside of Groovy-land.
