### ISSUE TITLE
Spock HTTPS certificate should be valid

### ISSUE THREAD

**Issue by lacasseio** [spockframework/spock#1004]
# Issue description
Browsing to https://spockframework.org/ gives a NET::ERR_CERT_COMMON_NAME_INVALID. I would expect the certificate to be valid.

<img width="725" alt="Screen Shot 2019-06-13 at 6 05 22 PM" src="https://user-images.githubusercontent.com/22181740/59452580-e6d1ca80-8e05-11e9-90c0-05cc51b724a4.png">

The certificate is for `*.github.com`. If I'm not mistaking, the website is hosted on GitHub Page so maybe this blog post could help with solving this issue: https://github.blog/2018-05-01-github-pages-custom-domains-https/

# How to reproduce

Browse to https://spockframework.org/

**Comment by paplorinc** [comment]
Wanted to report the same :)

**Comment by leonard84** [comment]
I can't really do much about it as long as @pniederw still holds the domain.

**Comment by danielrehmann** [comment]
If it is impossible to secure the current domain maybe ditch it. Go full github pages without custom domain and if possible create a redirect from the old domain?

**Comment by Vampire** [comment]
Downgrading to a sub-domain of some service is imho a very bad option.
Especially as you never know how long the service survives.

**Comment by danielrehmann** [comment]
But the current situation is even worse. I do not say it's a good solution, but it's much better than using wrong certificats and having an insecure connection. If you hace a better suggestion feel free to share your thoughts.

**Comment by Vampire** [comment]
Well, it is not insecure, just because the hostname does not match.
The connection is still secure if you continue.
Of course the situation is suboptimal, but downgrading to a subdomain of someone elses domain that will be gone in 2 years is non-sense.
Either get it fixed up (there are people currently trying to reach Peter) or settle on a new domain.
And no, I don't have better suggestions that those that are already present and I just repeated. I just voted against a suggestion I think makes absolutely no sense.

**Comment by danielrehmann** [comment]
I was not talking about a random subdomain service i was talking about github pages that still have a professional vibe and can be used with a custom domain as soon as it is available.

**Comment by danielrehmann** [comment]
Quick lookup showed that spocktest.org is also available. Moving to a new domain might ve a different option.

**Comment by Vampire** [comment]
Yay, I finally made contact, now hopefully all will become good :-)

**Comment by JLLeitschuh** [comment]
Still broken

**Comment by Vampire** [comment]
Of course, I said I just made contact and said all will become good, not all is good, neither did I close the ticket. ;-)

**Comment by JLLeitschuh** [comment]
AH! Makes sense! Thanks!!

**Comment by leonard84** [comment]
It works now.
