### ISSUE TITLE
NoClassDefFoundError for transitive runtime dependecnies

### ISSUE THREAD

**Issue by pmendelski** [spockframework/spock#1009]
# Issue description
When groovy/spock tests are compiled NoClassDefFoundError is thrown. Groovy compiler does not see transitive dependencies from main runtime scope. I'm not sure if this is a problem of groovy or spock framework.

# How to reproduce
- Download [sample project](https://github.com/pmendelski/bug-sample-groovy-runtime-deps-inheritance)
- Run: `./gradlew compileTestGroovy`

# Additional Environment information

## Java/JDK
`java -version`
```
java -version
openjdk version "12" 2019-03-19
OpenJDK Runtime Environment AdoptOpenJDK (build 12+33)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12+33, mixed mode, sharing)
```
## Groovy version
`2.5` - from dependencies

## Gradle
gradle 5.5.1

## Operating System
Ubuntu 18.04

**Comment by szpak** [comment]
There is something wrong with the transitive dependencies in sherlock itself. While `sherlock-inmem-common` seems to be a transitive dependency of `sherlock-inmem-reactive` looking at the `gw dependencies` output, it is itself reported as a `runtime variant` which isn't available at compilation time:
```
$ gw dependencyInsight --dependency sherlock-inmem-common --configuration testCompile

> Task :dependencyInsight
com.coditory.sherlock:sherlock-inmem-common:0.3.0
   variant "runtime" [     <----- Why?
      org.gradle.status   = release (not requested)
      org.gradle.usage    = java-runtime (not requested)
      org.gradle.category = library (not requested)
   ]

com.coditory.sherlock:sherlock-inmem-common:0.3.0
+--- com.coditory.sherlock:sherlock-inmem-reactive:0.3.0
|    \--- testCompile
\--- com.coditory.sherlock:sherlock-inmem-sync:0.3.0
     \--- com.coditory.sherlock:sherlock-inmem-reactive:0.3.0 (*)

(*) - dependencies omitted (listed previously)
```
When explicitly added `sherlock-inmem-common` as a compile dependency, an the error changes:
> Caused by: java.lang.NoClassDefFoundError: com.coditory.sherlock.LockDuration
(another transitive dependency missing at compilation time)

It's too late for me to investigate it further today, but maybe it will help you to analyze your upstream project.

**Comment by pmendelski** [comment]
Thanks for such a fast answer.

I don't want `sherlock-inmem-common` to be exposed to the clients of `sherlock-inmem-reactive` library so I marked it as [an implementation dependency](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation) in [`gradle.build`](https://github.com/coditory/sherlock-distributed-lock/blob/release-0.3.0/inmem/reactive/build.gradle#L6). Then
`sherlock-inmem-common` was mapped from gradle `implementation` dependency to maven `runtime` dependency ([pom](https://oss.sonatype.org/service/local/repositories/releases/content/com/coditory/sherlock/sherlock-inmem-reactive/0.3.0/sherlock-inmem-reactive-0.3.0.pom)) by gradle [maven-publish plugin](https://github.com/coditory/sherlock-distributed-lock/blob/9494694c61979accdf088d70ed7070bb6fbfb72f/gradle/publish-project.gradle#L77).

Documentation says it suppose to be the correct configuration and it works with java tests. I'm pretty sure it's a problem of my configuration or groovy compiler. Any hint would be very appreciated.

Currently I changed dependency scopes in my library to use `compile` and it solved the issue but I'm still trying to find the root cause. 

Thanks for you time.

**Comment by pmendelski** [comment]
I believe that this issue is unfixable. Details: https://github.com/gradle/gradle/issues/10265

**Comment by pmendelski** [comment]
...or maybe it could be fixed by limiting some Spock introspection (see https://github.com/gradle/gradle/issues/10265), or at least don't cause an error if introspected class does not exist.

**Comment by JLLeitschuh** [comment]
> don't cause an error if introspected class does not exist

This sounds like the right choice here.

**Comment by leonard84** [comment]
@pmendelski is this really caused by Spock AST Transformation, or the groovy compiler itself? If it is the latter, I don't think that we can do anything.

**Comment by pmendelski** [comment]
@leonard84 I'm pretty sure it's Spock.

I've created 3 branches:
- [java-junit-example](https://github.com/pmendelski/bug-sample-groovy-runtime-deps-inheritance/tree/java-junit-example) - Build passes
- [groovy-junit-example](https://github.com/pmendelski/bug-sample-groovy-runtime-deps-inheritance/tree/groovy-junit-example) - Build passes
- [groovy-spock-example](https://github.com/pmendelski/bug-sample-groovy-runtime-deps-inheritance/tree/groovy-spock-example) - Build fails

**Comment by pmendelski** [comment]
Good news, it works with spock 2 with groovy 3 (tested on `2.0-M2-groovy-3.0`).
Branch: (groovy-spock2-example)[https://github.com/pmendelski/bug-sample-groovy-runtime-deps-inheritance/tree/groovy-spock2-example]
