### ISSUE TITLE
Main page subdomains links are not accessible

### ISSUE THREAD

**Issue by tikal** [spockframework/spock#1019]
http://docs.spockframework.org/ as well as others subdomains links from the http://spockframework.org/ are not loading.

**Comment by rtretyak** [comment]
works fine for me ¯\_(ツ)_/¯

**Comment by namhokim** [comment]
About 15 hours ago, I couldn't load the document, too.
But now it seems to recover the normal.

**Comment by tikal** [comment]
yeah, seems intermittent, works fine for me now too.
