### ISSUE TITLE
pipe-characters in value of data table cell

### ISSUE THREAD

**Issue by Vampire** [spockframework/spock#1024]
I'd like to be able to do something like the following:

```groovy
        where:
            testee                                                | _
            restrictionChainElement                               | _
            restrictionChainElement & restrictionTwo.getClass()   | _
            (restrictionChainElement | restrictionTwo.getClass()) | _
            restrictionChainElement.negate()                      | _
```

where in the next to last line the pipe character is part of the actual cell value, calculating an _or_.

**Comment by rtretyak** [comment]
Not sure if I understood correctly, but I guess you can do sth like
```
        where:
        var                      | _
        {it -> false | false }() | _
        {it -> true | false }()  | _
```

**Comment by Vampire** [comment]
Urgh, yes this works, thanks, but I think this is very ugly.
Besides that IntelliJ cannot handle this syntax properly.
As it is actually an `or` method in this case, I just use the `or` method, but it would be nice if for example parenthese would work like suggested in my original post.

**Comment by Vampire** [comment]
Hm, the parentheses suggestion cannot work.
After the Groovy parser did his work, `(false | true) | _` and `false | true | _` are exactly the same, so there is no way to differentiate.

There are also other quirky situations, like for example `true && true  | _` which due to operator precedence is interpreted like `true && (true  | _)` and so is not recognized as table row.
This can acutally be "fixed" by `(true && true ) | _`.

But I'd like to suggest a more dynamic approach to what table column separators can be.
Currently it is `|` or `||` in arbitrary mixture.
What I like to suggest is similar to what the `sed` utility provides if you know it.
The header row of a table, defines which column separators are valid for this table.

There are actually 32 binary operators that could be used in a way the Groovy parser is happy.
I'd suggest to support all of them and it is the users responsibility to pick the one he likes most for his current table.
Of course we still want the opportuntiy to visually separate input columns from output columns, so I suggest to split these 32 operators into 10 groups.
The first operator found in the header row will define the group that is effective for the current table.
Within this group any operator can be used as separator in the current table.

As soon as a row with a binary operator that is not in the current group is observed, a new table starts with that operator group.

You can then e. g. have tables like:
```groovy
a / b /= c
1 / 2 /= 3
4 / 5 /= 6

d | e || f
1 | 2 || 3
4 | 5 || 6
```

The groups I'd suggest are:
```java
    Types.FIND_REGEX                   // =~
    Types.MATCH_REGEX                  // ==~
    Types.COMPARE_NOT_EQUAL            // !=
    Types.COMPARE_IDENTICAL            // ===
    Types.COMPARE_NOT_IDENTICAL        // !==
    Types.COMPARE_EQUAL                // ==
    Types.COMPARE_TO                   // <=>

    Types.PLUS                         // +
    Types.PLUS_EQUAL                   // +=

    Types.MINUS                        // -
    Types.MINUS_EQUAL                  // -=

    Types.MOD                          // %
    Types.MOD_EQUAL                    // %=

    Types.DIVIDE                       // /
    Types.DIVIDE_EQUAL                 // /=

    Types.MULTIPLY                     // *
    Types.POWER                        // **
    Types.MULTIPLY_EQUAL               // *=
    Types.POWER_EQUAL                  // **=

    Types.RIGHT_SHIFT                  // >>
    Types.RIGHT_SHIFT_UNSIGNED         // >>>
    Types.LEFT_SHIFT_EQUAL             // <<=
    Types.RIGHT_SHIFT_EQUAL            // >>=
    Types.RIGHT_SHIFT_UNSIGNED_EQUAL   // >>>=

    Types.BITWISE_AND                  // &
    Types.LOGICAL_AND                  // &&
    Types.BITWISE_AND_EQUAL            // &=

    Types.BITWISE_XOR                  // ^
    Types.BITWISE_XOR_EQUAL            // ^=

    Types.BITWISE_OR                   // |
    Types.LOGICAL_OR                   // ||
    Types.BITWISE_OR_EQUAL             // |=
```

The groups are open for discussion of course.

The code for implementing this is actually pretty easy and straightforward. (It is basically done already).

What do you think about this suggestion @leonard84?

**Comment by leonard84** [comment]
I don't think that is necessarily a good idea, sure it might help in some edge cases, but it makes the code harder to parse for users. As a users you have to know that
```
where:
a + b
1 + 2
```
is a data table instead of some weird useless calculation, or a more extreme example
```
where:
a + b ^ c * d >> e
1 + 2 ^ 3 * 4 >> 5
```

I agree that it is suboptimal, that the parentheses are not available in the semantic_analysis phase anymore.

However, I think that we can use the header to determine whether we use 
```
Types.BITWISE_OR                 // |
Types.LOGICAL_OR                 // ||
```
as separators, this would fix you problem right, then you only have a problem if you need both `|` and `||` in your values?

**Comment by Vampire** [comment]
The sense of supporting `|` and `||` is to have a ways to separate input columns from output columns for example.
There are even tests that you can freely mix those two how you want.
So I'm not sure whether it is a good idea to quit supporting this.

I'd say it is in the responsibility of the user to use an operator that is readable enough for his data table.
If he want to obfuscate his tests, it is his decision.

And it was pretty easy to just support any binary operator with which you can build Groovy-parser valid expression statements.
If you don't like the user having this freedom, how about at least adding the possibility for using `/` instead of a mixture of `|` and `||`? With that the user has less freedom than with my suggestion, but he should probably be able to tackle most edge cases and it looks nearly like a column line too, just a bit askew.

**Comment by leonard84** [comment]
As I understood this suggestion, is that you use the layout of the header row to identify the separators for the data rows. So if you'd exclusively used `||`  in the header, you could ignore any `|` in the data rows and vice-versa.

> I'd say it is in the responsibility of the user to use an operator that is readable enough for his data table.
> If he want to obfuscate his tests, it is his decision.

One of the strengths of Spock is that it provides certain restrictions, that in turn structure your tests and make them look similar and easier to read, e.g. the block labels. Relaxing those restrictions can lead to harder to understand tests. Sometimes it is better to not allow everyone to shoot themselves into the foot, or more precisely the poor guy that has to maintain the tests after the other guy left.

I also thought about allowing `/`, since it is visually similar to `|`, but you might run into a problem with [slashy-strings](https://groovy-lang.org/syntax.html#_slashy_string).

**Comment by Vampire** [comment]
I don't think we run into an issue with slashy strings.
Except there are expressions I didn't think of.
We do not split on slashes or pipes.
We split nested binary expressions.
So the slash in a slashy string is different from the division operator which is the separator.
I actually just tried and even this works fine (even if it breaks the highlighting in Groovy Console, the highlighting in IntelliJ works better):
```groovy
    testee          / a   / b
    true            / /a/ / /b/
    (true && true)  / /a/ / /b/
    (false || true) / /a/ / /b/
    !false          / /a/ / /b/
```

You got my suggestion slightly wrong I think.
I didn't want to break existing code for no reason.
And this is perfectly finde currently:
```groovy
a |  b |  c
1 || 2 || 3
```
or
```groovy
a |  b || c
1 || 2 |  3
```
There are even tests for those mixed cases.

What my suggestion and implementation does is, it looks for the first binary operator found in the header line (depends on operator precedence and evaluation order), that is the top-most binary expression. If this operator is a `|` or `||`, then those two are allowed freely mixed in the table.
The same for the other groups I wrote above.

If you do not want to allow anything else besides `/` additionally, that's ok, but I would stay to my suggestion to not allow to mix `/` with the other two. Because if you do not allow mixing, then you can actually use `|` or `||` in the cell. You will still need to to put them in parentheses due to higher precedence of `/`, but still better to use `(false | true) / _` than having to use `{ false | true }() | _`. For other edge cases there is still the closure-trick as the closure has the highest precedence.

What do you think @leonard84? If you are all against it and just want to support `/` additionally, that will not solve this issue here in any way, but it then also is not solvable and we can close it. Would also be acceptable I guess if you insist. :-)

Another (additional) idea could be to deviate a bit from the "row is a binary expression" paradigm. Paul suggested as idea to support `;` as separator, so something like this should probably be possible with grouping the expressions where last line of previous expression is the same as first line of next expression:
```groovy
    testee          ; a   ; b
    true            ; /a/ ; /b/
    true && true    ; /a/ ; /b/
    false | true    ; /a/ ; /b/
    !false          ; /a/ ; /b/
```

**Comment by Vampire** [comment]
I think I actually like the `;` idea, you can also use any amount of successive semicolons to seperate inputs from outputs or multiple sections:
```groovy
    testee          ; a    ;; b    ;;; c
    true            ; /a1/ ;; /b1/ ;;; /c1/
    true && true    ; /a2/ ;; /b2/ ;;; /c2/
    false || true   ; /a3/ ;; /b3/ ;;; /c3/
    !false          ; /a4/ ;; /b4/ ;;; /c4/
```

**Comment by Vampire** [comment]
Yep, this works great.
And in combination with my data table separator PR you can even draw outer lines like
```groovy
    where:
    ___________________________________________
    ; testee          ; a    ;; b    ;;; c    ;
    ; true            ; /a1/ ;; /b1/ ;;; /c1/ ;
    ; true && true    ; /a2/ ;; /b2/ ;;; /c2/ ;
    ; false || true   ; /a3/ ;; /b3/ ;;; /c3/ ;
    ; !false          ; /a4/ ;; /b4/ ;;; /c4/ ;
    ___________________________________________
```

**Comment by Vampire** [comment]
So as you don't like all binary operators to be supported, the questions left basically are:
- support `/` or not
- if yes, mixed with `|` and `||` or exclusively
- support `;` or not
- if yes, mixed with `|` and `||` or exclusively

Actually now, that I played with `;`, I think I don't quite like the `/` anymore.
It has a pretty high precedence (level 4 of 15 where 1 is highest), so if you want to use any of the lower precedence operators in a cell, you need to use parentheses.

`;` is so-to-say on level 16, it has lower precedence than any operator, so you can have any possible statement in the cells as it is the native statement separator in Groovy, besides a linebreak.
And as the parser just swallows multiple semicolons, the user can use a line of arbitrary thickness if he wants and even have a left and right border. (As long as any other statement is between the header row and the label, as the label cannot be stand-alone, thus the data table separator from my other PR comes in handy)

So I'd tend to say `/` no, as it has too high precedence,
`;` yes, it is perfectly suited for what we need and also looks similar to a straight line,
`;` and `|` / `||` should be separate, a table should either use the one or the other, but not be able to mix. This makes things easier and allows to use `|` or `||` in tables that use `;` as separator.

**Comment by leonard84** [comment]
Using `;` as an alternative to `|` seems like a good solution to me, what do others think @spockframework/supporter  ?

**Comment by szpak** [comment]
I haven't encountered a case where I needed to use `|`, but as `@Vampire` pointed out it is possible. I personally like an ability to use both `|` and `||` as separators and I would like to keep it. For cases with `|` (or `||`) in data tables, an option to use `;`/`;;` explicitly as separators looks sensible for me.

Mixing `;` with `|` or `||` as separators in one table would probably complicate the implementation (and make it more problematic to use `|` in input date and `;` as a separator), so I would not go that way. Especially that I don't know why people would like to mix it (as separators in one table).

**Comment by masooh** [comment]
`;` also looks good for me. Especially the low precedence convinced me. Apart from that I like the optic better than `/`. `!` would also be nice, but has a high precedence. I would not support a mixed mode.
