### ISSUE TITLE
Spock grails should be mentioned in the documentation

### ISSUE THREAD

**Issue by anshbansal** [spockframework/spock#103]
The spock grails support should be mentioned somewhere in the documentation. It is still relevant, right?

https://github.com/spockframework/spock-grails

**Comment by anshbansal** [comment]
I also raised an issue in https://github.com/grails/grails-doc/issues/269

**Comment by pniederw** [comment]
It's only relevant for Grails 2.2 and earlier. Grails 2.3 and later have Spock support built in.
