### ISSUE TITLE
What's the meaning of ">> _" in an interaction

### ISSUE THREAD

**Issue by Vampire** [spockframework/spock#1035]
The only reference I found is in the "valid but senseless" example.
I would have thought it replaces "something" from the mocked method.
But at least for a `Spy` it does call the real method instead of returning "something".
Does that mean "return the default value"? Which for a spy would of course be the result of the real method.
But what sense does it have then if it is equivalent to just omitting it?
At least it should be documented somewhere.

**Comment by leonard84** [comment]
Are you referring to 
> Note | Although `(..) * .(*_) >> _` is a valid interaction declaration, it is neither good style nor particularly useful.

It is just listed for completeness, as it is the ultimate wildcard expression, but not as a suggestion that `>> _` should be used anywhere.

**Comment by Vampire** [comment]
That's the example I referenced, yes.
But I'm not talking about the whole expression, just about the last part.
My question is, if it is syntactically valid, it should have some defined meaning / behavior that is meaningful in at least one use-case.
If no use-case exists, where this is meaningful and / or the behavior is not defined anyway, imho it would be a syntax error.

**Comment by leonard84** [comment]
`_`  is just an instance of `Wildcard`, with the latter having some special meaning in specific places. If we would make it illegal what about a method that should return an instance of it. Or if you return it in a closure `>> { _ }` and so on?

**Comment by Vampire** [comment]
I didn't suggest to make the wildcard itself illegal, it is useful in various places.
I asked about the specific meaning of `>> _` or if there is none, forbidding it.
But you can of course also say no and close this issue. :-)

**Comment by Vampire** [comment]
It seems `>> _` is identical to `>> null`, is that corret?
I had a method with `Object` return type.
I wanted to return something non-null and so tried to use `>> _`, but that returned `null` it seems.
After I changed it to `>> this`, it returned the test instance properly.
So if this is true and always the case, I'd still suggest to forbid `>> _` as it is not intuitive and the same as `>> null` if this is really the case.

**Comment by leonard84** [comment]
Well we have `org.spockframework.mock.response.WildcardResponseGenerator` which is used here.

Javadoc:
> "Returns the default value for the invoked method's return type."

`return invocation.getMockObject().getDefaultResponse().respond(invocation);`

**Comment by leonard84** [comment]
We could change it to always use the `Stub` behavior `org.spockframework.mock.EmptyOrDummyResponse` instead of whatever is the default. That would be a potentially breaking change.

**Comment by Vampire** [comment]
Omg, I'm dumb.
I even wrote in my initial comment, that it seems to return the default value.
So I think I'm back to my original question and suggestion.

As it returns the default response, which is the default behaviour, what sense does it have?
Is there at least one single case where adding it is different from omitting it currently?

If the answer is yes, then my request is to document its behavior and where it is significant.

If the answer is no, then my suggestion is to either change the meaning as you suggested as "wildcard" is more intuitive to mean "something", so that it actually has a valid use-case, or to forbid it, throwing an error if observed as it just makes the spec harder readable imho as it is not intuitively clear that it does the same as omitting it.

In either case this would be a potentially breaking change. (except if only doc is updated of course)

**Comment by masooh** [comment]
My preferred solution is that if you define `>> _` for a mock it has a default response like a stub: `EmptyOrDummyResponse`. In that case the following tests would be green:

```groovy
def "null mock response"() {
    when:
    def result = mock.string()

    then:
    result == null

    and:
    1 * mock.string()
}

def "default mock response"() {
    when:
    def result = mock.string()

    then:
    result == ""

    and:
    1 * mock.string() >> _
}
```
