### ISSUE TITLE
Spock datatable just accepting integers in Speck inputs

### ISSUE THREAD

**Issue by jpsalvadorm63** [spockframework/spock#1038]
># Spock datatable just accepting integers in Speck inputs

Hi, I'm working in migrating a large application from Grails 3.3 to Grails 4.

On of the issues we got is related to Spock, the functionality we used in Grails 3.39 seems to be missing: *whe using a datatable to represent the specs, the column for the inputs, seems to be accepting jus integers values*

In the below code just the first line of the specks is passing the text. No the next two, as the spock is transforming to integer befor passing it to `Math.round(value)`

    import spock.lang.*

    @Unroll
     void 'test to demostrate Spock is just accepting integer in datatable column value'() {
       expect:
           Math.round(value) == result   
       where:
       value     | result
       1234      | 1234
       4321.56d  | 4322d
       1111.56f  | 1112d
     }

I was noty getting this issue in version 3.3 of Grails.

Thanks in advance for attend this issue

Juan

**UPDATE**:

*The change of behavior described, actually occurs when the test based on datatable is preceded by a test that includes throwing an excetion*

**WORK AROUND**:

Move the test that includes the exception throwing to be the last test.

**Comment by virtualdogbert** [comment]
This would be going from Spock 1.1 to 1.2.

**Comment by leonard84** [comment]
Just a hint, use typed arguments to avoid typing issues.

```groovy
  @Unroll
    def 'data driven test'(double value, int result) {
        expect:
            Math.round(value) == result

        where:
            value    | result
            1234     | 1234
            4321.56d | 4322d
            1111.56f | 1112d
    }
```
