### ISSUE TITLE
compareTo operator cannot be used for stubbing

### ISSUE THREAD

**Issue by Vampire** [spockframework/spock#1039]
With this:

```groovy
def setup() {
    (higherRole <=> lowerRole) >> 1
    lowerRole.compareTo(higherRole) >> -1
}
```

the second line is properly stubbed, but the first line is not.
Functional these are equal as the comparison operator is implemented by calling the `compareTo` method.
Would be nice if the operator syntax would also work, especially as CodeNarc advises to use it rightfully.

**Comment by Vampire** [comment]
I'm unsure whether we want this @leonard84.

While thinking about it, the question is where to draw the line.
`a ** b` could stub `a.power(b)`.
`a + b` could stub `a.plus(b)`.
`a in b` could stub `b.isCase(a)`.
`a[b]` could stub `a.getAt(b)` or `a.putAt(b)` depending on context.
...
Even some unary expressions could be used.
`~a` could stub `a.bitwiseNegate()`.
`-a` could stub `a.negative()`.
`--a` could stub `a.previous`.
...

Maybe it would be better to not do this magic?
Especially as I'm not aware of some Groovy functionality that can translate the binary or unary expression to a method call expression.

What do you think?

**Comment by leonard84** [comment]
I think it would be better to require the users to always use the operator method name, i.e., `compareTo` instead of the symbol `<=>`.
