### ISSUE TITLE
Stubbing a property getter only works with "it."

### ISSUE THREAD

**Issue by Vampire** [spockframework/spock#1040]
Having this:

```java
Guild server = Stub {
    it.roles >> [higherRole, lowerRole]
    getRoleById(higherRoleId) >> higherRole
}
```

works properly.
But removing the `it.` complains that the test class has no `roles` property.
So currently it works without qualifier for explicit methods, but not for property getters in property syntax.

**Comment by leonard84** [comment]
Yes it is a current not so well documented limitation, either you have to use `it.prop` or just `getProp()`. I thought it was documented, but I couldn't find it in the user quide. 

If you are up to it, you can look into enhancing the AST rewriter.
