### ISSUE TITLE
Interrupted state of main thread not cleared after test causes unrelated tests to fail 

### ISSUE THREAD

**Issue by Schwaller** [spockframework/spock#1061]
# Issue description
If a tests sets the java.lang.Thread.currentThread().interrupted() flag, this flag is not cleared  after the test (on the main thread). This can cause issues in other tests, namely spring boot tests for example that are really hard to track down. It would be great if spock would call:

Thread.currentThread().isInterrupted(true);  // on main thread

to avoid this issue. 

JUnit solved this here: https://github.com/junit-team/junit4/issues/1365

# How to reproduce

class InterruptIssueSpec extends Specification {

    def "setting state"() {
        Thread.currentThread().interrupt()
        expect:
        true
    }

    def "checking state"() {
        Thread.sleep(4000)
        expect:
        Thread.currentThread().isInterrupted() == false
    }

}

## Java/JDK
11

## Groovy version
spock-core:1.3-groovy-2.5

**Comment by leonard84** [comment]
It was fixed for the JUnit Platform in https://github.com/junit-team/junit5/issues/1688 and since Spock 2.0 implements `HierarchicalTestEngine` its fixed for us as well.
