### ISSUE TITLE
Can blocks inside `with` be split by AST for reporting?

### ISSUE THREAD

**Issue by treyturner** [spockframework/spock#1065]
Is it possible for Spock blocks inside a Groovy [`with(Closure)`](http://docs.groovy-lang.org/latest/html/groovy-jdk/java/lang/Object.html#with(groovy.lang.Closure)) method to be split up for the purposes of reporting? It would be nice to not need to terminate a closure only to reopen it in the next block, and still have the blocks correctly separated in the report.

In an ideal state, this would correctly apply even to nested `with` blocks.

I initially requested this feature in `spock-reports`, but [was redirected](https://github.com/renatoathaydes/spock-reports/issues/185#issuecomment-569147255) here since they rely on Spock's ASTs to provide the parsed blocks.

Thank you for Spock and your consideration!

# How to reproduce
Generate a BDD report from a spec similar to this Geb example:
```
    def "The 'Toolbar' should validate"() {
        given: "the user is at the 'Inventory Management' screen"
        at InventoryManagement

        with (toolbar) {
            expect: "the 'Toolbar' to validate"
            header.isDisplayed()

            and: "the 'Toggle Group' is displayed"
            toggleGroup.isDisplayed()

            and: "the 'Filter Toggle' to validate"
            filterToggle.isDisplayed()
            filterToggle.isEnabled()
        }
    }
```

The resulting report won't separate blocks inside the `with` block:
![image](https://user-images.githubusercontent.com/1878152/71490205-4a927280-27ef-11ea-8b88-0bebfb77667d.png)

# Additional Environment information

Java 1.8.0_231
Groovy 2.5.8
Gradle 5.6.4
Windows 10 1809
IntelliJ IDEA Community 2019.3
Dependencies:
```
compile 'org.spockframework:spock-core:1.3-groovy-2.5'
compile('com.athaydes:spock-reports:1.6.2') { transitive = false }
```

**Comment by leonard84** [comment]
Sorry, but this is not possible without extensive rework and does not have enough gain IMO.
