### ISSUE TITLE
Spock 2.0-M1 - @Tag annotation from JUnit5 requires @Test annotation to work??

### ISSUE THREAD

**Issue by andrew908b** [spockframework/spock#1069]
# Issue description
When Spock test method has only `@Tag` annotation (doesn't have `@Test` annotation) then the method is not taken into account when tests are executed with `includeTags` option.

# How to reproduce

- Create the following Spec:
```
import org.junit.jupiter.api.Tag
import org.junit.jupiter.api.Test
import spock.lang.Specification

class TagsContainingSpec extends Specification {

    @Tag('smoke')
    def "should test something 1"() {
        expect:
        1 == 1
    }

    @Test
    @Tag('smoke')
    def "should test something 2"() {
        expect:
        2 == 2
    }
}
```

build.gradle:
```
plugins {
    id 'groovy'
}

repositories {
    jcenter()
}

dependencies {
    testImplementation 'org.spockframework:spock-core:2.0-M1-groovy-2.5'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.5.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.5.1'
}

test {
    useJUnitPlatform {
        includeTags 'smoke'
    }
}
```

- Run tests:
`./gradlew test`

Expected behaviour:
Both test methods from `TagsContainingSpec` executed

Actual behaviour:
Only "should test something 2" method executed

## Java/JDK
`openjdk version "11.0.2"`

### Gradle
`6.0.1`

**Comment by leonard84** [comment]
JUnit Platform and JUnit Jupiter are two separate things. Spock uses the Platform only and provides its own engine implementation for it. Jupiter is another engine with its own system and they are not supposed to be used together in the same file. You can use both of them for separate tests without problem, but don't mix them.

**Comment by andrew908b** [comment]
@leonard84 - thank you for the explanation. I just hoped Spock-2.0 will provide more friendly way of tagging test cases.

**Comment by leonard84** [comment]
@andrew908b it does have a way http://spockframework.org/spock/docs/1.3/all_in_one.html#_include_and_exclude

**Comment by adrian-skybaker** [comment]
It would be great if `@Tag` was respected, since it has tooling support (eg you can specify tags using the JUnit 5 console launcher, or the gradle test task).

**Comment by iggymoran** [comment]
@leonard84 - Sorry if this is not the right forum for this, but how us Spock meant to integrate with (for example) the `groups` feature of the Maven Surefire Plugin? Specifically if you're application is based on a parent POM which you cannot modify?
