### ISSUE TITLE
Placeholders in test name should be automatically resolved in Spock 2

### ISSUE THREAD

**Issue by szpak** [spockframework/spock#1079]
# Issue description
In Spock 2 parameterized tests are automatically "unrolled". Therefore, it seems to be intuitive to automatically resolved placeholders put in a test name.

# How to reproduce
```
def "should resolve placeholder in test name by default (#text)"() {
    expect:
        text.length() == lenght
    where:
        text | lenght
        "dog" | 3
        "tiger" | 5
}
```
generates:
![image](https://user-images.githubusercontent.com/148013/72609582-a00cfb80-3925-11ea-9c55-b6fed6c91dce.png)

It is required to use `@Unroll` implicitly to resolve placeholders.

## Link to a gist or similar (optional)
Slightly related regarding the context - #1070 (but for Spock 1.3 and probably with different implementation reason).

# Additional Environment information
OpenJDK 11.0.2, spock-core:2.0-M1-groovy-2.5, Idea 2019.3.2.

**Comment by Vampire** [comment]
This should be fixed now
