### ISSUE TITLE
Please provide data variables in PreconditionContext

### ISSUE THREAD

**Issue by Vampire** [spockframework/spock#1085]
I have a test with `where`-block where one of the tests fails on Java 8 due to a JRE bug that is fixed on Java 9.
It would be great if I could ignore only the iteration that fails on Java 8 on Java 8, something like `@IgnoreIf({ jvm.java8 && (userId == 'foo') })` where `userId` is the data variable and `'foo'` its value for the bug-triggering case.

While reporting this, I observed that this also implies a request to check `IgnoreIf` per iteration, not per feature. :-)

**Comment by Vampire** [comment]
Of course `assume...` can be used for this too, but it would imho cleaner to be able to specify it as annotation, especially in cases where one would use `PendingFeatureIf` once it is added instead of `IgnoreIf` :-)

**Comment by leonard84** [comment]
So how would you handle the cases where you don't want to execute the `where`-blocks at all?

**Comment by Vampire** [comment]
Uhm, good question, didn't think about that.
How about checking whether the closure references a data variable and if not, apply it to the whole feature?
As Groovy code is pretty dynamic this can probably not be done upfront, but the names of the data variables are known, aren't they?
So you could evaluate the closure for the feature with dummy properties for the data variables, if one of these gets used during evaluation, you know data variables are used and check the closure per iteration instead. If none of the dummy variables was used, no data variable is used and the closures result can be effective on the feature right away.

**Comment by leonard84** [comment]
I'm not really sure I like this magic, it might be simpler to just have a dedicated extension. Or you could just throw a `TestAbortedException` (Spock 2.0) yourself. This maybe not as fancy but I don't know how often this feature would get used compared to the added complexity of the extension code.

**Comment by Vampire** [comment]
Well, it is not that much more complexity I'd say.
I gave it a quick shot that you can see at #1094.

**Comment by Vampire** [comment]
I pulled out the common logic of `@IgnoreIf`, `@PendingFeatureIf` and `@Requires` into a common base class that got the extended logic.
