### ISSUE TITLE
Docs issue about mocks, CGLIB and JDK 8?

### ISSUE THREAD

**Issue by wujek-srujek** [spockframework/spock#110]
The documentation (in 'Interaction Based Testing') says:

"Java 8 is only supported from CGLIB 3.2 onwards, which has not been released as of 2015-03-02."

But, I am on JDK8, my target is Java 8, have cglib 3.1 in my runtime classpath and mocking Java classes with Spock just works fine, it seems. What is not supposed to work?

**Comment by siordache** [comment]
In many situations, Spock on Java 8 still works fine even with CGLIB 3.1. But this is not always the case. One example is when mocking classes with [bridge methods](https://docs.oracle.com/javase/tutorial/java/generics/bridgeMethods.html#bridgeMethods).

[This gist](https://gist.github.com/siordache/a6f5b05d5c819cd825b6) shows a specification that works fine with Java 6 and CGLIB 3.1 or with Java 8 and CGLIB 3.2, but fails for Java 8 and CGLIB 3.1.

**Comment by leonard84** [comment]
@wujek-srujek see #116 for an example
