### ISSUE TITLE
Enhance strict mocking output to include feedback from code argument constraints

### ISSUE THREAD

**Issue by Brickster** [spockframework/spock#1117]
# Issue description
I often use strict mocking to ensure nothing is missed when writing a test. These same tests often take advantage of 1.3's new implicit assertions within code constraints. However, strict mocking doesn't print the feedback. Limiting its usefulness.

It would be nice to get the best of both features.

# How to reproduce

```
package com.something.service

import spock.lang.Specification

class NoOtherMocksSpec extends Specification {

  Service service = new Service(repository: Mock(Repository))

  void 'test'() {

    given:
    List<String> list = ['a']

    when:
    List<String> actual = service.foo(list)

    then:
    1 * service.repository.bar({ it == ['aaa'] }) >> list
    0 * _

    actual == list
  }

  static class Service {
    Repository repository

    List<String> foo(List<String> list) {
      return repository.bar(list)
    }
  }

  static interface Repository {
    List<String> bar(List<String> list)
  }
}
```

Resulting in:

```
Too many invocations for:

0 * _   (1 invocation)

Matching invocations (ordered by last occurrence):

1 * <Repository>.bar(['a'])   <-- this triggered the error
```

Removing the `0 * _` will result in the new (as of 1.3) code constraint assertion error format. Which is much more helpful within complex tests.

```
Too few invocations for:

1 * service.repository.bar({ it == ['aaa'] }) >> list   (0 invocations)

Unmatched invocations (ordered by similarity):

1 * <Repository>.bar(['a'])
One or more arguments(s) didn't match:
0: Condition not satisfied:
   
   it == ['aaa']
   |  |
   |  false
   [a]
```

# Additional Environment information
## Java/JDK
```
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

## Groovy version
`Groovy Version: 2.5.4 JVM: 11.0.1 Vendor: Oracle Corporation OS: Mac OS X`

### Gradle
```
------------------------------------------------------------
Gradle 5.0
------------------------------------------------------------

Build time:   2018-11-26 11:48:43 UTC
Revision:     7fc6e5abf2fc5fe0824aec8a0f5462664dbcd987

Kotlin DSL:   1.0.4
Kotlin:       1.3.10
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.1 (Oracle Corporation 11.0.1+13)
OS:           Mac OS X 10.14.6 x86_64

```

## Operating System
Mac

## IDE
IntelliJ

### Gradle/Grails
    testCompile "org.spockframework:spock-core:1.3-groovy-2.5"

**Comment by tkarampatsisBG** [comment]
Any updates on this one?

**Comment by leonard84** [comment]
No, it isn't high on the todo list. 

The case might be a bit annoying, but it works as specified.
We don't have special support for strict mocking. Instead, you just have something that matches everything and then fails because it exceeds the expected count.

When you encounter a problem, you can remove the catchall, and then you see the proper error.
