### ISSUE TITLE
Native TemporaryFolder rule replacement in Spock 2

### ISSUE THREAD

**Issue by szpak** [spockframework/spock#1126]
# Issue description
The `TemporaryFolder` rule from JUnit 4 can only be used with the `spock-junit4` module. It should work flawlessly, but eventually, to get rid of `junit4.jar` from the classpath of projects using Spock 2 it would be nice to have a native replacement for Spock.

Similar implementations to look at:
 - original [TemporaryFolder](https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/rules/TemporaryFolder.java) from JUnit 4
 - new [TempDir](https://github.com/junit-team/junit5/blob/master/junit-jupiter-api/src/main/java/org/junit/jupiter/api/io/TempDir.java) from JUnit 5

**Comment by DQinYuan** [comment]
I want to help. But I do not understance the mean of **"native replacement"**. Do you mean we do not depend 
 on junit `Rule`,  but develop a special `Specification` subclass (for example, `TemporaryFolderSpec`), if user want to use it, he only need to `extends TemporaryFolderSpec`:

```java
class XxxTest extends TemporaryFolderSpec {
     //...
}
```

I don't know whether my understand is right or not?

**Comment by Vampire** [comment]
"native" probably means supported in Spock itself wihtout the need to use a JUnit rule.
But for sure not with a `Specification` subclass.
More likely an [annotation driven local extension](http://spockframework.org/spock/docs/2.0-M3/all_in_one.html#_annotation_driven_local_extensions)
