### ISSUE TITLE
Cover groovy.test.NotYetImplemented in tests

### ISSUE THREAD

**Issue by szpak** [spockframework/spock#1127]
# Issue description
Groovy 3 deprecated old `groovy.transform.NotYetImplemented` annotation in favor of `groovy.test.NotYetImplemented`. It would be good to make tests also for it.

However, as the transformation itself is strictly bound to `junit.framework.AssertionFailedError` it requires junit4 on runtime classpath. In addition those tests require also Groovy 3 (will not compile with Groovy 2.5) which makes it hard (ugly) to setup it in Spock project.

This issue could be covered once `NotYetImplementedASTTransformation` uses `org.opentest4j.AssertionFailedError` from opentest4j instead.

**Comment by shils** [comment]
>This issue could be covered once NotYetImplementedASTTransformation uses org.opentest4j.AssertionFailedError from opentest4j instead.

@szpak is there an issue for this in the groovy project jira?

**Comment by szpak** [comment]
There is a TODO in code. I don't know if there is an issue.

**Comment by szpak** [comment]
I created one to remember about it: https://issues.apache.org/jira/browse/GROOVY-9492
