### ISSUE TITLE
`Mock` interaction doesn't work when it follows `sleep` statement inside `then` block to wait async behavior to occur .  

### ISSUE THREAD

**Issue by chenxi-null** [spockframework/spock#1129]
# Issue description
`Mock` interaction doesn't work when it follows `sleep` statement inside `then` block to wait async behavior to occur .  
This description may be a little abstract, the code is shown below:

# How to reproduce
```java
class SpecMockTest extends Specification {

    List list = Mock()

    def "normal mock"() {
        when:
        new Thread({
            sleep(500)
            list.add(1)
        }).start()
        sleep(2000)

        then:
        1 * list.add(_)
    }

    @FailsWith(TooFewInvocationsError)
    def "wired mock"() {
        when:
        new Thread({
            sleep(500)
            list.add(1)
        }).start()

        then:
        sleep(2000)
        throw new RuntimeException("can't go to there")
        1 * list.add(_)
    }
}
```

I take a look at the class file generated by spock, the mock interaction is put in front of the other code (the sleep and throwing statement) inside 'then' block, 
which is originally in front of mock interaction in spock code.   
So, I guess it's the cause of this phenomenon.  

I just want to determine whether it's a bug or the inherent characteristics of Spock.
![image](https://user-images.githubusercontent.com/16267732/77429827-33c2e280-6e15-11ea-9540-73b05ce667e2.png)

## Java/JDK
1.8.0_181

## Groovy version
2.5.8

### Apache Maven
3.5.4 

## Operating System
Mac

## IDE
IntelliJ

### Apache Maven
```xml
<dependency>
    <groupId>org.spockframework</groupId>
    <artifactId>spock-core</artifactId>
    <version>1.3-groovy-2.5</version>
</dependency>
```

**Comment by Vampire** [comment]
That interactions from `then` are moved in front of the according `when` is expected and documented.
If you need non-interaction lines along with the interaction like local veriables, you need to explicitly group them with an `interaction` closure also as documented, then it is moved as block.
This of course would not help in your situation, as the would just wait 2 seconds before the interaction is registered and before it is evaluated.

In the Groovy Console it is a bit more readable:
```groovy
    @spock.lang.FailsWith(value = org.spockframework.mock.TooFewInvocationsError)
    @org.spockframework.runtime.model.FeatureMetadata(name = 'wired mock', ordinal = 1, line = 17, blocks = [org.spockframework.runtime.model.BlockKind.WHEN[]org.codehaus.groovy.ast.AnnotationNode@d9f41, org.spockframework.runtime.model.BlockKind.THEN[]org.codehaus.groovy.ast.AnnotationNode@d9f41], parameterNames = [])
    public void $spock_feature_0_1() {
        org.spockframework.runtime.ErrorCollector $spock_errorCollector = new org.spockframework.runtime.ErrorCollector(false)
        org.spockframework.runtime.ValueRecorder $spock_valueRecorder = new org.spockframework.runtime.ValueRecorder()
        try {
            this.getSpecificationContext().getMockController().enterScope()
            this.getSpecificationContext().getMockController().addInteraction(new org.spockframework.mock.runtime.InteractionBuilder(28, 9, '1 * list.add(_)').setFixedCount(1).addEqualTarget(list).addEqualMethodName('add').setArgListKind(true, false).addEqualArg(_).build())
            new java.lang.Thread({ 
                this.sleep(500)
                list.add(1)
            }).start()
            this.getSpecificationContext().getMockController().leaveScope()
            try {
                org.spockframework.runtime.SpockRuntime.verifyMethodCondition($spock_errorCollector, $spock_valueRecorder.reset(), 'sleep(2000)', 26, 9, null, this, $spock_valueRecorder.record($spock_valueRecorder.startRecordingValue(0), 'sleep'), new java.lang.Object[], $spock_valueRecorder.realizeNas(4, false), false, 3)
            } 
            catch (java.lang.Throwable throwable) {
                org.spockframework.runtime.SpockRuntime.conditionFailedWithException($spock_errorCollector, $spock_valueRecorder, 'sleep(2000)', 26, 9, null, throwable)} 
            finally { 
            } 
            throw new java.lang.RuntimeException('can\'t go to there')
            this.getSpecificationContext().getMockController().leaveScope()
        } 
        finally { 
            $spock_errorCollector.validateCollectedErrors()} 
    }
```

When `leaveScope` is called, the interactions of the respective Scope are verified.
So when you leave the `when` block, the scope is left and the interactions must be fulfilled.
That is also why your first example works, because the sleep is still within the scope.

Btw. for testing async code, there are also the utilites `spock.util.concurrent.AsyncConditions`, `spock.util.concurrent.BlockingVariable` and `spock.util.concurrent.PollingConditions` available, maybe they will help you for your tasks.

**Comment by chenxi-null** [comment]
@Vampire Thanks for answering!

I read the document again and find the [place](http://spockframework.org/spock/docs/1.2/all_in_one.html#_explicit_interaction_blocks) where 
explain the implicit interaction movement.

About verifying async interaction, I tried `PollingCondition` before, but it doesn't work. 
Thanks for recommending `AsyncConditions`. It works for my situation, which is more elegant than using `sleep`. 
```java
@FailsWith(TooFewInvocationsError)
def "mock async behavior with `PollingCondition`"() {
    when:
    new Thread({
        sleep(500)
        list.add(1)
    }).start()

    then:
    pollingConditions.within(2, { 1 * list.add(_) })
}

def "mock async behavior with `AsyncConditions`"() {
    setup:
    def conditions = new AsyncConditions()
    List<Integer> list = Stub {
        add(_) >> { Integer e -> conditions.evaluate { assert e == 1 } }
    }

    when:
    Thread.start {
        sleep(500)
        list.add(1)
    }

    then:
    conditions.await()
}
```

btw, would you tell me what's tools should I use to convert the class file generated by spock or spock source code to groovy code, just like the code you shown?   
I'm a java programer, not similar with groovy tech stack.

**Comment by Vampire** [comment]
Of course `PollingConditions` does not work in your case here, I mentioned those utils in general when you test async code, not for this use-case specifically. The `PollingConditions` still wait in the `then` block which is still too late. Besides, as its name suggests, it is more for conditions, not interactions. You could do it similar to how you did it with the `AsyncCondition` of course also with the `PollingCondition`. There are many ways to do it, but it is hard to give a recommendation as it depends on your real test case, so recommending with dummy code is hard, so I just gave you proper hints.

Here another way to rewrite your example:
```groovy
  def "mock async behavior with `AsyncConditions`"() {
    setup:
    def waitForAdd = new BlockingVariable<Object>(2)
    List list = Mock()

    when:
    Thread.start {
      sleep(500)
      list.add(1)
    }
    waitForAdd.get()

    then:
    1 * list.add(_) >> { waitForAdd.set(_) }
  }
```

> btw, would you tell me what's tools should I use to convert the class file generated by spock or spock source code to groovy code, just like the code you shown?

I did, it is the Groovy Console.
- install Groovy
- start the Groovy Console
- Paste in your class
```groovy
@Grab('org.spockframework:spock-core:1.3-groovy-2.4')
import spock.lang.Specification

class SpecMockTest extends Specification {
    List list = Mock()

    def "normal mock"() {
        when:
        new Thread({
            sleep(500)
            list.add(1)
        }).start()
        sleep(2000)

        then:
        1 * list.add(_)
    }

    def "wired mock"() {
        when:
        new Thread({
            sleep(500)
            list.add(1)
        }).start()

        then:
        sleep(2000)
        throw new RuntimeException("can't go to there")
        1 * list.add(_)
    }
}
```
- Invoke `Script -> Inspect Ast` or press `Ctrl+T`
- Select `At end of Phase: Semantic Analysis`
