### ISSUE TITLE
Access variables defined within a test method from where block

### ISSUE THREAD

**Issue by YaroSpace** [spockframework/spock#113]
As per documentation, only variables defined outside the test method (i.e. class fields) can be accessed in the where block. 
However, I think, it would be very convenient if we could reference local variables or at least delay evaluation of a variable in the where block until it is actually used. 
Can this be done currently or perhaps hoped for in the future?

Example:

```
given:
  def userWithProfile = User.build(..)
  def userWithoutProfile = User.build(..)
when:
  controller.params = myParams
  controller.callAction()
then:
  assert ..
where:
  event | params | response
   User has a profile | [userId: userWithProfile.id] | [....]
   User has no profile | [userId: userWithoutProfile.id] [ ....]
  ..  ..
```

As you can see, I need to pass an id which will be known only after the given block is evaluated. 
Currently, I am doing this. 

```
given:
  sharedVar.userId = User.build().id
...
where:
  params
  [ userId: "${->sharedVar.userId}" ]
```

I.e. userId is lazily evaluated (or in fact, every time) and it works. However, this produces a string, which is ok in case of controller params, but not in cases when I need the actual value.

**Comment by leonard84** [comment]
This will be problematic in conjunction with the `@Unroll` annotation and variable expansion in the feature name, since the variable would not be available at that time. Furthermore, at least this example does not really make a point on why this would be useful? But as you already found out you can use closures to delay evaluation, you don't really need to put them in a GString though. 
Actually only `@Shared` fields are available in the `where` block.

**Comment by YaroSpace** [comment]
Sorry, was not clear enough (updated the code). In my specs, it is very common to have several cases that I unroll for various type users (with profile, without, with permissions, etc). 
The input params are the same and I am testing the output for each user. I am constructing users inside the test, as they are specific to the test and not to the whole Spec.  
Unroll and where block are very convenient, because I do not need to have 4 tests for 4 different users, the only problem is getting the id of the user currently under test. 
So, GString is working fine, but if I pass a plain closure, it does not actually get evaluated, I just get a value of type Closure.

**Comment by leonard84** [comment]
If your params are a map, I think it is totally fine to add them in the spec itself, what I find weird is that, in the example you construct all users in the given block even if you are only using one. You could also leverage Groovy's dynamic method lookup to just have methods named `userWithProfile` `userWithoutProfile` and do something like:

```
@Unroll
def "Testing something for #userprofile" () {
given:
def user = "$userProfile"()
params.userId = user.id
...
where:
userprofile | params
'userWithProfile' | [...]
'userWithoutProfile ' | [...]
}
```

This way you can even use it in the `@Unroll` description.

**Comment by YaroSpace** [comment]
In this particular example, the params map is the same for all unroll cases, but usually it is different, so it's more convenient to have them in the where block, rather than the spec itself.
Having all users constructed in the given block is like saying 'given I have these types of users, when one of them logins, then a response is returned which is specific to that user.

Great workaround with `$userProfile` - nice and simple.  Thanks.

**Comment by leonard84** [comment]
> In this particular example, the params map is the same for all unroll cases, but usually it is different, so it's more convenient to have them in the where block, rather than the spec itself.

Sure that is why I just add the userId in the given block to the params from the where block.

>Having all users constructed in the given block is like saying 'given I have these types of users, when one of them logins, then a response is returned which is specific to that user.

If it is not essential to the test that there are more than one user, I would avoid creating multiple different users and only use one of them, that is why we have data driven test, so we can separate this neatly.

**Comment by timotei** [comment]
@leonard84 I have an example where using local variables is needed:

```
def 'when an unreleased snapshot library was not downloaded in #age days it is deleted'() {
        given:
        def result = new SnapshotCleaner.CleanupResult()
        // actually has a more comprehensive setup than what's written here
        def snapshotArtifact = artifact(age)
        artifactFactory.from(snapshotItem) >> snapshotArtifact

        when:
        tested.cleanupSnapshots(result)

        then:
        deletionCount * snapshotArtifact.delete(repositories)
        result.snapshotsRemoved == removedSnapshots

       where:
       age | removedSnapshots  | deletionCount
       1 | [] | 0 
       5 | [snapshotArtifact] | 0
    }
``` 

Here, we have a local variable setup, and we have two cases (at least), when it would check that collection to be empty or have the artifact we set up. There are multiple tests similar to this, with different setups, so creating another method like you suggest will make things more complicated than needed.

**Comment by leonard84** [comment]
This feature is not possible, since the where block is actually moved and executed **before** the test itself.
