### ISSUE TITLE
Replace osgi plugin with biz.aQute.bnd.gradle

### ISSUE THREAD

**Issue by leonard84** [spockframework/spock#1139]
Gradle removed the deprecated `osgi` plugin and this is blocking the update to gradle 6. The recommended replacement is the `biz.aQute.bnd.gradle` plugin.

While upgrading it would be nice, if the information about version ranges could be inferred from the dependencies if possible, or at least validated against them.

**Comment by szpak** [comment]
This (Gradle 6 upgrade) blocks also testing Spock with Java 13+ :-/
