### ISSUE TITLE
SpockConfig.groovy to be set via spock.configuration property has no effect

### ISSUE THREAD

**Issue by tinca** [spockframework/spock#1140]
# Issue description
I want to configure an extension ('com.athaydes:spock-reports:1.7.1') via config file that is provided by setting spock.configuration system property.

# How to reproduce
In project root is defined a directory that holds my SpockConfig.groovy which contains properties to be configured, like:
spockReports {
    set 'com.athaydes.spockframework.report.internal.HtmlReportCreator.inlineCss': false
}

Running:
gradle -Dspock.configuration=<abs path> test
shows no effect of the settings (for the example: css is to be place into separate file instead of report html).
Also, tried to set it via settings.gradle to no avail:
System.setProperty('spock.configuration', new File(rootProject.projectDir, 'config/').path)
I both cases System.getProperty(..) proves 'spock.configuration' is present.

When the config file is moved to ~/.spock dir, it works fine.

Am I doing something wrong, or is it a bug?

# Additional Environment information
org.spockframework:spock-core:1.3-RC1-groovy-2.5

## Java/JDK
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

### Gradle
------------------------------------------------------------
Gradle 5.6.4
------------------------------------------------------------

Build time:   2019-11-01 20:42:00 UTC
Revision:     dd870424f9bd8e195d614dc14bb140f43c22da98

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          11.0.6 (AdoptOpenJDK 11.0.6+10)
OS:           Mac OS X 10.15.4 x86_64

# closing words
Earlier used jUnit, TestNG, but Spock makes me smile whenever I work with tests.  I am so relived! :-)
Thank you for this wonderful tool!

**Comment by Vampire** [comment]
You set a system property on the Gradle run.
But instead you need to set a system property on the test task.
The test task is run in a different process and the system properties are not copied over.
You have to set manually which system properties should be set on the test task in your Gradle script.
Alternatively you can simply put the file in the root of the test classpath, so moving it to `src/test/resources` would also be sufficient.

**Comment by tinca** [comment]
You mean this?
test {
        System.setProperty('spock.configuration', new File(rootProject.projectDir, 'config/SpockConfig.groovy').path)
}
It does not work.

Putting under resources not a desired option, because of a multiproject build. It would require copying and later changing them in multiple places.

**Comment by tinca** [comment]
Just to make it clear. There is a working solution that I am currently using. But I am interested in this bug, or what I am doing wrong to accomplish the goal I outlined.

**Comment by Vampire** [comment]
You are still setting it in the VM running Gradle. You must tell Gradle to set it in the VM running the tests.
```groovy
test {
    systemProperty 'spock.configuration', rootProject.file('config/SpockConfig.groovy').absolutePath
}
```
or in your case maybe
```groovy
allprojects {
    test {
        systemProperty 'spock.configuration', rootProject.file('config/SpockConfig.groovy').absolutePath
    }
}
```

**Comment by tinca** [comment]
My apologies, I did my version for the subprojects too, but that syntax is wrong. Yours did work. Thank you for your help!
