### ISSUE TITLE
Unable to run Spock tests from JUnit 5 console launcher

### ISSUE THREAD

**Issue by georgeharley** [spockframework/spock#1157]
# Unable to run Spock tests from JUnit 5 console launcher
I have tried to use the latest JUnit 5 console launcher to run Spock tests from the command line but it is proving unsuccessful. The Spock test engine appears to successfully register and the specified spec class is located but none of its tests are discovered. There are no error messages. Hopefully this is a case of user error. 

# How to reproduce
I've created a [small standalone repo](https://github.com/georgeharley/spock-test-app) to try and demonstrate the problem in the simplest way I can think of. The README contains instructions on how to run the launcher against some trivial Spock code.

# Additional Environment information
The repo referenced above is using a Spock 2.0 snapshot and version 1.7.0-M1 of the JUnit 5 console launcher.

## Java/JDK
Java 8

## Groovy version
Groovy version 2.5.9

## Build tool version
N/A

### Gradle
Gradle 6.3

### Apache Maven
N/A

## Operating System
macOS

## IDE
IntelliJ

**Comment by Vampire** [comment]
> Hopefully this is a case of user error.

It is. :-)
Add `--help` and amongst other things you will find 
```
 -n, --include-classname=PATTERN
                             Provide a regular expression to include only classes whose
                               fully qualified names match. To avoid loading classes
                               unnecessarily, the default pattern only includes class
                               names that begin with "Test" or end with "Test" or
                               "Tests". When this option is repeated, all patterns will
                               be combined using OR semantics. Default: [^(Test.*|.+[.$]
                               Test.*|.*Tests?)$]
```
If you adapt the option to match your class name, it will be discovered and executed.
If you don't like this, for example because you actually specified the concrete class name as argument, you need to complain to the JUnit 5 guys. :-)

**Comment by georgeharley** [comment]
Thank you very much @Vampire, I can confirm that adding `--include-classname="^.*Spec$"` to the launch command results in the tests being discovered and executed as hoped. Having to supply a regex pattern as well as the concrete class name does feel like slightly dubious usability so FWIW I'll open a JUnit5 issue on the matter. In the meantime, thanks once again for your guidance.
