### ISSUE TITLE
Spock calls new BigDecimal(myObject.toString()) during execution of '==' when myObject implements Comparable<myObject> then BigDecimal throws execption.

### ISSUE THREAD

**Issue by fishjd** [spockframework/spock#1170]
I am upgrading from 
compile group: 'org.codehaus.groovy', name: 'groovy-all', version: '2.4.12'
testCompile group: 'org.spockframework', name: 'spock-core', version: '1.1-groovy-2.4'

to : 
compile group: 'org.codehaus.groovy', name: 'groovy-all', version: '3.0.0', ext: 'pom'
testCompile group: 'org.spockframework', name: 'spock-core', version: '2.0-M2-groovy-3.0'

All my tests ran fine in Spock 1.1. 

The test now throws a BigDecimal exception.  

The following conditions must be meet:  
The Class under test (CUT) must: 
1) implement Comparable<CUT> 
2)  the CUT.toString() does not simply return a value.   i.e.  new BigDecimal(CUT.toString()) throws an exception.  
3)  the test calls   Cut value 1 ==  Cut value 2

# How to reproduce
## Link to a gist or similar (optional)

My CUT is ByteUnsigned  see:  https://github.com/fishjd/HappyNewMoonWithReport/blob/ab9323b5bffcbff8a2a5f9a36975d9b55599296a/src/main/java/happynewmoonwithreport/type/JavaType/ByteUnsigned.java

The test is: 
https://github.com/fishjd/HappyNewMoonWithReport/blob/ab9323b5bffcbff8a2a5f9a36975d9b55599296a/src/test/groovy/happynewmoonwithreport/opcode/Memory/ByteUnsignedSimple.groovy

The test throws an exception on line 46  '''result == expected'''

The whole repository:
https://github.com/fishjd/HappyNewMoonWithReport/tree/ab9323b5bffcbff8a2a5f9a36975d9b55599296a  

on branch "update Groovy and Spock"  

The main issue is somewhere on line 46 a call to  BigDecimal(String val) is excuted.  The assumption is that the output of CUT.toString() will convert to BigDecimal without an exception.    I don't think this is a valid assumption.  It is a valid assumption for Java Integer.  

## Known Workarounds
1) modify CUT.toString() output to convert to BigDecimal without exception.   
2) modify CUT to not implement Comparable<CUT>

# Additional Environment information
> Version of your build tool(if used), Java, Groovy, IDE, OS etc

## Java/JDK
`java -version`
java jdk 11.05

## Groovy version
 version: '3.0.0'

### Gradle
`gradle -version`

------------------------------------------------------------
Gradle 5.6.2
------------------------------------------------------------

Build time:   2019-09-05 16:13:54 UTC
Revision:     55a5e53d855db8fc7b0e494412fc624051a8e781

## Operating System
Windows 10 

## IDE
> IntelliJ, Eclipse, etc.
Running all tests executed in IntelliJ 'Community 2019.3' 

### Gradle/Grails
See:  https://github.com/fishjd/HappyNewMoonWithReport/blob/ab9323b5bffcbff8a2a5f9a36975d9b55599296a/build.gradle

Thanks!  I hope this helps.

**Comment by Vampire** [comment]
That's not Spock calling anything, that is just pure Groovy.
And it also happens with 2.5 already.
If you go to https://groovyconsole.appspot.com/edit/5200014540275712 and press `Execute script`, you will see that you get a `NumberFormatException` in the line with `_1 == _2`.
It is exactly your code minus the package declaration and plus the lines 3-5.
You should ask or report to the Groovy guys at https://groovy-lang.org/support.html about this.

**Comment by fishjd** [comment]
Thanks,  I will submit to Groovy.   I was not sure whether it was Spock or Groovy.  So I started with Spock.   Thanks also for confirming it is an anomaly.
