### ISSUE TITLE
Using thrown() causes IllegalAccessError for 2.0-M2-groovy-3.0 on JDK 8 with noverify switch

### ISSUE THREAD

**Issue by dmurat** [spockframework/spock#1177]
# Issue description
Not really sure if this needs fixing, but I'm reporting anyway so you can decide.

When running Spock 2.0-M2 with Groovy 3 on JDK 8 with `-noverify` switch, I'm getting `llegalAccessError` on any attempt of using `thrown()` method.
There is no problem with JDK 11, and with JDK 8 there is no error if `-noverify` is removed.

I usually run my tests with `-noverify` and `-XX:TieredStopAtLevel=1`options set. This is inspired by numerous talks and blogs from Spring's Dave Syer (i.e. https://spring.io/blog/2018/12/12/how-fast-is-spring).

# How to reproduce
Use JDK 8. With Gradle the following in `build.gradle` for tests
```
  test {
    jvmArgs = ["-noverify", "-XX:TieredStopAtLevel=1"]
    useJUnitPlatform()
  }
```

Execute any test containing any variant of `thrown()`.

# Additional Environment information
## Java/JDK
```
java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```

## Groovy version
3.0.4

### Gradle
```
gw --version
------------------------------------------------------------
Gradle 6.4.1
------------------------------------------------------------

Build time:   2020-05-15 19:43:40 UTC
Revision:     1a04183c502614b5c80e33d603074e0b4a2777c5

Kotlin:       1.3.71
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.7 (Oracle Corporation 11.0.7+8-LTS)
OS:           Mac OS X 10.15.5 x86_64
```

## Operating System
 Mac OS X 10.15.5 x86_64

### Gradle/Grails
`testImplementation "org.spockframework:spock-core:2.0-M2-groovy-3.0"`

**Comment by Vampire** [comment]
Interesting.
`-XX:TieredStopAtLevel=1` is irrelevant.
And with Groovy 2.5 it does not happen.
But with Groovy 3.0 and `-noverify` it is easily reproducible. :-/

**Comment by Vampire** [comment]
@paulk-asert can you have a look at this? I believe this might be a Groovy 3.0 bug.

**Comment by paulk-asert** [comment]
@Vampire I'll take a look

**Comment by paulk-asert** [comment]
If anyone gets a chance before I do, please check against the latest 3.0.5-SNAPSHOT. This might already be fixed. I do plan to look at that myself but probably not until the weekend.

**Comment by dmurat** [comment]
I just tried. Unfortunately, 3.0.5-SNAPSHOT does not resolve the issue yet.

**Comment by paulk-asert** [comment]
Thanks @dmurat. I also tried and it didn't help. We fixed a different IllegalAccessError but obviously not this one.

**Comment by paulk-asert** [comment]
Just FYI, `noverify` is deprecated from JDK13:
https://bugs.openjdk.java.net/browse/JDK-8218003

**Comment by paulk-asert** [comment]
I created https://issues.apache.org/jira/browse/GROOVY-9643

**Comment by dmurat** [comment]
Closing as it is fixed in https://issues.apache.org/jira/browse/GROOVY-9643 .

**Comment by Vampire** [comment]
We should probably increase our dependency to 3.0.5 to have this fix included because of this issue, so can you please reopen the ticket?

**Comment by dmurat** [comment]
sure
