### ISSUE TITLE
TestRule impls are not notified of test failure

### ISSUE THREAD

**Issue by alkemist** [spockframework/spock#118]
Can be verified by using a JUnit TestWatcher impl that collects errors. No errors will be collected, because the Statement given to the rule will never throw.

**Comment by leonard84** [comment]
TestWatcher extends `TestRule` which are not supported yet, only `MethodRule` based rules are supported by Spock atm. (https://stackoverflow.com/questions/17545264/injecting-a-rule-into-a-spock-specification)

So this could be converted into a feature request to support `TestRule`.

**Comment by JohnRoach** [comment]
Hi,
I have ran across this issue. Is there a fix for it in release "1.1-groovy-2.4-rc-1" ? Or any releases at all? This is really hurting us from using a lot of reporting tools.

**Comment by JohnRoach** [comment]
I am willing to work on this if someone can point me to the problem... @alkemist @leonard84

**Comment by JohnRoach** [comment]
Seriously, free help here! @alkemist @leonard84 just need you guys to show me where to start looking...

**Comment by leonard84** [comment]
@JohnRoach thanks for your offer, but I can only point you at the already established facts in my comment above. The main problem is that the exceptions are swallowed and logged before they reach the `TestRule`. The code which delegates to the `TestRule`s is in `org.spockframework.runtime.extension.builtin.TestRuleInterceptor` and the initial invocation Object is created here `org.spockframework.runtime.BaseSpecRunner#invoke`.

Good Luck

**Comment by TheJusticeLeague** [comment]
Is this planned to be fixed for version 1.1? :-)

**Comment by mpetko** [comment]
Looks like this issue was not fixed in version 1.1. Is there a plan for fixing this?

**Comment by leonard84** [comment]
The way `TestRule` and `MethodRule` expect exceptions is incompatible with Spocks extension model which is similar to JUnit 5 Jupiters extensions. You'll probably need to write a Spock extension if you need access to the exception. If you are using Spring then you could also use a `TestExecutionListener`. However, if you want to swallow the Exception then a Spock extension is the way to go.

I'm closing this as wont fix.

**Comment by KingSoares** [comment]
Just a quick question as I am pretty new to this :-) 
I should write a spock extension to what? Any specific class?

Sorry the beginner question :-)

**Comment by leonard84** [comment]
http://spockframework.org/spock/docs/1.1/all_in_one.html#_writing_custom_extensions
