### ISSUE TITLE
Spock 2.0-M3-groovy-3.0 compatibility issues working with Gradle 6.5

### ISSUE THREAD

**Issue by mhajirnis** [spockframework/spock#1184]
# Issue description
I'm trying to upgrade to latest Spock with Groovy and Gradle but seems to be incompatible with one another

# How to reproduce
Create a Gradle project with the dependencies with the versions specified and run `gradle clean test` 

# Additional Environment information
Use Spock-core version: 2.0-M3-groovy-3.0 within Gradle 6.5 with JDK 11

## Java/JDK
`java -version`
`11.0.7`

## Groovy version
`groovy -version`
`3.0.4`

### Gradle
`gradle -version`
`6.5`

### Apache Maven
`mvn -version`
N/A but `3.6.3`

## Operating System
macOS Catalina version 10.15.5
`uname -a`
```
Darwin My-MBP.lan 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
```

## IDE
N/A since we can reproduce the issue with / without IDE
Just FYI,
IntelliJ IDEA 2020.1.2 (Ultimate Edition)
Build #IU-201.7846.76, built on May 31, 2020

Runtime version: 11.0.7+10-b765.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Non-Bundled Plugins: com.intellij.kubernetes, aws.toolkit, org.jetbrains.kotlin, org.intellij.scala, com.jetbrains.edu, training

### Gradle/Grails
```gradle
apply plugin: 'groovy'
....
dependencies {
  testImplementation 'org.spockframework:spock-core:2.0-M3-groovy-3.0'
  testImplementation 'org.spockframework:spock-spring:2.0-M3-groovy-3.0'
...
  testImplementation('com.athaydes:spock-reports:2.0-RC2') {
        transitive = false
    }
}
```

**Comment by szpak** [comment]
Strange, it was working for me just yesterday ;-).

Nevertheless, it's hard to say anything, if you didn't provide the error you receive. In addition, please (temporarily) remove also spock-reports to ensure it doesn't generate that error.

**Comment by Vampire** [comment]
@szpak it is pure guesswork, but I guess it is the usual "Groovy 2 is still somewhere burried in the classpath" issue that makes the AST transformation fail to work. If so, can't we somehow make the error more meaningful?

**Comment by szpak** [comment]
Btw, you might also take a look at the migration guide I posted some time ago: https://blog.solidsoft.pl/2020/01/02/migrating-spock-1.3-tests-to-spock-2.0/

**Comment by mhajirnis** [comment]
Thanks @szpak / @Vampire 
I still had trouble with my existing project. So I decided to create dummy project with the config I have mentioned in the original comment
Please find the git repo: [Spock-demo](https://github.com/mhajirnis/spock-demo)
Now, on command line everything seems to be fine. Only issue is with IntelliJ. It doesn't detect Spock (please see attachment)
<img width="825" alt="Screen Shot 2020-06-29 at 12 33 00 PM" src="https://user-images.githubusercontent.com/34136039/86048144-dd150800-ba04-11ea-8153-6e4c614ff586.png">
even though I see that dependency was added successfully.
Also, I'm able to just right click and run all the tests in IntelliJ successfully

p.s. In the same project, when I switch back to spock-core:1.2-groovy-2.5, it immediately detects and syntax highlighting error goes away
Let me know if this is just me or IntelliJ has issue. I also added Spock plugin in IntelliJ but no luck

**Comment by szpak** [comment]
Which Idea version do you use?

With Idea Community 2020.1 it was imported just fine:
![image](https://user-images.githubusercontent.com/148013/86049596-b4b3fa80-ba52-11ea-9960-bf5bb6309e75.png)

Please try to reimport it from scratch and/or upgrade to never Idea (to check if it could be a problem). Maybe there were some issues with mixing Groovy and Kotlin in the older versions?

**Comment by mhajirnis** [comment]
@szpak 
I tried with Community edition and yes, you are correct. I didn't see the issue there; but in Ultimate edition (latest), it's still the issue.
I'm going to close this since it's not related to Spock version, but something is probably wrong with IntelliJ Ultimate edition imports itself
Thanks for the help @szpak and @Vampire (I'm so jealous that you got such an awesome Github handle :D)

**Comment by Vampire** [comment]
I don't think this has to do with Ultimate.
Maybe with one of your plugins or there was some problem with importing that could also happen with Community or something.
I cloned your repo, opened it with Ultimate 2020.1.2 and it works perfectly fine.
