### ISSUE TITLE
Migrate Issues from Google Code

### ISSUE THREAD

**Issue by leonard84** [spockframework/spock#119]
Since Google Code is being closed there is now a direct migration button to Github.
However, since Spock migrated ahead of time it can't be used. Nevertheless,
there seems to be a fairly automated way to migrate issues from Google Code to Github.

https://code.google.com/p/support-tools/wiki/IssueExporterTool

Since there are still very useful requests and bugs those issues should be migrated.

**Comment by robfletcher** [comment]
Issues are exported successfully but the Python script doesn't work for me. I'm going to try to figure that out.

**Comment by robfletcher** [comment]
Some are now imported but the script hit a GitHub rate limit so it didn't complete. I'll need to now sort which issues have and have not been imported then re-run

**Comment by robfletcher** [comment]
Finally done
