### ISSUE TITLE
A Spock like testing framework based on Kotlin instead of Groovy

### ISSUE THREAD

**Issue by tglaeser** [spockframework/spock#1210]
Spock is tightly coupled to Groovy, is it feasible or would it make sense at all to port it to depend on Kotlin instead?

Looking for your thoughts/concerns on the topic. Thanks.

**Comment by Vampire** [comment]
That would be amazing and I would love you for doing it.
I know one guy once said he gives it a shot long time ago and I never heard anything about it again.
Unfortunately I don't think this is really possible.
Spock depends heavily on the dynamic language features and also on AST transformations.
I have no idea whether you can do similar things as the AST transformations with a Kotlin compiler plugin or with the new upcoming IR backends.
If someone savvy in those things would give it a shot, I would be happy to give any information I can provide to support that.
So PR heavily welcome. :-D

**Comment by tglaeser** [comment]
Thank you @Vampire for your valuable input; I can see that Groovy's dynamic vs Kotlin's static type checking makes the difference here; I merely was curious to find out if someone already gave this some consideration.

**Comment by tglaeser** [comment]
FYI, also started a related discussion under [MockK](https://github.com/mockk/mockk/issues/489#issue-700650131).
