### ISSUE TITLE
  Junit5 @RegisterExtension is unsupported as replacement for @Rule

### ISSUE THREAD

**Issue by JLLeitschuh** [spockframework/spock#1214]
# Issue description

With the removal of support for JUnit 4's `@Rule` in Spock 2.0, the replacement in JUnit 5 are extensions. I'd like to use `@RegisterExtension` to register an extension to execute before and after each test.

# How to reproduce

```
class RegisterExtensionTest extends Specification {

    @RegisterExtension
    RegisteredExtension extension = new RegisteredExtension()

    def "test what is invoked"() {
        expect:
        extension.setValue != null
    }

    static class RegisteredExtension implements BeforeAllCallback {

        String setValue = null

        @Override
        void beforeAll(ExtensionContext context) throws Exception {
            println("Before All")
            setValue = "A value"
        }
    }
}
```

# Additional Environment information

`org.spockframework:spock-core:2.0-M3-groovy-2.5`

```
------------------------------------------------------------
Gradle 6.6.1
------------------------------------------------------------

Build time:   2020-08-25 16:29:12 UTC
Revision:     f2d1fb54a951d8b11d25748e4711bec8d128d7e3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_212 (Azul Systems, Inc. 25.212-b04)
OS:           Mac OS X 10.15.5 x86_64
```

## Java/JDK
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (Zulu 8.38.0.13-CA-macosx) (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (Zulu 8.38.0.13-CA-macosx) (build 25.212-b04, mixed mode)
```

**Comment by Vampire** [comment]
`@RegisterExtension` is a Jupiter annotation.
Spock is on the same level as Jupiter.
Both are Testengines running on the JUnit Platform.
Spock does not support any of Jupiter annotations so far and I'm not sure how likely it is that it will unless someone contributes it as separate module.
You can still use JUnit 4 rules by using the `spock-junit4` artifact.
But the best solution would be to use a native Spock extensions and not an integration for JUnit annotations, be it JUnit 4 rules or Jupter annotations which is always just a patchwork and might result in slightly different behavior.

**Comment by JLLeitschuh** [comment]
Hey @Vampire,
Thanks! Is there any documentation on how to write spock extensions? The only official documentation I saw ended in a TODO. See: http://spockframework.org/spock/docs/1.0/extensions.html#_writing_custom_extensions

**Comment by Vampire** [comment]
Yes, I documented it in detail when I wrote my first Spock extension and contributed it.
Maybe you shouldn't read the Docs of version 1.0? ;-)
http://spockframework.org/spock/docs/2.0-M3/extensions.html#_writing_custom_extensions

**Comment by JLLeitschuh** [comment]
Looks like you may need to do a bit of Search Engine Optimization (SEO). When you google writing extensions, you get the 1.0 docs.

---

Also, just a friendly heads up, Google and other search engines intentionally de-prioritize `http` based sites over `https`. You may want to fix that at some point. HTTPs certs are free through lets encrypt, or, if you're hosting through GitHub pages, you should be able to get HTTPS there for free as well.

**Comment by JLLeitschuh** [comment]
I'm going to close this out as resolved. Thanks @Vampire!

**Comment by Vampire** [comment]
If we were able to contact the domain owner we would. (#1004)
You don't happen to have contact to @pniederw, do you? :-)

**Comment by kriegaex** [comment]
@Vampire, some of Peter's accounts like GitHub and Twitter seem not to have been updated in the last few years, but [this web site](https://nofluffjuststuff.com/conference/speaker/peter_niederwieser) looks recent and on the bottom there is an e-mail address. Maybe they can help you get in touch with Peter. I assume you have tried his [LinkedIn profile](https://www.linkedin.com/in/pniederw/) already? Just shots into the dark, but maybe you get lucky.
