### ISSUE TITLE
Document old-Method in the Guide

### ISSUE THREAD

**Issue by leonard84** [spockframework/spock#1228]
Since version 0.2 (#128) Spock supported the `old` method, but this was never mentioned in the docs, only in external [blog posts ](http://davesmith.me/blog/2013/spocks-old-method.html) this should be rectified. This should probably put into the new [utilities](http://spockframework.org/spock/docs/2.0-M4/utilities.html) section.

**Comment by AndreasTu** [comment]
@leonard84 Can you have a look at the PR, if this is enough documentation for the feature?
