### ISSUE TITLE
Nested asserts cannot be transformed

### ISSUE THREAD

**Issue by paplorinc** [spockframework/spock#1232]
Hey,

We've just tried out latest `Spock 2.0-M4`, we're getting the following exception:
> Task :compileTestGroovy
startup failed:
NestedAssertTest.groovy: -1: The current scope already contains a variable of the name $spock_errorCollector
 @ line -1, column -1.
NestedAssertTest.groovy: -1: The current scope already contains a variable of the name $spock_valueRecorder
 @ line -1, column -1.
2 errors

The cause seems to be that nested` assert`s seem to generate conflicting code, irrespective of their level or other previously generated ones (can be `"".with {}` or whatever closure):
```groovy
def nestedAssert() {
    tap {
        assert 0
        tap { assert 0 }
    }
}
```

The following reproducer can be used by running `./gradlew build`:
https://github.com/paplorinc/spock-bug/blob/master/src/test/groovy/NestedAssertTest.groovy

**Comment by kriegaex** [comment]
This test also fails on the previous milestone `M3`. It passes on Spock 1.3, though, if this is where you come from. Did it ever pass on any 2.x version for you?

**Comment by kriegaex** [comment]
@leonard84, is this somehow contextually related to #783?

**Comment by paplorinc** [comment]
We've only tried with 1.3, where this was working before.

**Comment by rtretyak** [comment]
Hope the above pr fixes it for feature methods as well, because it is also a thing in `2.0-M4-groovy-3.0`. this code does not compile in 2.0-M4 but works fine in 1.3
```
    def test() {
        expect:
        with([1,2]) {
            it.size() > 0
            it.each { assert it > 0 }
        }
    }
```

**Comment by Vampire** [comment]
Yes @rtretyak the PR fixes both.
In both was the problem only when you did not have any top-level condition and as `with` does return `void` it is not considered a condition.

**Comment by kriegaex** [comment]
As the merged PR does not contain any regression tests, I just built the current master and manually ran the test from this issue. It passes now.

**Comment by Vampire** [comment]
What do you mean?
Did you miss https://github.com/spockframework/spock/pull/1239/files#diff-47b16cca894a339507feda0cc9a675d00a438e4effddccda32291c9b8e0e3786 ?

**Comment by kriegaex** [comment]
Yes, because when glancing at the file list - I did not scroll to read the code - I was looking for `*Test` or `*Spec`. 😉

![image](https://user-images.githubusercontent.com/1537384/101271498-dc537f80-37b5-11eb-8448-73a00270c9f6.png)

I just saw `RecorderScope`, did not notice `smoke`.

**Comment by Vampire** [comment]
Yeah, naming is not too consistent in some points in Spock sources :-D

**Comment by Vampire** [comment]
Basically everything in spock-specs is either test or fixture

**Comment by kriegaex** [comment]
My bad entirely. But an additional manual test does not hurt, it was worth 5 minutes of my lifetime. :-)

**Comment by Vampire** [comment]
Yes, definitely, thanks for verifying fixes, also an important contribution. :-)

**Comment by paplorinc** [comment]
The latest SNAPSHOT seems to have fixed these, thanks!
