### ISSUE TITLE
Iteration name provider does not apply to non parameterized tests in Spock 2

### ISSUE THREAD

**Issue by ldaley** [spockframework/spock#1236]
# Issue description

In Spock 1, the iteration name provider also applied to non parameterized tests. In Spock 2, it does not.

# How to reproduce

[spock-2-iteration-name-provider-bug.zip](https://github.com/spockframework/spock/files/5535315/spock-2-iteration-name-provider-bug.zip)

The above is a complete Gradle project that can run a test with Spock 1 or 2.

Works:

```
$ ./gradlew test -Pspock1

> Task :test

pkg.ExampleSpec > test [suffix] STARTED

pkg.ExampleSpec > parameterized [suffix] STARTED

pkg.ExampleSpec > parameterized [suffix] STARTED

```

Not works (Spock 2):

```
$ ./gradlew test

> Task :test

ExampleSpec > test STARTED

ExampleSpec > parameterized [suffix] STARTED

ExampleSpec > parameterized [suffix] STARTED
```

**Comment by leonard84** [comment]
@ldaley could you motivate your usecase of a bit more. 
With Spock 2.0 we actually get proper nesting for iterations so those nodes won't be templated.

See also the comment https://github.com/spockframework/spock/pull/1238#pullrequestreview-539390236

**Comment by ldaley** [comment]
@leonard84 I commented on that PR.
