### ISSUE TITLE
Document @ConditionBlock annotation in the guide

### ISSUE THREAD

**Issue by Vampire** [spockframework/spock#1242]
Spock 0.7 added the `@ConditionBlock` annotation to support user-defined blocks with implicit annotations, but it is missing from the docs.

**Comment by johannesgottschalk** [comment]
Hi @Vampire I would like to take over this issue and add the annotation to the docs. Do I need to be assigned to this ticket or can I just go with the fix? Thanks for your support!

**Comment by leonard84** [comment]
@johannesgottschalk your comment is enough, if you have any question feel free to ask.

**Comment by AndreasTu** [comment]
@leonard84 Can you have a look at the PR, if this is enough documentation for the feature?
I am also not sure if the location of the docu is a good place in the `spock_primer`, I would say this is an advanced feature, but I did not see another section for such things, so I grouped in to the other mentions of conditions.
