### ISSUE TITLE
SpingBoot 1.5.22.RELEASE doesn't work well with spock

### ISSUE THREAD

**Issue by luckywzy** [spockframework/spock#1244]
I follow the example [example](https://github.com/spockframework/spock/blob/master/spock-spring/boot-test/src/test/groovy/org/spockframework/boot/SimpleBootAppIntegrationSpec.groovy)  in my company project.
but the ApplicationContext is null, also other spring bean is null too. spock cannot get spring application Context.
springboot version is 1.5.22.RELEASE,JDK is 1.8, maven is 3.x , Gradle is 'spock-core:1.1-groovy-2.4-rc-2',
its a bug?
please help me,thanks

**Comment by Vampire** [comment]
First question is, why are you using a release candidate of an age old version 1.1?
Can you please try with 1.3 or maybe even 2.0-M4?

**Comment by leonard84** [comment]
Did you include the `spock-spring` module or only `spock-core`?

**Comment by luckywzy** [comment]
Thank you for helping me solve the problem！！
I follow a wrong spock-core version cause this problem。
