### ISSUE TITLE
Data driven Feature: Display wrong number in the report

### ISSUE THREAD

**Issue by VijilPatodi** [spockframework/spock#1259]
Hello Team,

I am executing one scenario with data driven feature using where clause. It's working as expected however in report it is giving count as 1 scenario only. I want to show the number of time it is executed through iteration. 

For example:

def login ()
{

where:
username1| password1
username2| password2
username3| password3

}

instead of showing 
total pass Fail
3       2       1

it is showing
total pass Fail
1       0       1

How we can handle this?

**Comment by Vampire** [comment]
In 1.3 you have to manually unroll the feature using an annotation or an extension like https://github.com/szpak/spock-global-unroll.
See http://spockframework.org/spock/docs/1.3/all_in_one.html#_method_unrolling for more information.
In 2.0 this will be the default behaviour.
