### ISSUE TITLE
Groovyc: The current scope already contains a variable of the name 

### ISSUE THREAD

**Issue by davidobber** [spockframework/spock#1262]
#  Groovyc: The current scope already contains a variable of the name myParam

With Spock 2 (M4) - Groovy 3, there's a name clash between where variables and the parameter name of a anonymous class. 

The sample provided shows that a name used in the where table clashes with the name of a parameter of an anonymous class defined inside the test. Using different names or move the creation outside the test method solves the problem.

[sample.zip](https://github.com/spockframework/spock/files/5843299/sample.zip)
# How to reproduce

Just run this simple specification. 

~~~groovy
import spock.lang.Specification

interface TestInterface {
    void test(String myParam);
}

class TestInterfaceSpec extends Specification {

    def "a name used in the where clause clashes with the parameter name of the anonymous class method"() {
        given:
        TestInterface testInterface = new TestInterface() {
 //WORKAROUND change myParam in myParam1 or move the construction in a helper method
            @Override
            void test(String myParam) {
                println("hi, $myParam")
            }
        }

        when:
        testInterface.test(myParam)

        then:
        noExceptionThrown()

        where:
        myParam << "1"
    }
}

~~~

# Additional Environment information

## Java/JDK
~~~
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
~~~

## Groovy version
Groovy 3.0.7

### Gradle
Gradle 6.3

## Operating System
Windows 10

## IDE
~~~
IntelliJ IDEA 2020.3.1 (Community Edition)
Build #IC-203.6682.168, built on December 29, 2020
Runtime version: 11.0.9.1+11-b1145.63 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
~~~

### Gradle/Grails
~~~
implementation('org.codehaus.groovy:groovy-all:3.0.7')
testImplementation group: 'net.bytebuddy', name: 'byte-buddy', version:'1.9.3'
testImplementation "org.spockframework:spock-core:2.0-M4-groovy-3.0"
testImplementation 'cglib:cglib-nodep:3.2.4'
testImplementation group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.+'
~~~

**Comment by Vampire** [comment]
I don't think this should be "fixed".
The more verbose version of your spec is
```
import spock.lang.Specification

interface TestInterface {
    void test(String myParam);
}

class TestInterfaceSpec extends Specification {

    def "a name used in the where clause clashes with the parameter name of the anonymous class method"(myParam) {
        given:
        TestInterface testInterface = new TestInterface() {
 //WORKAROUND change myParam in myParam1 or move the construction in a helper method
            @Override
            void test(String myParam) {
                println("hi, $myParam")
            }
        }

        when:
        testInterface.test(myParam)

        then:
        noExceptionThrown()

        where:
        myParam << "1"
    }
}
```
(the change is the added parameter in the method)
It is just convenience by Spock that you can leave out the explicit parameter definition if you don't want to strongly type it.

So what you have is basically the same as
```
def foo(obj) {
    new Object() {
        @Override
        boolean equals(Object obj) {
            false
        }
    }
}
```
which simply is not allowed in Groovy.

**Comment by Vampire** [comment]
Or probably even
```
def foo(obj) {
    def obj
}
```
So if you just declare a local variable `myParam` in your feature method, it will probably fail with the same error.

**Comment by davidobber** [comment]
You're right, it fails with Groovy, even with the 2.5.13.

But it worked well with Spock 1.3.

testImplementation group: 'junit', name: 'junit', version:'4.+'
implementation('org.codehaus.groovy:groovy-all:2.5.13')
testImplementation "org.spockframework:spock-core:1.3-groovy-2.5"

This error happened converting tests from Spock 1.3 to Spock 2.0. This
is a reason why I've opened the issue.

David



Il giorno mer 20 gen 2021 alle ore 16:41 Björn Kautler <
notifications@github.com> ha scritto:

**Comment by Vampire** [comment]
Oh, that's an important detail you didn't mention before and an unexpected one actually.
Then it should at least be investigated a bit further.

**Comment by leonard84** [comment]
I'd assume this is caused by the change that introduced the usage of `VariableScopeVisitor` b0507d9e6a16d78f3dcd9b037237ce76c46c8c3f

**Comment by Vampire** [comment]
Hm, but then it was probably more a bug that it worked before.

**Comment by Vampire** [comment]
Yes, I quickly verified it is the change that includes the `VariableScopeVisitor` and if you explicitly declare the parameter it fails with the same message even without the `VariableScopeVisitor` change.

So unfortunately it was a bug that you could do this in 1.3.

**Comment by davidobber** [comment]
Ok, sounds good to me. I don't like this way of writing tests, they lack of
readability. Using an helper method is a better approach.


Il giorno mer 20 gen 2021 alle ore 19:58 Björn Kautler <
notifications@github.com> ha scritto:
