### ISSUE TITLE
Using @Retry with SETUP_FEATURE_CLEANUP mode incorrectly reports failed tests for unrolled features

### ISSUE THREAD

**Issue by rieske** [spockframework/spock#1267]
# Issue description
Using `@Retry` with `Retry.Mode.SETUP_FEATURE_CLEANUP` incorrectly reports failed tests for unrolled features.
An iteration failure is wrongly attributed to the subsequent iteration in the test report.

# How to reproduce
```groovy
@spock.lang.Retry(mode = spock.lang.Retry.Mode.SETUP_FEATURE_CLEANUP)
class RetrySpec extends spock.lang.Specification {
    def "retried feature"() {
        expect:
        false

        where:
        foo << ['a', 'b', 'c', 'd']
    }
}
```
will yield:
![image](https://user-images.githubusercontent.com/5560673/106254553-8503e580-6221-11eb-8f96-74f3802b1113.png)
The failure of the fourth iteration seems to be attributed to the feature method as seen in the test report:
![image](https://user-images.githubusercontent.com/5560673/106255193-63efc480-6222-11eb-96d3-7bf5c10a0412.png)

Without the Retry annotation, or when using `Retry.Mode.ITERATION`, the test failures are reported as expected:
![image](https://user-images.githubusercontent.com/5560673/106255326-93063600-6222-11eb-8334-715af25a29b5.png)
![image](https://user-images.githubusercontent.com/5560673/106255367-a1ece880-6222-11eb-8af0-c86635b0e8e6.png)
`spock.lang.Retry.Mode.SETUP_FEATURE_CLEANUP` also does not show this problem with `org.spockframework:spock-core:1.3-groovy-2.5`

Another case demonstrating the problem:
```groovy
@spock.lang.Retry(mode = spock.lang.Retry.Mode.SETUP_FEATURE_CLEANUP)
class RetrySpec extends spock.lang.Specification {
    def "confusing case"() {
        expect:
        result

        where:
        result << [true, false]
    }
}
```
In this case, only the second iteration is made to fail and the report looks like this:
![image](https://user-images.githubusercontent.com/5560673/106255653-fc864480-6222-11eb-9444-cfb966698852.png)
Flipping the where clause to `result << [false, true]` yields:
![image](https://user-images.githubusercontent.com/5560673/106259957-8c7abd00-6228-11eb-8853-37b400fd53ce.png)

# Additional Environment information

I used Gradle runner in IntelliJ and Gradle test reports.
I also tried it with a Maven project and using IntelliJ's test runner the reports showed the same problem.

## Build-tool dependencies used
`testImplementation("org.spockframework:spock-core:2.0-M4-groovy-3.0")`

**Comment by leonard84** [comment]
Seems we have overlooked a case, we already removed [Retry.Mode.FEATURE](http://spockframework.org/spock/docs/2.0-M4/release_notes.html#_misc_3) as it doesn't work properly with the changed reporting in JUnit Platform.
