### ISSUE TITLE
RepeatedTest analog in spock 2.0

### ISSUE THREAD

**Issue by rtretyak** [spockframework/spock#1285]
Spock version: `2.0-groovy-3.0-SNAPSHOT`
Problem: need a tool to repeat certain test _regardless_ of the outcome
Junit5 equivalent: [@RepeatedTest](https://junit.org/junit5/docs/current/user-guide/#writing-tests-repeated-tests)

I used to have a simple custom 'Rerun' extension for this purpose, but it no longer works in spock 2.0.
my extension for spock 1.3: [RerunExtension](https://github.com/telstra/open-kilda/blob/8158bf1cd10cce6e00373811a006db57cabf7966/src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/rerun/RerunExtension.groovy)
error I receive in spock 2.0:
```
java.util.NoSuchElementException
	at java.util.LinkedList.removeFirst(LinkedList.java:270)
	at org.spockframework.mock.runtime.MockController.leaveScope(MockController.java:76)
```
which is thrown right after the end of the second run (first repeated run).
Looking at available `@Retry`, I don't think it's possible to achieve with current implementation since it only retries on throwable thrown.
I unfortunately wasn't able to track down the issue or come up with a workaround, so any help/hint will be greatly appreciated.

**Comment by leonard84** [comment]
Do you need this for also for data-driven tests? Otherwise it would be just `where: i << (1..10)`

**Comment by rtretyak** [comment]
That should do the trick, thx
