### ISSUE TITLE
Unable to access a declared data variable from another data provider in 'where' block

### ISSUE THREAD

**Issue by rtretyak** [spockframework/spock#1289]
Spock version: `2.0-groovy-3.0-SNAPSHOT`
Test:
```
    def "test"() {
        expect: true

        where:
        a << [1, 2]
        b << [a + 1, a + 2]
    }
```
Error: ` groovy.lang.MissingPropertyException: No such property: a for class: `
Works fine in spock 1.3

**Comment by Vampire** [comment]
This is an intentional and documented breaking change: https://spockframework.org/spock/docs/2.0-SNAPSHOT/all_in_one.html#_no_access_to_data_variables_in_data_pipes_anymore
This only worked sometimes and could very easily lead to shooting yourself in the foot.

Your example should either be
```groovy
def "test"() {
    expect: true

    where:
    a | b
    1 | a + 1
    2 | a + 2
}
```
or
```groovy
def "test"() {
    expect: true

    where:
    a << [1, 2]
    aToB << [1, 2]
    b = a + aToB
}
```

**Comment by Vampire** [comment]
If you want more details you can also have a look at the according PR: https://github.com/spockframework/spock/pull/1111

**Comment by rtretyak** [comment]
Thank you. should have read the doc more carefully
