### ISSUE TITLE
Support for meta-annotations in extension annotations

### ISSUE THREAD

**Issue by szpak** [spockframework/spock#1309]
## Issue description

In some cases, it is useful to have an ability to define an extension annotation as meta-annotation. Especially, if it is non-trivial and is used across the test suite. That could be supported by Spock (as it is already by Spring Framework or JUnit Jupiter).

## Sample usage

```
@RunOnMacInCIPipeline
class MacOsSpecific17Spec extends Specification { ... }

@Target({ ElementType.TYPE, ElementType.METHOD })
@Retention(RetentionPolicy.RUNTIME)
@Requires({ os.macOs })
@Requires({ env['CI'] != null })
public @interface RunOnMacInCIPipeline {
}
```

## Implementation cases

1. As repeatable annotations are supported, probably those placed directly and those in meta-annotation could be splashed and considered together.
2. For not repeatable annotation probably it could be still done at the annotation parsing level.
3. Meta-annotations should be considered the same way as regular/direct annotations while processing them together with other level annotations (e.g. a meta-annotation at the method level should be the same strong as a direct annotation while compared to a class level annotation).

## Other notes

This change is not backward compatible, but the impact should be minimal. 2.0 would be a good candidate, but it might be decided to add it also in the 2.x minor release.

**Comment by leonard84** [comment]
Can't you just use an [AnnotationCollector](https://docs.groovy-lang.org/latest/html/api/groovy/transform/AnnotationCollector.html) ?

**Comment by szpak** [comment]
Thanks Leonard. I have to admit, I didn't know `AnnotationCollector`. I gave it a try and it does what I wanted. Probably it is not worth to invest into a separate support for meta-annotations. Closing.

Btw, Idea seems to cache the compiled annotation and after the lambda expression is changed it requires to clean/rebuild project to make it visible. Nevertheless, it doesn't seem to be Spock specific.

**Comment by leonard84** [comment]
> Btw, Idea seems to cache the compiled annotation and after the lambda expression is changed it requires to clean/rebuild project to make it visible. Nevertheless, it doesn't seem to be Spock specific.

You could open an issue for IDEA for that.

**Comment by szpak** [comment]
> You could open an issue for IDEA for that.

Definitely I plan, after further investigation.

Btw, recently they resolved (as fixed!) the ticket I created [11 years ago](https://youtrack.jetbrains.com/issue/IDEA-57574), so there is a hope ;-)

**Comment by leonard84** [comment]
@szpak would you perhaps be willing to write a small chapter in the docs regarding this?

**Comment by szpak** [comment]
Good Idea. I also plan to add some basic unit tests for `@AnnotationCollector`, to track possible regressions (e.g. with Groovy version changes).

**Comment by szpak** [comment]
FYI. There are [some](https://issues.apache.org/jira/browse/GROOVY-10040) [issues](https://issues.apache.org/jira/browse/GROOVY-10041) with `@AnnotationCollector` and extensions (annotations) using `Closure` (such as `@Required` and `@IgnoreIf`) which makes it harder to write regression tests. I will cover that feature (in tests and documentation) later on, once they are resolved upstream.
