### ISSUE TITLE
IAnnotationDrivenExtension - how to get the contents of the where block

### ISSUE THREAD

**Issue by Bjego** [spockframework/spock#1317]
Hey guys,
when I'm writing my own IAnnotationDrivenExtension  and overriding:
`
@Override
    void visitFeatureAnnotation(SomeImpl instance, FeatureInfo featureInfo)
`
how do I get the contents of the where block? 
Tried to get it via the block -> getText()
and also via the dataproviders.

Is there a simple way to get the plain where block as text, or to resolve the values?

Thanks

**Comment by Vampire** [comment]
`getTexts()` is a bit misleading maybe.
It is not about getting the content of the block.
You can have
```groovy
where: 'foo'
    a | _
    1 | _
```
then `foo` will be in that returned list.

I don't think what you want is possible, not even via parsing bytecode as the where block completely gets rewritten during compilation.
What do you actually want to achieve, what is your use-case?
If you really need the text content, you would probably need an AST transformation that runs before the one of Spock that captures the text for you.

**Comment by Bjego** [comment]
Ah I think I spotted something - will use the IRunListener interface !

**Comment by kriegaex** [comment]
I don't see how that gives you the literal where block source code. The closest would be the iteration info and the data values as a part of it.

If you ask a question and then close it with an unrelated comment and without further explanation about how what you found solves your problem, at the same time ignoring the person's question who volunteered to help you - Björn asked what you actually want to achieve - in my opinion that is at least careless and borders on rude.
