### ISSUE TITLE
Update Spock Release notes on main website

### ISSUE THREAD

**Issue by renatoathaydes** [spockframework/spock#1327]
I've noticed that the "official" release notes only include the 1.x branch releases.

https://spockframework.org/spock/docs/1.3/release_notes.html

You get redirected to this page (1.3 release) if you go to https://spockframework.org/spock/docs/ so I suppose this is what most people see when looking up the Spock latest version.

This is making Spock look like an abandoned project, as the last release was in March 2019, over 2 years ago now. I actually found out about this because of a colleague who asked me if Spock had been abandoned!

I know it's not abandoned as I've been following the large amount of work that's going into the 2.x branch, but that's not very visible from the website.

If you do not want to make the 2.x branch visible on the website yet, perhaps add a note with a link to the latest release candidate release notes: https://github.com/spockframework/spock/blob/master/docs/release_notes.adoc

That would make it apparent that Spock is just doing a lot of work behind the scenes :)

Thanks!

**Comment by leonard84** [comment]
Well, Spock 2.0 has been released so I'd say this issue is fixed.

**Comment by renatoathaydes** [comment]
Timely 👍
