### ISSUE TITLE
2.0 final - regression with `thrown` block

### ISSUE THREAD

**Issue by boris-petrov** [spockframework/spock#1332]
# Issue description
This worked in `2.0-M5-groovy-3.0` but broke in `2.0-groovy-3.0`.

# How to reproduce
```groovy
package test

import spock.lang.Specification

class SomeSpec extends Specification {
	def 'bar'() {
		when:
		def (a, b) = foo()

		then:
		thrown(Exception)
	}
}
```

The problem is with the deconstruction of the result of `foo()`. With it the Spock compiler blows up:

```
Description	Resource	Path	Location	Type
Groovy:Unexpected error during compilation of spec 'test.SomeSpec'. Maybe you have used invalid Spock syntax? Anyway, please file a bug report at http://issues.spockframework.org.
```

# Additional Environment information
Eclipse IDE. Same result with Gradle.

## Java/JDK
```
openjdk 15.0.2 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7)
OpenJDK 64-Bit Server VM (build 15.0.2+7, mixed mode)
```

## Groovy version
3.0.7

## Build tool version
`2.0-groovy-3.0`

### Gradle
`Gradle 7.0.2`

## Operating System
Linux

## IDE
Eclipse

**Comment by leonard84** [comment]
This is probably caused by #1314
