### ISSUE TITLE
Error message points to non-existent link

### ISSUE THREAD

**Issue by ndw** [spockframework/spock#1343]
## Describe the bug

I attempted to use `org.spockframework:spock-core:1.3-groovy-2.5` with Gradle 7.0. I get:

> Could not instantiate global transform class org.spockframework.compiler.SpockTransform specified at jar:file:/Users/ndw/.gradle/caches/modules-2/files-2.1/org.spockframework/spock-core/1.3-groovy-2.5/6f0df2cf4549dcc4b914971675da7e224e893e82/spock-core-1.3-groovy-2.5.jar!/META-INF/services/org.codehaus.groovy.transform.ASTTransformation  because of exception org.spockframework.util.IncompatibleGroovyVersionException: The Spock compiler plugin cannot execute because Spock 1.3.0-groovy-2.5 is not compatible with Groovy 3.0.7. For more information, see http://versioninfo.spockframework.org

Unfortunately, `versioninfo.spockframework.org` appears not to exist:

```
$ curl http://versioninfo.spockframework.org
curl: (6) Could not resolve host: versioninfo.spockframework.org
```

(I have a related problem, namely that upgrading to 2.0-groovy-3.0 no longer fails in this way, but silently ignores my tests. I'm assuming that's a Gradle issue not a Spock framework issue, but I could be mistaken.)

**Comment by Vampire** [comment]
For the URL, we are waiting for Cloudflare to answer, whether we get an OSS free account, so that we can have more HTTPS Subdomains.

For your other problem, you probably should read the release notes / breaking changes / migration section. My guess is, that you just changed the dependency. While 1.x was JUnit 4 based, 2+ is now a JUnit 5 platform engine, so you need to change that in Gradle too.

**Comment by szpak** [comment]
> I attempted to use org.spockframework:spock-core:1.3-groovy-2.5 with Gradle 7.0. I get:

I suspect, that in the case you want to use Spock in Gradle plugin development, the root reason before the error message might be the fact that Gradle 7 switched to Groovy 3 and you would need to have a Groovy 3 compatible Spock version (e.g. 2.0-groovy-3.0).

I agree with @Vampire in the other case - maybe you miss:

```
test {
    useJUnitPlatform()
}
```

in your [configuration](https://docs.gradle.org/current/userguide/java_testing.html#using_junit5)?

**Comment by leonard84** [comment]
The link was changed in 9d3e28cd111d611c702336c74c45cd8e69028253
