### ISSUE TITLE
Add onTimeout support for PollingConditions

### ISSUE THREAD

**Issue by leonard84** [spockframework/spock#1355]
### Is your feature request related to a problem?

Sometimes you want to log some additional information when a `waitFor` times out.

### Describe the solution you'd like

Add a `String onTimeout(Closure<Throwable>)` that is called when the retries are exceeded, which returns a `String` that is then added to the `SpockTimoutError` message. If the methods is called repeatedly, only the last closure is used, when called with `null` it will disable it again.

### Describe alternatives you've considered

It would also be possible to add a second argument to the `within`/`eventuall` methods, but having multiple closures is confusing, and the proposed solution has the added benefit that it can be configured in `setup` and shared by multiple tests, instead of having to be repeated.

**Comment by questras** [comment]
Hello, I would like to implement this feature.
