### ISSUE TITLE
Failed assumption in iteration interceptor leads to unexpected behavior

### ISSUE THREAD

**Issue by rtretyak** [spockframework/spock#1367]
### Describe the bug

When TestAbortedException is thrown from within the iteration interceptor before the iteration is executed, then current iteration is aborted, but marked as 'success', and ALL further iterations of this feature are skipped instantly.

### To Reproduce

Extension:
```
class IterationAbortExtension implements IGlobalExtension {

    @Override
    void visitSpec(SpecInfo spec) {
        spec.getAllFeatures().each { feature ->
            feature.addIterationInterceptor(new IMethodInterceptor() {
                @Override
                void intercept(IMethodInvocation invocation) throws Throwable {
                    assumeFalse(invocation.iteration.displayName.contains("abort me"))
                    invocation.proceed()
                }
            })
        }
    }
}
```

Spec:
```
class Test extends Specification {
    def "#name"() {
        expect: true
        where: name << ["run me", "abort me", "run me", "abort me", "run me"]
    }
}
```

Result:
![image](https://user-images.githubusercontent.com/7931639/129586954-5bb5731a-b00d-4353-b001-d12384e4e616.png)

### Expected behavior

Iterations which fail the assumption check are marked as skipped(aborted). All the iterations chain is not aborted after the first assumption failure.

### Actual behavior

First iteration which fails the assumption check is marked as success. All the further iterations are aborted after the first assumption failure.

### Java version

1.8

### Buildtool version

gradle 6.9

### What operating system are you using

Windows

### Dependencies

spock 2.0-groovy-3.0

### Additional context

This example worked as expected in spock 1.3.
The original purpose of calling assumptions in iteration interceptor was for my custom tag-manager extension. I used to do assumptions before `invocation.proceed` in order to skip certain iterations that did not match the requested tags. Now I realized my extension does not work anymore.
If this new behavior was intended for spock2.0, please suggest the way I can skip a certain iteration using spock extenstions.

**Comment by leonard84** [comment]
If you replace `feature.addIterationInterceptor` by `feature.featureMethod.addInterceptor`, then it works as expected.

Reproducer for the op code

```groovy
import org.spockframework.runtime.extension.*
import org.spockframework.runtime.model.*;
    
import java.lang.annotation.*;
    
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
@ExtensionAnnotation(SkipperExtension)
@interface Skipper {}

class SkipperExtension implements IAnnotationDrivenExtension<Skipper> {
    @Override
    void visitFeatureAnnotation(Skipper skip, FeatureInfo feature) {
        feature.addIterationInterceptor(new IMethodInterceptor() {
                @Override
                void intercept(IMethodInvocation invocation) throws Throwable {
                    if (invocation.iteration.displayName.contains("abort me")) {
                        throw new org.opentest4j.TestAbortedException("Aboooort!")
                    }
                    invocation.proceed()
                }
            })
    }
}

class ASpec extends Specification {
    @Skipper
    def "test"() {
        expect: true
        
        where:
        a | b
        1 | "hello"
        2 | "abort me"
        3 | "world"
        4 | "foo"
    }
}
```
[On Groovy WebConsole](https://gwc-experiment.appspot.com/?codez=eJyFU8Fu2zAMvfsrOJ_sohCwraduGBKgHuZD2qH1PkCx6ESNLAmS4iTo8u-THFtO1gDlReQj-UhKFG-1Mg6UWRGrVb1pDG1xp8yGmK10vEWCe4fSciXJTcI_jG4VQ0FuviXgZYx_pR0lgsoVoVIqR13PNsTMntEXCFAWtd9K8PpAnv88VuWiyJNZRc0KXVYIbH1EddBIFkX16-nB-4qxwXkkz142XGs00eXDuHRoGlojDE54OyZJLai18H84-MZPpSyUE-2D4R3KGPV9SPsBb_0os6cOjeEMe6tTnEHHLXc_kbqtwfftgfXnLQz-UjYKmpOeD5RBBohQxko_Qs9QhmFq1E6ZTOIOygW6tWLn8DnFKJcdnkvfLR_Ts8jXqbov6H2jmoNbG7WzUIWDLgVeqRSEN5BNaYSPzRPGrRb08OiXh9RKOsqlzVK6DLvSYppfa32UvjaEmcMWKu3fCK27eyWVP-aBAlmxD0OEi0494sW4T2l-lfJ4vfOpa21Ujciy9-mXqcdTwDGJSzV_0VhD_32YXzFv8IYPtzkszLAHvcGwgTTMkl48He59orsHZ7bTq0Vlt0aD99Gk8BeW0frsrXSNQqg0Yl8CFm86wl8D7D-yYBN2F7BGDcn9YBcT_wOByEaG)
