### ISSUE TITLE
Call order for @Before and @After when using the spock-junit4 extension is different

### ISSUE THREAD

**Issue by longwa** [spockframework/spock#1396]
### Describe the bug

When natively running with JUnit 4 and Spock 1.x, if you have something like below in a test:

It will execute as:
    beforeEach
    setup
    test method 1
    cleanup
    afterEach

With the spock-unit4 extension running in JUnit 5 and Spock 2.1-M2, it runs as:
    setup
    beforeEach
    test method 1
    cleanup
    afterEach

We use a lot of traits and/or base classes to define @Before logic to configure things before the localized setup and cleanup methods run and now they run out of order.

Also, it would at least make sense to run them such that the teardown is the reverse order.

It seems like Spock 2.0 doesn't really support the newer BeforeEach and AfterEach either, so our only choice seems to be writing custom spock extensions.

### To Reproduce

```
    def "test method 1"() {
        when:
        println "test method 1"

        then:
        true
    }

    @Before
    void beforeEach() {
        println "beforeEach"
    }

    @After
    void afterEach() {
        println "afterEach"
    }

    void setup() {
        println "setup"
    }

    void cleanup() {
        println "cleanup"
    }
```

### Expected behavior

The hooks should run in the same order as natively on JUnit 4

### Actual behavior

The hooks run in an order that is not super useful.

### Java version

11.0.13

### Buildtool version

gradle 7.2

### What operating system are you using

Mac

### Dependencies

```
spock.version=2.1-M2-groovy-3.0
junit4Version=4.13.2    

testImplementation "org.spockframework:spock-core:${project.'spock.version'}"
testImplementation "org.codehaus.groovy:groovy-test-junit5:$groovyVersion"
testImplementation(platform('org.junit:junit-bom:5.8.1'))
testImplementation('org.junit.jupiter:junit-jupiter')
testImplementation "org.spockframework:spock-junit4:${project.'spock.version'}"

testImplementation "junit:junit:$junit4Version"
testRuntimeOnly "org.junit.vintage:junit-vintage-engine"
```

**Comment by szpak** [comment]
It's a side effect of the [refactoring](https://github.com/spockframework/spock/pull/1128) needed to remove junir4 from transitive dependencies of spock-core.

Closing, as it is documented as a breaking change in 2.0-M3:
https://spockframework.org/spock/docs/2.0/release_notes.html#_removal_of_junit_4_dependency_from_spock_core
