### ISSUE TITLE
Interaction count mismatch interrupts business logic

### ISSUE THREAD

**Issue by lobodpav** [spockframework/spock#1399]
### Describe the bug

When a `then` section expects <ins>more interaction count</ins> with a mock than actually happened, the `when` section is fully executed and then the amount of interactions is evaluated. That is what is expected.

However, when a `then` section expects <ins>less interaction count</ins> with a mock than actually happened, the business logic is interrupted and the test fails.

I.e.:
When the `Too few invocations` test is run, it fails with
```
Too few invocations for:

6 * mock.method()   (2 invocation)
``` 

This is expected.

However, when the `Too many invocations` test is run, it fails with
```
Too many invocations for:

1 * mock.method()   (2 invocations)
```

Rather than saying that `1 * mock.method()   (4 invocations)`

This makes identifying the test issues more difficult. The worst thing, however, is that it actually **interrupts** the business logic. When the mocked code is called from a `stream` during debugging, the debugger won't stop on the third item because Spock terminates the code execution after the second invocation when it decides that the number of invocations is higher than the number of expected invocations. 

### To Reproduce

```groovy
class InteractionCounterSpec extends Specification {

    def mock = Mock(TestClass)

    def "Too few invocations"() {
        when:
        2.times { mock.method() }

        then: "Prints out Too few invocations for:   6 * mock.method()   (2 invocation)"
        6 * mock.method()
    }

    def "Too many invocations"() {
        when:
        4.times { mock.method() }

        then: "Prints out Too many invocations for:   1 * mock.method()   (2 invocations)"
        1 * mock.method()
    }
}

class TestClass {
    def method() {}
}
```

### Expected behavior

The comparison of *actual* and *expected* number of invocations should be made after the whole `when` block is evaluated, to prevent interruption of business logic execution.

### Actual behavior

The business logic is terminated when the actual number of invocations exceeds the number of expected invocations.

### Java version

openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Homebrew (build 11.0.12+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.12+0, mixed mode)

### Buildtool version

------------------------------------------------------------
Gradle 7.3
------------------------------------------------------------

Build time:   2021-11-09 20:40:36 UTC
Revision:     96754b8c44399658178a768ac764d727c2addb37

Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.12 (Homebrew 11.0.12+0)
OS:           Mac OS X 12.0.1 x86_64

### What operating system are you using

Mac

### Dependencies

```
+--- project :Library:test
|    +--- org.spockframework:spock-bom:2.0-groovy-3.0
|    |    +--- org.spockframework:spock-core:2.0-groovy-3.0 (c)
|    |    \--- org.spockframework:spock-spring:2.0-groovy-3.0 (c)
|    +--- org.spockframework:spock-core -> 2.0-groovy-3.0
|    |    +--- org.junit:junit-bom:5.7.2
|    |    |    +--- org.junit.platform:junit-platform-engine:1.7.2 (c)
|    |    |    +--- org.junit.platform:junit-platform-testkit:1.7.2 (c)
|    |    |    +--- org.junit.platform:junit-platform-commons:1.7.2 (c)
|    |    |    \--- org.junit.platform:junit-platform-launcher:1.7.2 (c)
|    |    +--- org.codehaus.groovy:groovy:3.0.8
|    |    +--- org.junit.platform:junit-platform-engine -> 1.7.2
|    |    |    +--- org.junit:junit-bom:5.7.2 (*)
|    |    |    +--- org.apiguardian:apiguardian-api:1.1.0
|    |    |    +--- org.opentest4j:opentest4j:1.2.0
|    |    |    \--- org.junit.platform:junit-platform-commons:1.7.2
|    |    |         +--- org.junit:junit-bom:5.7.2 (*)
|    |    |         \--- org.apiguardian:apiguardian-api:1.1.0
|    |    +--- org.junit.platform:junit-platform-testkit -> 1.7.2
|    |    |    +--- org.junit:junit-bom:5.7.2 (*)
|    |    |    +--- org.apiguardian:apiguardian-api:1.1.0
|    |    |    +--- org.assertj:assertj-core:3.16.1
|    |    |    +--- org.opentest4j:opentest4j:1.2.0
|    |    |    \--- org.junit.platform:junit-platform-launcher:1.7.2
|    |    |         +--- org.junit:junit-bom:5.7.2 (*)
|    |    |         +--- org.apiguardian:apiguardian-api:1.1.0
|    |    |         \--- org.junit.platform:junit-platform-engine:1.7.2 (*)

```

**Comment by leonard84** [comment]
This is working as intended, keep in mind that you can combine mocking and stubbing, i.e., `1 * mock.method() >> "some value"` this would stop returning the mocked value after the invocations are exhausted. If we change this, then it would stop responding with a stubbed value and return `null`. 

Another issue with letting it continue, is that it could lead to further violated interactions potentially shadowing the root cause or at least making it really hard to figure out what caused the issue.

How should Spock display the error if there were 100+ additional invocations, would that be more helpful?

--- 

> When the mocked code is called from a stream during debugging, the debugger won't stop on the third item because Spock terminates the code execution after the second invocation when it decides that the number of invocations is higher than the number of expected invocations.

I would simply temporarily change the limit to `_` so that I can debug.

---

If the method has a parameter they will be reported properly.
[Groovy Console](https://gwc-experiment.appspot.com/?codez=eJydkUFrAjEQhe_7Kx572ngQKqUHwZOnHgSh3suSncXQJiObWbWI_71JtFEXoeJcksm8eZOP0d-193h3Ql2txbCbcx-Tjw1p0F7INR4xMa3RdRTgUBQI0VALy_oLMyzCUa3Iyzy6qUu9XDGjpR2M2_Kp3ZeVChY4x25NbpqzyViMJY9Dch5bkjU3lRGFY5FFEltQLjvjxIN7wZ0paLmbBvEbRjdeKrxVkyulKrPxUPupUuk44LG1-3kU6PV5oOGYP6KX_4j8FdJQnJHCeJ1Wn9d2ZkhrPYnj1fU20CX95cMxfgEbpqZ6)

```
╷
└─ Spock ✔
   └─ InteractionCounterSpec ✔
      ├─ Too few invocations ✘ Too few invocations for:
      │     
      │        6 * mock.method(_)   (2 invocations)
      │     
      │        Unmatched invocations (ordered by similarity):
      │     
      │        None
      └─ Too many invocations ✘ Too many invocations for:
            
               1 * mock.method(_)   (2 invocations)
            
               Matching invocations (ordered by last occurrence):
            
               1 * mock.method(1)   <-- this triggered the error
               1 * mock.method(0)
```

**Comment by lobodpav** [comment]
The example I've provided is a greatly simplified version. In my real-world case, I was debugging stubbed interactions.

In my real app, I made a mistake and said that the number of interactions is to be `1` whereas the mock was called `6` times. When the code stopped at a breakpoint, I knew I had 6 items in a stream but only 2 items were processed and the test was ended.

Just by an accident, I was debugging deep enough to get into a `catch` block where I've seen a Spock exception, and at that point in time, I figured why just 2 of my stream items were processed.

To be honest, even after all these years of coding tests in Spock, I thought the number of invocations is only used to match against the real number of mock/stub invocations.

The behaviour I would expect is:
1. The mocked `mock.method()` would always return `"some value"` no matter the interaction count. This would be consistent with the behaviour of `_ * mock.method() >> "some value"` as well as with `mock.method() >> "some value"` without any interaction count.
2. At the end of the test, the expected number of invocations would be compared to the number of real invocations, actually the same way as for the `Too few invocations` test.
3. If a mock is called more times than it should, I don't see any issue with that as far as it keeps on returning the `"some value"`. If I don't specify the interaction count, my code can execute the mock as many times as it wants anyway.

This way seems consistent to me. But I might not be aware of some other scenarios that you are likely aware of.

**Comment by leonard84** [comment]
If you only saw Spock's `TooManyInvocationsError` in a catch block, then your production code is catching `Error` or `Throwable` which shouldn't be done normally and will lead to weird problems when handled incorrectly (such as this one apparently).

---

```
class Foo extends Specification {
  def "list"() {
    given:
    List mock = Mock()

    when:
    5.times { mock.add(it) }

    then:
    2 * mock.add(_)
  }
}
```

will report as 
```
Too many invocations for:

2 * mock.add(_)   (3 invocations)

Matching invocations (ordered by last occurrence):

1 * mock.add(2)   <-- this triggered the error
1 * mock.add(1)
1 * mock.add(0)



	at org.spockframework.mock.runtime.MockInteraction.accept(MockInteraction.java:70)
	at org.spockframework.mock.runtime.MockInteractionDecorator.accept(MockInteractionDecorator.java:50)
	at org.spockframework.mock.runtime.InteractionScope$1.accept(InteractionScope.java:57)
	at org.spockframework.mock.runtime.MockController.handle(MockController.java:40)
	at org.spockframework.mock.runtime.JavaMockInterceptor.intercept(JavaMockInterceptor.java:84)
	at org.spockframework.mock.runtime.DynamicProxyMockInterceptorAdapter.invoke(DynamicProxyMockInterceptorAdapter.java:34)
	at Foo.list_closure1(Foo.groovy:10)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:428)
	at Foo.list(Foo.groovy:10)
```

with the stacktrace pointing add the point where it occurred. Interactions don't capture a stacktrace, as this costs performance. So, if we only validated the count after the `when` has finished, we now have no idea where it happened. To fix that we would have to record the stacktrace for every interaction that occurs, just in case we might need it later and incur the cost of creating a stacktrace every time.

---

Another thing to keep in mind are [ordered interactions](https://spockframework.org/spock/docs/2.0/all_in_one.html#_invocation_order_2), they would not work if we didn't consider the mock to be exhausted after it's interaction limit has been reached.

```
  def "ordered interaction"() {
    given:
    List mock = Mock()

    when:
    5.times { mock.add(it) }

    then:
    1 * mock.add(0)
    then:
    1 * mock.add(1)
    then:
    1 * mock.add(2)
    then:
    1 * mock.add(3)
    then:
    1 * mock.add(4)
  }
```

**Comment by lobodpav** [comment]
My code indeed catches `Exception` on a root level, logs that error to the database and re-throws the exception.

I was afraid there is something else that will prevent evaluating the interaction count after the `when` block finishes. The ordered interactions make sense to me, I'm not really sure what I would expect the mock to return if all interactions are exhausted.

Not sure I understand the `stacktrace` issue though. If the code throws, the test would end with an unexpected exception. If the code works normally, why should any stacktrace be needed? The only thing I am interested in is to see that the mock was called 5-times whereas I declared it should be run 2-times only. If I get a list of all the extra invocations, I would be happy. What do I miss?

Anyway, it is a pity. It would be nice to at least see the amount of `mock.add(it)` calls in the log, which should be `5` if the code wouldn't get interrupted.

When having a data-driven test, it is often the case that incorrect data cause the extra mock calls. Without the total amount of interactions, I have no idea how many times the mock would be actually executed to understand what data are wrong.

**Comment by leonard84** [comment]
> Not sure I understand the stacktrace issue though. If the code throws, the test would end with an unexpected exception. If the code works normally, why should any stacktrace be needed? The only thing I am interested in is to see that the mock was called 5-times whereas I declared it should be run 2-times only. If I get a list of all the extra invocations, I would be happy. What do I miss?

The mock might be called in completely different places, so the stacktrace helps locate where the offending call came from.

>Anyway, it is a pity. It would be nice to at least see the amount of mock.add(it) calls in the log, which should be 5 if the code wouldn't get interrupted.

You can easily get this number, if you temporarily set the expected count to a high number so that it fails with `Too few interations`, which will tell you the actual invocations.

**Comment by lobodpav** [comment]
Thanks for all your help, @leonard84!

Even though I think it would be much better when Spock would handle these automatically, at least I now have the understanding of why it behaves the way it does, and what do to if I meet this problem again 😊
