### ISSUE TITLE
Defining responses for `additionalInterfaces` doesn't work

### ISSUE THREAD

**Issue by boris-petrov** [spockframework/spock#1405]
### Describe the bug

There is some additional context [here](https://gitter.im/spockframework/spock?at=61c4286e82a4667b25403d7f). Check the reproduction for explanation what the bug is.

cc @leonard84

### To Reproduce

```groovy
class A {}
class B {}
interface C { B foo() }
...
def a = Stub(A, additionalInterfaces: [C]) {
    foo() >> { println 2; new B() }
}
println(a instanceof C)
def b = a.foo()
println b.getClass()
```

### Expected behavior

To print `true`, `2` and `class B`.

### Actual behavior

Prints `true` and `class java.lang.Object`.

### Java version

openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12)
OpenJDK 64-Bit Server VM (build 17.0.1+12, mixed mode)

### Buildtool version

------------------------------------------------------------
Gradle 7.3.3
------------------------------------------------------------

Build time:   2021-12-22 22:43:07 UTC
Revision:     <unknown>

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.1 (Oracle Corporation 17.0.1+12)
OS:           Linux 5.15.10-arch1-1 amd64

### What operating system are you using

Linux

### Dependencies

Spock is the only dependency. Any version (including `2.1-M2`).

**Comment by AndreasTu** [comment]
The PR #1730 should resolve this issue.
