### ISSUE TITLE
The method X has an incorrect modifier transient

### ISSUE THREAD

**Issue by renatoathaydes** [spockframework/spock#1431]
### Describe the bug

We use a Groovy trait from a Spock Specification. It looks like this:

```groovy
trait MyTrait {

    String loadKeyStoreFrom(String url, char[] passwordChars = null) {
        ''
    }

}
```

Example Spec:

```groovy
class ExampleSpec extends Specification implements MyTrait {
    def 'my test'() {
        expect:
        loadKeyStoreFrom('', ''.chars) == ''
    }
}
```

Compiling this results in an error.

### To Reproduce

Try to compile and run the specification pasted in the example.

### Expected behavior

The specification should compile and run without issues.

### Actual behavior

```
groovy-tests/src/test/groovy/tests/ExampleSpec.groovy: -1: The method 'java.lang.String loadKeyStoreFrom(java.lang.String, [C)' has an incorrect modifier transient.
 @ line -1, column -1.
1 error
```

### Java version

Tried both:
* 17.0.2 (Oracle Corporation 17.0.2+8-86)
* 11.0.14 (Azul Systems, Inc. 11.0.14+9-LTS)

### Buildtool version

```
------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.14 (Azul Systems, Inc. 11.0.14+9-LTS)
OS:           Mac OS X 12.2.1 aarch64
```

This happens on Intel Mac as well, not specific to ARM.

### What operating system are you using

Mac

### Dependencies

```groovy
dependencies {
    def spockVersion = '2.2-M1-groovy-4.0'
    implementation 'org.apache.groovy:groovy:4.0.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.2'
    testImplementation ("org.spockframework:spock-core:$spockVersion") {
        exclude group: 'org.apache.groovy'
        exclude group: 'org.junit'
    }
}
```

### Additional context

The Groovy class can be compiled and executed properly when not using Spock.

A JUnit test that implements that trait runs without problems.

The Spock specification runs without problems when compiled with Groovy 3 and Spock `2.1-groovy-3.0`.

**Comment by renatoathaydes** [comment]
This error also occurs when I use an `interface` instead of `trait`:

```groovy
interface MyTrait {

    default String loadKeyStoreFrom(String url, char[] passwordChars) {
        ''
    }

}
```

**Comment by renatoathaydes** [comment]
The problem appears to be due to the array in the argument.
When I remove the type of `passwordChars` then it works correctly:

```groovy
interface MyTrait {

    default String loadKeyStoreFrom(String url, passwordChars) {
        ''
    }

}
```

**Comment by leonard84** [comment]
@renatoathaydes a simple test in the [Groovy Web Console](https://gwc-experiment.appspot.com/?g=groovy_4_0&codez=eJxljssKwjAQRff5itmlQvEDhK5EN-Kq7sRFSKYayKMkI6ZI_92kluLjbmbuPA8FoQmOw2mKTwZZLQXtrmC8UAccWvIB98Hbaq7fg6lB3kQ4X6AXMT58UNts42reL-J8Skc2MiZNnoJdErY32PYoAROhUxGK0Z2WgrR3oEvfoqP4A6SwA24HIIzEq883mPIF2iz-j5nzOrOs5Zuvab7AlrWiF8A-Tt0) did not reproduce the problem.

**Comment by renatoathaydes** [comment]
Interesting. I can send you the full project.

**Comment by renatoathaydes** [comment]
It's on GitHub: https://github.com/renatoathaydes/spock-groovy4-trait-issue/runs/5300419761?check_suite_focus=true
As you can see, I setup a GitHub Action to run the spec and it fails with this problem there as well.
I suspect the Groovy Web Console is not correctly setting up Groovy 4 and Spock if it doesn't show this problem.

**Comment by leonard84** [comment]
Interestingly, this only happens if the `trait` and the spec are in different compilation units, when both are in `test` then this doesn't happen.

@paulk-asert this seems to be a groovy 4 bug, WDYT?

**Comment by renatoathaydes** [comment]
I don't think it's a Groovy bug because when I convert the Spock test  to JUnit it works fine. @leonard84 Have you tried that?

**Comment by renatoathaydes** [comment]
Ah, scrap that.

I must've tried when the trait was also on the test folder!!

It does happen with pure Groovy:

```groovy
class ExampleSpec
//        extends Specification
        implements MyTrait {

    @Test
    def 'my test'() {
//        expect:
        loadKeyStoreFrom('', ''.chars) == ''
    }

}

```

I can report that to the Groovy maintainers! Sorry about that.

**Comment by renatoathaydes** [comment]
https://issues.apache.org/jira/browse/GROOVY-10513
