### ISSUE TITLE
EnableSharedInjection is package private

### ISSUE THREAD

**Issue by erdi** [spockframework/spock#1471]
### Describe the bug

`@EnableSharedInjection` is package private while it clearly is intended to be used outside of `org.spockframework.spring` package and therefore should be public.

### To Reproduce

Just try to annotate a spec with `@EnableSharedInjection` in IntelliJ and it will mark the usage as exceeding access rights

### Expected behavior

Intellij should not mark usages of `@EnableSharedInjection` on specs as exceeding access rights

### Actual behavior

Intellij marks usages of `@EnableSharedInjection` on specs as exceeding access rights

### Java version

N/A

### Buildtool version

N/A

### What operating system are you using

Mac

### Dependencies

N/A

**Comment by jonnybot0** [comment]
Hope I'm not overstepping, but I figured this was an easy fix & I'd JFDI.
https://github.com/spockframework/spock/pull/1472

**Comment by erdi** [comment]
I definitely overlooked it when contributing that class. And the reviewer also missed it. ;) As you say, sometimes it's easy to not notice that you're no longer in Groovy...

**Comment by szpak** [comment]
Fixed by #1472.
