### ISSUE TITLE
Unable to access protected constant when spying instances

### ISSUE THREAD

**Issue by victorcm-iriusrisk** [spockframework/spock#1501]
### Problem
I have a test that spies an instance:

```
private MainKnowledgeSessionService service

    void setup() {
        service = new MainKnowledgeSessionService()
        
        [... hidden code for clarity...]
    }

    @Unroll
    void "test"() {
        given: "an spy of the service"
        MyService spiedService = Spy(service)

        when:
        spiedService.runMethod(param)
        
        then:
        true
    }
```
The service class that I’m spying is defined in groovy as _MyService.groovy_ as this:

```
@Transactional
@Service
class MyService extends ParentService {
  [... hidden code for clarity...]
}
```
The parent service is defined in java as _ParentService.java_ as this:

```
public abstract class ParentService {

    protected static final boolean MONITOR_ENABLED = LoggerFactory.getLogger(ParentService.class).isDebugEnabled();
```
As you can see the constant _MONITOR_ENABLED_ is protected so it is accesible from the _MyService_ class.

But, when I run the test, in some part of the _MyService_ I execute this block of code:

```
if (MONITOR_ENABLED) {
    // whatever
}
```
Then, I that point, the tests is failing with this error:

```
No signature of method: com.foo.services.MyService.getMONITOR_ENABLED() is applicable for argument types: () values: []
groovy.lang.MissingMethodException: No signature of method: com.foo.services.MyService.getMONITOR_ENABLED() is applicable for argument types: () values: []
```
Why Groovy is asking me for a getter when the constant is accesible from the _MyService_ class?

### Cause
We did a bit of research debugging the creation of a spy using Spock and we founded that in the method org.spockframework.mock.runtime.JavaMockFactory#createInternal we are generating a proxy class and copying the fields from the instance class to the proxy class

```
private Object createInternal(IMockConfiguration configuration, Specification specification, ClassLoader classLoader) {
    if (Modifier.isFinal(configuration.getType().getModifiers())) {
      throw new CannotCreateMockException(configuration.getType(),
          " because Java mocks cannot mock final classes. If the code under test is written in Groovy, use a Groovy mock.");
    }
    if (configuration.isGlobal()) {
      throw new CannotCreateMockException(configuration.getType(),
          " because Java mocks cannot mock globally. If the code under test is written in Groovy, use a Groovy mock.");
    }

    MetaClass mockMetaClass = GroovyRuntimeUtil.getMetaClass(configuration.getType());
    IProxyBasedMockInterceptor interceptor = new JavaMockInterceptor(configuration, specification, mockMetaClass);
    Object proxy = ProxyBasedMockFactory.INSTANCE.create(configuration.getType(), configuration.getAdditionalInterfaces(),
      configuration.getConstructorArgs(), interceptor, classLoader,
      configuration.isUseObjenesis());
    if ((configuration.getNature() == MockNature.SPY) && (configuration.getInstance() != null)) {
      ReflectionUtil.deepCopyFields(configuration.getInstance(), proxy);
    }
    return proxy;
  }
```
Then, we compared the metaclass field of the proxy instance generated between  Groovy 2.4.21 and Groovy 3.0.10 and these are the differences:

Groovy 2
![image](https://user-images.githubusercontent.com/78414119/181056664-2ee781e7-7272-43e2-9aea-59a8b46380e7.png)

Groovy 3
![image](https://user-images.githubusercontent.com/78414119/181056693-78d51baa-4b10-40f3-8c62-30c36aa64354.png)

As you can see, there is a new property at CacheField class that is called madeAccessible that is set to false using Groovy 3. 

### To Reproduce

Create a test that spies an instance:

```
private MyService service

    void setup() {
        service = new MyService()
        
        [... hidden code for clarity...]
    }

    @Unroll
    void "test"() {
        given: "an spy of the service"
        MyService spiedService = Spy(service)

        when:
        spiedService.runMethod(param)
        
        then:
        true
    }
```

Create a service class defined in groovy as _MyService.groovy_ as this:

```
class MyService extends ParentService {
  public runMethod() {
if (MONITOR_ENABLED) {
    println "Well done!"
}
}
}
```

Create parent service in java as _ParentService.java_ as this:

```
public abstract class ParentService {

    protected static final boolean MONITOR_ENABLED = true;
```
Run the test and check that is free of exceptions and pass.

### Expected behavior

The protected constant should be accesible from the child class since it is protected.

### Actual behavior

The constant is not accessible and we have getting the error 

```
No signature of method: com.foo.services.MyService.getMONITOR_ENABLED() is applicable for argument types: () values: []
groovy.lang.MissingMethodException: No signature of method: com.foo.services.MyService.getMONITOR_ENABLED() is applicable for argument types: () values: []
```

### Java version

openjdk version "1.8.0_332"
OpenJDK Runtime Environment (Zulu 8.62.0.19-CA-linux64) (build 1.8.0_332-b09)
OpenJDK 64-Bit Server VM (Zulu 8.62.0.19-CA-linux64) (build 25.332-b09, mixed mode)

### Buildtool version

------------------------------------------------------------
Gradle 6.9.2
------------------------------------------------------------

Build time:   2021-12-21 20:18:38 UTC
Revision:     5d94aa68c0fdbe443838bb977080e3b9f273e889

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          1.8.0_332 (Azul Systems, Inc. 25.332-b09)
OS:           Linux 5.15.0-41-generic amd64

### What operating system are you using

Linux

### Dependencies

+--- org.codehaus.groovy:groovy:3.0.10
+--- org.codehaus.groovy:groovy-all:3.0.10 (*)
+--- org.spockframework:spock-core:2.1-groovy-3.0
|    +--- org.codehaus.groovy:groovy:3.0.9 -> 3.0.10
|    +--- org.junit.platform:junit-platform-testkit -> 1.8.2
|    |    +--- org.junit:junit-bom:5.8.2 (*)
|    |    +--- org.assertj:assertj-core:3.20.2 -> 3.22.0
|    |    +--- org.opentest4j:opentest4j:1.2.0
|    |    \--- org.junit.platform:junit-platform-launcher:1.8.2 (*)
|    +--- org.jetbrains:annotations:20.1.0
|    +--- org.ow2.asm:asm:9.2
|    +--- net.bytebuddy:byte-buddy:1.12.1 -> 1.12.11
|    +--- cglib:cglib-nodep:3.3.0
|    +--- org.objenesis:objenesis:3.2
|    +--- org.junit:junit-bom:5.8.1 -> 5.8.2 (*)
|    +--- org.junit.platform:junit-platform-engine -> 1.8.2 (*)
|    \--- org.hamcrest:hamcrest:2.2
+--- org.objenesis:objenesis:3.2
+--- org.springframework.boot:spring-boot-starter-test -> 2.7.1
|    +--- org.springframework.boot:spring-boot-starter:2.7.1 (*)
|    +--- org.springframework.boot:spring-boot-test:2.7.1
|    |    \--- org.springframework.boot:spring-boot:2.7.1 (*)
|    +--- org.springframework.boot:spring-boot-test-autoconfigure:2.7.1
|    |    +--- org.springframework.boot:spring-boot:2.7.1 (*)
|    |    +--- org.springframework.boot:spring-boot-test:2.7.1 (*)
|    |    \--- org.springframework.boot:spring-boot-autoconfigure:2.7.1 (*)
|    +--- com.jayway.jsonpath:json-path:2.7.0
|    |    +--- net.minidev:json-smart:2.4.7 -> 2.4.8
|    |    |    \--- net.minidev:accessors-smart:2.4.8
|    |    |         \--- org.ow2.asm:asm:9.1 -> 9.2
|    |    \--- org.slf4j:slf4j-api:1.7.33 -> 1.7.36
|    +--- jakarta.xml.bind:jakarta.xml.bind-api:2.3.3 (*)
|    +--- org.assertj:assertj-core:3.22.0
|    +--- org.hamcrest:hamcrest:2.2
|    +--- org.junit.jupiter:junit-jupiter:5.8.2
|    |    +--- org.junit:junit-bom:5.8.2 (*)
|    |    +--- org.junit.jupiter:junit-jupiter-api:5.8.2 (*)
|    |    +--- org.junit.jupiter:junit-jupiter-params:5.8.2
|    |    |    +--- org.junit:junit-bom:5.8.2 (*)
|    |    |    \--- org.junit.jupiter:junit-jupiter-api:5.8.2 (*)
|    |    \--- org.junit.jupiter:junit-jupiter-engine:5.8.2 (*)
|    +--- org.mockito:mockito-core:4.5.1 -> 2.23.4
|    |    +--- net.bytebuddy:byte-buddy:1.9.3 -> 1.12.11
|    |    +--- net.bytebuddy:byte-buddy-agent:1.9.3 -> 1.12.11
|    |    \--- org.objenesis:objenesis:2.6 -> 3.2
|    +--- org.mockito:mockito-junit-jupiter:4.5.1
|    |    +--- org.mockito:mockito-core:4.5.1 -> 2.23.4 (*)
|    |    \--- org.junit.jupiter:junit-jupiter-api:5.8.2 (*)
|    +--- org.skyscreamer:jsonassert:1.5.0
|    +--- org.springframework:spring-core:5.3.21 (*)
|    +--- org.springframework:spring-test:5.3.21 (*)
|    \--- org.xmlunit:xmlunit-core:2.9.0
+--- com.shazam:shazamcrest:0.7
|    +--- org.skyscreamer:jsonassert:1.2.0 -> 1.5.0
|    +--- com.google.code.gson:gson:2.2.4 -> 2.8.9
|    +--- junit:junit:4.11 -> 4.13.1 (*)
|    \--- org.apache.commons:commons-lang3:3.1 -> 3.8.1
+--- org.hamcrest:hamcrest-all:1.3
+--- org.mockito:mockito-core:2.23.4 (*)
+--- org.hamcrest:hamcrest-library:1.3
|    \--- org.hamcrest:hamcrest-core:1.3 -> 2.2 (*)
+--- com.tngtech.archunit:archunit:0.16.0
|    \--- org.slf4j:slf4j-api:1.7.30 -> 1.7.36

**Comment by leonard84** [comment]
Please post actual valid reproducer code have a look at https://stackoverflow.com/help/minimal-reproducible-example what this means. Ideally it is runnable in https://gwc-experiment.appspot.com/

**Comment by jasongarrett** [comment]
Here is a trivial reproduction of the bug:  https://gwc-experiment.appspot.com/?g=groovy_3_0&codez=eJxlj8EOgjAMhu97ih7hwgOYeNGzJ3yB0RVZHNtCa5QY3l2GCAH_Q7N137_-tW0MnQDHgPfCaX8rykhoa4tabPBKodPMcOlPmuk8nd8KRsUuCKGQgSoER9qDRiRmWzmCI0j3IDWs9q-VXkLe7L_bY1diWdBNnHm2oRqkocRl-dxLejbkD8st6Te47cvYj7HGms29fAHlzzbhxbrQ9DikoBvsAwP-YMU

This example works fine with Groovy 2.5 but throws a MissingMethodException with Groovy 3.0 and 4.0.  This happens any time you try to access a protected member of a superclass with a Spy.

**Comment by AndreasTu** [comment]
#1729 would fix this issue by changing the Mock-Class generated by `ByteBuddyMockFactory` to add the `@Internal` annotation to the intercepted `getProperty(String)` method, which would then be used by Groovy 3&4 to resolve the protected const correctly.
