### ISSUE TITLE
Hope to support Scala or kotlin

### ISSUE THREAD

**Issue by tangjiafu** [spockframework/spock#1504]
### Describe the solution you'd like

1 scala and kotlin is also JVM language，actually  I just need the feature for scala

**Comment by leonard84** [comment]
I personally haven't tried it, but as both scala and kotlin are jvm languages you should be able to test the code with Spock. Spock specifications will always be written in Groovy.

**Comment by tangjiafu** [comment]
感谢您的来信，您的邮件我已经收到。

**Comment by tangjiafu** [comment]
> I personally haven't tried it, but as both scala and kotlin are jvm languages you should be able to test the code with Spock. Spock specifications will always be written in Groovy.

OK，I will try it

**Comment by tangjiafu** [comment]
thx for your email, and I receiver it.
