### ISSUE TITLE
Make Data Variables mutable during runtime

### ISSUE THREAD

**Issue by ArkiMargust** [spockframework/spock#1505]
### Is your feature request related to a problem?

I am using Geb-Spock for my Test Automation Project.

Most of the Geb Page Classes generate data during runtime that other Geb Page Classes consume.

Instead of making a huge mess by declaring classes/properties/variables to store these data, I would like to use `specificationContext.currentIteration.dataVariables.put("Key", "Value")`.

Also, I would like to log to console these generated data before the end of each iteration/feature in the cleanup method. I find it messy and tedious that I have to print to console in different Geb Page Classes.

However, it's not possible at the moment because `put()` throws `UnsupportedOperationException`

Here is the code block from `DataVariableMap.java`

```
@Nullable
@Override
public Object put(String key, Object value) {
    throw new UnsupportedOperationException();
}
```
In my use case, having this will be truly convenient. I hope others feel the same way.

Thank you.

### Describe the solution you'd like

Allow `specificationContext.currentIteration.dataVariables.put("Key", "Value")`

### Describe alternatives you've considered

At the moment I resorted to storing these runtime generated data in classes/properties/variables

### Additional context

Nothing more.

**Comment by leonard84** [comment]
I don't understand what you are trying to achieve, `specificationContext.currentIteration.dataVariables` is only valid for the current iteration and will not carry over to some other iteration, it is only intended as the input for the current feature method.

Please share a practical example of what your are actually doing as there is probably a better way to achieve it.

**Comment by ArkiMargust** [comment]
@leonard84 

I don't mean to share it across iterations. Just within the same iteration/feature. The Geb Page Classes will share the `specificationContext.currentIteration.dataVariables`

Below is my actual use case

```
class MyBaseSpec extends GebReportingSpec {

    protected LoginPage login

    void setup() {
        login = new LoginPage(specificationContext)
    }

    void cleanup()  {
        //unpack the runtime generated data and log to console
        specificationContext.currentIteration.dataVariables.every {
             if (it.key.contains("runtimeGenerated")) println "${it.key.replace("runtimeGenerated", "")} : $it.value"
        }
        clearCookies()
        quit()
    }

}
```

```
class CreateAndProcessAnOrderSpec extends MyBaseSpec {

    def "Create and Process an Order from #country"() {
        
        when:
        to login
        
        login
            .loginAs(actor)
            .inHeaderMenu
            .clickCreateAnOrder()
            .moreStepsHere()
            
        then:
            at OrderCompletePage
            
            assert shippingNo.isDisplayed
            orderStatus == 'Shipped'
            //some other assertions
            
         where:
            //feature specific data variables
        
    }

}
```

In my Geb Page Classes, I want to do this

```
class OrderCreationPage extends BasePage {

    OrderCreationPage(ISpecificationContext iSpecificationContext) {
        super(iSpecificationContext)
    }
    
    //some Geb related content here to be used in the method below
    
    OnToTheNextPage someMethodThatWhenCalledWillGenerateAnOrderNumber() {
    
        //some codes here to create and order
        
        //when an order is created store it in specificationContext.currentIteration.dataVariables
        iSpecificationContext.currentIteration.dataVariables.put("runtimeGenerated_OrderNo", orderNo.text())
        
        //some codes here to go to the next page where the OrderNo will be used
        
        browser.at new OnToTheNextPage(iSpecificationContext)
    
    }
    
}
```

**Comment by leonard84** [comment]
I don't see how this is in any way more elegant than having a simple map in your base spec, or better even a purpose build `Context` object that you pass to your pages.

**Comment by ArkiMargust** [comment]
I agree. Thanks.
