### ISSUE TITLE
Count of invocation arguments varies for fixture methods that use default values

### ISSUE THREAD

**Issue by piotrminkina** [spockframework/spock#1512]
### Describe the bug

While writing an extension to the Spock Framework I came across a strange case with the number of arguments I get from the `IMethodInvocation.getArguments()` method in the interceptor implementation. This number depends on the existence of the `cleanup()` method in the specification, the form of Data Tables and the Java version.

See attached [spock-ext.tar.gz](https://github.com/spockframework/spock/files/9460953/spock-ext.tar.gz) and cases described in "Actual behavior".

### To Reproduce

I am including an attachment, with the implementation of the specification, reduced to a minimum, to demonstrate the problem.
[spock-ext.tar.gz](https://github.com/spockframework/spock/files/9460953/spock-ext.tar.gz)

See "Actual behavior" for commands to reproduce this issue.

### Expected behavior

I should get the same results on the standard output, regardless of the above cases.

```
# spock.WithCleanupSpec
method: private java.lang.Object spock.WithCleanupSpec.setup(java.lang.String,java.lang.Integer,java.lang.String)
arguments count: 3
stringValue: overwritten
intValue: 3333
anotherStringValue: overwritten
# spock.WithoutCleanupSpec
method: private java.lang.Object spock.WithoutCleanupSpec.setup(java.lang.String,java.lang.Integer,java.lang.String)
arguments count: 3
stringValue: overwritten
intValue: 3333
anotherStringValue: overwritten
```

### Actual behavior

The Java version seems to make a difference. I ran the test as is in the attached [spock-ext.tar.gz](https://github.com/spockframework/spock/files/9460953/spock-ext.tar.gz) file in the Docker Images listed below, using the following command (where `openjdk:8` is one of the images below):

```console
$ pwd
/tmp/spock-ext
$ docker run --rm -it -w `pwd` -v `pwd`:`pwd` openjdk:8 ./gradlew clean test
```

1. same, but invalid results with these images: `openjdk:8`, `openjdk:10` (not always)

```
# spock.WithCleanupSpec
method: private java.lang.Object spock.WithCleanupSpec.setup(java.lang.String,java.lang.Integer)
arguments count: 2
stringValue: overwritten
intValue: 3333
anotherStringValue: defaultValue
# spock.WithoutCleanupSpec
method: private java.lang.Object spock.WithoutCleanupSpec.setup(java.lang.String,java.lang.Integer)
arguments count: 2
stringValue: overwritten
intValue: 3333
anotherStringValue: defaultValue
```

2. different results with these images: `openjdk:9`, `openjdk:10` (only once, after switching from `openjdk:9`)
```
# spock.WithCleanupSpec
method: private java.lang.Object spock.WithCleanupSpec.setup(java.lang.String,java.lang.Integer,java.lang.String)
arguments count: 3
stringValue: overwritten
intValue: 3333
anotherStringValue: overwritten
# spock.WithoutCleanupSpec
method: private java.lang.Object spock.WithoutCleanupSpec.setup(java.lang.String,java.lang.Integer)
arguments count: 2
stringValue: overwritten
intValue: 3333
anotherStringValue: defaultValue
```

3. another different results with these images: `openjdk:10` (not always), `openjdk:11`, `openjdk:12`, `openjdk:13`, `openjdk:14`
```
# spock.WithCleanupSpec
method: private java.lang.Object spock.WithCleanupSpec.setup(java.lang.String,java.lang.Integer)
arguments count: 2
stringValue: overwritten
intValue: 3333
anotherStringValue: defaultValue
# spock.WithoutCleanupSpec
method: private java.lang.Object spock.WithoutCleanupSpec.setup(java.lang.String)
arguments count: 1
stringValue: overwritten
intValue: 2222
anotherStringValue: defaultValue
```

4. another same, but still invalid results with these images (once, after switching the Java version): `openjdk:11`, `openjdk:12`
```
# spock.WithCleanupSpec
method: private java.lang.Object spock.WithCleanupSpec.setup(java.lang.String)
arguments count: 1
stringValue: overwritten
intValue: 2222
anotherStringValue: defaultValue
# spock.WithoutCleanupSpec
method: private java.lang.Object spock.WithoutCleanupSpec.setup(java.lang.String)
arguments count: 1
stringValue: overwritten
intValue: 2222
anotherStringValue: defaultValue
```

### Java version

Java version depending on the Docker image used.

```console
$ docker run --rm -it openjdk:8 java -version 
openjdk version "1.8.0_342"
OpenJDK Runtime Environment (build 1.8.0_342-b07)
OpenJDK 64-Bit Server VM (build 25.342-b07, mixed mode)

$ docker run --rm -it openjdk:9 java -version
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+12-Debian-4)
OpenJDK 64-Bit Server VM (build 9.0.4+12-Debian-4, mixed mode)

$ docker run --rm -it openjdk:10 java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Debian-2)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Debian-2, mixed mode)

$ docker run --rm -it openjdk:11 java -version
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment 18.9 (build 11.0.16+8)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.16+8, mixed mode, sharing)

$ docker run --rm -it openjdk:12 java -version
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+10)
OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)

$ docker run --rm -it openjdk:13 java -version
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)

$ docker run --rm -it openjdk:14 java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)
```

### Buildtool version

For Image `openjdk:14`:

```console
$ ./gradlew --version

------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          14.0.2 (Oracle Corporation 14.0.2+12-46)
OS:           Linux 5.15.0-46-generic amd64
```

### What operating system are you using

Linux

### Dependencies

[dependencies-report.txt](https://github.com/spockframework/spock/files/9461060/dependencies-report.txt)

**Comment by kriegaex** [comment]
I have not tried your example yet, but does it work as expected if instead of `invocation.arguments.length` you use `invocation.arguments.size()` like in the example test introduces in #1306?

https://github.com/spockframework/spock/blob/53ae1b2d3d774b62b7c7ff5ceb21c321ea5ab1e3/spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/MethodParameters.groovy#L258-L268

**Comment by piotrminkina** [comment]
No changes. Please note that the `setup()` method it always has the same source code, but has 3 different signatures when take from the `invocation.method` variable.

Method source code:
```groovy
@InjectDataValues('stringValue')
def setup(String stringValue, Integer intValue = 2222, String anotherStringValue = 'defaultValue') {
    // [...]
}
```

Reflection signature (where `*` is `With` or `Without`):
```
private java.lang.Object spock.*CleanupSpec.setup(java.lang.String)
private java.lang.Object spock.*CleanupSpec.setup(java.lang.String,java.lang.Integer)
private java.lang.Object spock.*CleanupSpec..setup(java.lang.String,java.lang.Integer,java.lang.String)
```

I think it's not just a problem with the number of arguments, but with Reflection as a whole.

**Comment by kriegaex** [comment]
> No changes.

I did not expect any, just wanted to exclude the possibility.

I think that with your reproducer, Leonard or another contributor should be able to identify the root cause of the problem.

**Comment by leonard84** [comment]
The problem is that you are using default values, this causes gradle to generate overloads which end up duplicating the `setup` method. Spock only supports one fixture method per class for each of the fixture types, and it will [use the first one that matches the name](https://github.com/spockframework/spock/blob/cadc6e920ffc442ab138f30de379f0bf1d1dd814/spock-core/src/main/java/org/spockframework/runtime/SpecInfoBuilder.java#L192-L199). So your extension must support default values in a different way, e.g. `@Default("value")`.

To see what happens, check the generated code via `Inspect AST` on the [Groovy Web Console](https://gwc-experiment.appspot.com/?g=groovy_2_5&codez=eJxLSU1TKE4tKS3QCC4pysxLVygGU2GJOaWpOgqeeSWp6alFCpl5JWARBVsFIyDQUYAqTszLL8lILQpG6AGqUE9JTUsszYHoUNdUqOZSAIICoJKSnDwNdSQLrBTUFbSRbdREVQqzFqIOxkNThOkGiHJMcU2uWgB5p1E8)

**Comment by piotrminkina** [comment]
@leonard84 Thank you very much for this analysis! I didn't expect that Groovy overloads a method with default values like this. Could you implement a safety feature in Spock that throws an adequate exception if more than one setup/cleanup method occurs?
