### ISSUE TITLE
Upgrade to org.spockframework:spock-core:2.2-groovy-4.0 is trying to get groovy 4.0.4

### ISSUE THREAD

**Issue by jesperancinha** [spockframework/spock#1517]
### Describe the bug

After the upgrade to org.spockframework:spock-core:2.2-groovy-4.0, gradle seems to be looking for groovy 4.0.4. I only see 3.0.12 as its higher version. The name of the new dependency also suggests that you are using groovy-4.0 in this release, which makes me difficult to understand why is this issue happening. 

### To Reproduce

Just check this pipeline example please:
https://github.com/jesperancinha/xml-adder/runs/8119423467?check_suite_focus=true

The error I'm getting is:

```shell
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileJava'.
> Could not resolve all files for configuration ':app:compileClasspath'.
   > Could not resolve org.codehaus.groovy:groovy:3.0.12.
     Required by:
         project :app
      > Module 'org.codehaus.groovy:groovy' has been rejected:
           Cannot select module with conflict on capability 'org.codehaus.groovy:groovy:3.0.12' also provided by [org.apache.groovy:groovy:4.0.4(groovyApiElements)]
   > Could not resolve org.apache.groovy:groovy:4.0.4.
     Required by:
         project :app > org.spockframework:spock-core:2.2-groovy-4.0
         project :app > org.spockframework:spock-core:2.2-groovy-4.0 > org.apache.groovy:groovy:4.0.4 > org.apache.groovy:groovy-bom:4.0.4
      > Module 'org.apache.groovy:groovy' has been rejected:
           Cannot select module with conflict on capability 'org.codehaus.groovy:groovy:4.0.4' also provided by [org.codehaus.groovy:groovy:3.0.12(compile)]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### Expected behavior

I just want this to work

### Actual behavior

It fails

### Java version

17

### Buildtool version

./gradlew clean build test jacocoTestReport -i

### What operating system are you using

Mac

### Dependencies

dependencies {
    implementation "org.kohsuke.args4j:args4j-maven-plugin:2.33"
    implementation "com.opencsv:opencsv:5.6"
    implementation "org.codehaus.groovy:groovy:3.0.12"
    implementation "org.spockframework:spock-core:2.2-groovy-4.0"
    implementation "org.apache.commons:commons-io:1.3.2"
    testImplementation "junit:junit:4.13.2"
    testImplementation "org.jmock:jmock-junit4:2.12.0"
    testImplementation "org.jmock:jmock-legacy:2.12.0"
}

**Comment by leonard84** [comment]
Groovy 4.x has a new groupId `org.apache.groovy`.

So the problem is that you are requesting Groovy 3 explicitly

```
implementation "org.codehaus.groovy:groovy:3.0.12"
```

while using a Spock version for Groovy 4.
```
implementation "org.spockframework:spock-core:2.2-groovy-4.0"
```

So, either use Spock for Groovy 3

```
implementation "org.spockframework:spock-core:2.2-groovy-3.0"
```

or use Groovy 4 
```
implementation "org.apache.groovy:groovy:4.0.4"
```
or just delete the groovy dependency and use whatever Spock provides.

**Comment by jesperancinha** [comment]
Thanks @leonard84! It worked!
