### ISSUE TITLE
`FeatureMetadata#dataVariableNames()` has no default or `SpecAnnotator#addFeatureMetadata` does not add attribute value for it

### ISSUE THREAD

**Issue by eric-milles** [spockframework/spock#1549]
### Describe the bug

As noted in the title, the annotation attribute population is incomplete for `FeatureMetadata`.  I am in process of fixing [GROOVY-10862](https://issues.apache.org/jira/browse/GROOVY-10862) which stops setting annotation default value for each and every `MethodNode` and spock's `FeatureMetadata` now gives error:
```
No explicit/default value found for annotation attribute 'dataVariableNames' in @org.spockframework.runtime.model.FeatureMetadata
```

### To Reproduce

```groovy
            @Grab('org.spockframework:spock-core:2.4-M1-groovy-4.0')
            @GrabExclude('org.apache.groovy:*')
            import spock.lang.Specification

            trait T {
                def m(Class<?> clazz, Object... array) {
                    clazz.name + array
                }
            }

            class C extends Specification implements T {
                void test() {
                  when:
                    String result = m(Object,'x')
                  then:
                    result == 'java.lang.Object[x]'
                }
            }

            org.junit.runner.JUnitCore.runClasses(C)
```

### Expected behavior

Test should run as before.

### Actual behavior

Error for missing annotation attribute value or default.

### Java version

N/A

### Buildtool version

N/A

### What operating system are you using

Windows

### Dependencies

N/A

**Comment by leonard84** [comment]
It looks like this is an unused piece of code added in https://github.com/spockframework/spock/commit/12447cb296619723623085c8fa617b4cc15a5d50.
@eric-milles do you happen to know the implications of simply removing it? If it was never assigned a value, will it still invalidate the compiled bytecode?
