### ISSUE TITLE
Add output of verfied object in verifyAll assertions

### ISSUE THREAD

**Issue by mkutz** [spockframework/spock#1567]
### Is your feature request related to a problem?

When I `verifyAll` with a parameter, e.g.

```groovy
verifyAll(user) {
  name == 'Spock'
  rank == 'Commander'
}
```

the output in case of a failure does not include `user`, in this case:

```plain
name == 'Spock'
|    |
|    false
'Kirk'
```

In some cases, especially when verifying items in a collection, this m might be to little information to identfy the failing object.

### Describe the solution you'd like

The output of `verifyAll` could be changed to output the verified object's `toString` once. E.g.

```plain
User(name = 'Kirk', rank = 'Captain')
name == 'Spock'
|    |
|    false
'Kirk'
```

### Describe alternatives you've considered

In the current implementation it is already possible to include the `it` to the assertion. E.g.

```groovy
verifyAll(user) {
  it.name == 'Spock'
  it.rank == 'Commander'
}
```

**Comment by leonard84** [comment]
I've thought about adding something like this before.

Basically adding new methods `with` -> `withContext` 
and `verifyAll` -> `verifyAll(With)Context` or 
```groovy
withContext (user) {
  verifyAll {
  }
}
```
