### ISSUE TITLE
@Shared Resource cannot request current feature

### ISSUE THREAD

**Issue by Frankie0701** [spockframework/spock#1589]
### Describe the bug

We have built a test framework on top of Spock for our own testing purpose. We have some resource to establish connection and send/receive messages, and we want these messages to be utilized when generating our customized test report and can be categorized under each feature and iteration. Due to this resource requires establishing connection, we are treating it as expensive resource and recommend our user to mark it as @Shared. After we upgrade spock-core from 1.3-groovy-2.5 to 2.1-groovy-3.0, this message report generation breaks, and will get` java.lang.IllegalStateException: Cannot request current feature in @Shared context`.

### To Reproduce

Please try following snippet, and will get exception mentioned above. I understand removing @Shared on ExpensiveResource will make things work, but we want the ExpensiveResource to be reusable for every feature.

```
class TestSharedExpensiveResource extends Specification {
    static class ExpensiveResource {
        private Specification spec
        private Map<String, String> featureData = [:]

        ExpensiveResource(Specification spec) {
            this.spec = spec
        }

        def reportData() {
            featureData.put(spec.class.name + spec.specificationContext.currentFeature, "data generated in current feature")
        }
    }

    @Shared
    def expensiveResource = new ExpensiveResource(this)

    def setup() {
        expensiveResource.reportData()
    }

    def 'test'() {
        expect:
        true
    }
}
```

### Expected behavior

No exception will be thrown

### Actual behavior

`java.lang.IllegalStateException: Cannot request current feature in @Shared context` will be thrown from `spec.specificationContext.currentFeature`

### Java version

17.0.3

### Buildtool version

gradle-7.5

### What operating system are you using

Windows

### Dependencies

only lib relevant is spock-core-2.1-groovy-3.0

**Comment by kriegaex** [comment]
How about this?

```java
  @Shared
  def expensiveResource //= new ExpensiveResource(this)

  def setup() {
    expensiveResource = new ExpensiveResource(this)
    expensiveResource.reportData()
  }
```

**Comment by kriegaex** [comment]
If you want to instantiate the resource only once, you can pass the spec to `reportData`:

```java
class SharedExpensiveResourceTest extends Specification {
  static class ExpensiveResource {
    private Map<String, String> featureData = [:]

    def reportData(Specification spec) {
      featureData.put(spec.class.name + spec.specificationContext.currentFeature, "data generated in current feature")
    }
  }

  @Shared
  def expensiveResource = new ExpensiveResource()

  def setup() {
    expensiveResource.reportData(this)
  }

  def 'test'() {
    expect:
    true
  }
}
```

**Comment by Frankie0701** [comment]
Thanks for the reply, real code is bit more complicated than this snippet, which we register Specification with SetupSpecInterceptor for @Shared, but indeed, I try to register it with SetupInterceptor, and then issue is solved.
