### ISSUE TITLE
@Stepwise does not automatically trigger previous features anymore with Spock 2.x as well as with Gradle 2.12+

### ISSUE THREAD

**Issue by dartilla** [spockframework/spock#1593]
After transition from spock1 to spock2 @Stepwise functionality is lost (suspect junit4 to junit5 transition)

See spock.lang.StepwiseExtensionSpec.

Try to execute 'step 3'. No 'step 1' and 'step 2' executed at all.
Checked on 1b0b6764 and 5398f5eb

**Comment by Vampire** [comment]
Running through Maven also does not trigger the previous features

**Comment by Vampire** [comment]
Ah, sorry, I probably made too many different tests.
Indeed now `master` without Gradle delegation also only runs `step 3` here.

**Comment by Vampire** [comment]
So to summarize:

Gradle 2.11 + Spock 1.0 => works
Gradle 2.12 + Spock 1.0 => does not work
IntelliJ (without Gradle delegation) + Spock 1.3 => works
IntelliJ (without Gradle delegation) + Spock 2.0 => does not work
Maven 3.6.0 + Spock 1.3 => works
Maven 3.6.0 + Spock 2.0 => does not work

So changes in Spock 2.0 made it break and additionally changes in Gradle 2.12 made it break.

**Comment by Vampire** [comment]
@marcphilipp can you maybe have a look?
We have a test using a `MethodSelector` that works perfectly fine.
But when for example testing a Maven-run, only the `ClassSelector` comes in.
So without too much deeper analysis, I'd guess they only use the `ClassSelector` and do the method filtering themselves somehow which then breaks this Spock functionality.
But can it really be that Maven, Gradle, and IntelliJ use JUnit platform incorrectly and all cause the same issue here?
Or is there something Spock can do to fix this?

**Comment by Vampire** [comment]
Yep, all three let JUnit Platform only filter for the right class and then use a post-discovery filter instead of a method selector to select the requested test. Maybe also because some support patterns like `step*`.

I'm not sure Spock can do much about this without significant effort.

**Comment by leonard84** [comment]
Yes @Vampire is right, unless we break/ignore the JUnit Platform Execution model we can't fix this in Spock. If the tools would use the proper `MethodSelector` then Spock also adds the necessary methods back in, however they remove the nodes after the discovery.

**Comment by Vampire** [comment]
Well, I wouldn't (and didn't) say "we can't fix".
We can also dynamically add test nodes for data driven tests, so at least with some effort we could most probably also execute those features even if they fell through the post discovery filter.

**Comment by leonard84** [comment]
It is not something that an extension, like `@Stepwise`, can do at the moment.

I'm not saying it is impossible to do, but they will be awkward workarounds.
