### ISSUE TITLE
Spied object throws MissingMethodException when accessing a protected member of a superclass.

### ISSUE THREAD

**Issue by jasongarrett** [spockframework/spock#1608]
### Describe the bug

If a class being spied accesses a protected property of a superclass, a MissingMethodException is thrown for the (nonexistent) synthetic getter.

### To Reproduce

This example works correctly with Groovy 2.5 but fails with a MissingMethodException with Groovy 3 and Groovy 4.
https://gwc-experiment.appspot.com/?g=groovy_3_0&codez=eJxtT0sOgyAQ3XMKlrrxAE26adddadI1wliJCIQZ05rGu1etnxL7FgSY95mnW-8CcfRONpkR9pHlHqSutBSknWVMGoHIb_1FIFzn-5vxET44AkmgeOmcAWG5kBIQdWmAnzmFDtiwy79SeBFY9c9uNVEOsKg13l1oknQZTghAXfgNmSfDIaMApC0n6rKYKag41TDxooBnDfa0vSasW7d97vux03gmy1-6Eekgm-lZXGRflkXcD-B6dDM

### Expected behavior

Protected superclass properties can be accessed normally.

### Actual behavior

An attempt is made to use a generated getter and a MissingMethodException is thrown.

### Java version

OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1), and whatever version gwc-experiment.appspot.com using.

### Buildtool version

Gradle 5.6.4 and gwc-experiment.appspot.com

### What operating system are you using

Mac

### Dependencies

  "groovyVersion": "3.0.15",
  "spockVersion": "2.3.0-groovy-3.0"

**Comment by leonard84** [comment]
Accessing the field directly works as [expected](https://gwc-experiment.appspot.com/?g=groovy_3_0&codez=eJxtT0sOgyAQ3XMKlrrhAE2aNO26K026RhwrEYEwY1rTePei9RNjZ0GA95unW-8CcfRONcJI-xSZB6UrrSRpZxlTRiLye3-VCLfp_mE8jg-OQBGUvHDOgLRcKgWIujDAz5xCB2zY5D8pvAls-c9uMSkdYF5rfLjQJOkMjhOAumA5RUxctqgJHw5JOSCtabtGs2UJVfSCkbeLedVgT-trnGX3ts98H5vFM5n_0pVIB9lEF_s627Jsx_0CDA12WQ), as well as accessing a protected [method](https://gwc-experiment.appspot.com/?g=groovy_3_0&codez=eJx1j8EOgjAQRO_9ij3qhQ8w8aCePWHiuZRRGrBtukuUEP5dQIUQdU7dzfTNjr0FH4U4eFMmlXbXJA0w9mKNFuudUqbSzHRs9ppxGN-tol4heoER5JR5X0E7ukJ2xoDZZhVWa6KWRucgiTVeU6e6GfoC4iFw-a-QDzr34FNh-exj2ZPbiRshdXSkp9w_GSewTDmLhm9YjgtJgcG3CLgXcJtpGvS5-takoaFtT2tW79167vv1bbQnyyLzsWrhfQJnt3gz).

**Comment by jasongarrett** [comment]
It does not work for statically compiled code [when access is in a closure](https://gwc-experiment.appspot.com/?g=groovy_3_0&codez=eJxtT0sOgyAQ3XMKlrrxAE26adddadI1wliJCIQZ05rGu1etnxL7FgSY95mnW-8CcfRONpkR9pHlHqSutBSknWVMGoHIb_1FIFzn-5vxET44AkmgeOmcAWG5kBIQdWmAnzmFDtiwy79SeBFY9c9uNVEOsKg13l1oknQZTghAXfgNmSfDIaMApC0n6rKYKag41TDxooBnDfa0vSasW7d97vux03gmy1-6Eekgm-lZXGRflkXcD-B6dDM).

**Comment by jasongarrett** [comment]
Access to the "log" member created by @Slf4j does not work from within a closure in a spied class.

**Comment by AndreasTu** [comment]
Was fixed by https://github.com/spockframework/spock/pull/1729
