### ISSUE TITLE
spock-specs are flaky

### ISSUE THREAD

**Issue by Vampire** [spockframework/spock#1615]
If you check https://ge.spockframework.org/scans?search.names=Git%20commit%20id%20short&search.relativeStartTime=P90D&search.tasks=not:spock-spring:boot3-test:build&search.timeZoneId=Europe/Berlin&search.usernames=bkautler&search.values=d5b03a1b, you can observe a flaky behavior.

The one with the compile error and the one(s) without requested tasks are to be ignored.

The first build that was successful got the `:spock-specs:test` result from remote cache from this build: https://ge.spockframework.org/s/6dfyyzsskf6uc.
The other successful then got it from the local cache.
The failed builds were run with `--rerun-tasks` or `--rerun` to avoid using the cached result.
They all have failing tests, but not necessarily the same ones.

**Comment by leonard84** [comment]
I think 4c82f7598a5afc235c794442c80e0fef6e8748e2 introduced the problem, checking the commit before didn't produce flaky results in my testing.

**Comment by leonard84** [comment]
The `ImplicationFeatureNode` doesn't forward `org.junit.platform.engine.support.descriptor.AbstractTestDescriptor#setParent` since it is final.

**Comment by Vampire** [comment]
Should that change anything?
The `ImplicationFeatureNode` is the one that is inserted into the hierarchy.
The `FeatureNode` is just the delegate to do the actual execution logic.
It should not need to know the parent, should it?

**Comment by leonard84** [comment]
Something breaks, with the parameterized execution the `IterationNodes` have the `ParameterizedFeatureNode` as parent (not the `ImpliedFeatureNode`), which doesn't have a parent and thus the lookup of the execution mode fails.

**Comment by Vampire** [comment]
Argh, right.
Yeah all those that are flaky are ones with `@Stepwise`, thanks.
