### ISSUE TITLE
`MethodInvocation#resolveArgument` probably misbehaving

### ISSUE THREAD

**Issue by Vampire** [spockframework/spock#1633]
It is nice to have such a convenience method now.

But there are two points I think are questionable.

I see (and had in the past) three use-cases for parameter injection
- only inject a value if none was injected so far
- overwrite whatever is there already whether already set or not
- claim ownership and fail if some other extension already injected a value

The current method only supports the last way, while I think the other two are equally fine and common.
So maybe we should provide two more of these convenience methods (together with stuff in `ParameterResolver`),
or maybe better add a parameter that selects one of these three behaviors (together with stuff in `ParameterResolver`).

---

And the second point, the currently supported failing case is using `org.spockframework.util.Assert.that`.
I don't think that is an appropriate choice here.
These `Assert.that` methods throw `InternalSpockError`s which are `Error`s.
I think those should only be used to check spock internal assertions and having thrown such an error signifies a bug within Spock that needs to be fixed.
Using `Assert.that` there would also fail with an `InternalSpockError` if a 3rd party extension or user-code is misbehaving which I don't think is a good idea.

**Comment by kriegaex** [comment]
Not having looked into and parameter resolver details, just having noticed this in your description:



> the currently supported failing case is using `org.spockframework.util.Assert.that`.
> I don't think that is an appropriate choice here.
> These `Assert.that` methods throw `InternalSpockError`s which are `Error`s.
> I think those should only be used to check spock internal assertions and having thrown such an error signifies a bug within Spock that needs to be fixed.

Looking at https://github.com/spockframework/spock/blob/04483cf6bffa7cac2dd0477e0a60d0703920c60c/spock-core/src/main/java/org/spockframework/util/Assert.java#L24 and https://github.com/spockframework/spock/blob/04483cf6bffa7cac2dd0477e0a60d0703920c60c/spock-core/src/main/java/org/spockframework/util/InternalSpockError.java#L23, this really does not look right, unless the intent really was to signal a non-recoverable error, which would lead to terminating the whole Spock enging altogether. So, you probably have a point there.

**Comment by leonard84** [comment]
Can you provide real world examples for these other use-cases?

> * only inject a value if none was injected so far
> * overwrite whatever is there already whether already set or not
 
I could see a decorator use-case but as that logic would be different I chose not to implement it.

Valid point about the misuse of `Assert.that`.

**Comment by Vampire** [comment]
Actually, I don't right now remember the concrete use-cases, but am pretty sure I had them.
But maybe I confuse them with field injection use-cases I had.
We can also ignore it for now and I re-complain when I hit it again. :-D
You can anyway still just inject the attributes like before and just not have a convenience method.
Maybe the use-cases are also too rare to have a built-in convenience method as long as there still is a way to do it.
