### ISSUE TITLE
Syntax to permit assignment in expect/then block

### ISSUE THREAD

**Issue by chrylis** [spockframework/spock#1660]
### Is your feature request related to a problem?

When writing component-level specs for complete business processes, I often use `@Stepwise` with individual methods for each step of the process. I need to store values (e.g., generated IDs) into `@Shared` variables for use in later methods.

Currently, assignment without declaration is forbidden in `expect` and `then` blocks. The only ways to assign these variables are wrapping the assignment into a lambda or declaring an extra temporary variable and then using `cleanup` to copy it to the `@Shared` one.

### Describe the solution you'd like

It would be convenient to have some way to make individual exceptions and permit specific assignment operations inside assertion blocks.

**Comment by Vampire** [comment]
What's so bad about using a closure, like
```groovy
then:
    generateId().tap { id = it } > 100
```
?
Well, it is maybe a bit bulky, yeah.
With #1532 you will be able to do
```groovy
then:
    !!(id = generateId())
    id > 100
```
How about that? :-)

**Comment by chrylis** [comment]
I think the syntax for #1532 would do what I'm after. Looks like it's going to happen, so I'll close this one in favor of that!
