### ISSUE TITLE
@PostConstruct is not invoked on test with @SpringBootTest after upgrading SpringBoot to 3.x

### ISSUE THREAD

**Issue by toyopilgrim** [spockframework/spock#1748]
### Describe the bug

After upgrading Spring Boot to 3.x, Spock specs started to fail because `@PostConstruct` isn't triggered.

In the demo application, you'll see `DemoServiceSpec` fails while `DemoServiceTest`(normal JUnit) passes.
Likewise, `InitializingBean` also works with JUnit, but doesn't work with Spock.

For instance, when switching back the Spring Boot to 2.7.4, DemoServiceSpec passes. 

This implicates that 'org.spockframework:spock-spring:2.3-groovy-4.0' may have some compatibility issue with jakarta or SpringBoot3 itself. 

### To Reproduce

Demo repository
https://github.com/toyopilgrim/spock-issue-with-springboot3-demo

The test 
https://github.com/toyopilgrim/spock-issue-with-springboot3-demo/blob/master/src/test/groovy/demo/DemoServiceSpec.groovy

```
Cannot read field "messageSource" because "com.example.demo.DemoPostConstruct.instance" is null
java.lang.NullPointerException: Cannot read field "messageSource" because "com.example.demo.DemoPostConstruct.instance" is null
```

DemoPostConstruct.instance is null because `@PostConstruct` isn't triggered with Spring Boot 3.x.

I wrote a JUnit test in the same way. But it doesn't suffer from the problem. 
https://github.com/toyopilgrim/spock-issue-with-springboot3-demo/blob/master/src/test/java/com/example/demo/DemoServiceTest.java 

### Expected behavior

The classes that are specified in `@SpringBootTest` are initialized properly. 

### Actual behavior

It's not initialized properly after upgrading the application to SpringBoot 3.x.  I checked that breakpoint doesn't reach a point inside the post construct method. 

### Java version

17

### Buildtool version

Corretto-17

### What operating system are you using

Mac

### Dependencies
+--- org.springframework.boot:spring-boot-starter -> 3.1.2
+--- org.springframework.boot:spring-boot-starter-test -> 3.1.2
+--- org.spockframework:spock-core:2.3-groovy-4.0
\--- org.spockframework:spock-spring:2.3-groovy-4.0

**Comment by AndreasTu** [comment]
@toyopilgrim Sorry but I can't reproduce this problem.
I have tested it on current Spock-master with spring-boot 3.1.2 and 3.0.0, Groovy 3.0 and 4.0 and Java 17
See Test [org.spockframework.boot3.issue1748.Issue1748Spec](https://github.com/AndreasTu/spock/blob/Issue1748/spock-spring/boot3-test/src/test/groovy/org/spockframework/boot3/issue1748/Issue1748Spec.groovy)
in branch <https://github.com/AndreasTu/spock/tree/Issue1748>

Both tests are green and printing:
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.1.2)

Empty MessageSource
Empty MessageSource
```

**Comment by AndreasTu** [comment]
@toyopilgrim Ok I tried your repo, which fails with spock 2.3 but is OK with spock `2.4-M1`.
Please try if the `2.4-M1` would fix your issues.

This ticket seams to be releated with #1539.

**Comment by toyopilgrim** [comment]
Confirmed that it works! Thank you.

**Comment by toyopilgrim** [comment]
@AndreasTu
Is there any plan to release stable 2.4 soon or backport to 2.3 as posed at https://github.com/spockframework/spock/issues/1539#issuecomment-1595192911?

**Comment by toyopilgrim** [comment]
Got it.  Since my project prohibits usage of unstable artifacts, I’m gonna keep using `2.3` for the time being with the workaround : `@ContextConfiguration` instead of `@SpringBootTest`.
