### ISSUE TITLE
Define semantics of overriding a feature method

### ISSUE THREAD

**Issue by robfletcher** [spockframework/spock#175]
Originally reported on Google Code with ID 53

```
Current behavior: both the overridden and the overriding method are run. Probably it
would be 
better to only run the overriding method, which is closer to conventional inheritance
semantics. A 
concrete use case would help. See spec SpecInheritance.

```

Reported by `pniederw` on 2009-11-18 20:50:50

**Comment by thecodesmith** [comment]
I agree that in most cases this makes sense. However, I ran into a use case where inheritance seemed to be the best option, where I wanted to run common tests in many individual modules in a multi-module Maven project. The inheritance model would allow me to create the common tests in one module, and depend on and import them in another. Then I could extend the common tests and selectively ignore or override feature methods that do not apply in a specific module.

I have created a Spock extension library to enable this: https://github.com/thecodesmith/spock-override-extension. The README there has details on the use case, and example usage. I hope it is useful in case a few others stumble across this issue like I did. Thanks!
