### ISSUE TITLE
Inject beans by parameters into methods: setupSpec(), setup(), cleanup(), cleanupSpec()

### ISSUE THREAD

**Issue by lowcasz** [spockframework/spock#1833]
### Is your feature request related to a problem?

I'm always frustrated when I have to use @Shared fields and @EnableSharedInjection or do workarounds to use it in setupSpec().
Other Issue is when I'm using inheritance and superclasses e.g. DomainTest, RepositoryTest, IntegrationTest. This classes could contains @Autowired fields accessed in all subclasses, but I have to inject them in all subclasses code manually.
I cannot use the same transaction, or Jdbc, Sql in cleanupSpec() methods too.

### Describe the solution you'd like

I think all fields of these superclasses can be setted by overloded setupSpec(@Autowired SomeBean bean...) methods.
In special and simple situations fields are no needed and beans could be accessed directly in ovcerloaded setup methods: setupSpec(), setup(), cleanup(), cleanupSpec().
Then @Shared fields, or problematic @EnableSharedInjection won't be needed in many situations.

### Describe alternatives you've considered

All Specification classes can use constructor with autowired fields, but it can be problem with many constructors in groovy.

@Autowired fields in superclass can be injected in all subclasses, but it solves only part of above problems and this is probably not the correct solution.

**Comment by lowcasz** [comment]
#76 It can be connected with older issue ["Enable usage of Spring beans in @Shared fields, setupSpec() and cleanupSpec()"](https://github.com/spockframework/spock/issues/76).

**Comment by leonard84** [comment]
Can you provide an MCVE, I'm not really understanding what scenario you want to solve.

**Comment by lowcasz** [comment]
For example I would have abstract class for integration tests:
> @SpringBootTest(webEnvironment = RANDOM_PORT)
> @TestExecutionListeners([DependencyInjectionTestExecutionListener])
> @WebMvcTest
> class IntegrationTests extends Specification {
>     @Autowired
>     protected Sql sql
>     @Autowired
>     protected TestRestTemplate rest
>     @Autowired
>     protected MockMvc mvc
> }

And use it some test:
> class SomeTests extends IntegrationTests {
> def "Some test case used IntegrationTest fields"() {
> when:
> rest.perform(...)
> then:
> noExceptionThrow()
> }
> }

Spock not autowire fields declared in super class, every autowired field must be copied into all subclasses.

**Comment by leonard84** [comment]
I did a simple test and could not recreate your example, it worked fine for me at least modifying one of the sample tests in `:spock-spring:boot3-test`.

A few things to note, just remove the `protected` from the fields its just clutter for tests. Why do you have `@TestExecutionListeners([DependencyInjectionTestExecutionListener])` this doesn't make sense. And if I'm not mistaken you should either use `@WebMvcTest` or `@SpringBootTest(webEnvironment = RANDOM_PORT)` not both at the same time. `MockMvc` doesn't work with a real server IIRC.
