### ISSUE TITLE
Cannot use EmbeddedSpecRunner

### ISSUE THREAD

**Issue by renatoathaydes** [spockframework/spock#1849]
### Describe the bug

We have a specification that uses the `spock.util.EmbeddedSpecRunner` class to test our Spock extension.
I've updated Spock from `2.1-M2-groovy-3.0` to `2.4-M1-groovy-3.0` and our spec no longer compiles.

### To Reproduce

Build file:

```groovy
plugins {
    id 'groovy'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

test {
    useJUnitPlatform()
}

dependencies {
    implementation('org.codehaus.groovy:groovy-all:3.0.19')
    testImplementation('org.spockframework:spock-core:2.3-groovy-3.0')
}
```

Minimum spec:

```groovy
class MyTest extends Specification {
    EmbeddedSpecRunner runner = new EmbeddedSpecRunner()

    def 'Can run a spec'() {
        when:
        runner.runWithImports('''
        class Testing extends Specification {
          def 'testing'() {
            expect: true
          }
        }
        ''')

        then:
        noExceptionThrown()
    }

}
```

### Expected behavior

With a dependency on `org.spockframework:spock-core:2.1-M2-groovy-3.0` this test passes.

### Actual behavior

With dependency `org.spockframework:spock-core:2.3-groovy-3.0`:

```
Expected no exception to be thrown, but got 'groovy.lang.MissingMethodException'
	at app//spock.lang.Specification.noExceptionThrown(Specification.java:118)
	at specs.MyTest.Can run a spec(MyTest.groovy:21)
Caused by: groovy.lang.MissingMethodException: No signature of method: spock.util.EmbeddedSpecRunner.runWithImports() is applicable for argument types: (String) values: [
        class Testing extends Specification {
          def 'testing'() {
            expect: true
          }
        }
        ]
	at specs.MyTest.Can run a spec(MyTest.groovy:12)
```

### Java version

```
openjdk 17.0.2 2022-01-18 LTS
OpenJDK Runtime Environment Zulu17.32+13-CA (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.32+13-CA (build 17.0.2+8-LTS, mixed mode, sharing)
```

Also tried Java 21 without changes.

### Buildtool version

```
Gradle 7.5.1
```

Also tried with the latest, 8.5 but that doesn't impact anything.

### What operating system are you using

Windows

### Dependencies

See build file attached.

### Additional context

We were doing this in the setupSpec before:

```
runner.addClassImport(Specification)
```

In which case the error says that there's no method `addClassImport(Class)` (but there is), which is the same problem, looks like all methods of this `EmbeddedSpecRunner` class became invisible?!

**Comment by renatoathaydes** [comment]
Also tried with spock `2.4-M1-groovy-3.0`, then with Groovy 4 and latest Spock, but the result is the same... this build file was used:

```groovy
plugins {
    id 'groovy'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

test {
    useJUnitPlatform()
}

dependencies {
    implementation('org.apache.groovy:groovy:4.0.6')
    testImplementation('org.spockframework:spock-core:2.4-M1-groovy-4.0')
    testImplementation('org.junit.jupiter:junit-jupiter:5.10.1')
    testRuntimeOnly('org.junit.platform:junit-platform-launcher:1.10.0')
}
```

**Comment by szpak** [comment]
It might be related to the problem described in https://github.com/spockframework/spock/issues/1178. Please add the `junit-platform-testkit` depedency.

**Comment by renatoathaydes** [comment]
@szpak this helped... but a strange behaviour now is that this stopped working:

```groovy
runner.addClassImport(Specification)
```

When I add the imports in the actual text given to `runner.run()`, it works though.

**Comment by Vampire** [comment]
That's expected.
If you use `run()` then you are expected to give the full source.
Things you gave to `add...Import` are only considered when you do `runWithImports` or "below" (below meaning for example `runSpecBody` or `runFeatureBody`)

**Comment by renatoathaydes** [comment]
Hm... the code was working fine before the update.. but maybe I changed this as I tried to figure out the issue... will try again after the holidays.

**Comment by Vampire** [comment]
I'm not talking about the missing optional dependency.

My message just referred to the last comments about the imports.

**Comment by renatoathaydes** [comment]
Yes, I know.

**Comment by leonard84** [comment]
I assume this has been resolved.
