### ISSUE TITLE
`SpockReleaseInfo.version` returns a different version than officially used

### ISSUE THREAD

**Issue by Vampire** [spockframework/spock#1859]
For Spock release `2.3-groovy-4.0` `SpockReleaseInfo.version` provides `2.3.0-groovy-4.0`.
These should be made consistent, either by releasing always with micro version or by fixing the version implementation.

**Comment by leonard84** [comment]
You have to use `SpockReleaseInfo.version.toOriginalString()`

**Comment by Vampire** [comment]
Well, I could, if I would use 2.4-M2 which is the first release containing that method. ;-)
But I still question the necessity for this.
Why can it not be consistent?

**Comment by leonard84** [comment]
It could be. Currently, it just returns the `VersionNumber` object that is used for other cases as well and supports up to patch version.

**Comment by Vampire** [comment]
Hm, at least the JavaDoc also briefly says it has "format major.minor.micro-qualifier" which I just didn't read. :-D
So with the addition of `toOriginalString`, let's consider this "fixed" in 2.4-M2.
