### ISSUE TITLE
`MockController` is not concurrency-friendly and leads to a deadlock

### ISSUE THREAD

**Issue by boris-petrov** [spockframework/spock#1882]
### Describe the bug

I've been debugging a random failure in one of my tests. It led me to the following stack-trace of a blocked thread:

```
      org.spockframework.mock.runtime.MockController.handle(MockController.java)
      org.spockframework.mock.runtime.JavaMockInterceptor.intercept(JavaMockInterceptor.java:86)
      org.spockframework.mock.runtime.ByteBuddyInterceptorAdapter.interceptNonAbstract(ByteBuddyInterceptorAdapter.java:35)
      ...
```

In my test basically I have a mock:

```groovy
def latch = new CountDownLatch(1)
Mock(Foo) {
  get(1) >> {
    assert latch.await(5, TimeUnit.SECONDS)
  }
  get(2) >> {
    latch.countDown()
  }
}
```

And then I concurrently call `get` with `1` and with `2`. If the thread that calls `1` gets to the `await` - the test fails. `MockController.handle` is a `synchronized` method and hence the second thread can't get in it (as the first one is in that method). Not sure if that's a known issue? If so, what's the workaround?

### To Reproduce

See above.

### Expected behavior

No deadlock.

### Actual behavior

Deadlock.

### Java version

21.0.2

### Buildtool version

Gradle 8.6.

### What operating system are you using

Linux

### Dependencies

Just Spock.

**Comment by leonard84** [comment]
Duplicates #583

**Comment by boris-petrov** [comment]
Thanks. The other one is closed however? Not sure what that means - is it a "wontfix"?

**Comment by boris-petrov** [comment]
I'm in the process of converting our application to use virtual threads. Therefore I changed a bunch of places to use new threads. That now causes a lot of deadlocks in Spock in cases like the above or like a mocked object's method calling something else which in another thread calls back in the mocked object. I'm not really sure how to fix those unfortunately.

**Comment by AndreasTu** [comment]
The PR  #1885 will fix both of the Tickets. See comment in the PR. I guess the "wont fix" #583 is wrong.

**Comment by boris-petrov** [comment]
Awesome! Thank you very much for the great support as usual!

**Comment by boris-petrov** [comment]
Great, thanks for merging the fix! Do you have an ETA on a new release (even a beta)?

**Comment by leonard84** [comment]
@boris-petrov https://github.com/spockframework/spock/releases/tag/spock-2.4-M2 was released today

**Comment by boris-petrov** [comment]
@leonard84 thanks for the new release! It seems to work great!

I did, however, hit another deadlock. Check the following code:

```groovy
class Foo {
    void bar() {
    }
}

...

def called = false
def foo
foo = Mock(Foo) {
    bar() >> {
        if (!called) {
            called = true
            Thread.start { foo.bar() }.join()
        }
    }
}
foo.bar()
```

This will deadlock. The problem seems (at least to me) to be in `MockInteraction` - there is a write lock that is acquired in `accept` and that causes the deadlock.

Let me know what you think. Should I open a new issue?

**Comment by leonard84** [comment]
@boris-petrov please open a new issue, as this is much smaller in scope. However, I'm not sure we can fix deadlocks in self-referential invocations while maintaining the integrity of the mock interactions. 
Moving the line https://github.com/spockframework/spock/blob/ce21741106ba0caa54174d7119f69078211285b5/spock-core/src/main/java/org/spockframework/mock/runtime/MockInteraction.java#L76
out of the lock would fix this, but it also means that the response generators would have to be thread-safe, which they are not, and users can bring their own. So, by fixing this we might introduce another set of bugs.

**Comment by boris-petrov** [comment]
@leonard84 thanks for taking the time to look into it!

I opened a new issue.

I understand the worry you have. I'm not sure what you mean by "response generators would have to be thread-safe" - is the "response generator" the part of code after `>>`? If so - I personally never expected that to be thread-safe. It's just "another method" - if I wanted thread-safety, I make sure it is. I definitely think that self-referential Mocks are more often encountered than the need for thread-safe response generators. Another point is that people can always make response generators thread-safe - just wrap them in a lock. But such a deadlock can't be worked-around in any way.

**Comment by Vampire** [comment]
I highly discourage you from using 2.4-M2.
It does not at all fix the deadlock, but on the other hand introduces major breakage in interaction matching in a multi-threaded situation.
Imho the PR needs to be reverted and a new release be done.
If you are interested in the details, please have a look at my latest comment on the linked PR.
