### ISSUE TITLE
`setupSpec()` execution order is incorrect.

### ISSUE THREAD

**Issue by GavinGuan24** [spockframework/spock#1888]
### Describe the bug

`DerivedSpec` in examples.

I rewrite the `derivedSpecMethod` method.

```
    def derivedSpecMethod() {
        setup:
        println 'UT setup'
        expect:
        xx == yy
        cleanup:
        println 'UT cleanup'

        where:
        xx | yy
        0  | 0
        1  | 1
    }
```

Then, stdout like this.

<img width="286" alt="image" src="https://github.com/spockframework/spock/assets/33683337/e59009ae-0c22-4e83-aafe-5e7a3cc8e9c4">

The `setupSpec()` execution order is incorrect.

### To Reproduce

`DerivedSpec` in examples.

I rewrite the `derivedSpecMethod` method.

```
    def derivedSpecMethod() {
        setup:
        println 'UT setup'
        expect:
        xx == yy
        cleanup:
        println 'UT cleanup'

        where:
        xx | yy
        0  | 0
        1  | 1
    }
```

Then, stdout like this.

<img width="286" alt="image" src="https://github.com/spockframework/spock/assets/33683337/e59009ae-0c22-4e83-aafe-5e7a3cc8e9c4">

The `setupSpec()` execution order is incorrect.

### Expected behavior

`base setupSpec()`
`derived setupSpec()`

base field initializer
derived field initializer
base setup()
derived setup()
UT setup
UT cleanup
derived cleanup()
base cleanup()
base field initializer
derived field initializer
base setup()
derived setup()
UT setup
UT cleanup
derived cleanup()
base cleanup()

~base setupSpec()~
~derived setupSpec()~

derived cleanupSpec()
base cleanupSpec()

### Actual behavior

base field initializer
derived field initializer
base setup()
derived setup()
UT setup
UT cleanup
derived cleanup()
base cleanup()
base field initializer
derived field initializer
base setup()
derived setup()
UT setup
UT cleanup
derived cleanup()
base cleanup()
`base setupSpec()`
`derived setupSpec()`
derived cleanupSpec()
base cleanupSpec()

### Java version

oracle jdk1.8.0_371

### Buildtool version

oracle jdk1.8.0_371
Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)

### What operating system are you using

Mac

### Dependencies

me.fizz:spock-ut:jar:1.0.0-SNAPSHOT
+- me.fizz:the-jar:jar:0.0.1-SNAPSHOT:test
|  +- org.springframework.boot:spring-boot-starter-web:jar:2.3.12.RELEASE:test
|  |  +- org.springframework.boot:spring-boot-starter-json:jar:2.3.12.RELEASE:test
|  |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.11.4:test
|  |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.11.4:test
|  |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.11.4:test
|  |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.11.4:test
|  |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.11.4:test
|  |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.11.4:test
|  |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.3.12.RELEASE:test
|  |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.46:test
|  |  |  +- org.glassfish:jakarta.el:jar:3.0.3:test
|  |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.46:test
|  |  +- org.springframework:spring-web:jar:5.2.15.RELEASE:test
|  |  |  \- org.springframework:spring-beans:jar:5.2.15.RELEASE:test
|  |  \- org.springframework:spring-webmvc:jar:5.2.15.RELEASE:test
|  |     +- org.springframework:spring-aop:jar:5.2.15.RELEASE:test
|  |     +- org.springframework:spring-context:jar:5.2.15.RELEASE:test
|  |     \- org.springframework:spring-expression:jar:5.2.15.RELEASE:test
|  +- com.baomidou:mybatis-plus-boot-starter:jar:3.3.2:test
|  |  +- com.baomidou:mybatis-plus:jar:3.3.2:test
|  |  |  \- com.baomidou:mybatis-plus-extension:jar:3.3.2:test
|  |  |     +- com.baomidou:mybatis-plus-core:jar:3.3.2:test
|  |  |     |  +- com.baomidou:mybatis-plus-annotation:jar:3.3.2:test
|  |  |     |  +- com.github.jsqlparser:jsqlparser:jar:3.1:test
|  |  |     |  \- org.mybatis:mybatis:jar:3.5.4:test
|  |  |     \- org.mybatis:mybatis-spring:jar:2.0.4:test
|  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.3.12.RELEASE:test
|  |  \- org.springframework.boot:spring-boot-starter-jdbc:jar:2.3.12.RELEASE:test
|  |     +- com.zaxxer:HikariCP:jar:3.4.5:test
|  |     \- org.springframework:spring-jdbc:jar:5.2.15.RELEASE:test
|  |        \- org.springframework:spring-tx:jar:5.2.15.RELEASE:test
|  +- com.alibaba:druid-spring-boot-starter:jar:1.2.16:test
|  |  +- com.alibaba:druid:jar:1.2.16:test
|  |  \- org.slf4j:slf4j-api:jar:1.7.30:test
|  +- mysql:mysql-connector-java:jar:8.0.25:test
|  +- org.apache.shardingsphere:sharding-jdbc-spring-boot-starter:jar:4.0.0-RC1:test
|  |  +- org.apache.shardingsphere:sharding-jdbc-core:jar:4.0.0-RC1:test
|  |  |  +- org.apache.shardingsphere:sharding-core-entry:jar:4.0.0-RC1:test
|  |  |  |  +- org.apache.shardingsphere:sharding-core-parse-common:jar:4.0.0-RC1:test
|  |  |  |  |  +- org.apache.shardingsphere:sharding-core-parse-spi:jar:4.0.0-RC1:test
|  |  |  |  |  +- org.apache.commons:commons-collections4:jar:4.2:test
|  |  |  |  |  \- org.antlr:antlr4-runtime:jar:4.7.1:test
|  |  |  |  +- org.apache.shardingsphere:sharding-core-parse-mysql:jar:4.0.0-RC1:test
|  |  |  |  +- org.apache.shardingsphere:sharding-core-parse-postgresql:jar:4.0.0-RC1:test
|  |  |  |  +- org.apache.shardingsphere:sharding-core-parse-oracle:jar:4.0.0-RC1:test
|  |  |  |  +- org.apache.shardingsphere:sharding-core-parse-sqlserver:jar:4.0.0-RC1:test
|  |  |  |  +- org.apache.shardingsphere:sharding-core-optimize:jar:4.0.0-RC1:test
|  |  |  |  +- org.apache.shardingsphere:sharding-core-route:jar:4.0.0-RC1:test
|  |  |  |  +- org.apache.shardingsphere:sharding-core-rewrite:jar:4.0.0-RC1:test
|  |  |  |  +- org.apache.shardingsphere:sharding-core-execute:jar:4.0.0-RC1:test
|  |  |  |  \- org.apache.shardingsphere:sharding-core-merge:jar:4.0.0-RC1:test
|  |  |  \- org.apache.shardingsphere:sharding-transaction-core:jar:4.0.0-RC1:test
|  |  +- com.google.guava:guava:jar:18.0:test
|  |  \- org.slf4j:jcl-over-slf4j:jar:1.7.30:test
|  \- org.apache.shardingsphere:sharding-core-common:jar:4.0.0-RC1:test
|     +- org.apache.shardingsphere:sharding-core-api:jar:4.0.0-RC1:test
|     +- org.yaml:snakeyaml:jar:1.26:test
|     \- commons-codec:commons-codec:jar:1.14:test
+- org.springframework.boot:spring-boot-starter-test:jar:2.3.12.RELEASE:test
|  +- org.springframework.boot:spring-boot-starter:jar:2.3.12.RELEASE:test
|  |  +- org.springframework.boot:spring-boot:jar:2.3.12.RELEASE:test
|  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.3.12.RELEASE:test
|  |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:test
|  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.3:test
|  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.13.3:test
|  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.13.3:test
|  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.30:test
|  |  \- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:test
|  +- org.springframework.boot:spring-boot-test:jar:2.3.12.RELEASE:test
|  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.3.12.RELEASE:test
|  +- com.jayway.jsonpath:json-path:jar:2.4.0:test
|  |  \- net.minidev:json-smart:jar:2.3.1:test
|  |     \- net.minidev:accessors-smart:jar:2.3.1:test
|  |        \- org.ow2.asm:asm:jar:5.0.4:test
|  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:test
|  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:test
|  +- org.assertj:assertj-core:jar:3.16.1:test
|  +- org.hamcrest:hamcrest:jar:2.2:test
|  +- org.junit.jupiter:junit-jupiter:jar:5.6.3:test
|  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.6.3:test
|  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.6.3:test
|  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.6.3:test
|  +- org.junit.vintage:junit-vintage-engine:jar:5.6.3:test
|  +- org.mockito:mockito-core:jar:3.3.3:test
|  |  \- net.bytebuddy:byte-buddy-agent:jar:1.10.22:test
|  +- org.mockito:mockito-junit-jupiter:jar:3.3.3:test
|  +- org.skyscreamer:jsonassert:jar:1.5.0:test
|  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
|  +- org.springframework:spring-core:jar:5.2.15.RELEASE:test
|  |  \- org.springframework:spring-jcl:jar:5.2.15.RELEASE:test
|  +- org.springframework:spring-test:jar:5.2.15.RELEASE:test
|  \- org.xmlunit:xmlunit-core:jar:2.7.0:test
+- org.junit.platform:junit-platform-launcher:jar:1.9.0:test
|  +- org.junit.platform:junit-platform-engine:jar:1.9.0:test
|  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
|  |  \- org.junit.platform:junit-platform-commons:jar:1.9.0:test
|  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
+- org.spockframework:spock-core:jar:2.3-groovy-3.0:test
|  \- org.codehaus.groovy:groovy:jar:3.0.19:test
+- org.spockframework:spock-junit4:jar:2.3-groovy-3.0:test
|  \- junit:junit:jar:4.13.2:test
|     \- org.hamcrest:hamcrest-core:jar:2.2:test
+- net.bytebuddy:byte-buddy:jar:1.14.8:test
\- org.objenesis:objenesis:jar:3.3:test

### Additional context

nothing

**Comment by kriegaex** [comment]
> `DerivedSpec` in examples.

Assuming you are talking about [this set of classes](https://github.com/spockframework/spock-example/blob/10538d068e8773990aba56d80548d784d2ab07e5/src/test/groovy/SpecInheritanceSpec.groovy), changing the sample code according to your description looks like this:

```groovy
import spock.lang.*

abstract class BaseSpec extends Specification {
  def x = { println 'base field initializer' }()

  def setupSpec() { println 'base setupSpec()' }
  def cleanupSpec() { println 'base cleanupSpec()' }

  def setup() { println 'base setup()' }
  def cleanup() { println 'base cleanup()' }

  def baseSpecMethod() { setup: println 'base spec method' }
}

class DerivedSpec extends BaseSpec {
  def y = { println 'derived field initializer' }()

  def setupSpec() { println 'derived setupSpec()' }
  def cleanupSpec() { println 'derived cleanupSpec()' }

  def setup() { println 'derived setup()' }
  def cleanup() { println 'derived cleanup()' }

  def derivedSpecMethod() {
    setup:
    println 'UT setup'
    expect:
    xx == yy
    cleanup:
    println 'UT cleanup'

    where:
    xx | yy
    0  | 0
    1  | 1
  }
}
```

Running this on the lastest master version on JDK 8 yields the following console log for me:

```text
base setupSpec()
derived setupSpec()
base field initializer
derived field initializer
base setup()
derived setup()
base spec method
derived cleanup()
base cleanup()
base field initializer
derived field initializer
base setup()
derived setup()
UT setup
UT cleanup
derived cleanup()
base cleanup()
base field initializer
derived field initializer
base setup()
derived setup()
UT setup
UT cleanup
derived cleanup()
base cleanup()
derived cleanupSpec()
base cleanupSpec()
```

That is exactly according to your expectation. I.e., I cannot reproduce the problem. Please either share a forked repository showing **exactly** what you changed, of compare yourself, if you might have changed something else. Like this, I think the bug should be closed.

**Comment by leonard84** [comment]
I have the same results as @kriegaex it works like [documented](https://spockframework.org/spock/docs/2.3/spock_primer.html#_invocation_order).

**Comment by GavinGuan24** [comment]
Please, You guys download the tgz file. And reproduce the problem.

**Comment by kriegaex** [comment]
Why didn't you just clone the repository and share a link? That way, we could verify your claim easily, displaying a diff to the original.

**Comment by GavinGuan24** [comment]
Because I want to preserve the full context.
Also, you don't want this project to be just about keeping behavior consistent in your environment.

**Comment by kriegaex** [comment]
Both are not reasons to select an uploaded archive instead of a shared Git project. Why make matters easy, if you can also complicate them? 😉

Anyway, I can take a look in a while, unless someone else is faster.

**Comment by GavinGuan24** [comment]
Ok, According to your custom,  I fork a Git project and modify some files. You can try it.

https://github.com/GavinGuan24/spock-example

**Comment by kriegaex** [comment]
Too late, I already unpacked your `.tgz` archive. Then, I deleted the IntelliJ stuff and backup files with underscores, imported the project freshly into IntelliJ and ran the test. I cannot reproduce your problem, the log output looks normal. Maybe you have some outdated stuff somewhere in your local project.

**Comment by GavinGuan24** [comment]
I don't know why it happened.
perhaps,  the reason is        I'm using `org.codehaus.groovy`'s groovy library?

**Comment by kriegaex** [comment]
I did not check in detail yet, but you must have messed up your Maven build, because the Maven build does not run the tests. It looks as if you removed the Maven Surefire setup from the sample project. See? That is the problem with claiming "I only changed one detail", if in reality you changed way more than that. That way, you are just making your own life more difficult than necessary.

**Comment by GavinGuan24** [comment]
NO way. I don't change `Maven Surefire setup`.

https://github.com/GavinGuan24/spock-example

it's exists.

**Comment by GavinGuan24** [comment]
I implore you to examine this project in detail.
I know you must be wondering if I've made some weird configuration.
But I didn't.

I believe this problem exists and has an impact on other projects.

It's just that Spock may not be the real problem.

**Comment by GavinGuan24** [comment]
`how much experience you have with Maven?`

only one.

Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)
Java version: 1.8.0_371, vendor: Oracle Corporation
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"

**Comment by GavinGuan24** [comment]
`how much experience you have with Maven?`

only one.

Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)
Java version: 1.8.0_371, vendor: Oracle Corporation
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"

**Comment by GavinGuan24** [comment]
https://github.com/GavinGuan24/spock-example

In this environment, This is a bug that is bound to appear.

**Comment by GavinGuan24** [comment]
The status quo is, you think the project is fine, I think there's bound to be a bug.
em......, I don't know why.
I even switched JDK17. But the bug is still there.

Although I may not be able to find the problem for the time being, I still appreciate your time.

Well, I suggest you keep an eye on the situation. In fact, my former colleagues had the same problem.

Also, he uses Windows, and the local environment is very different from what I have now.

**Comment by GavinGuan24** [comment]
For the time being. Thank you very much.

**Comment by kriegaex** [comment]
Do you have any special setup for parallel execution or something else that is not part of the project we see here?

I even forked your project again and expanded the build matrix to run on Windows, Linux and MacOS, each on JDK 8 and 21. The builds are passing, and on MacOS (which you seem to be using) it also looks fine:

* https://github.com/dev-aspectj/Spock_GH-1888_2/actions/runs/8049991982/job/21984608959#step:5:645
* https://github.com/dev-aspectj/Spock_GH-1888_2/actions/runs/8049991982/job/21984609273#step:5:645

Also, have you checked the build output from Maven, just to exclude the possibility that you have some problem with the internal console in the IDE?

**Comment by kriegaex** [comment]
IMO, even though a bug is always a possibilty, the probability is quite low, because I guess with the example project probably being used by many newbies, it would have surfaced earlier. It looks as if it is some local peculiarity connected to your local setup. I cannot prove that, of course. But you have not been able to provide something I can reproduce, either. It is hard to analyse a problem that neither occurs locally nor on a CI build on a matrix of several OS and JDK versions.

**Comment by GavinGuan24** [comment]
I found a new computer.  There is nothing about my current company.
And I did just:
1. git clone
2. use IntelliJ Idea unit test run


The problem is still here. 
JDK17 build-in with Idea.

There is nothing that concerns me alone.
I've given you everything I know.

That's too bad. Maybe it's just my fate.

**Comment by kriegaex** [comment]
> NO way. I don't change `Maven Surefire setup`.
> 
> https://github.com/GavinGuan24/spock-example

I was talking about your uploaded .tgz archive, the project named `sharding-jdbc-demo2`. There, definitely Surefire is missing. Please, next time test locally before editing an existing project and just uploading the result.

**Comment by GavinGuan24** [comment]
Github's integrated test environment is online. They work, but that doesn't mean they can replace a physical computer.
If possible, your team might want to verify it using a physical computer.

This issue is definitely independent of the JDK version. I've already verified it.

**Comment by kriegaex** [comment]
> 1. git clone
> 2. use IntelliJ Idea unit test run

I asked you to run Maven (`mvn clean test`) to exclude the possibility of an IDEA glitch. FWIW, I am running:

```text
IntelliJ IDEA 2023.3.4 (Ultimate Edition)
Build #IU-233.14475.28, built on February 13, 2024
```

I works, just as Maven does. Java 8, 17, 21, no difference. If it is not reproducible, I cannot help you. Maybe @leonard84 has more ideas. I do not.

**Comment by kriegaex** [comment]
> Github's integrated test environment is online. They work, but that doesn't mean they can replace a physical computer.

I already told you, I ran the tests locally. But I only have a Windows box, so I ran it on Linux and MacOS on GitHub for your sake, not mine. This conversation ends here, if you cannot provide a reproducible sample. BTW, please do not think I am a Spock team member. I have no commit rights here. I am just a user, like you, albeit a somewhat experienced one. I do not speak for the Spock team, just trying to unburden them on some of their support work.

**Comment by GavinGuan24** [comment]
> > Github's integrated test environment is online. They work, but that doesn't mean they can replace a physical computer.
> 
> I already told you, I ran the tests locally. But I only have a Windows box, so I ran it on Linux and MacOS on GitHub for your sake (because you are a Mac user), not mine.
> 
> This conversation ends here, if you cannot provide a reproducible sample. BTW, please do not think I am a Spock team member. I have no commit rights here. I am just a user, like you, albeit a somewhat experienced one. I do not speak for the Spock team, just trying to unburden them of some of their support work.


It worked. 
OMG, Thank you very much !!!
My English is not good. And I just realized you're not on the team.
You are even willing to spend this much time with me to identify this problem.
Thank you very much !!!
Thank you very much !!!
Thank you very much !!!

I have confirmed that it is the problem of the Idea unit test plug-in.
It worked on CLI.

Thank you very much !!!
Thank you very much !!!
Thank you very much !!!

**Comment by GavinGuan24** [comment]
If anyone is experiencing the same problem, please check the version of Idea.

the Idea unit test plug-in is bad.  --- IntelliJ IDEA 2022.3.3 (Ultimate Edition).
Later versions may still have this problem.

so, please, use CLI.

**Comment by kriegaex** [comment]
@GavinGuan24, are you sure? Can you please link to the IntelliJ IDEA issue describing the problem? I would like to check, if it was confirmed by JetBrains and whether it was solved or not. The reason is that I cannot remember to even have experienced this problem, and I have been using IDEA for many years, also the 2022.x versions. Does a version upgrade solve your problem? That it works on Maven, hints at the IDE, but root cause analysis is still important.

**Comment by GavinGuan24** [comment]
> @GavinGuan24, are you sure? Can you please link to the IntelliJ IDEA issue describing the problem? I would like to check, if it was confirmed by JetBrains and whether it was solved or not. The reason is that I cannot remember to ever have experienced this problem, and I have been using IDEA for many years, also the 2022.x versions. Does a version upgrade solve your problem? That it works on Maven, hints at the IDE, but root cause analysis is still important.

The Spock framework works really well when using the CLI.
I'm pretty sure this plugin is causing the problem.

### 1. incompatibility

The default version of dependencies used by plugins is too low.
Occured a mistake, but I can't remember what it was.

So I introduced a higher version of the dependency into the demo project. Then it worked.
```
    <dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-launcher</artifactId>
      <version>1.9.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-engine</artifactId>
      <version>1.9.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-commons</artifactId>
      <version>1.9.0</version>
      <scope>test</scope>
    </dependency>
```

### 2. Non-idempotence

First, I restarted computer and cleared all the caches of IDE.

when I ran `derivedSpecMethod` at first time, the output is correct, just like [documented](https://spockframework.org/spock/docs/2.3/spock_primer.html#_invocation_order).

then, I ran it again, The appearance of `setupSpec` will be chaotic again.

And, now, I don't know how to reproduce this problem. `setupSpec` always appears out of order at each time.

After a long time, I tried this method again, and it worked once, and then it was always chaotic again.

perhaps , the problem is related to some cache of IDE.


Using CLI, Spock always output the correct result at each time.

---
`Can you please link to the IntelliJ IDEA issue describing the problem?` 
I don't know how to search any issue for IntelliJ IDEA. I haven't been paying attention to that.

**Comment by GavinGuan24** [comment]
IntelliJ IDEA 2022.3.3 (Ultimate Edition)
Junit (bundled 223.8836.41)

**Comment by kriegaex** [comment]
The IntelliJ IDEA bug and feature tracker is here:
https://youtrack.jetbrains.com/projects/IDEA

What happens, if you use a more recent IDEA version?

**Comment by GavinGuan24** [comment]
> The IntelliJ IDEA bug and feature tracker is here: https://youtrack.jetbrains.com/projects/IDEA
> 
> What happens, if you use a more recent IDEA version?

You're really kind. I can describe the problem about IntelliJ Idea. 
But I don't want to spend time raising issues to the IntelliJ Team.

I noticed you're a maintainer of Eclipse AspectJ. This is your area of expertise.
If possible, You can follow up on this in your spare time.

actually very simple, I'm working on macOS(,10.15.7,x86_64,MacBook Pro 16-inch, 2019).

the dialog of the new version IDE appears with a significant delay.
every UI component with a significant delay.

Forget it. It's not an important thing.  I can keep using the old version IDE.

**Comment by kriegaex** [comment]
> I can describe the problem about IntelliJ Idea.
> But I don't want to spend time raising issues to the IntelliJ Team.

I do not understand this kind of attitude. You are opening an invalid ticket here and people are successfully trying to help you. You say, the issue persists in IntelliJ, even though nobody else can reproduce it here. You also say, your colleague has a similar problem. Are you not interested in getting the problem resolved? As an IDE user, you do not want to rely on Maven builds only but also build successfully from the IDE, don't you? So why then is iis too much work to create a reproducer and raise an issue for IDEA? You cannot expect for the error to just go magically away in the next update or so, if nobody at JetBrains is even aware of any possible problem in the first place. But up to you. (*shrug*)
