### ISSUE TITLE
Cannot cast BooleanAssert to Boolean when using assertj-core:3.25.3 StringAssert's in a Spock then block

### ISSUE THREAD

**Issue by nweiser94** [spockframework/spock#1897]
### Describe the bug

In the `3.25.3` release of `assertj-core` a feature was added that allows any `StringAssert` to be interpreted and asserted as a boolean value through the `AbstractStringAssert#asBoolean()` method. `asBoolean()` returns a `BooleanAssert` instance to allow further method chaining with boolean assertions.

The `then` block in a Spock test feature wraps any assertion code line with a Groovy Power Assert `assert` under the hood and expects the actual assertion to be evaluated as a boolean value.
This conflicts with the Groovy built-in `org.codehaus.groovy.runtime.DefaultGroovyMethods#asBoolean(java.lang.Object)` that Spock is using on anything that is not a Boolean value.

In the end this produces ClassCastExceptions for any usage of `StringAssert` from assertj.

### To Reproduce

```groovy
import spock.lang.Specification

import static org.assertj.core.api.Assertions.assertThat

class DemoSpec extends Specification {
    def 'assert some integer'() {
        when:
        def someInteger = 10

        then:
        assertThat(someInteger).isEqualTo(10)
    }

    def 'assert some string'() {
        when:
        def someString = 'some string'

        then:
        assertThat(someString).isEqualTo('some string')
    }
}
```

### Expected behavior

All tests are successful.

### Actual behavior

The `assert some string` feature fails due to a `ClassCastException - BooleanAssert cannot be casted to Boolean`.

### Java version

openjdk 17.0.10 2024-01-16
OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7)
OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode)

### Buildtool version

------------------------------------------------------------
Gradle 8.6
------------------------------------------------------------

Build time:   2024-02-02 16:47:16 UTC
Revision:     d55c486870a0dc6f6278f53d21381396d0741c6e

Kotlin:       1.9.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.10 (Eclipse Adoptium 17.0.10+7)
OS:           Mac OS X 14.2.1 aarch64

### What operating system are you using

Mac

### Dependencies

- org.apache.groovy:groovy-all:4.0.18
-  org.spockframework:spock-core
- org.spockframework:spock-bom:2.3-groovy-4.0
- org.spockframework:spock-junit4
- org.assertj:assertj-core:3.25.3

**Comment by AndreasTu** [comment]
Can you expain the reason, why you want to write:

```groovy
then:
assertThat(someInteger).isEqualTo(10)
assertThat(someString).isEqualTo('some string')
```
instead of:

```groovy
then:
someInteger == 10
someString == 'some string'
```
The Spock power asserts are shorter to write and have a better error message than the AssertJ assertions.


Note: Since `2.4-M2`: If you want to suppress the assertion you can write `!!` before a line to prevent assertions.
```groovy
then:
!!assertThat(someInteger).isEqualTo(10)
```
See [Opt-out of condition handling](https://spockframework.org/spock/docs/2.4-M2/spock_primer.html#opt-out-of-condition-handling) for details.

**Comment by AndreasTu** [comment]
Also [here](https://gwc-experiment.appspot.com/?g=groovy_4_0&codez=eNp1T1EKwjAM_e8pwn62_XgAwQ_FE1gvULtMC1srTcYE6d1tO-mY4PsIeUneSyKEHhQRnHF08oka8MVoO4JETG-0YuMsvAVEdNhDHafRM5AbEYi9sfe6ab8DCfMD7b6wJHFwAIszXJH4mNWSp1vTijLFG43b9ZPVsZ9IyDEH4niMhuXgrdm6fluHxWltJ3jkydu41FCph5KVRObnQNHJuQGV_WNTyeul-vEJInwAir5cjw) is a reproducer without AssertJ dependency:

```groovy
class DemoSpec extends Specification {
    def 'assert some string'() {
        when:
        def o = new TestAssertStub()

        then:
        o.func()
    }
    
    static class TestAssertStub{
        TestAssertStub func(){
            return this
        }
        
        String asBoolean(){
            return "STR"
        }
    }
}
```

Throws:
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean
````

**Comment by AndreasTu** [comment]
I am really not sure here, because this also break, when Spock is not involved, but only Groovy:

```groovy
def o = new TestAssertStub()
assert o.func()

class TestAssertStub{
    TestAssertStub func(){
        return this
    }

    String asBoolean(){
        return "STR"
    }
}
```

AssertJ does not play well here with the Groovy sematic to use the method `asBoolean()` to convert it to a boolean.

**Comment by leonard84** [comment]
Spock 2.4-M2 introduced an [opt-out for assertions](https://spockframework.org/spock/docs/2.4-M2/spock_primer.html#opt-out-of-condition-handling)

**Comment by leonard84** [comment]
I don't think there is anything for us to fix, as @AndreasTu already pointed out we have the opt-out operator, but in this particular case the `asBoolean` conflicts with Groovy's [default methods](https://docs.groovy-lang.org/latest/html/gapi/org/codehaus/groovy/runtime/DefaultGroovyMethods.html#asBoolean(java.lang.Object)).

**Comment by scordio** [comment]
@leonard84 @AndreasTu I'd be happy to get your thoughts on https://github.com/assertj/assertj/issues/3381#issuecomment-1972158364.
