### ISSUE TITLE
variables not substituted during Unroll

### ISSUE THREAD

**Issue by am312** [spockframework/spock#1913]
### Describe the bug

When naming tests, `#someVariable` will be substituted in the HTML test report output but not in the std out logs.   

### To Reproduce

  defining a test like this:

  `def "testing '#someVariable' now!"() {...}`

### Expected behavior

I expect to see "testing 123.45 now!" in both the HTML report and the logs.  

### Actual behavior

Variable is substituted in the HTML report but not in the logs

### Java version

JDK-21

### Buildtool version

------------------------------------------------------------
Gradle 8.4
------------------------------------------------------------

Build time:   2023-10-04 20:52:13 UTC
Revision:     e9251e572c9bd1d01e503a0dfdf43aedaeecdc3f

Kotlin:       1.9.10
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          1.8.0_402 (Azul Systems, Inc. 25.402-b06)
OS:           Mac OS X 14.3.1 aarch64

### What operating system are you using

Mac

### Dependencies

variable

**Comment by leonard84** [comment]
Please provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) that illustrates your problem.
