### ISSUE TITLE
Mock Beans

### ISSUE THREAD

**Issue by urmichm** [spockframework/spock#1950]
### Is your feature request related to a problem?

When running the Specification test. It would be great to mock a Bean. Especially the beans which are not part of the tested controller or deeply nested within beans hierarchy. So we can avoid the following problems:
```
Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'javax.sql.DataSource' available: expected at least 1 bean which qualifies as autowire candidate.
```
DataSource object is part of the repo which is used in a service which is part of the controller which i have intention to use or deal with in my unit test of completely unrelated controller. 

### Describe the solution you'd like

To Mock a bean

### Describe alternatives you've considered

quitting spockframework

**Comment by Vampire** [comment]
Is Spock Spring not providing what you need? 
https://spockframework.org/spock/docs/2.3/modules.html#_spring_module

**Comment by urmichm** [comment]
it did not help as DataSource and its service and its controller are all grails and are from grails-app scope.
Even with use of annotations like @SpringBean or mock bean, does not help. Probably (just my thought) the exception is thrown before mocks initialized

**Comment by Vampire** [comment]
I have no idea about Grails, but it has built-in Spock support since version 2.3.

**Comment by urmichm** [comment]
Sorry, I just realized I opened the wrong issue
