### ISSUE TITLE
When the mocked function parameter is int and the mock is as int, it will always fail!

### ISSUE THREAD

**Issue by liudaolunboluo** [spockframework/spock#1974]
> ### Describe the bug
> When the mocked function parameter is int and the mock is as int, it will always fail! The reason is that spock uses the isIntance method internally, in mock.spockframework.constraint.TypeArgumentConstraint.java:
```java 
  @Override
  public boolean isSatisfiedBy(Object argument) {
    return type.isInstance(argument) && constraint.isSatisfiedBy(argument);
  }
```
> In java, int's isInstance is converted to an object, meaning that it will convert int i to Integer, and int instance Integer is > definitely false
> That is, as long as my method arguments are of primitive types like int long, then as long as I use the as keyword in the > unit test, then the unit test will never pass
> ### To Reproduce
> 
> 
> The method to be mocked is：
 ```java
    String test(int a,int b);
 ```
> 
> 
> calling code：
> ```java
> public void testInt() {
>     int i = 123;
>     int j = 456;
>     String a = client.test(i, j);
>     System.out.println(a);
> }
> ```
> 
> and Our unit tests:
> ```groovy
>     def test_testInt() {
>         given: "param"
> 
>         and: "mock"
>       //test method
>         client.test(_ as int, _ as int) >> "success"
> 
>         when: "invoke"
>       //now invoke method
>         XXX.testInt()
> 
>         then: "validation"
>         1 * client.test(_ as int, _ as int)
> 
>     }
> ```
> 
> 
> ### Expected behavior
> 
> Able to successfully run unit tests and print success
> 
> ### Actual behavior
> 
> and result:
> null
> 
> Too few invocations for:
> 
> 1 * client.test(_ as int, _ as int)   (0 invocations)
> 
> Unmatched invocations (ordered by similarity):
> 
> 1 * client.test(123, 456)
> One or more arguments(s) didn't match:
> 0: argument instanceof int
>    |        |          |
>    |        false      int
>    123 (java.lang.Integer)
> 1: argument instanceof int
>    |        |          |
>    |        false      int
>    456 (java.lang.Integer)
> 
> 
> Here int should be treated as integer, otherwise it will always be false because of Java's automatic boxing mechanism.
> 
> ### Java version
> 
> jdk11
> 
> ### Buildtool version
> 
> 11.0.16.1
> 
> ### What operating system are you using
> 
> Mac
> 
> ### Dependencies
```xml
>   <dependency>
>             <groupId>org.codehaus.groovy</groupId>
>             <artifactId>groovy-all</artifactId>
>             <version>3.0.9</version>
>             <type>pom</type>
>         </dependency>
>         <dependency>
>             <groupId>org.spockframework</groupId>
>             <artifactId>spock-core</artifactId>
>             <version>2.3-groovy-3.0</version>
>             <scope>test</scope>
>         </dependency>
```
> ### Additional context
> 
> _No response_
> ```

**Comment by liudaolunboluo** [comment]
> ### Describe the bug
> When the mocked function parameter is int and the mock is as int, it will always fail! The reason is that spock uses the isIntance method internally, in mock.spockframework.constraint.TypeArgumentConstraint.java:
> 
>  public boolean isSatisfiedBy(Object parameter) {
>     Return type.isInstance(parameter) && Constraint.isSatisfiedBy(parameter); ``` public boolean isSatisfiedBy(object parameter)
>   }
> 
> ### To Reproduce
> 
> 
> The method to be mocked is：
 ```java
    String test(int a,int b);
 ```
> 
> 
> calling code：
> ```java
> public void testInt() {
>     int i = 123;
>     int j = 456;
>     String a = client.test(i, j);
>     System.out.println(a);
> }
> ```
> 
> and Our unit tests:
> ```groovy
>     def test_testInt() {
>         given: "param"
> 
>         and: "mock"
>       //test method
>         client.test(_ as int, _ as int) >> "success"
> 
>         when: "invoke"
>       //now invoke method
>         XXX.testInt()
> 
>         then: "validation"
>         1 * client.test(_ as int, _ as int)
> 
>     }
> ```
> 
> 
> ### Expected behavior
> 
> Able to successfully run unit tests and print success
> 
> ### Actual behavior
> 
> and result:
> null
> 
> Too few invocations for:
> 
> 1 * client.test(_ as int, _ as int)   (0 invocations)
> 
> Unmatched invocations (ordered by similarity):
> 
> 1 * client.test(123, 456)
> One or more arguments(s) didn't match:
> 0: argument instanceof int
>    |        |          |
>    |        false      int
>    123 (java.lang.Integer)
> 1: argument instanceof int
>    |        |          |
>    |        false      int
>    456 (java.lang.Integer)
> 
> 
> Here int should be treated as integer, otherwise it will always be false because of Java's automatic boxing mechanism.
> 
> ### Java version
> 
> jdk11
> 
> ### Buildtool version
> 
> 11.0.16.1
> 
> ### What operating system are you using
> 
> Mac
> 
> ### Dependencies
> 
>   <dependency>
>             <groupId>org.codehaus.groovy</groupId>
>             <artifactId>groovy-all</artifactId>
>             <version>3.0.9</version>
>             <type>pom</type>
>         </dependency>
> 
>         <dependency>
>             <groupId>org.spockframework</groupId>
>             <artifactId>spock-core</artifactId>
>             <version>2.3-groovy-3.0</version>
>             <scope>test</scope>
>         </dependency>
> 
> ### Additional context
> 
> _No response_
> ```

**Comment by AndreasTu** [comment]
**Reproducer** 
Yes I can reproduce the issue with:

```groovy 
class MockPrimitiveTypeResponsesSpec extends Specification {
  private static final String SUCCESS = "success"

  @Issue("https://github.com/spockframework/spock/issues/1974")
  def "Mock Response with primitive types Issue #1974"() {
    given:
    ObjClass client = Mock()

    when: "invoke"
    def response = client.test(123, 456)

    then: "validation"
    1 * client.test(_ as int, _ as int) >> SUCCESS
    response == SUCCESS
  }

  static class ObjClass {
    String test(int a, int b) {
      return ""
    }
  }
}
```
See [WebConsole of TestSpec above](https://groovyconsole.dev/?g=groovy_3_0&codez=eNpVUUtLw0AQvudXDOslkdJQrYqFFqF48CCK0bNst5N2TLoJmUmqiP_d3U3i47bz-F6zptTMcF-Z4rGhAwl1-PxR4xNyXVlGzmo0gO-CdsvgC8rJaKHKwmcEUDfUaUFgcT0DOVldQiYN2R1kL-v1bZbBEhS3xiCzihzk5o65xVjtRWpepOmOZN9upqY6pE7TFHmjD3ismqIvU_LrnM6ur-Yqcfgt5qC8YRhNwtFReCu9fxAXgCHIwEnAxUlwC7Bzc7sIz4fN2zqENyWhFWfTk8ZJFKbHvdsDRbarClSh5YWbUXI5wKaCLPHs7HwC84vLASw9uNMlbcOteoIZnP5DvYJmICsTGF8JrFbj3QLkV2_5p__lZYaTm5DhJ0wfc_iBoOJoQU88O2zGM3hiaRsLqnf2FUgdbRR9A0AjpFM)

**Workarounds**
If you remove the `int`s from the `1 * client.test(_ as int, _ as int)`, 
=> `1 * client.test(_, _) >> "success"`  which would work

You can also make it `1 * client.test(_ as Integer,  _ as Integer) >> "success"` if you want to be sure they are ints.
See [Working WebConsole](https://groovyconsole.dev/?g=groovy_3_0&codez=eNpVUc1OwzAMvvcprHBp0bRqMEBM2oQ0ceCAQBTOKMvcLrRLq9jtQGjvTpK2ME6J7Xx_jqokETzWqny2eq9Zd_j61eALUlMbQsoaVICfjGZL4AudayVZ1wa-I4DG6k4yArHrKci1kRVkbLUpIHtbr--zDJYgqFUKiUTkIHcPRC3GYsfc0CJNC827djNV9T51mqrMrdzjobZlX6baP6d0dnszF4nDbzEH4Q3DaBIOjsJb6f0DuwAEQQbOAi5OgluAws3NIlyfNh_rEF5VGg07m540TqIwPezcOxDadHWJIrS8sB0llwNsykgczy4uJzC_uh7A3IM7Welt2FVPMIPzf6h3kM6mYSzQTuC0SmC1GvcXoH-6y5P-0csNq1chy2-oPu7wE0FNu4xyAv7YjOvwxNxaA6J3eAykjjaKfgDjBKdZ)

**Question**
So my question would be, why do you need the *real* primitive `int` type in the test code?

**Comment by liudaolunboluo** [comment]
> **重现者** 是的，我可以使用以下方法重现该问题：
> 
> ```groovy
> class MockPrimitiveTypeResponsesSpec extends Specification {
>   private static final String SUCCESS = "success"
> 
>   @Issue("https://github.com/spockframework/spock/issues/1974")
>   def "Mock Response with primitive types Issue #1974"() {
>     given:
>     ObjClass client = Mock()
> 
>     when: "invoke"
>     def response = client.test(123, 456)
> 
>     then: "validation"
>     1 * client.test(_ as int, _ as int) >> SUCCESS
>     response == SUCCESS
>   }
> 
>   static class ObjClass {
>     String test(int a, int b) {
>       return ""
>     }
>   }
> }
> ```
> 
> 参见[上文TestSpec的WebConsole](https://groovyconsole.dev/?g=groovy_3_0&codez=eNpVUUtLw0AQvudXDOslkdJQrYqFFqF48CCK0bNst5N2TLoJmUmqiP_d3U3i47bz-F6zptTMcF-Z4rGhAwl1-PxR4xNyXVlGzmo0gO-CdsvgC8rJaKHKwmcEUDfUaUFgcT0DOVldQiYN2R1kL-v1bZbBEhS3xiCzihzk5o65xVjtRWpepOmOZN9upqY6pE7TFHmjD3ismqIvU_LrnM6ur-Yqcfgt5qC8YRhNwtFReCu9fxAXgCHIwEnAxUlwC7Bzc7sIz4fN2zqENyWhFWfTk8ZJFKbHvdsDRbarClSh5YWbUXI5wKaCLPHs7HwC84vLASw9uNMlbcOteoIZnP5DvYJmICsTGF8JrFbj3QLkV2_5p__lZYaTm5DhJ0wfc_iBoOJoQU88O2zGM3hiaRsLqnf2FUgdbRR9A0AjpFM)
> 
> **解决方法** 如果你`int`从`1 * client.test(_ as int, _ as int)`, =>中删除 s`1 * client.test(_, _) >> "success"` 就可以了
> 
> `1 * client.test(_ as Integer, _ as Integer) >> "success"`如果你想确保它们是整数，也可以这样做。 请参阅[“正在使用的 WebConsole”](https://groovyconsole.dev/?g=groovy_3_0&codez=eNpVUc1OwzAMvvcprHBp0bRqMEBM2oQ0ceCAQBTOKMvcLrRLq9jtQGjvTpK2ME6J7Xx_jqokETzWqny2eq9Zd_j61eALUlMbQsoaVICfjGZL4AudayVZ1wa-I4DG6k4yArHrKci1kRVkbLUpIHtbr--zDJYgqFUKiUTkIHcPRC3GYsfc0CJNC827djNV9T51mqrMrdzjobZlX6baP6d0dnszF4nDbzEH4Q3DaBIOjsJb6f0DuwAEQQbOAi5OgluAws3NIlyfNh_rEF5VGg07m540TqIwPezcOxDadHWJIrS8sB0llwNsykgczy4uJzC_uh7A3IM7Welt2FVPMIPzf6h3kM6mYSzQTuC0SmC1GvcXoH-6y5P-0csNq1chy2-oPu7wE0FNu4xyAv7YjOvwxNxaA6J3eAykjjaKfgDjBKdZ)
> 
> **问题**所以我的问题是，为什么在测试代码中 需要_真正的_原始类型？`int`

Because my parameters are primitive types, int and Integer are automatically unboxed and boxed in Java. If my parameters are primitive types, then my test will also be primitive types. This makes logical sense, and In the idea, what will be automatically generated is also based on the parameter type of the method. Here is the primitive type. If Spock does not support primitive types, this should be explained in the document, but I did not find it.

**Comment by liudaolunboluo** [comment]
> **Reproducer** Yes I can reproduce the issue with:
> 
> ```groovy
> class MockPrimitiveTypeResponsesSpec extends Specification {
>   private static final String SUCCESS = "success"
> 
>   @Issue("https://github.com/spockframework/spock/issues/1974")
>   def "Mock Response with primitive types Issue #1974"() {
>     given:
>     ObjClass client = Mock()
> 
>     when: "invoke"
>     def response = client.test(123, 456)
> 
>     then: "validation"
>     1 * client.test(_ as int, _ as int) >> SUCCESS
>     response == SUCCESS
>   }
> 
>   static class ObjClass {
>     String test(int a, int b) {
>       return ""
>     }
>   }
> }
> ```
> 
> See [WebConsole of TestSpec above](https://groovyconsole.dev/?g=groovy_3_0&codez=eNpVUUtLw0AQvudXDOslkdJQrYqFFqF48CCK0bNst5N2TLoJmUmqiP_d3U3i47bz-F6zptTMcF-Z4rGhAwl1-PxR4xNyXVlGzmo0gO-CdsvgC8rJaKHKwmcEUDfUaUFgcT0DOVldQiYN2R1kL-v1bZbBEhS3xiCzihzk5o65xVjtRWpepOmOZN9upqY6pE7TFHmjD3ismqIvU_LrnM6ur-Yqcfgt5qC8YRhNwtFReCu9fxAXgCHIwEnAxUlwC7Bzc7sIz4fN2zqENyWhFWfTk8ZJFKbHvdsDRbarClSh5YWbUXI5wKaCLPHs7HwC84vLASw9uNMlbcOteoIZnP5DvYJmICsTGF8JrFbj3QLkV2_5p__lZYaTm5DhJ0wfc_iBoOJoQU88O2zGM3hiaRsLqnf2FUgdbRR9A0AjpFM)
> 
> **Workarounds** If you remove the `int`s from the `1 * client.test(_ as int, _ as int)`, => `1 * client.test(_, _) >> "success"` which would work
> 
> You can also make it `1 * client.test(_ as Integer, _ as Integer) >> "success"` if you want to be sure they are ints. See [Working WebConsole](https://groovyconsole.dev/?g=groovy_3_0&codez=eNpVUc1OwzAMvvcprHBp0bRqMEBM2oQ0ceCAQBTOKMvcLrRLq9jtQGjvTpK2ME6J7Xx_jqokETzWqny2eq9Zd_j61eALUlMbQsoaVICfjGZL4AudayVZ1wa-I4DG6k4yArHrKci1kRVkbLUpIHtbr--zDJYgqFUKiUTkIHcPRC3GYsfc0CJNC827djNV9T51mqrMrdzjobZlX6baP6d0dnszF4nDbzEH4Q3DaBIOjsJb6f0DuwAEQQbOAi5OgluAws3NIlyfNh_rEF5VGg07m540TqIwPezcOxDadHWJIrS8sB0llwNsykgczy4uJzC_uh7A3IM7Welt2FVPMIPzf6h3kM6mYSzQTuC0SmC1GvcXoH-6y5P-0csNq1chy2-oPu7wE0FNu4xyAv7YjOvwxNxaA6J3eAykjjaKfgDjBKdZ)
> 
> **Question** So my question would be, why do you need the _real_ primitive `int` type in the test code?

Because my parameters are primitive types, int and Integer are automatically unboxed and boxed in Java. If my parameters are primitive types, then my test will also be primitive types. This makes logical sense, and In the idea, what will be automatically generated is also based on the parameter type of the method. Here is the primitive type. If Spock does not support primitive types, this should be explained in the document, but I did not find it

**Comment by leonard84** [comment]
We could check `type.isPrimitive()` and then lookup the boxed variant in `TypeArgumentConstraint`. I'm pretty sure that differentiating between `int` and `Integer` is impossible at this point.
