### ISSUE TITLE
Allow users/frameworks to register a `DefaultValueProvider` to enhance `EmptyOrDummyResponse` via `ServiceLoader`

### ISSUE THREAD

**Issue by leonard84** [spockframework/spock#1984]
### Is your feature request related to a problem?

Stubs will try to respond with a non-null value. This works fine most of the time, but in certain circumstances, it can lead to difficult-to-diagnose errors. For example, https://ratpack.io/ has an async API based on `ratpack.exec.Promise`. Since there is no special handling, a `Stub` will create another `Stub` when generating a value for `ratpack.exec.Promise`. The problem is that this `Stub` will not comply with the contract of `Promise`, and any chain it becomes part of will stop computing.

### Describe the solution you'd like

I want to introduce a DefaultValueProvider interface that is loaded via `ServiceLoader` in `EmptyOrDummyResponse`. `EmptyOrDummyResponse` will ask the registered `DefaultValueProvider` to provide a value before falling back to generating a `Stub`.

Users could create their own `DefaultValueProvider` in their projects to handle these problems. Framework authors can also ship a `DefaultValueProvider` for their classes that need special handling with their test library.

### Describe alternatives you've considered

Currently, users can override the default `EmptyOrDummyResponse` using the `defaultResponse`, e.g., `Stub(type, defaultResponse: RatpackAwareEmptyOrDummyResponse.INSTANCE)`. However, this requires that every use site be changed.

An alternative option that could achieve this and might still complement the `DefaultValueProvider`, is to make the `defaultResponse` configurable via the spock config for the build.

**Comment by AndreasTu** [comment]
Ich would like such a feature. I had similar problems in the past with some return types, which have a default value.

**Comment by leonard84** [comment]
Implemented by #1994
