### ISSUE TITLE
Release spock 2 for groovy-version 2.4

### ISSUE THREAD

**Issue by Pymann** [spockframework/spock#2000]
### Is your feature request related to a problem?

Yes, we have issues with spock testing framework 1.3, that are solved in version 2.
But version 2 is not release for groovy version 2.4.21, that a jenkins master is using. And problem is, a jenkins master cannot update its groovy version due to issues https://issues.jenkins.io/browse/JENKINS-53372
Therefore last version usable of spock for testing jenkins pipeline code is 1.3

### Describe the solution you'd like

release https://mvnrepository.com/artifact/org.spockframework/spock-bom
for groovy version 2.4.21

### Describe alternatives you've considered

no idea of any alternatives....

### Additional context

its also not possible to update only gradle build to groovy 2.5 because it has jenkins-package-dependencies depending on groovy 2.4.21

**Comment by leonard84** [comment]
Groovy 2.4.x is [EOL](https://endoflife.date/apache-groovy), so I don't think releasing a new version and fixing all the problems that might occur with 2.4.x is the right thing to do. 

I would try to raise the pressure on the Jenkins side to update to a supported Groovy version.
