### ISSUE TITLE
configure the test method to run multiple times

### ISSUE THREAD

**Issue by robfletcher** [spockframework/spock#320]
Originally reported on Google Code with ID 198

```
For some concurrent integration tests I found myself running some methods multiple times
to chase some race conditions that show up intermittently.

Something like:

@InvocationCount(10)
def "should..."() {

That would be useful for debugging, for sanity checks when one wants to run a test
method say 100 times to make sure it is rock solid, etc.

In theory the idea could grow into something more robust. Inspiring from testNG:
@Concurrent(threadPoolSize = 3, invocationCount = 10,  timeOut = 10000)

It's just an idea. Think about it and if it makes sense it would be cool to have it
in the framework :)
```

Reported by `szczepiq` on 2011-09-01 09:01:21

**Comment by iousin** [comment]
Some way to do it via GebConfig will be non-intrusive.

**Comment by leonard84** [comment]
FYI Spock 2.3 has a new [@RepeatUntilFailure](https://spockframework.org/spock/docs/2.3/all_in_one.html#_repeat_until_failure) extension, that can be used for manual checking for race conditions or debugging in general.

I don't plan to add a general `@Repeat(X)` annotation, as I think that it is not a good practice to have a test that is repeated X times to "sure" that it works in your code base, as this will slow all testing down, and if one is added it will not be the last.
