### ISSUE TITLE
Option for running tests in a single spec

### ISSUE THREAD

**Issue by robfletcher** [spockframework/spock#415]
Originally reported on Google Code with ID 293

```
Provide a method for running a single spec, or even a single package, from the command
line. Something similar to Grails' `test-app ExampleService` would be very useful by
allowing developers to quickly run a test in a single spec rather than having to @Ignore
the tests they do not want to run.

```

Reported by `poorgeek` on 2013-01-14 18:12:12

**Comment by farrukhnajmi** [comment]
```
This is accomplished as follows: `gradle [testTask] -D[testTask].single=[className]`

Example: `gradle test -Dtest.single=MySpec`
```

Above will run all tests in the class. What we need is ability to run a single specified test.

In case of junit where Class is `Foo` and test method is `bar` one can run the following gradle task:

gradle test --tests Foo.bar

What is the equivalent of that for gradle to run a specific SPock test.

Please consider reopening this issue.

**Comment by rtretyak** [comment]
Try `-- test "Foo#bar"`. This works with maven, not sure above gradle

**Comment by leonard84** [comment]
See 
* https://docs.gradle.org/current/userguide/java_testing.html#simple_name_pattern
* https://docs.gradle.org/current/userguide/java_testing.html#full_qualified_name_pattern

**Comment by farrukhnajmi** [comment]
It does not seem to work with gradle 4.7.

**Comment by leonard84** [comment]
It is `--tests` you are missing a `s`

**Comment by farrukhnajmi** [comment]
> It is `--tests` you are missing a `s`

Doh! Thanks a million @leonard84. It works
