### ISSUE TITLE
Support creation of mocks outside the Spock context and allow to associate such a mock with a specification

### ISSUE THREAD

**Issue by robfletcher** [spockframework/spock#427]
Originally reported on Google Code with ID 305
```
Spock should offer an API that allows
* Creating a mock outside a Specification instance (for example a bean instance managed
by some container such as Spring, etc.)
* Associate such a mock with the current specification instance.


This would allow creating an integration test where complex interactions with external
resources such as 3rd-party services (web service) can be mocked. This is often requried
as these services are slow, accessible only with complex authentication, etc.

See also the forum discussion at https://groups.google.com/forum/?fromgroups=#!topic/spockframework/mKD4HD7tbEs

```

Reported by `Martin.Ahrer` on 2013-03-27 10:35:03

**Comment by derkork** [comment]
Any news about this? I think the feature would still be useful.

**Comment by leonard84** [comment]
See #17

**Comment by randomeizer** [comment]
Is there a 1.1 release (or even a beta release) coming anytime soon? We would like to use this feature in production.

**Comment by nirud** [comment]
We also need this feature. 
I could not find any information about the planned 1.1 release. Is there a planned time or should we better use a snapshot build?

**Comment by dudadornelles** [comment]
+1folks, this feature is much needed!

**Comment by snimavat** [comment]
+1

**Comment by robfletcher** [comment]
Implemented in #546

Will be released in 1.1

**Comment by Blackbaud-JasonBodnar** [comment]
@robfletcher could you share a quick example of how to do this?

**Comment by szpak** [comment]
@Blackbaud-JasonBodnar You can take a look into PRs diff. For example those [tests](https://github.com/spockframework/spock/pull/546/files#diff-ecf388e685548aaac0b20359bfacfc68R7).

**Comment by leonard84** [comment]
@Blackbaud-JasonBodnar see also http://spockframework.org/spock/docs/1.1-rc-3/modules.html
