### ISSUE TITLE
Soft assertions

### ISSUE THREAD

**Issue by robfletcher** [spockframework/spock#454]
Originally reported on Google Code with ID 332

```
Describe the new feature you have in mind.

It would be great to have possibility to execute "soft" assertions. I mean something
like verify*() methods in Selenium API.

Which particular problem would this feature solve for you?

It would let me execute a following (next) assertion even if the current one fails.
E.g. in case when I need to check more than one object attribute value.

Please provide any additional information below. You can also assign labels.

The syntax could be like

expect:
object != null               // standard assertion (a mandatory check)
@Soft object.attributeA == a // soft assertion (I need to know if the attributeB has
expected value as well)
@Soft object.attributeB == b // soft assertion (I need to know if the attributeC has
expected value as well)
object.attributeC == c       // standard assertion (the last check never needs to be
a soft assertion)

I understand that the issue can be solved using complicated helper methods but it is
not a groovy way, is it?
```

Reported by `krakadzeyau` on 2013-10-08 10:33:58

**Comment by arnonmoscona** [comment]
Anybody interested in soft assertions and how they behave needs to look at [AssertJ](http://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html#soft-assertions)

As @robfletcher says - this "helper" can work as-is in Spock, but this is certainly not the Groovy way. It would be nice to have a cleaner syntax. maybe something like:

```groovy
given: "preconditions"
//...
when: "stimulus"
//...
then: "assertions"
1==1
and:
1<2
andAll: "this is a set of soft assertions"
1>2 // failes, but does not stop the test
2<3 // tested and passes
2>4 // tested, fails
```

In a syntax like this `thenAll` and `andAll` labels use soft assertions, where the test does not stop running on the first assertion failure, but instead continues to the end of the soft section, where all failures are collected and messages for all of them are emitted to the output (should any fail)

**Comment by leonard84** [comment]
Related to #50 

I like the idea of having the `thenAll`, `expectAll` to make it more clearer than the suggested annotation in #50. However, I'm against `andAll` since `and` is just visual sugar and does not actually create a new block, so having `andAll` behaving differently would be suboptimal.

Btw: these issues were imported and robfletcher didn't actually write any of this ;)

**Comment by arnonmoscona** [comment]
Thanks @leonard84 
I was just thinking, maybe even a cleaner syntax would be following the syntax of `with()` in a `then:` block. Something like:
```groovy
given: "preconditions"
//...
when: "stimulus"
//...
then: "assertions"
1==1
validateAll() { // this is a set of soft assertions
  1>2 // failes, but does not stop the test
  2<3 // tested and passes
  2>4 // tested, fails
}
```

This would not introduce a new type of block, and would be syntactically/visually consistent with the use of `with(something){}` in the same context...

Just an idea...

**Comment by dzieciou** [comment]
What is the current state of this feature request?

**Comment by szpak** [comment]
It's already implemented in https://github.com/spockframework/spock/pull/595 and released in 1.1.

**Comment by StephenOTT** [comment]
@szpak is this feature supposed to work with Groovy Power Assertions?  It appears that doing a power assertion `assert x == y` does not respect the verifyAll() usage.

**Comment by szpak** [comment]
Hmm, looking at that code [snipped](https://github.com/spockframework/spock/pull/595/files#diff-5cbe48135a8759989f5136c7223ef19fR16) (from the corresponding PR) I would expect to have it working.

Could share a sample test the actual and the expect result?

**Comment by StephenOTT** [comment]
@szpak when i do

``
veryifyAll {

    assert a == b
    assert x == y

}
```

The second assert will not be reached.
It is the same issues if you use assertJ assertThat, or use assert that() from hamcrest.
If you just use `that()` without the "assert" in front it works as expected

Here is a snippet of a example i am working with:

``` groovy
  @Unroll
  def "Message Events Check: External Implementation"(){
    expect:
      verifyAll {
        that(event['implementation']['topic'], notNullValue())
        that(event['eventId'], notNullValue())
        that(event['eventName'], notNullValue())
      }
   where:
   event << model.getMessageEvents().findAll { it['implementation']['camundaType'] == 'external'}
}
```

**Comment by szpak** [comment]
I didn't know. I suspect that explicit "assert" shorts the logic. It can be a problem having assertions extracted to a separated methods.

@jarl-dk what do you think about that? Would it be easy to implement/enhance?

**Comment by StephenOTT** [comment]
Should htis be opened as a new issue?

**Comment by szpak** [comment]
I would opt for it as the original request - soft assertions - is already implemented.

**Comment by StephenOTT** [comment]
x-ref: https://github.com/spockframework/spock/issues/855
