### ISSUE TITLE
Ability to create nested specs

### ISSUE THREAD

**Issue by robfletcher** [spockframework/spock#479]
Originally reported on Google Code with ID 357
```
I think it would be great to have the ability to have the ability to create and execute
nested specs, similar to the capability to use nested describe and context blocks in
RSpec.

This would allow for considerable DRY'ness in code.
```

Reported by `sherbhachu` on 2014-04-05 13:35:22

**Comment by paplorinc** [comment]
I think this needs a better description and some example usecase

**Comment by leonard84** [comment]
I would say this duplicates #106 so I'm closing it, if someone disagrees we can reopen it.
