### ISSUE TITLE
Groovy 'star-dot' '(*.) operator doesn't work on properties of Spock doubles

### ISSUE THREAD

**Issue by robfletcher** [spockframework/spock#482]
Originally reported on Google Code with ID 360

```
Seems that Groovy 'star-dot' operator doesn't like stubbed properties of Spock doubles.
Instead of returning the stubbed value, it returns an object. See the attached test
case (ready to run in Groovy console):

@Grapes([
    @Grab(group='org.spockframework', module='spock-core', version='0.7-groovy-2.0'),
    @Grab(group='cglib', module='cglib-nodep', version='3.1'),
])

class AmountHolderSpec extends spock.lang.Specification {
    def "star-dot operator doesn't work with Spock doubles"() {
        given:
        def holders = [
            Stub(AmountHolder) { it.amount >> 10.0 },
            Stub(AmountHolder) { it.amount >> 20.0 },        
        ]        

        expect:
        holders[0].amount == 10.0 // fine
        holders[1].amount == 20.0 // fine
        holders*.amount == [10.0, 20.0] // failure
    }
}

class AmountHolder {
    BigDecimal getAmount() {
        throw new IllegalArgumentException('should be stubbed')
    }
}


```

Reported by `mgryszko` on 2014-04-22 12:14:04

**Comment by AndreasTu** [comment]
Works with Spock 2.3.0 and Groovy 2.5, 3.0 and 4.0.
See [Groovy Web Console](https://gwc-experiment.appspot.com/?g=groovy_4_0&codez=eJyVUUFrwjAYvfdXfHhRh6vV46CCY4Pt7FF6SJPPNBiTknxZheF_X9Nq7RAG-255vPfyeI9r5j1sTzYY-rBaoNvVyAHPhEZ48LXlx1QzI9OIq4PijJQ18J1AewIPMPHE3LOwBLZGx8g6EBa9mRI01h2hUVTBLvq0eCg1-slsftXHk-oLzcvwjJZVF8RDDvsBj7ejUM7GWVsfUJSyDoLNBlZZmsFl8U_VulfdBIO6GJABwnNbA93jXqPus-Lml-d9iuUSDsrgA3M1Zq7_YD6NePtouejoRcdnSgfXSy7JJUn4w47Xil-VfGuHOzENEqkn_OqfKmcbMNjAp9Yomd46GU5o6P3MsY5jz6a-skELKBF8W2aJYjq_fz3u-ge0XalJ)

So I am closing this ticket.
