### ISSUE TITLE
Spock and Slf4j combination causes compilation error

### ISSUE THREAD

**Issue by robfletcher** [spockframework/spock#491]
Originally reported on Google Code with ID 369

```
When using Spock in combination with Slf4j, compilation errors can occur.

Example test with compilation error:
-------------
@Slf4j
class ExampleUnitTest extends Specification {

    def 'exercise compilation error'() {

        given:
        true

        when:
        true

        then:
        [1, 2, 3].each { assert true }
    }
}
----------------
Resulting error:
----------------
Error:Groovyc: The current scope already contains a variable of the name $spock_valueRecorder
--------------------

Doing any of the following will fix the test:
- comment out the '@Slf4j' line
- remove the 'assert' from within the closure
- move the 'assert' outside the closure

Again, this is a combination of having an 'assert' inside a closure, while also having
the test annotated with @Slf4j.

This occurs with:
spock version 0.7-groovy-2.0
groovy version = 2.3.3-indy

This *does not* occur with:
spock version 0.7-groovy-2.0
groovy version = 2.3.1-indy

We tend to log in our unit and integration tests, and Slf4j has worked great so far
with us. However, we are now stuck at either Groovy 2.3.1, or need to remove all instances
of log messages. Removing assertions from closures is probably not an option, since
it would invalidate many tests.
```

Reported by `msal98` on 2014-07-09 12:52:17

**Comment by guptapranav01** [comment]
Hi,

I am using spock-core:1.0-groovy-2.4. I am also facing same error:
/Users/pranav_gupta/plugins/calypso-tdd-plugin/branches/CALYPSO-TDD-PLUGIN_2-0_PATCHES_GRADLE2/src/test/groovy/com/calypso/gradle/tdd/integrationtest/taskchaining/AbstractRunChainedTask.groovy: -1: The current scope already contains a variable of the name $spock_valueRecorder
 @ line -1, column -1.

Can somebody help me?

**Comment by dcw312** [comment]
I am also seeing this. I just upgraded to...
org.codehaus.groovy:groovy-all:jar:2.4.3
org.spockframework:spock-core:jar:1.0-groovy-2.4

removing @Slf4j annotation from the child or parent eliminates the problem but a fix would be nice.

**Comment by cooniur** [comment]
Also see this bug using together with Spring Boot `1.4.3.RELEASE`
```
    testCompile("org.spockframework:spock-core:1.1-groovy-2.4-rc-2")
    testCompile("org.spockframework:spock-spring:1.1-groovy-2.4-rc-2")
```

Btw, I'm surprised that this bug hasn't been addressed yet...

**Comment by leonard84** [comment]
My guess is that the AST modifications (log and spock) interfere with each other. I can only say that this is a fairly low priority, as using logging in tests is not that common/recommended. If there is an easy fix we will accept a PR for this.

**Comment by lubosek** [comment]
Workaround is to declare the logger in the non-Groovy, plain-ol'-Java way:
`//@Slf4j
class TestClass extends Spec {
    final static Logger log = LoggerFactory.getLogger(TestClass.class)`

**Comment by JeffQuandt** [comment]
This currently appears to work with `1.1-groovy-2.4`.

**Comment by shivamcausecode** [comment]
@JeffQuandt Not working with `1.1-groovy-2.4`.

**Comment by cooniur** [comment]
Just got hit by this issue with following versions (using `@Slf4j`):
```
org.spockframework:spock-spring:1.1-groovy-2.4
org.spockframework:spock-core:1.1-groovy-2.4
```

**Comment by leonard84** [comment]
Fixed with #856

**Comment by leonard84** [comment]
@gantaa as stated in the docs

>The latest release version is 1.2-RC2 (**1.2-RC2-groovy-2.4**, 1.2-RC2-groovy-2.5), released on 2018-08-14.

**Comment by gantaa** [comment]
My mistake.  thanks for the quick reply.  I was mis-led because I didnt see the 1.2-RC2-groovy-2.4 listed in maven repo browser: https://mvnrepository.com/artifact/org.spockframework/spock-core

But after adding the dependency anyways it downloads fine.  thank you

**Comment by rtretyak** [comment]
1.2-RC2-groovy-2.4 also fixes the same issue I had with using `@Memoized` transformation on helper methods inside spec
