### ISSUE TITLE
Move from Maven Central/Sonatype to jCenter (or other repo that uses HTTPS)

### ISSUE THREAD

**Issue by robfletcher** [spockframework/spock#494]
Originally reported on Google Code with ID 372
```
For security reasons, usage of Maven Central should be deprecated.

See:
http://blog.ontoillogical.com/blog/2014/07/28/how-to-take-over-any-java-developer/
```

Reported by `msgilligan` on 2014-07-29 10:37:48

**Comment by leonard84** [comment]
Use JCenter it provides https

**Comment by szpak** [comment]
@robfletcher Isn't it an obsolete case? Maven Central provides HTTPS access as well - https://repo1.maven.org/maven2/org/spockframework/spock-core/1.0-groovy-2.4/. 

What's more it has seemed to be active since August 2014 - http://www.infoq.com/news/2014/08/Maven-SSL-Default

**Comment by szpak** [comment]
Ups, I missed it was an issue imported from Google Code and it's date is not August 2015, but "2014-07-29 10:37:48".
