### ISSUE TITLE
Where block parameters should be able to reference each other

### ISSUE THREAD

**Issue by robfletcher** [spockframework/spock#509]
Originally reported on Google Code with ID 387
```
It would be nice if parameters defined with `<<` could reference previous definitions.
Then one could do things like this to make one's tests more robust to refactoring:

    where:
        IDENTIFIER = 'fooId'
        snippet << ["""<label for="${IDENTIFIER}"/><input type="text" id="${IDENTIFIER}"
/>"""]

However, this is not currently possible:

- Parameters defined with `=` can reference ones defined previously
- Parameters defined with `<<` or in table format cannot reference ones defined previously,
not even those defined with `=`

Example: https://github.com/emlun/spock-parameter-cross-reference-fail/blob/master/src/test/groovy/Foo.groovy

It would also be nice if parameters in table format could reference other parameters
as well, but I suspect its usefulness is more limited.
```

Reported by `lundberg.emil` on 2015-02-11 11:37:15

**Comment by paplorinc** [comment]
+1 for both!

@spockframework, should I try to provide a pull request for it?

**Comment by paplorinc** [comment]
Related test: `spock-specs\src\test\groovy\org\spockframework\smoke\parameterization\DataTables.groovy` # `"cells cannot reference other cells"`

**Comment by leonard84** [comment]
This could get quite ugly, you'll get into an ordering hell (prevent cross-references). Some cases might work while others don't, which might confuse the user. 

Although it is not as fancy you can already reference `@Shared` fields in tables and lists.

**Comment by Fuud** [comment]
Shared fields conflicts with concurrent execution. Also Shared fields should not be used on a per-test basis, such usage will confuse users.

Cross-referensing can be fixed by strong evaluation order: from up to down and from left to right.

**Comment by paplorinc** [comment]
> Cross-referencing can be fixed by strong evaluation order: from up to down and from left to right.
Exactly, I don't see why this should be a problem, just evaluate it via normal flow (and have compile errors for forward references).

I would like to experiment with this, would a PR be welcome for this feature?
