### ISSUE TITLE
spockframework.org still points to Google Code

### ISSUE THREAD

**Issue by harningt** [spockframework/spock#516]
Since the Google Code page is archived and read-only, the domain should be updated to a new location - perhaps to a webpage based on GitHub Pages.

**Comment by antony** [comment]
Agreed. This is gives bad impression (sense of abandonment!) for the framework.

**Comment by andyvdh** [comment]
Sorry, didn't found this issue while searching.

**Comment by vogella** [comment]
+1

**Comment by nicolaiparlog** [comment]
By now Google code gives a "404 - The project spock was not found" for the target URL https://code.google.com/archive/p/spock/ . This should really be fixed.

**Comment by nicolaiparlog** [comment]
The same is true for some of the links listed in [spock-example's README](https://github.com/spockframework/spock-example).

**Comment by stavytskyi** [comment]
+1

**Comment by barrow-wight** [comment]
http://spockframework.org/ still gives a 404

Doesn't look good when you're trying to persuade others to use the framework when this is the first thing they get on following links in the README

**Comment by jirutka** [comment]
@pniederw, pretty please, could you change http://spockframework.org/ to redirect to https://github.com/spockframework/spock instead of already dead Google Code?

**Comment by bluepoet** [comment]
+1

**Comment by jhermann** [comment]
I just wanted to go to a homepage (if one exists). C'mon guys, the move is a while back now, and Google did not manage to redirect all old URLs properly.

**Comment by leonard84** [comment]
Yes we want that too, the problem is that we have issues to reach the owner of the actual domain.

**Comment by pniederw** [comment]
@leonard84 That's not the problem. I had a recent conversation on this with Rob. He said he'd get back to me when he's ready to make a change, and didn't want to make a change until then.

**Comment by leonard84** [comment]
I stand corrected my information was outdated.

**Comment by leonard84** [comment]
Already been fixed for some time.
