### ISSUE TITLE
Wrong Import-Package version range for cglib

### ISSUE THREAD

**Issue by ShahimEssaid** [spockframework/spock#519]
Wrong version range on https://github.com/spockframework/spock/blob/master/spock-core/core.gradle#L32 

```
instruction 'Import-Package', 
    'org.objenesis;version="[1,2)";resolution:=optional', 
    'org.apache.tools.ant;version="[1,2)";resolution:=optional', 
    'org.apache.tools.ant.types;version="[1,2)";resolution:=optional',
    'net.sf.cglib.proxy;version="[2.2,2)";resolution:=optional'   <-- problem
```

This should probably be [2,2.2). I noticed this when Nexus was failing to create the P2 metadata from the Jar file. The full error message is:

org.sonatype.nexus.plugins.p2.repository.internal.DefaultP2MetadataGenerator - Could not generate p2 metadata of [central:org/spockframework/spock-core/1.0-groovy-2.4/spock-core-1.0-groovy-2.4.jar] due to Range minimum "2.2.0" is not less then range maximum "2.0.0" (inclusion is required at both ends if the versions are equal). Bailing out.

**Comment by ShahimEssaid** [comment]
I also had to add several JUnit package imports to resole class not found errors. These are appended at the end of the full header shown below. Only after these changes was I able to run this test: https://code.google.com/p/spock/wiki/HelloSpock

Import-Package: org.objenesis;version="[1,2)";resolution:=optional,net
 .sf.cglib.proxy;version="[2,2.2)";resolution:=optional,org.apache.too
 ls.ant.types.selectors;version="[1.7,2)";resolution:=optional,groovy.
 lang;version="[1.8,3)",org.codehaus.groovy.ast;version="[1.8,3)",org.
 codehaus.groovy.ast.expr;version="[1.8,3)",org.codehaus.groovy.ast.st
 mt;version="[1.8,3)",org.codehaus.groovy.classgen;version="[1.8,3)",o
 rg.codehaus.groovy.control;version="[1.8,3)",org.codehaus.groovy.cont
 rol.messages;version="[1.8,3)",org.codehaus.groovy.reflection;version
 ="[1.8,3)",org.codehaus.groovy.runtime;version="[1.8,3)",org.codehaus
 .groovy.runtime.callsite;version="[1.8,3)",org.codehaus.groovy.runtim
 e.metaclass;version="[1.8,3)",org.codehaus.groovy.runtime.typehandlin
 g;version="[1.8,3)",org.codehaus.groovy.runtime.wrappers;version="[1.
 8,3)",org.codehaus.groovy.syntax;version="[1.8,3)",org.codehaus.groov
 y.transform;version="[1.8,3)",org.codehaus.groovy.util;version="[1.8,
 3)",org.junit.runner;version="[4,7)",org.apache.tools.ant.types;versi
 on="[1,2)";resolution:=optional,org.apache.tools.ant;version="[1,2)";
 resolution:=optional,org.junit.runner.manipulation;version="[4,7)",or
 g.junit.runners.model;version="[4,7)",org.junit;version="[4,7)",org.j
 unit.internal.runners.model;version="[4,7)",org.junit.runner.notifica
 tion;version="[4,7)"

**Comment by leonard84** [comment]
`[2.2,2)` should probably be `[2.2,3)`.

The question is if we can somehow generate it from the maven dependencies, since this is not currently verified in tests and thus prone to be forgotten.

**Comment by Steve973** [comment]
I just checked the latest snapshot at https://oss.sonatype.org/content/repositories/snapshots/org/spockframework/spock-core/1.1-groovy-2.4-SNAPSHOT/spock-core-1.1-groovy-2.4-20160202.210844-36.jar and the error is still in the manifest file.

**Comment by leonard84** [comment]
@Steve973 could you check the PR to verify that it works.
