### ISSUE TITLE
Incompatible versions

### ISSUE THREAD

**Issue by georgepapas** [spockframework/spock#52]
Has something recently changed.  We have been using 1.0-groovy-2.0-SNAPSHOT for quite some time.   Suddenly all our builds are failing with the error:

`The Spock compiler plugin cannot execute because Spock 1.0.0-groovy-2.0-SNAPSHOT is not compatible with Groovy 2.3.6`

Any ideas?
Cheers

**Comment by pniederw** [comment]
You’ll need to switch to 1.0-groovy-2.3-SNAPSHOT.

Cheers,
Peter

**Comment by georgepapas** [comment]
Thanks for the quick reply!

**Comment by shiyang-fei** [comment]
Hi,

I also hit the same error. I tried to use 2.3-SNAPSHOT but I hit the below error. Does this mean I will have to update my groovy to 2.3.10?

GRADLE CONFIG
        compile 'org.codehaus.groovy:groovy-all:2.3.1'

        testCompile 'org.spockframework:spock-core:1.0-groovy-2.3-SNAPSHOT'
        testCompile 'org.spockframework:spock-spring:1.0-groovy-2.3-SNAPSHOT'

ERROR:
Warning:Groovyc: The global transform for class groovy.grape.GrabAnnotationTransformation is defined in both jar:file:/C:/Users/sfei.ENSO/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-all/2.3.1/feb21b101e98f2346af46c52fbb7177d81525ee8/groovy-all-2.3.1.jar!/META-INF/services/org.codehaus.groovy.transform.ASTTransformation and jar:file:/C:/Users/sfei.ENSO/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-all/2.3.10/e6fc2dc8fe2512efa0e78a2c0ae52ea1d724106d/groovy-all-2.3.10.jar!/META-INF/services/org.codehaus.groovy.transform.ASTTransformation - the former definition will be used and the latter ignored.

**Comment by robfletcher** [comment]
That's because `spock-core` depends on `groovy` and you're explicitly pulling in `groovy-all`. That's fine but you should exclude the transitive dependency from `spock-core` to prevent a clash.

**Comment by facundofarias** [comment]
I will keep the old 0.7-groovy-2.0 version. Any ideas when this will be released?
Thanks.

**Comment by guptapranav01** [comment]
Hi,

We are just upgrading to java 8 for which we have groovy 2.4. The spock framework compatible only with groovy-2.4 is 1.0. When I am trying to build using project with all these, I am having test cases failure. Some failures are due to the methods which we are using and those methods are removed from spock-1.0.
Do anybody have idea how to resolve it.

**Comment by robfletcher** [comment]
@guptapranav01 which methods are missing?
