### ISSUE TITLE
@Ignore on superclass specification ignored

### ISSUE THREAD

**Issue by chrylis** [spockframework/spock#534]
I tried to disable a suite of integration tests in preparation for shutting down an obsolete feature by annotating their common base class with `@Ignore`, but all of the feature methods, from both super- and subclasses, ran. I believe that `@Ignore` on a superclass should ignore all specs in the hierarchy.

I'm using 1.0-groovy-2.4.

**Comment by gajo4256** [comment]
Hi @chrylis ,

maybe you can try sth like this: https://gist.github.com/gajo4256/4f2c7079fedd840e2222

**Comment by chrylis** [comment]
Perhaps make that logic an annotation parameter? `@Ignore(inherited = true)`?

**Comment by gajo4256** [comment]
why not, but since we don't have this option for `@Ignore`...  The question is whether this is sth that spock guys would like to have, when yes I could create PR for that (with java 7 code of course)

**Comment by tomdcc** [comment]
Just tried to do this with `@IgnoreIf` to do something like the opposite: temporarily disable a set of tests while some supporting work was still ongoing.
