### ISSUE TITLE
@IgnoreIf cannot be combined with @Requires

### ISSUE THREAD

**Issue by davidnortonjr** [spockframework/spock#535]
We've got a scenario where we want to use both `@IgnoreIf` and `@Requires`. Something like:

    @IgnoreIf({ getEnvironment() == 'brokenEnvironment' })
    @Requires({ appVersion() > 123 })
    void "test" () {
        expect:
        ....
    }

What appears to occur is that it will run even when `environment == brokenEnvironment`, because the IgnoreIf extension calls `setSkipped(true)`, but then the `RequiresExtension` calls `setSkipped(false)`. I would expect that given both of these annotations, the test should only run if both the `@IgnoreIf` condition is false, and the `@Requires` condition is true.

Obviously I could just combine them into one annotation, but the real issue is that I have a custom extension that extends `AbstractFilterExtension`, and that cannot be reliably combined with an `@IgnoreIf` or `@Requires` extension.

Would it make sense to change `IgnoreIfExtension` and `RequiresExtension` to follow the logic of `AbstractFilterExtension`? I can submit a PR.

    if(GroovyRuntimeUtil.isTruthy(result)) {
        skippable.setSkipped(true);
    }

Here's a failing test:

    @IgnoreIf({ true })
    @Requires({ true })
    void "test" () {
        expect:
        false
    }

**Comment by leonard84** [comment]
@davidnortonjr yes it makes sense that `@IgnoreIf` and `@Requires` only set skipped to true if they apply, but don't set it to false if they don't. Would you like to create a PR? The commit message should be something like `Fix @IgnoreIf and @Requires erroneously enabling tests`

**Comment by davidnortonjr** [comment]
@leonard84 will do, sometime this weekend. Thanks.

**Comment by leonard84** [comment]
Merged the fix (356584c6bafe45f40af66d6e40c8f39be4febf47), thanks for the contribution.

**Comment by mkutz** [comment]
Any idea when the next release of Spock will happen?

We want to use `@Requires` together with our own [Scopes Extension](https://github.com/mkutz/spock-scope-extension) and it simply doesn't work due to this bug.

I it will take multiple months we would rather consider to write our own implementation of `@Requires` but we would clearly prefer not to do that.

**Comment by leonard84** [comment]
@mkutz the only thing that blocks the planned 1.1 is #17, I've talked to @robfletcher today and we worked out the missing parts. I'll try to get it implemented in the next two weeks.

**Comment by mkutz** [comment]
@leonard84 thanks for the answer. I think we can wait for 2-4 weeks.

**Comment by mkutz** [comment]
@leonard84 as far as I can see #17 is closed. So will there be a release any time soon?
