### ISSUE TITLE
Designing a Spock logo

### ISSUE THREAD

**Issue by andyvdh** [spockframework/spock#545]
Spock has no logo yet. I thought i'll give it a try...
(Disclaimer: I’m not a designer)<br><br>

![spock](https://raw.githubusercontent.com/andyvdh/spock/master/logo.png)

**Comment by leonard84** [comment]
Related #34
Thanks for the idea, I think it's to close to the starfleet logo to be usable.

**Comment by sbglasius** [comment]
At least it's very close to my PR #34 about a year back. I like the font though. :)
