### ISSUE TITLE
Requirement for a new Label/Block for Spock for Spock Reports

### ISSUE THREAD

**Issue by manueljordan** [spockframework/spock#559]
Hello

Just curious if is possible create a new Label/Block named how _Notes_ or _Observations_

I know I can work through many _then_ blocks and add some text data. But just to add or highlight some complement data how "note" or "observation" after of some _then_ block, I am asking for this possible new feature. 

Of course that is new block is going to be used to improve the Spock Reports output data for a method test. 

Thanks

**Comment by leonard84** [comment]
Sorry we will not be adding new blocks.
