### ISSUE TITLE
Documentation: @Ignore has no "reason" parameter

### ISSUE THREAD

**Issue by mkutz** [spockframework/spock#56]
According to the extensions https://github.com/spockframework/spock/blob/master/docs/extensions.adoc the `@Ignore` annotation has a `reason` parameter, but it has not (see https://github.com/spockframework/spock/blob/07c2d477563ccb40dde6a7f701a2056ebe4c10e1/spock-core/src/main/java/spock/lang/Ignore.java).

**Comment by PascalSchumacher** [comment]
Issue should be closed. Thanks!

**Comment by jaredsburrows** [comment]
Yes, this issue can be closed.
