### ISSUE TITLE
Asserting multiple properties of a mock invocation parameter

### ISSUE THREAD

**Issue by ddimtirov** [spockframework/spock#562]
I need to verify that certain listener is being called with particular data. The "right" way to do it currently is:

```
1 * listener.onEvent({ 
    it.cursorName                 == 'all messages' &&
    it.description                == 'a message from the middle' &&
    it.pattern                    == msg(a: 4) &&
    it.assertionResult            == msg(a: 4) &&
    it.skippedMessages.size()     == 3 &&
    it.skipping &&
    !it.negative &&
    it.timeoutMs >= it.durationMs &&
    it.cursorSelector &&
    it.predicate &&
    !it.predicateThrows 
})
```

Notice the dangling `&&` at the end of every line. It also is a bit difficult to read (I know I could introduce a method, but I would like to actually see the expressions.

After some reshufling, our current code looks like this:

```
1 * listener.onEvent({ 
    assert it.cursorName                 == 'all messages'
    assert it.description                == 'a message from the middle'
    assert it.pattern                    == msg(a: 4)
    assert it.assertionResult            == msg(a: 4)
    assert it.skippedMessages.size()     == 3

    assert it.skipping
    assert !it.negative
    assert it.timeoutMs >= it.durationMs
    assert it.cursorSelector
    assert it.predicate
    assert !it.predicateThrows
    true
})
```

The advantage is that when debugging, one can see where the exception is thrown (would be nice to have been reported - i.e. not only which method did not match, but also why). 

Note the `true` at the end of the closure - it is required as the closure is treated as expression.

Ideally I would prefer a syntax along these lines:

```
1 * listener.onEvent(matchArg { 
    cursorName                 == 'all messages'
    description                == 'a message from the middle'
    pattern                    == msg(a: 4)
    assertionResult            == msg(a: 4)
    skippedMessages.size()     == 3
    skipping
    !negative
    timeoutMs >= it.durationMs
    cursorSelector
    predicate
    !predicateThrows
})
```

Each line is an assertion (similar to `then` block). The error message will specify which assertion failed for which method.

**Comment by voberle** [comment]
This is quite a dangerous thing. It's quite easy to write by accident:

    1 * listener.onEvent(matchArg { 
        cursorName                 == 'all messages'
    })

and have your test "pass", while the condition is actually not checked.

I'm wondering if there is some tool that can catch such mistakes, like a way to configure FindBugs or PMD?

**Comment by leonard84** [comment]
You can already do this kind of assertions in Spock using the `with` method.

```java
  def "use closure to match arguments"() {
    List list = Mock()

    when:
    list.add("spock")
    then:
    1 * list.add({
      with(it) {
        size() == 5
        charAt(2) == "o"
        contains("ock")
      }
      true
    })
  }
```

There is a caveat, it uses assertions instead of Boolean matching, so you can use it only if you expect a single type of call to a method, you can't use it to differentiate between multiple calls to the same method.

@voberle I don't quite get what you mean.
