### ISSUE TITLE
Failure stack trace should contain data table row.

### ISSUE THREAD

**Issue by Fuud** [spockframework/spock#563]
For example for test

```
package package1

import spock.lang.Specification
import spock.lang.Unroll


class Test extends Specification {
    @Unroll
    def test(int a, int b) {
        expect:
            a > b
        where:
            a | b
            1 | 2
            3 | 4
            6 | 6

    }
}
```

Stack trace will be following:

```
Condition not satisfied:

a > b
| | |
1 | 2
  false


    at package1.Test.test(Test.groovy:11)
```

It is hard to navigate to data provider line (it will be even harder if data is complicated).

For table-based parametrization stack should be like this:

```
Condition not satisfied:

a > b
| | |
1 | 2
  false


    at package1.Test.test(Test.groovy:11)
    at package1.Test.test(Test.groovy:14)       
```

**Comment by nach-o-man** [comment]
@Fuud There is a mechanism of placeholders for this purpose.
[from documentation](http://spockframework.github.io/spock/docs/1.0/data_driven_testing.html)

> @Unroll
> def "maximum of #a and #b is #c"() { ... }
> This method name uses placeholders, denoted by a leading hash sign (#), to refer to data variables a, b, and c. In the output, the placeholders will be replaced with concrete values:
> 
> maximum of 3 and 5 is 5   PASSED
> maximum of 7 and 0 is 7   FAILED
>

**Comment by Fuud** [comment]
@nach-o-man 
Yes it can be a workaround. But only in simple cases. And not usefull in complecated ones or with big tables. It is hard to manually search for line with specified data.

**Comment by leonard84** [comment]
You can use "hidden" `iterationCount` in `@Unroll`

```
  @Unroll("max of #a and #b is #c [#iterationCount]")
  def "unroll with naming pattern in annotation"() {
    expect:
    Math.max(a, b) == c

    where:
    a | b  | c
    1 | 4  | 4
    5 | 30 | 30
    1 | 1  | 1
  }
```

> max of 1 and 4 is 4 [0]
> max of 5 and 30 is 30 [1]
> max of 1 and 1 is 1 [2]

I don't think that actually manipulating the stacktrace to include the datatable position as a stackframe is that helpful and it would be quite hacky if at all possible.
