### ISSUE TITLE
Mocking service class method parameter incorrectly calls service base class method

### ISSUE THREAD

**Issue by mbjarland** [spockframework/spock#569]
Pasting issue description from: 

[example project exhibiting this problem](https://bitbucket.org/mbjarland/spock-mocking-issue).

---
## Problem

We have the following setup: (see [the specification class](https://bitbucket.org/mbjarland/spock-mocking-issue/src/c31661de54ab7db9d206fde1ce397b98f7303caa/src/test/groovy/org/bobba/FailingSpockMockingSpecification.groovy?at=master&fileviewer=file-view-default) for details)
- We have a ServiceSubClass with a method 'method(HttpRequest p)'
- ServiceSubClass has a base class ServiceBaseClass which also has method 'method(HttpRequest p)'.  
- The _parameter class_ HttpRequest inherits from class HttpRequestBase
- HttpRequestBase implements interface HttpRequestInterface (we made this all up to make 
  things easier to grok, the class/interface names are arbitrary)
- ServiceBaseClass also implements an overloaded method 'method(HttpRequestInterface p)'

given this setup and the following code: 

``` groovy
def "Mocking should work with sub class service call"() {
  setup: 
    HttpRequest p = Mock()
    def service = new ServiceSubClass()

  when: 
    def answer = service.method(p)

  then: "expect the sub class service method to be called, not base class"
    answer.tokenize("|").first().trim() == "sub class method(HttpRequest p)"
}
```

we would expect the service sub class method to be called as the method is overloaded in three places: 
- ServiceBaseClass.method(HttpRequestInterface p) // should not be called 
- ServiceBaseClass.method(HttpRequest p) // shadowed by sub class override
- ServiceSubClass.method(HttpRequest p)  // should be called 

but instead the base class interface method is called, i.e. the above test results in: 

```
-- Mocking should work with sub class service call
Condition not satisfied:

answer.tokenize("|").first().trim() == "sub class method(HttpRequest p)"
|      |             |       |      |
|      |             |       |      false
|      |             |       |      13 differences (68% similarity)
|      |             |       |      (ba)s(e-) class method(HttpRequest(Interface) p)
|      |             |       |      (--)s(ub) class method(HttpRequest(---------) p)
|      |             |       base class method(HttpRequestInterface p)
|      |             base class method(HttpRequestInterface p) 
|      [base class method(HttpRequestInterface p) ,  called with Mock for type 'HttpRequest' named 'p' -> null]
base class method(HttpRequestInterface p) | called with Mock for type 'HttpRequest' named 'p' -> null

  at org.bobba.FailingSpockMockingSpecification.Mocking should work with sub class service call(FailingSpockMockingSpecification.groovy:15)
```

**Comment by siordache** [comment]
I don't see this as a Spock bug. This is the standard behavior of Groovy when the type of the argument passed to the method does not exactly matches the type in the method signature.
You can check this behavior by inserting the following code in your FailingSpockMockingSpecification class:
```
static void main(String[] args) {
	def service = new ServiceSubClass()

	HttpRequest p1 = new HttpRequest()
	println service.method(p1).split('\\|')[0]

	HttpRequest p2 = new HttpRequest() {}
	println service.method(p2).split('\\|')[0]
}
```
Running the main method above will produce the following output:
```
sub class method(HttpRequest p) 
base class method(HttpRequestInterface p) 
```
The call of the base class method is due to the fact that p2 is a type derived from HttpRequest. The same is true for the mock object p in your test. There is no way of having a mock for which getClass() returns HttpRequest.

**Comment by mbjarland** [comment]
Thank you for the pointer and clarification. We can disqualify this issue and attribute it to groovy. 

In our specific scenario this behavior led to some very unexpected and hard to grok issues...makes you wish there was some way of making the mock behave like the mocked class in this scenario. 

I have to say that the following still throws me off a bit: 

```groovy
def service = new ServiceSubClass()

HttpRequest p1 = new HttpRequest()
println service.method(p1) // 1. sub

HttpRequest p2 = new HttpRequest() {} //subclass of HttpRequest
println service.method(p2) // 2. base 
println service.method(p2 as HttpRequest) // 3. sub 

HttpRequest p3 = p2 as HttpRequest
println service.method(p3) // 4. base
```
when comparing 2, 3, and 4 it seems that the "as HttpRequest" (and java type cast seems equivalent) within the method call parens has a special place. In other words, if we pull out the "p2 as HttpRequest"  from the method call into a variable, behavior changes. To me this seems to break [referential transparency](https://en.wikipedia.org/wiki/Referential_transparency), but perhaps that is just how it is. 

Don't know if this comes all the way from java and/or if I'm just missing something, but this behavior didn't entirely align with my expectations. Feel free to enlighten me if you feel inclined. 

In either case, we can drop this issue. Perhaps it would be nice to add a note about behavior like this in the mocking documentation somewhere.

**Comment by siordache** [comment]
Until today, I wasn't actually aware of the way groovy chooses the method to call. I just discovered how it works while trying to understand why your test fails (so, thanks for posting your question).
You may also have a look at the source code of groovy to better understand what happens. 
Some of the interesting methods involved in deciding which method to call are: chooseMethod() and chooseMostSpecificParams() from groovy.lang.MetaClassImpl; and calculateParameterDistance() from org.codehaus.groovy.runtime.MetaClassHelper.
