### ISSUE TITLE
HamcrestSupport.expect() does not work unless at the top level of the block

### ISSUE THREAD

**Issue by ddimtirov** [spockframework/spock#573]
I am statically importing `expect` and `closeTo`:

The following code works:

```
when:
def f = createFunction()

then: 
expect f(1), closeTo(3, EPSILON)
```

The following throws: InvalidSpecException: that() can only be used where a condition is expected

```
when:
def f = createFunction()

then: 
for (i in 1..1000) {
   expect f(i), closeTo(i+2, EPSILON)
}
```

And then the following works:

```
when:
def f = createFunction()

then: 
for (i in 1..1000) {
   assert expect(f(i), closeTo(i+2, EPSILON))
}
```

Ideally I'd like not to need that assert and the parens for the `expect` call.

**Comment by leonard84** [comment]
The handling of special methods is bound to certain environments and requires the usage of `assert` if used outside those, this won't be changed.
