### ISSUE TITLE
Allow to create a mock implementing multiple interfaces (and optionally a single class)

### ISSUE THREAD

**Issue by ddimtirov** [spockframework/spock#576]
See also http://blog.freeside.co/2014/08/11/multiple-interface-mocks-with-spock/

EDIT: Half a year later I need the same thing and lo and behold - I've filed an issue already :-)

**Comment by renatoathaydes** [comment]
Hey, just thought I would give a hint here how to achieve this just with Groovy:

Just cast the mock to the interface you want to add, you can do it several times:

```groovy
when:
def c1 = (Mock( Node ) as SelectionHandler.SelectableNode) as Runnable

then:
c1 instanceof  SelectionHandler.SelectableNode
c1 instanceof Runnable
```

I did this as I needed something sub-classing a JavaFX `Node` but also a couple of interfaces...

Hope that helps.

**Comment by leonard84** [comment]
Native support was added to master (6ca84d59da57a0186910daf88fce7d5e1cbb2dfa) and will be in 1.2

**Comment by renatoathaydes** [comment]
Ah, good to know because my solution indeed makes the node an instance of all interfaces, but messes up the original cglib class for `Node` so in Java, the node can't be passed to parameters taking `Node`!
