### ISSUE TITLE
Assert behaviour into switch sentence (then block)

### ISSUE THREAD

**Issue by migupl** [spockframework/spock#577]
Hi,

during a test of objects inside a switch sentence I found what I think is a strange behaviour of  an assert

I replicate the case with this simple example

def "A simple example"() {
  when: "Number exists"
    def number = 6

  then:
    switch(number) {
      case Number:
        // Must fail but it does not
        0 == number

```
    // This fails
    assert 0 == number

    break
}
```

}

Sorry about my english. I would appreciate if you can confirm if I am doing something wrong or it is a known issue.

Thanks in advance

**Comment by leonard84** [comment]
It's not a bug, only top-level statements are transformed into assertions, otherwise you need to explicitly tell spock with `assert`.
