### ISSUE TITLE
Spock Mock unexpectedly wrapping List in Array

### ISSUE THREAD

**Issue by dlehammer** [spockframework/spock#603]
Grails service

```
class CallerService {

    ListService listService

    def serviceMethod(Long number) {
        listService.serviceMethod([number])
    }
}
```

Spock test

```
@TestFor(CallerService)
@TestMixin(GrailsUnitTestMixin)
class CallerServiceSpec extends Specification {

    ListService listService

    void setup() {
        listService = Mock(ListService)

        service.listService = listService
    }

    void "test list of numbers argument"() {
        given:
            Long number = 1L

        when:
            service.serviceMethod(number)

        then:
            1 * listService.serviceMethod(_ as List) >> { List numbers ->
                assert numbers == [number] // assertion is expected to be true - but fails

                return null
            }
            0 * _._ // no (more) method call on any mock
    }
}
```

Test result, notice how the List argument from CallerService to the ListService Mock is wrapped in an array.

```
Failure:  |
test list of numbers argument(spock.list.issue.CallerServiceSpec)
 |
Condition not satisfied:
numbers == [number]
|       |   |
[[1]]   |   1
        false
	at spock.list.issue.CallerServiceSpec.test list of numbers argument_closure1(CallerServiceSpec.groovy:29)
```

Symptom is present in spock-core v1.0-groovy-2.3 (and v0.7-groovy-2.0 - the default included with Grails v2.4.4)

I'll upload a project to github exhibiting the symptom, as soon as this issue has been created, so I can reference this issue.

**Comment by dlehammer** [comment]
I've shared a project illustrating the symptom:

https://github.com/dlehammer/spockframework-issue-603 

Below, screenshot of GGTS debugger - illustrating the unexpected state.

![Image of unexpected state in debugger](https://raw.githubusercontent.com/dlehammer/spockframework-issue-603/master/spockframework-issue-603_debug_screenshot_20160603.png)

**Comment by szpak** [comment]
Thanks for the report :). Spock by default passed an array of input elements to the closure, so in your case `it[0]` would return your list. Alternatively the named parameters can be used, like in your case, however in the mentioned situation it is not a clear for Spock if you would like to get a list of input parameters with the first argument (your list) as the first element (what is happening now) or rather just the first argument (the list). It can be confusing that or the other way and I'm not sure this behavior should be changed.

Anyway, in the meantime, feel free to make a PR to the [documentation](https://github.com/spockframework/spock/blob/master/docs/interaction_based_testing.adoc#computing-return-values) to cover that corner case.

**Comment by leonard84** [comment]
Not an actual issue, we accept documentation improvements as szapck said ;)
