### ISSUE TITLE
Switch mock creation syntax in documentation to enhancement in 1.1

### ISSUE THREAD

**Issue by szpak** [spockframework/spock#608]
#560 introduced warningless mock creation syntax with type defined only on the left side of an assignment.

```
Foo foo = Mock()
```

It is more meaningful (especially for Java developers using Spock) that previously used in docs:

```
def foo = Mock(Foo)
```

It would be probably good to rework documentation to use the "new" syntax when Spock 1.1 is released.

**Comment by enriquezrene** [comment]
+1

**Comment by leonard84** [comment]
@szpak do you want to create a PR?

**Comment by szpak** [comment]
Done in https://github.com/spockframework/spock/pull/798.
