### ISSUE TITLE
Evaluate @IgnoreIf condition for @Shared value

### ISSUE THREAD

**Issue by yeugenius** [spockframework/spock#628]
# Issue description

Spock supports conditional skipping using **@IgnoreIf** and **@Requires** annotations, but this functionality is very limited, as predicates are evaluated before Spec is loaded and started.

If would be very useful to add possibility to use flexible ignore tests functionality based on data from setupSpec() and setup() methods.

So the Spec can decide which tests to skip based on input data. Test only what is testable and skip everything else.

It is useful for testing documents structure and data flow when fields, block and attributes are not mandatory and documents in data flow could have them in numerous combinations.

How to reproduce:

```
@Shared condition = true

//OR

@Shared condition
def setupSpec(){
        condition=true
}


@IgnoreIf({condition})
def test01(){
expect:
1==1
}
```

```
Internal Error occured.
org.spockframework.runtime.extension.ExtensionException: Failed to evaluate @IgnoreIf condition
    at org.spockframework.runtime.extension.builtin.IgnoreIfExtension.evaluateCondition(IgnoreIfExtension.java:63)
    at org.spockframework.runtime.extension.builtin.IgnoreIfExtension.doVisit(IgnoreIfExtension.java:44)
    at org.spockframework.runtime.extension.builtin.IgnoreIfExtension.visitFeatureAnnotation(IgnoreIfExtension.java:39)
    at org.spockframework.runtime.extension.builtin.IgnoreIfExtension.visitFeatureAnnotation(IgnoreIfExtension.java:31)
    at org.spockframework.runtime.ExtensionRunner.doRunAnnotationDrivenExtensions(ExtensionRunner.java:95)
    at org.spockframework.runtime.ExtensionRunner.runAnnotationDrivenExtensions(ExtensionRunner.java:74)
    at org.spockframework.runtime.ExtensionRunner.runAnnotationDrivenExtensions(ExtensionRunner.java:51)
    at org.spockframework.runtime.ExtensionRunner.run(ExtensionRunner.java:41)
    at org.spockframework.runtime.Sputnik.runExtensionsIfNecessary(Sputnik.java:88)
    at org.spockframework.runtime.Sputnik.getDescription(Sputnik.java:55) 
    ...
Caused by: groovy.lang.MissingPropertyException: No such property: condition for class: org.spockframework.runtime.extension.builtin.PreconditionContext
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
    at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:52)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
    ...
```

**Comment by orbfish** [comment]
I was just trying to do myself - seconded! Although I'm happy to use a declared constant, don't need a setupSpec()

**Comment by stanlef** [comment]
Will this feature request be implemented.  I have a situation where I would like to ignore a test based on the product's configuration.  Currently I believe using static methods and system properties will work, but I am trying to figure out how to make it work in Intellij.

**Comment by leonard84** [comment]
You can easily use a static field instead of `@Shared`, just use the qualified name of it, i.e., `@IgnoreIf({MyClass.shouldExecute}}` see https://stackoverflow.com/questions/45368111/how-to-use-ignoreif-in-spock-when-i-check-the-variable or https://stackoverflow.com/questions/44013252/how-to-evaluate-spock-ignoreif-using-a-method which also is supported by the IDE.

**Comment by orbfish** [comment]
That did not work when I tried it. I'll try again ;)

**Comment by orbfish** [comment]
Oh, I see what you mean! static keyword instead of @Shared (which I assumed
translated to static under the hood).

Thank you,
Michael

**Comment by leonard84** [comment]
@orbfish no `@Shared` is not an alias for `static`, it has some commonalities such as that it is shared across test instances and from a test pov it can/should be used instead of static in most cases, however it is not the same.

**Comment by yeugenius** [comment]
The idea of the issue is different from choice of @Shared or static field. Once you declare static of shared value,  it is not possible to change it in setupSpec() or setup() methods and control test flow, which is desired behaviour. Maybe it is better to write separate feature request, as soon it is not an issue?

Here test1 is not skipped.

`class MySpec extends Specification {

    static Boolean skipCondition = false

    def setupSpec(){
        skipCondition = true
    }

    @IgnoreIf({MySpec.skipCondition})
    def test1(){
        expect:
        true
    }
}
`

**Comment by leonard84** [comment]
The intentions of the annotations are to run before any work is performed on the features, e.g., don't start the spring context if you can't use it anyway. You can use JUnits assumptions if you want to skip tests which have already started (eg. run some setup methods) `org.junit.Assume.assumeFalse(skipCondition)`,  here you can use `@Shared` again.

```java
import static org.junit.Assume.assumeFalse

class MySpec extends Specification {

    @Shared 
    boolean skipCondition = false

    def setupSpec(){
        skipCondition = true
    }

    def test1(){
        given:
        assumeFalse(skipCondition)
        expect:
        true
    }
}
```

**Comment by bagira-it** [comment]
@leonard84 Thanks a lot for all the hints! 
JUnit assumption was what I needed.

**Comment by yeugenius** [comment]
@leonard84 @bagira-it  It is definitely possible ti use JUnit's assumptions, but there is small side issue with that. Assumptions are not treated correctly.
https://github.com/renatoathaydes/spock-reports/issues/89

**Comment by sachingoyal0510** [comment]
We can change the value of skipCondition like this.

```
class MySpec extends Specification {
    static final Boolean skipCondition
    static {
    //some computation
   if ("condition")
       skipCondition = true
   else
       skipCondition = false
    }

    @IgnoreIf({MySpec.skipCondition})
    def test1(){
        expect:
        true
    }
}
```

**Comment by leonard84** [comment]
#1359 adds support for accessing shared values via `shared.`
