### ISSUE TITLE
Exceptions thrown from blocks that assert statements (then, expect) result in a PowerAssertionError and the original exception is swallowed

### ISSUE THREAD

**Issue by erdi** [spockframework/spock#636]
This is a change between 1.0 and 1.1-rc-1. You can observe it by cloning https://github.com/erdi/spock-exception-in-assertion, running `./gradlew test —continue` and then having a look at both test reports.

I can see that there might be benefits of reporting where exactly in the asserted statement the exception has happened but this is a breaking change, at least in my opinion, and should not be part of a minor release.

**Comment by robfletcher** [comment]
I'm not sure there's a way to preserve both behaviors. Either we include the exception information in the power assert _or_ we throw the original exception type. FWIW I lean toward the latter.

**Comment by leonard84** [comment]
Relates to #49

**Comment by leonard84** [comment]
@erdi can this be closed with now that #639 is merged?

**Comment by erdi** [comment]
Closed as you can now easily distinguish between not satisfied conditions and ones that failed with an exception thanks to `ConditionFailedWithExceptionError`
