### ISSUE TITLE
Suggestion : Transrated Korean spockframework document

### ISSUE THREAD

**Issue by bluepoet** [spockframework/spock#640]
@pniederw 

The reason I write this article, I want spock framework document to translate into Korean.

Because I want to share this translated document with other Korea programmers.

I would like to inform spock spread widely.

Before that I would like to ask you to accept this suggest.

I will wait for your reply.

**Comment by sbglasius** [comment]
Hi @bluepoet 
Thank you for proposing this. 

While we think, that a translation is a nobel offering, we feel that there are great risks that it will get out of sync with the English documentation.

The better way to contribute would be, that you write blog entries in your native language, describing the bits and pieces of Spock.

The official spockframework site (hopefully soon to be updated) could then link directly to the blog and that way give insights into Spock in your native language.

On behalf of the Spock committers,
/Søren

**Comment by bluepoet** [comment]
@sbglasius  

Thank you for your answer.

I understood you to say. 

I will translate the content of the following table of contents in my native language.

```
2.Getting Started
3.Spock Primer
4.Data Driven Testing
5.Interaction Based Testing
6.Extensions
```

And when spockframework document is updated , it will try to match the sink.

spock-example project source code run and I will briefly introduce.

The goal is to try to Spread the spock to other programmers.

@leonard84
