### ISSUE TITLE
@Mock annotation similar to EasyMock 

### ISSUE THREAD

**Issue by JakubDziworski** [spockframework/spock#643]
In easymock it is possible to annotate mocks with ```@Mock```. In combination with ```@TestSubject```.
the frameowrk automatically sets the fields on subject of matching type.

This would turn:

```groovy
    @Subject
    Subject subject = new Subject()

    SomeMock someMock

    def setup() {
        someMock = Mock()
        subject.someMock = someMock
    }
```

into this:

```groovy

    @Subject
    Subject subject = new Subject()
    
    @Mock
    SomeMock someMock
```

**Comment by szpak** [comment]
If I understood your intention correctly [spock-subjects-collaborators-extension](https://github.com/marcingrzejszczak/spock-subjects-collaborators-extension) could be useful for you.

**Comment by JakubDziworski** [comment]
Exactly. Thanks!
