### ISSUE TITLE
Spock-Spring: Problem when mocking StepScope beans since 1.1-groovy-2.4-rc2

### ISSUE THREAD

**Issue by sivaprakash-sel** [spockframework/spock#644]
# Issue description

I am using spring batch framework with beans defined in "StepScope". As part of writing test case, I had to mock one of the steps (i.e. bean with StepScope) in the job. I did that and it was working fine so far. Today, I tried using spock-spring (1.1-groovy-2.4-rc-2) and I am getting below error. Looking at the code of (spock-spring rc2), spring mock test execution listener is trying to get the bean from application context, which throws this error as step-scoped beans can only be instantiated during job execution. 

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.seederEntityReader': Scope 'step' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No context holder available for step scope
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:355)
    ......
    at org.spockframework.spring.SpringMockTestExecutionListener.beforeTestMethod(SpringMockTestExecutionListener.java:49)
    ....
Caused by: java.lang.IllegalStateException: No context holder available for step scope
    at org.springframework.batch.core.scope.StepScope.getContext(StepScope.java:167)
    at org.springframework.batch.core.scope.StepScope.get(StepScope.java:99)
    ....
# How to reproduce
- Create a spring boot project with spring-batch feature. Configure a job with at least one of the steps in the batch job to be at StepScope. Have that overridable (i.e Annotate with ConditionalOnMissingBean("myStepScopedBean")).
- Write a test case to launch that job. As part of that, in test spring java configuration class, override bean / step defined in StepScope. Of course it should be at StepScope even in test configuration class.
- While launching that job from the spock test spec, above error should be observed.
## Link to a gist or similar (optional)
# Additional Environment information

JDK 1.8
Spock-Spring 1.1-groovy-2.4-rc-2
## Java/JDK

`java -version`
java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)
## Groovy version

> **Note that versions older than 2.0 are no longer supported.**

`groovy -version`
2.4
### Gradle

`gradle -version`
### Apache Maven

`mvn -version`
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T22:11:47+05:30)
Maven home: C:\hbo-dev\apps\apache-maven-3.3.9
Java version: 1.8.0_71, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_71\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
## Operating System

Windows
## IDE

IntelliJ
### Apache Maven

```
<dependency>
  <groupId>org.spockframework</groupId>
  <artifactId>spock-core</artifactId>
  <version>1.1-groovy-2.4-rc-2</version>
</dependency>
```

**Comment by slnowak** [comment]
Any updates? Just encountered this issue.

**Comment by leonard84** [comment]
Close in favor of #655 since it has the same cause but the other thread is more active
