### ISSUE TITLE
Documentation link has problem in opening

### ISSUE THREAD

**Issue by rohinivasu** [spockframework/spock#649]
the documentation link is not opening. there is a problem loading that page. Can someone help on this.
Link for docs :
http://docs.spockframework.org/

**Comment by szpak** [comment]
Hmm, is the problem still valid?

The mentioned link redirects me to http://spockframework.org/spock/docs/1.1-rc-2/index.html

**Comment by rohinivasu** [comment]
Yes it is. Its not redirecting for me neither for my team

**Comment by szpak** [comment]
We cannot reproduce the issue. Could you check that from other location (e.g. from home) it also doesn't work for you?

**Comment by robfletcher** [comment]
If possible can you attach the output of these commands:

    curl -I http://docs.spockframework.org/
    curl -I http://spockframework.github.io/spock/docs
