### ISSUE TITLE
Reference documentation - all on one page option

### ISSUE THREAD

**Issue by shendrix** [spockframework/spock#65]
It would be nice if the reference documentation page had an option to view the whole thing on one page, so it's easy to search through without clicking through different sections.

Example of why this is needed:
http://stackoverflow.com/questions/21194523/can-spock-mock-a-java-constructor
The accepted answer links to 'Mocking Constructors' in the Spock documentation, but this now returns a 404.  I have to manually then go to the new reference and click and scan through each section before I find the associated doc.

**Comment by jirutka** [comment]
+1

**Comment by leonard84** [comment]
This was implemented in PR #68.
