### ISSUE TITLE
Spock-Spring regression bug: Initialization Error on version 1.1-groovy-2.4-rc-2 with Spring 3.x

### ISSUE THREAD

**Issue by ilsasdo** [spockframework/spock#654]
# Issue description

With spock-1.0-groovy-2.4 it works, with spock-1.1-groovy-2.4-rc-2 don't.
The error is when spock-spring checks for a spring-boot specification.
# How to reproduce

Make a test with spring-spock-1.1-groovy-2.4-rc-2 and Spring with version 3.x
## Link to a sample project

https://github.com/ilsasdo/SpockSpringBug
look at the `gradle.build` file
`./gradlew test`
# Additional Environment information

groovy-2.4
spring-3.x
spock-1.1-groovy-2.4-rc-2
spock-spring-1.1-groovy-2.4-rc-2

**Comment by leonard84** [comment]
Close in favor of #654 since it has the same cause but the other thread is more active
