### ISSUE TITLE
Error from toString() destroys failure context display

### ISSUE THREAD

**Issue by Vampire** [spockframework/spock#658]
Given the attached project [test.zip](https://github.com/spockframework/spock/files/515942/test.zip), you can see that executing `test1` and `test3` will just display the AssertionError, while executing `test2` will show the failure context display. The only difference is that the `toString()` method throws an `Error` or not. `RuntimeExceptions` work fine though.

**Comment by Vampire** [comment]
Hm, GitHub won't let me upload a ZIP anymore. :-(

**Comment by Vampire** [comment]
Ok, here you have it via Drive for now: https://drive.google.com/file/d/0B5p_hdEuEv5UWmJyWVZvblE3cTA/view?usp=sharing

**Comment by leonard84** [comment]
Errors should not be catched, generally if an `Error` is thrown something is really wrong and should not be ignored.
