### ISSUE TITLE
Make it possible to pass map constructor args to Spy

### ISSUE THREAD

**Issue by snimavat** [spockframework/spock#662]
When using grails, some time we want to mock some specific methods on a service. We can use the spock Spy for that. However the service has dependency on other services. The service created using the Spy will have those member fields null, resulting in NPE. Spy allows list of constructor args. however that forces us to write a constructor. Groovy objects comes up with a map constructor. Why cant Spy allow a map constructor -- 

`
some thing like -- XService service = Spy(Service, constructorArgs:[YService: yservice, xx:xx])
`

**Comment by szpak** [comment]
I didn't tested it, but have you tried to pass a map as the first list element?

```
= Spy(Service, constructorArgs: [[yService: yServiceRef, zService, zServiceRef]])
```

**Comment by snimavat** [comment]
Seems to work, but it would be great if i can accept the map directly.

**Comment by snimavat** [comment]
Cant we support a direct map constructor args instead of needing a map within a list ?
This is less confusing, and consistent with standard groovy
