### ISSUE TITLE
Default method setupSpec in interface not working

### ISSUE THREAD

**Issue by guenhter** [spockframework/spock#665]
# Issue description

Java 8 default methods are not considered in specs (`setupSpec`).
# How to reproduce

Make a java 8 interface with a default method called `setupSpec`.
Implement this Interface in a groovy-spec and execute it: The `setupSpec`-Method is not called.

It doesn't matter if the method in the interface is
`static void setupSpec() {`
or 
`default void setupSpec() {`
## Java/JDK

java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
## Groovy version

2.4.7:indy
### Gradle

---
## Operating System

Mac OS X
## IDE

IntelliJ 2016.2.4

**Comment by leonard84** [comment]
All the special methods (e.g. `setupSpec`, `setup`) must be in a subclass of `Specification` so that AST transforms can find and handle them.
