### ISSUE TITLE
Suggestion for new annotation @Only()

### ISSUE THREAD

**Issue by snimavat** [spockframework/spock#681]
Right now we have annotation to Ignore entire spec, or specific tests cases from within a spec using Ignore annotation

It would be great if spock can provide @Only annotation, which indicates that just this test case should be executed from given spec class.

Javascript test frameworks like mocha etc has this option.

**Comment by szpak** [comment]
Please take a look at [`@IgnoreRest`](https://github.com/spockframework/spock/blob/fab978b2461b6eb89d1abd9dd2e14938d1ee35c5/spock-core/src/main/java/spock/lang/IgnoreRest.java) annotation/extension.

**Comment by snimavat** [comment]
@szpak thats exactly what i was looking for... thanks
