### ISSUE TITLE
have serializable mocks

### ISSUE THREAD

**Issue by jay-peper** [spockframework/spock#683]
# Issue description

We are testing a framework that needs all injected objects to be serialisable (Google cloud sdk), so currently we cannot use spock mocks and have to create stub classes ourselves. Would it be possible to create mocks that can implement Serializable?

**Comment by leonard84** [comment]
Spock currently doesn't support to add additional interfaces to mocks, furthermore it would not work if they where actually serialized/deserialzed, since they would not be attached to the specification anymore.

**Comment by leonard84** [comment]
@jasontrublu with #752 spock supports the addition of interfaces for mocks. You can try the 1.2-SNAPSHOT. However, really serializing and deserializing a mock wont work.

**Comment by AndreasTu** [comment]
#1753 will fix this issue. The `mockito-inline` mock maker supports mocks which are serializable.
See [mockito documentation](https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/MockSettings.html#serializable()).
