### ISSUE TITLE
How to return values for multiple calls that depend on arguments?

### ISSUE THREAD

**Issue by asarkar** [spockframework/spock#693]
1. `subscriber.receive(_) >> "ok"` is for one call.
2. `subscriber.receive(_) >>> ["ok", "error", "error", "ok"]` is for multiple calls. 
3. `subscriber.receive(_) >> { args -> args[0].size() > 3 ? "ok" : "fail" }` is for computing return value.

How to combine 2 and 3? The following doesn't work.

```
class MyFirstSpec extends Specification {
  RemoteClient client

  def setup() {
    client = Mock(RemoteClient)
    client.call(_) >>> [{args -> args[0]}] >> {args -> 1}
  }
  def "let's try this!"() {
    when:
    def result1 = client.call(1)
    def result2 = client.call(15)
    then:
    result1 == 1
    result2 == 1
  }
}
```

**Comment by asarkar** [comment]
OK, I found by trial-and-error that the following works. Please document this as the triple-shift with array syntax doesn't work here, neither does `>>>` followed by `>>`:

`client.call(_) >> {args -> throw new RuntimeException ("${args[0]}")} >> {args -> 1}`

**Comment by leonard84** [comment]
@asarkar please look at `org.spockframework.smoke.mock.ChainedResponseGenerators` in spock-specs and tell me what not works, and if you look at the interaction based testing chapter for more documentation.
