### ISSUE TITLE
Documentation for 1.1-rc-2 and 1.1-rc-3 has error re. how mock objects are created

### ISSUE THREAD

**Issue by BillyRayPreachersSon** [spockframework/spock#696]
The first paragraph of the ["Creating Mock Objects" section for the 1.1-rc-3 docs](http://spockframework.org/spock/docs/1.1-rc-3/interaction_based_testing.html#_creating_mock_objects) reads:

`Mock objects are created with the 0 method.`

It also seems to affect the docs for 1.1-rc-2, but not those for 1.1-rc-1, where it reads:

`Mock objects are created with the MockingApi.Mock() method.`

**Comment by szpak** [comment]
Thanks @BillyRayPreachersSon. It seems to be an issue with AsciiDoc. In the code there is:
> Mock objects are created with the +MockingApi.Mock()+ method.footnote
