### ISSUE TITLE
IntelliJ gradle import fails

### ISSUE THREAD

**Issue by leonard84** [spockframework/spock#70]
Everytime I want to refresh the spock project in IntelliJ I get this error:
```
Error:Can't register given path of type 'SOURCE' because it's out of content root.
Content root: 'C:/Dev/github/spock/buildSrc'
Given path: 'C:\Dev\github\spock\spock-gradle\src\main\groovy'
```
Running `gradlew idea` and opening the generated project files didn't help either.

* Windows 7 x64
* IntelliJ 14.1 and 14

**Comment by guspower** [comment]
Replicated on `Linux 3.18.7` `idea-IU-141.177.4` `JDK 1.8.0_40-b25`

**Comment by guspower** [comment]
To be more specific, the 'Gradle projects' window is empty and the 'Gradle sync' message window says `Gradle 'spock' project refresh failed` with a similar `Can't register given path of type 'SOURCE'` message 

This is after configuring Intellij using `./gradlew -Dvariant=2.4 idea` and enabling gradle integration. Given that the project builds correctly from the command line using `./gradlew -Dvariant=2.4 assemble` I'm assuming this is a problem with the Intellij gradle plugin. Would anyone else care to comment?

**Comment by guspower** [comment]
After some more research I have learned that Intellij's pop-up `Import Gradle Project` does more than just populate the Gradle task view but rather queries the Gradle tooling API and updates the project settings accordingly. 

Since the Spock build is parametrized (e.g. `-Dvariant=2.0|2.3|2.4`) and the Intellij Gradle integration is not, the current approach is to use Gradle to generate the Intellij project files (`spock-2.4.ipr` etc.) rather than having Intellij query Gradle (i.e. gradle -> intellij not intellij -> gradle). 

The process for Intellij integration is then: 
* `./gradlew cleanIdea idea -Dvariant=2.x`, followed by 
* `File -> Open` in Intellij, then 
* select the appropriate `spock-2.x.ipr`. 

I will update the CONTRIBUTING.md to reflect this.

**Comment by guspower** [comment]
@leonard84 do you think this change is sufficient to mark this issue as closed?

**Comment by leonard84** [comment]
@guspower I think this is a workaround, and it would be better if the gradle import workflow from intellij would work.

If I comment out those two line in the buildSrc
```
sourceSets.main.groovy.srcDirs = ["../spock-gradle/src/main/groovy"]
sourceSets.main.resources.srcDirs = ["../spock-gradle/src/main/resources"]
```
the import works fine. 

The question is if the error is IntelliJ's fault or if it is a limitation of the gradle tooling api. If it is the latter then I would think about moving the code from spock-gradle back to buildSrc, since it wouldn't be really supported by gradle.

If you want we can close this issue and I can create another as feature req to support direct gradle import in IntelliJ, or we keep this one open.

**Comment by johnrengelman** [comment]
It is IntelliJ's fault. They prohibit you from setting a src directory for module outside of that module's path which is what is happening here. It is configured this way so that the Gradle plugin that this project creates can be used on itself.

**Comment by johnrengelman** [comment]
You should go vote for this ticket: https://youtrack.jetbrains.com/issue/IDEA-122577 so that they allow this type of behavior.

**Comment by johnrengelman** [comment]
Alternatively, you can tell Gradle not to perform this type of mapping when being imported into IntelliJ - https://gist.github.com/johnrengelman/9a20697b2246a9bfaca2#file-build-gradle-L13-L23 
The downside is that you will get some errors in the IntelliJ console for any Gradle build files where you are trying to import classes from that project.

**Comment by leonard84** [comment]
Closing this Issue, the benefit of using .ipr based project is that you can have all three combinations in the same directory. But maybe we should add this information more prominently on the README.md and not hide it in the CONTRIBUTING.md
