### ISSUE TITLE
Verification causes mock to behave in an unexpected way

### ISSUE THREAD

**Issue by behrangsa** [spockframework/spock#702]
# Adding a mock verification interaction statement changes the mock's behavior

Without mock interaction verification, this test is passing:

```java
    def "it should mock get"() {
        given:
        def httpClient = Mock(HttpClient)

        and:
        httpClient.get({ it.contains("/book") }) >> null
        httpClient.get({ it.contains("/text-book") }) >> "text-book"

        when:
        def result1 = httpClient.get("/book")
        def result2 = httpClient.get("/text-book")

        then:
        result1 == null
        result2 == "text-book"
    }
```

However adding a verification statement to the end of the test, causes `result2` to become `null`, rather than the expect value of `"text-book'`:

```
        and:
        2 * httpClient.get(_)
```

# How to reproduce

* Clone https://github.com/behrangsa/why-spock
* Run the `org.behrang.why.spock.RestServiceTest#it should mock get"` test (passes)
* Run the `org.behrang.why.spock.RestServiceTest#it should mock and verify get"` test (fails but should pass)

**Comment by behrangsa** [comment]
Even re-arranging the blocks and using `setup` and `interaction` the test still fails:

```java
    def "it should mock and verify get"() {
        setup:
        def httpClient = Mock(HttpClient) {
            get({ it.contains("/book") }) >> null
            get({ it.contains("/text-book") }) >> "text-book"
        }

        when:
        def result1 = httpClient.get("/book")
        def result2 = httpClient.get("/text-book")

        then:
        interaction {
            2 * httpClient.get(_)
        }

        and:
        result1 == null
        result2 == "text-book"
    }
```

**Comment by leonard84** [comment]
You are mixing stubbing with mocking, what happens is that your stubs which you set up earlier are overwritten by your mocking `2 * httpClient.get(_)` is basically `2 * httpClient.get(_) >> null`. Since mocking has always a higher priority than stubbing.

If you write it in the idomatic spock way then it works.
```groovy
def "it should mock and verify get"() {
        given:
        def httpClient = Mock(HttpClient)

        when:
        def result1 = httpClient.get("/book")
        def result2 = httpClient.get("/text-book")

        then:
        result1 == null
        result2 == "text-book"

        and:
        1 * httpClient.get({ it.contains("/book") }) >> null
        1 * httpClient.get({ it.contains("/text-book") }) >> "text-book"
    }
```

See also [Combining Mocking and Stubbing](http://spockframework.org/spock/docs/1.1-rc-3/all_in_one.html#_combining_mocking_and_stubbing) in the docs
