### ISSUE TITLE
Spring Boot 1.4 jay layout change caused Spock tests cannot find classes

### ISSUE THREAD

**Issue by LeeU1911** [spockframework/spock#719]
Hi all,

Wondering if anyone run into the same issue. Our project has below structure:
```
parent
  |_spock-tests
  |_core-module
```
## Issue 
`spock-tests` can't find classes of core-module.

## Description
`spock-tests` consists a set of groovy specs which uses spock to do unit test and integration test of core-module functionalities. Hence, module spock-tests has a dependency on core-module jar file.

`core-module` is a Spring Boot app.

`mvn clean install` runs spock tests quite well until we upgraded `core-module` to use Spring Boot 1.5. We found out that in Spring Boot 1.4, the fat jar layout was changed to use conventional delegation model in LaunchedURLClassLoader as described [here](https://github.com/spring-projects/spring-boot/commit/87fe0b2adeef85c842c009bfeebac1c84af8a5d7).

This caused the jar file created of `core-modul`e has a different folder structure than it once was. The classes are moved to under `BOOT-INF` folder instead of being at the root of the jar file as before. We think this makes spock tests somehow doesn't 'see' those classes, therefore, throws the errors.

If you have any idea how to fix this, please help.

Thanks.

**Comment by leonard84** [comment]
Please fill out all the information about your build system that is requested in the new issue template and provide a [SSCCE](http://sscce.org/) if possible. It looks like a problem with your build system maven/gradle and has probably nothing to do with spock itself.

**Comment by LeeU1911** [comment]
Thank you.
I think you're right. As I can run spock test successfully from the IDE. I'm gonna ask this question in gmavenplus github and close this issue then.
