### ISSUE TITLE
Publish a version of spock with no dependency on groovy-all

### ISSUE THREAD

**Issue by w25r** [spockframework/spock#723]
# Issue description
It is dangerous to depend on groovy-all.  It can cause hidden dependency conflicts both upstream and downstream.  But if I depend on groovy's core jar, then I have to go out of the way to remove Spock's dependency on groovy-all.  I'd like a version of Spock to be published with it's dependency on `org.codehaus.groovy:groovy` rather than `org.codehaus.groovy:groovy-all`.  

Perhaps something like ```org.spockframework:spock-core:1.1-groovy-core-2.4```

# How to reproduce
An example of a build.gradle currently required:  
```groovy
apply plugin: 'groovy'

repositories {
    mavenCentral()
}

dependencies {
    compile 'org.codehaus.groovy:groovy:2.4.10'

    testCompile('org.spockframework:spock-core:1.0-groovy-2.4') {
        exclude module : 'groovy-all'
    }
}
```

**Comment by leonard84** [comment]
Duplicates #71 and #102
