### ISSUE TITLE
Encapsulate test method

### ISSUE THREAD

**Issue by zatziky** [spockframework/spock#724]
Is it possible to encapsulate a test method to reuse it?

I could describe what I want to achieve as 

    // generic test method
    def genericMethod(args){
      given:
         def request = args.request
      when:
         def response = http.post(request)
      then:
         response.data == args.responseData
    }
    
    def specificTest1(){
      genericMethod([request: 1, responseData: 2])
    }
    
    def specificTest2(){
      genericMethod([request: 'A', responseData: 'B'])
    }

Unfortunately, Spock doesn't seem to work this way.

I am aware of `expect:` and `where:` labels but they are not suitable for my case.

Is it possible to simulate what I designated in the code above? 

Originally asked on [StackOverflow](http://stackoverflow.com/questions/43659715/encapsulate-test-method)

**Comment by zatziky** [comment]
I could partially succeed when using `expect:` only.

    // generic test method
    def genericMethod(args){
      def request = args.request
      def response = http.post(request)

      response.data == args.responseData
    }
    
    def specificTest1(){
      expect: 
         genericMethod([request: 1, responseData: 2])
    }
    
The test run but `specificTest1()` tests only whether `genericMethod` is T of F. (Yes, it's obvious. :-) )

**Comment by leonard84** [comment]
You need to explicitly add `assert` before your comparison. Implicit assertions are only applied in special block such as the `then:` block.

So `response.data == args.responseData` would get it to work. 

May I ask why `where` doesn't work for you?

-> Closing this issues since there is nothing for us to do.

**Comment by zatziky** [comment]
Imagine you tests for `car`s and `ship`s. Their requests are very similar. It can be

{
   type: <car|ship>,
   somethingElse: ...
}

Most of the tests are shared. Using `where`s and `expect`s seems logical. But what if you have a team that specializes in car implementations only? They would have to deal with ships too. Furthermore, when a test is encapsulated you can run a test for `car` only. Where else, with `where`s and `expects` you have to run all the tests or comment them out.

Another advantage is when a test is being 'naughty' and you'd like it `@Ignored`. Then what can you do? Comment out the test?

Thus instead of

def 'test aggresivity- #kind`(){
  expect:
       ....

  where:
       kind | arg1| ...
       'car' | ...
       'ship' | ...
}

you would have car tests like

def 'test aggressivity'(){
  expect:
      commonAggressivityTest('car', ...)
}

Have I made my point? @leonard84


**BTW., thx for the advise. :)**
