### ISSUE TITLE
Stubbing java.util.function.Function with different invocations

### ISSUE THREAD

**Issue by tde-desc** [spockframework/spock#727]
# Issue description
I'am unable to stub different invocations of java.util.function.Function. Any idea?

# How to reproduce

## Link to a gist
https://gist.github.com/tde-desc/40d0f59551bd32ade8ff010869d824d5

# Additional Environment information

## Java/JDK
1.8.0_45

## Groovy version
2.4.6
### Apache Maven
3.3.9

## Operating System
Linux Fedora

## IDE
IntelliJ

### Apache Maven
        <dependency>
            <groupId>org.spockframework</groupId>
            <artifactId>spock-core</artifactId>
            <version>1.1-groovy-2.4</version>
            <scope>test</scope>
        </dependency>

**Comment by leonard84** [comment]
This question is better suited to stackoverflow. 

Have a look at http://spockframework.org/spock/docs/1.1/all_in_one.html#_computing_return_values and http://spockframework.org/spock/docs/1.1/all_in_one.html#_argument_constraints you seem to try to mix those two together, by having an argument constraint behave like a return value. Note that the argument constraint must return either `true` or `false` to indicate wether the invocation should match, so just calling `it.getGeneralMessages()` does not do the trick. You'd need to look at  `it` inside the argument constrain and try to figure out which lambda it is. From a quick look at it, I don't see a good way to match lambdas. If you are sure that the methods are always invoked in the same order, you could just use http://spockframework.org/spock/docs/1.1/all_in_one.html#_returning_sequences_of_values

`loginConfig.getConfig(mandantId, _) >>> [generalMessages, fieldMessages]`

**Comment by tde-desc** [comment]
I guess regarding most of my attempts you're having a point. Nevertheless lines 32/33 are defined in a way which seems suitable following http://spockframework.org/spock/docs/1.1/all_in_one.html#_argument_constraints:

```
loginConfig.getConfig(mandantId, _ as Function<MessagesConfig, GeneralMessages>) >> generalMessages // <-- This is working but ...
loginConfig.getConfig(mandantId, _ as Function<MessagesConfig, FieldMessages>) >> fieldMessages // <-- ... this stub is being ignored
```

So far I'm still wondering why the second stub with different argument constraints is not being recognized by spock.

**Comment by leonard84** [comment]
You are running into the java type erasure problem, since generics types are removed spock only sees:

```groovy
loginConfig.getConfig(mandantId, _ as Function) >> generalMessages // <-- This is working but ...
loginConfig.getConfig(mandantId, _ as Function) >> fieldMessages // <-- ... this stub is being ignored
```

There is no difference here, so the first call always wins.
