### ISSUE TITLE
Explicit documentation on Code argument constraints return type

### ISSUE THREAD

**Issue by geoand** [spockframework/spock#733]
Hello,

I was playing around with the awesome argument constraints feature of Mocks, and I fell prey to an issue very similar to the one described [here](http://stackoverflow.com/questions/22111212/how-to-do-argument-capture-with-spock-framework).
A clue to Spock's behavior is provided in a comment by `Peter Niederwieser` in one of the answers which I think would be a very good addition to the documentation in `Argument Constraints` section.
The example provided in the documentation (`1 * subscriber.receive({ it.size() > 3 })`) does not immediately make it clear to the reader that the value returned by the closure is actually what Spock uses to determine whether or not a mock was interacted with.

I personally think that an example like (`1 * subscriber.receive({ it.size() > 3 && it.contains('a')})`) would make things much more clear, as would an explicit declaration (maybe via a comment) of the use the return value of the closure.

Please let me know what you think. I can of course submit a PR if/once a solution is agreed upon.

Thanks!

**Comment by leonard84** [comment]
@geoand please feel free to submit a PR with improved documentation

**Comment by geoand** [comment]
@leonard84 Sounds good! I will most likely do that tomorrow.
