### ISSUE TITLE
combine label

### ISSUE THREAD

**Issue by musketyr** [spockframework/spock#736]
# Issue description
Sometimes you want to execute tests against all possible combinations of input values. It would be great to have `combine:` label similar to `where:` which will execute the feature method with all possible combinations of the input:

```
void 'test feature on #os with #mem of memory and #disk disk space'() {
    expect:
        test(os, mem, disk)
    combine:
        os      | mem  | disk
        'Lion'  | '2G' | '250G'
        'Win8'  | '4G' | '350G'
        'Linux' | '8G' | '500G'

}
```

**Comment by leonard84** [comment]
You can already do that using Guava's [cartesianProduct](https://google.github.io/guava/releases/21.0/api/docs/com/google/common/collect/Sets.html#cartesianProduct-java.util.List-)

```
where:
[os, mem, disk] << Sets.cartesianProduct([
        ['Lion', 'Win8', 'Linux'] as Set,
        ['2G', '4G', '8G'] as Set,
        ['250G', '350G', '500G'] as Set
])
```

I don't think that this really warrants a new block type.

**Comment by musketyr** [comment]
I know there are other ways to do so (Groovy's `combinations()` can do the same). it just looks much nicer with the table like structure.

**Comment by leonard84** [comment]
While it may look nicer, it is actually rather limited.

You need to have the same number of rows on each column. Sure, you could do something like this

```
    combine:
    os      | mem  | disk
    'Lion'  | '2G' | '250G'
    'Win8'  | '4G' | '350G'
    'Linux' | _    | '500G'
    _       | _    | '800G'
```

but this doesn't really improve readability. The groovy way, which as you pointed out doesn't even require guava, doesn't need this workaround.

```
    where: [os, mem, disk] << [
        ['Lion', 'Win8', 'Linux'],
        ['2G', '4G'],
        ['250G', '350G', '500G', '800G']
      ].combinations()
```

Furthermore, you could even use `findAll` to post process the combinations and filter out unwanted entries.
