### ISSUE TITLE
Method chaining with lists

### ISSUE THREAD

**Issue by gajarajkalburgi** [spockframework/spock#748]
# Chaining Method Responses with lists
Chaining result gets scrambled while using lists.

# Issue description
Mock any class returning list of objects. 
Mocking and stubbing and result chaining given in example.

# Expected
First call should return [1,2,3]
Second call should return [4,5,6]

# Result
First call resturns [4,5,6]
Second call returns [1,2,3]

# How to reproduce    
```
def mockobj = Mock(Class)
given:
     mockobj.func(_) >>> [[1,2,3],[4,5,6]]
```
## Java/JDK
`Java version: 1.8.0_101, vendor: Oracle Corporation`

## Groovy version

`Groovy 2.4`

### Apache Maven
`Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T01:41:47+09:00)`

## Operating System
> Windows

## IDE
> IntelliJ

### Apache Maven
    <dependency>
           <groupId>org.spockframework</groupId>
           <artifactId>spock-core</artifactId>
	   <version>1.1-groovy-2.4</version>
    </dependency>

**Comment by leonard84** [comment]
I cannot reproduce your issue. This works fine for me:

```java
class TestMock extends Specification {

    def "mock list return"() {
        def mock = Mock(Foo)
        mock.func(_) >>> [[1,2,3],[4,5,6]]

        when:
        def r1 = mock.func(1)
        def r2 = mock.func(2)

        then:
        r1 == [1,2,3]
        r2 == [4,5,6]

    }


    def "stub list return"() {
        def mock = Stub(Foo)
        mock.func(_) >>> [[1,2,3],[4,5,6]]

        when:
        def r1 = mock.func(1)
        def r2 = mock.func(2)

        then:
        r1 == [1,2,3]
        r2 == [4,5,6]

    }

}

interface Foo {
    List func(param)
}

```

Please provide a [SSCCE](http://sscce.org/)
