### ISSUE TITLE
Spock does not start Spring context when using Spring 3

### ISSUE THREAD

**Issue by varad** [spockframework/spock#750]
I have a project that uses Spring 3 and I am trying to start a context before the test (using [@ContextConfiguration](https://docs.spring.io/spring/docs/3.2.9.RELEASE/javadoc-api/)).

But the context never started. I found a class [SpringExtension](https://github.com/spockframework/spock/blob/5157299cb5aac34d2070ed5aac10a449b06156ab/spock-spring/src/main/java/org/spockframework/spring/SpringExtension.java) and its method "isSpringSpec". I believe, there's an issue in that method because it tries to find @ContextConfiguration on SpecInfo class instead of the test class.

I forked Spock to show the issue - https://github.com/varad/spock/commit/90d0c61efc70aced30c443881639f1189712f387

What do you think of that? Thanks.

**Comment by leonard84** [comment]
@varad you are right, thanks for the example it allowed for a quick fix.

**Comment by tburny** [comment]
@leonard84 I also ran into this issue using Spock 1.1, Groovy 2.3 and Spring 3.2.8

Could you create a bugfix release for 1.1? That would be awesome! 

P.S.: Let me know if I you need a hand or two :)

**Comment by leonard84** [comment]
@tburny there will be no bugfix release for 1.1 as 1.2 should be released soon(ish). I'd suggest using jitpack.io if you don't want to use a snapshot version.

**Comment by tburny** [comment]
Thanks for your quick reply :) I know that backporting and releasing a new version might not be an easy thing, so I understand your point.

The problem is that the project I'm using is stuck with Groovy 2.3 and I cannot simply change that, so I cannot use Spock 1.2 (which afaik is for Groovy 2.4 only) when its ready.
