### ISSUE TITLE
MethodInvocation interceptors sortable

### ISSUE THREAD

**Issue by tkvw** [spockframework/spock#757]
There is no way to sort the interceptors of a methodinvocation; 
https://github.com/spockframework/spock/blob/5157299cb5aac34d2070ed5aac10a449b06156ab/spock-core/src/main/java/org/spockframework/runtime/extension/MethodInvocation.java#L46

I would be nice to allow sorting (check if the interceptor implements Comparable) of the interceptors in some way. I want to make an extension but it depends on another extension to have run setupSpec before, or is this intentional behaviour? I can make a PR for this.

**Comment by leonard84** [comment]
@tkvw extensions should work independently. Could you describe your use case a bit more in detail.

**Comment by tkvw** [comment]
I develop using grails, it uses interceptors to setup some tests. One of the interceptors sets up a mock persistent enviroment. I want to make an interceptor which depends on the fact that the persistent environment is setup before it can run it's setupSpec.

**Comment by leonard84** [comment]
Relates #646

**Comment by tkvw** [comment]
I'll close this in favor of #646
