### ISSUE TITLE
Mocking concrete classes using spring and detachedMockFactory

### ISSUE THREAD

**Issue by hm1rafael** [spockframework/spock#759]
When creating mocks of concrete classes using ```DetachedMockFactory``` and annotating a method with ```@Bean``` if the concrete class has other spring dependencies (```@Autowired``` dependencies, ```@PostConstruct```), should a Mock try to inject dependencies since will be used to "emulate" interactions?

I'm using Intellij, 
Groovy: 2.4.10
Java: 1.8
OS: Ubuntu 17.04
Spock: 1.1-groovy2.4

**Comment by leonard84** [comment]
@hm1rafael I don't understand what you mean, please elaborate further and provide a [SSCCE](http://www.sscce.org/)

**Comment by hm1rafael** [comment]
Hi @leonard84,

What I mean if you create a mock as a spring bean using ```DetachedMockFactory``` if the class being mock is a concrete class and has other spring dependencies, the Bean creation fails.

I created a simple example with spock and spring boot test, let me know if it is clear now.
Example: https://github.com/hm1rafael/mock-spock-spring

**Comment by leonard84** [comment]
If you want this behavior, then you need to use a different way to register those beans (credits to @twicksell).

```java
class MockPostProcessor implements BeanFactoryPostProcessor {

    def detachedMockFactory = new DetachedMockFactory()

    void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) throws BeansException {
        beanFactory.registerSingleton("example", detachedMockFactory.Mock(Example))
    }
}
```

You can use it like this:
```java
class ExampleSpockTestConfiguration {
    def detachedMockFactory = new DetachedMockFactory()

    @Bean
    MockPostProcessor mockPostProcessor() {
        new MockPostProcessor(['example': detachedMockFactory.Mock(Example)])
    }

    static class MockPostProcessor implements BeanFactoryPostProcessor {
        private final Map<String, Object> mocks

        MockPostProcessor(Map<String, Object> mocks) {
            this.mocks = mocks
        }

        void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) throws BeansException {
            mocks.each { name, mock ->
                beanFactory.registerSingleton(name, mock)
            }
        }
    }
}
```

**Comment by leonard84** [comment]
With #796 we've added an alternative will help in this case.
