### ISSUE TITLE
Wrong object returned from static stub when multiple classes are involved.

### ISSUE THREAD

**Issue by HFSDev** [spockframework/spock#761]
While unit testing grails 3.2.9 application with **grails dev test-app -unit**, test fails due to a **org.codehaus.groovy.runtime.typehandling.GroovyCastException**.

Consider domain classes ClassA and ClassB in the same package which are injected with method "get(id)". Consider service ServiceA which interacts with ClassA and ClassB.

In my unit test for the service, in setup method I declare:

    def setup() {
        GroovySpy(ClassA, global: true)
        GroovySpy(ClassB, global: true)
    }

In my feature method:

    void "Test 1"() {
        when:
            service.myMethodUnderTest();
        then:
            (1.._) * ClassA.get(_) >> new ClassA()
            (1.._) * ClassB.get(_) >> new ClassB()
    }

Now, first stub works just fine. But when myMethodUnderTest tries to run method **get** on ClassB, Spock is returning an object of type ClassA.

> java version "1.8.0_131" 
> grails 3.2.9
> gradle 3.5.1
> Windows
> Eclipse Oxygen

**Comment by leonard84** [comment]
Please provide a [SSCCE](http://www.sscce.org/).

**Comment by HFSDev** [comment]
[IsSpockBug.zip](https://github.com/spockframework/spock/files/1246716/IsSpockBug.zip)

Just created an app and did the following:

grails create-app IsSpockBug --profile rest-api
grails create-domain-class test.ClassA
grails create-domain-class test.ClassB
grails create-service test.ServiceA

And I modified the test for the ServiceA class.

All files included in the zip.

I'm running Gradle from a local installation, version 3.5.1.
Note that I've changed build.gradle to load dependencies from my network repositories because we are behind a proxy.

**Comment by leonard84** [comment]
@HFSDev yes the problem is this line of `MockObject`

```java
boolean match = global ? instance.getClass() == target.getClass() : instance == target;
```

Since your are mocking a static call the instance and target are both instances of `Class` and the `class` of both instances is the same. As a workaround you can't use the wildcard argument matcher, instead you need to have different conditions.

```java
    (1.._) * ClassA.get(1) >> new ClassA()
    (1.._) * ClassB.get(2) >> new ClassB()
```

**Comment by HFSDev** [comment]
@leonard84, yes, I figured it out. But I'd expect I could use cardinality as shown. Are you guys working on it? Will it be available in the next update?

**Comment by leonard84** [comment]
I'm working on a fix for the next version.

**Comment by HFSDev** [comment]
Thank you!

**Comment by leonard84** [comment]
@HFSDev have you tried the snapshot?
