### ISSUE TITLE
Cells in a data table can refer to the current value for a column to the left works only for the first row

### ISSUE THREAD

**Issue by zshamrock** [spockframework/spock#763]
Using Spock 1.1-groovy-2.4 version.

According to 1.1-rc-1 release the following new feature was introduced:
> Cells in a data table can refer to the current value for a column to the left

Although looks like it only works with the first row/line in the data table. See the example below:

```
def "cells in a data table can refer to the current value for a column to the left"(int a, int b, int c) {
        expect:
        Math.max(a, b) == c

        where:
        a  | b  || c
        10 | 20 || b
        5  | 3  || a
    }
```

And it fails with the following error:

```
Condition not satisfied:

Math.max(a, b) == c
     |   |  |  |  |
     5   5  3  |  10
               false

Expected :10

Actual   :5
```

So, it looks like that `c` "sticks" with the value of `a` from the first row of the data table, and ignores the values in the second row.

**Comment by leonard84** [comment]
I can confirm this, behavior. However, this does not seem to happen if the value is computed.

```java

  def "cells in a data table can refer to the current value for a column to the left"(int a, int b, int c) {
    expect:
    Math.max(a, b) == c

    where:
    a  | b  || c
    10 | 20 || b+0
    5  | 3  || a+0
  }
```
Works as expected.

**Comment by paplorinc** [comment]
Thanks for the fix @leonard84!
