### ISSUE TITLE
overinterpreted invocation order

### ISSUE THREAD

**Issue by pchudzik** [spockframework/spock#773]
Looks to me like [invocation order](http://spockframework.org/spock/docs/1.0/interaction_based_testing.html#_invocation_order) is overinterpreted. (I'm not sure if it is a spock bug, might be documentation oversimplification ;))

Consider following test cases:
```
import spock.lang.Specification
import spock.lang.Unroll

import java.util.concurrent.CountDownLatch
import java.util.concurrent.Executor
import java.util.concurrent.Executors
import java.util.concurrent.TimeUnit

class AsyncTest extends Specification {
	final Executor executor = Executors.newFixedThreadPool(4)

	@Unroll
	def "no order failure"() {
		given:
		final notifier = Mock(Notifier)
		CountDownLatch latch = new CountDownLatch(1)

		when:
		executor.execute({ ->
			notifier.notifyCompletion()
			latch.countDown()
		})

		then:
		latch.await(2, TimeUnit.SECONDS)
		1 * notifier.notifyCompletion()

		where:
		i << (1..10)
	}

	@Unroll
	def "fixed order pass"() {
		given:
		final notifier = Mock(Notifier)
		final latch = new CountDownLatch(1)

		when:
		executor.execute({ ->
			notifier.notifyCompletion()
			latch.countDown()
		})

		then:
		latch.await(2, TimeUnit.SECONDS)

		then:
		1 * notifier.notifyCompletion()

		where:
		i << (1..10)
	}

	static class Notifier {
		void notifyCompletion() {
		}
	}
}
```
(I don't think I will be able to reproduce this without concurrency, so I decided to do something similar to my original issue)

The first test ```no order failure``` fails every time.
The second test ```fixed order pass``` passes every time

What is confusing to me is that verification of interaction is executed _before_ latch.await(). To fix it I need to move await to when block or provide yet another block (second test)

I'm not sure if it is a bug or planned/expected behavior? If it is not a bug then I think you should update the documentation to be a little more specific because I've wasted some time today trying to figure out what's going on.

**Comment by leonard84** [comment]
@pchudzik Spock uses some AST rewrites for the verification in combination with stubbing, one side effect is that the invocations validation is the first thing that is performed in a `then` block. The correct/safe way would be to put the `await` inside the `when` block.

Do you have any suggestions on how the docs should be improved so that it would have helped you.

**Comment by pchudzik** [comment]
Maybe somewhere at the [end of paragraph](http://spockframework.org/spock/docs/1.0/interaction_based_testing.html#_verification_of_interactions) add Note with the warning. Or add short note in the beginning of the paragraph how it is working and what it means for the user. Something like:

> Note that Spock uses AST rewrites for the verification in combination with stubbing side effect is that invocation validation is the first thing performed in a ```then``` block.

Just state the fact that if you want to do something which is not assertion in ```then``` block you should be careful because verifications will be executed before everything else.

Feel free to close I'll know better in the future ;)

**Comment by pchudzik** [comment]
Hmm I'm not sure if I've ever seen this part o the documentation
http://spockframework.org/spock/docs/1.1/interaction_based_testing.html#_explicit_interaction_blocks

According to git history, it was there like forever :) I think this one can be closed because it looks like it is already in the docs I should've read it more thoroughly :)

**Comment by leonard84** [comment]
Well your particular case would fail if you'd use the `interaction` block. On another note you can also close your issues if you think they are no longer necessary.
