### ISSUE TITLE
How to test java class name start with small letter? example class helloworld { .. }

### ISSUE THREAD

**Issue by Kanti1702** [spockframework/spock#775]
># Help us help you
>We are glad you are reporting your issue.
>
>Please follow these guidelines when so we better can classify the issue.
>
> The more info you provide about your environment and how to reproduce the problem the easier and faster it will be to solve (win-win).
>
>Please check existing issues (both open and closed) prior to opening any new issue.
>Optionally make sure it is a bug by other users in [forum](http://forum.spockframework.org), [StackOverflow Spock questions](http://stackoverflow.com/questions/tagged/spock), etc.
>
> The block quotes can be omitted.
> Most of the sections are only applicable for bugs.

# Issue description
> A clear and concise description.
> Make sure you choose the correct label as well (bug or enhancement)

# How to reproduce
> Please provide information on how to reproduce this issue, a [Short, Self Contained, Correct (Compilable), Example](http://www.sscce.org/) helps tremendously.
> Only applicable for bugs.

## Link to a gist or similar (optional)

# Additional Environment information
> Version of your build tool(if used), Java, Groovy, IDE, OS etc

## Java/JDK
`java -version`

## Groovy version
>__Note that versions older than 2.0 are no longer supported.__

`groovy -version`

### Gradle
`gradle -version`

### Apache Maven
`mvn -version`

## Operating System
> Linux, Windows, Mac etc.

## IDE
> IntelliJ, Eclipse etc.

### Gradle/Grails
    compile 'org.spockframework:spock-core:1.1-groovy-2.4-rc-2'

### Apache Maven
    <dependency>
      <groupId>org.spockframework</groupId>
      <artifactId>spock-core</artifactId>
      <version>1.1-groovy-2.4-rc-2</version>
    </dependency>

### Groovy Grape
    @Grapes(
      @Grab(group='org.spockframework', module='spock-core', version='1.1-groovy-2.4-rc-2')
    )

### Scala SBT
    libraryDependencies += "org.spockframework" % "spock-core" % "1.1-groovy-2.4-rc-2"

**Comment by leonard84** [comment]
Please don't just open a random ticket here just because your SO post was put on hold due to lack of descriptive question https://stackoverflow.com/questions/46470809/spock-how-to-test-java-class-with-class-name-in-small-letter

This issue is low quality and not really suited for this issue tracker so please fix your SO post and give an 
[ Short, Self Contained, Correct (Compilable), Example](http://www.sscce.org/)

**Comment by Kanti1702** [comment]
Yeah, I understand. But this ticket is created before SO post. Anyway I will add more description.
