### ISSUE TITLE
Invocation of static interface methods on mock responses fails with jdk 9

### ISSUE THREAD

**Issue by marcusnyl** [spockframework/spock#780]
Invocation of static interface methods on mock responses fails with jdk 9.
Using:
JDK 9 181, 
groovy-all:2.4.12
spock-core:1.1-groovy-2.4

In the following test stream.of fails with:

java.lang.IncompatibleClassChangeError: Method java.util.stream.Stream.of(Ljava/lang/Object;)Ljava/util/stream/Stream; must be InterfaceMethodref constant

	at test.Test.test stream.of fails(Test.groovy:14)
 

package test

import spock.lang.Specification

import java.util.function.Supplier
import java.util.stream.Stream

class Test extends Specification {
    def "test stream.of fails"() {
        def m = Mock(Supplier)
        when:
        def r = m.get()
        then:
        m.get() >> Stream.of("a")
        r.count() == 1
    }

    def "test stream.of ok"() {
        expect:
        Stream.of("a").count() == 1
    }
}

**Comment by AlexElin** [comment]
same problem without any mocking. (See test in the https://github.com/spockframework/spock/pull/814)

**Comment by AndreasTu** [comment]
This works with Groovy 2.5, 3.0 and 4.0. So I am closing this issue.
See:
[Groovy Web Console](https://gwc-experiment.appspot.com/?g=groovy_4_0&codez=eJxlzk0KgzAQBeB9TjG40k2g24LeoCt7gSFObGpMQjK2heLdq-IP0mwCeV94L6DqsCVgSiyE6YOPDCl41UmLrpV1IGW0UcjGux088YVyYGOlHpyaI1kPIVhD8Z8kjoS9rJdLCGUxJbhPfUAfJtckOJXAV8B0GtKQzatg_e81aDQ2ZXmxko31UMJtWpxvG4o9fj_IXU84TriXLXF-KD6pNYWqgnqrzjPMDh-l8oObTVnCZXkexfgDRsVkYA)
