### ISSUE TITLE
Mocking a static method of Domain Class is not happening

### ISSUE THREAD

**Issue by AnilPatidar** [spockframework/spock#79]
I have a classes 
Class Account{ 
static mapping = {
        table 'Account'
        id column : 'Account_ID'
}

Account account=Account.get(Account_ID)

Not able to mock the get method..it should return me the account object !!

If any body have solutions than please mail me on anilpatidar36@gmail.com 
Thank you very much !!

**Comment by leonard84** [comment]
Please provide a [SSCCE](http://sscce.org/)
