### ISSUE TITLE
defining mock interaction in cleanup() throws exception

### ISSUE THREAD

**Issue by craffael** [spockframework/spock#795]
# Issue description
Defining a mock interaction in the cleanup method of a specification yields a `java.util.NoSuchElementException`. I think this is a bug as there can be many scenarios where it is needed to define a mock interaction in the cleanup method (e.g. if other components of the system under test must be cleaned up and have the mock injected).

Also note that if we define the mock interaction directly after defining the mock, i.e. 
```groovy
MyInterface myMock = Mock() {
    foo() >> null
  }
```

Then the code runs fine, but if the method `foo()` is called in `cleanup()`, the defined interaction is actually not called!

# How to reproduce
```groovy
class tempSpec extends Specification {
  
  interface MyInterface {
    void foo()
  }
  
  MyInterface myMock = Mock()
  
  int callFoo() {
    myMock.foo()
  }
  
  def "dummy test"() {
    expect:
      5 == 5
  }
  
  def cleanup() {
    1 * myMock.foo() >> null
    callFoo()
  }
  
}
```

will yield a 
```
java.util.NoSuchElementException
	at java.util.LinkedList.getFirst(LinkedList.java:244)
	at org.spockframework.mock.runtime.MockController.addInteraction(MockController.java:55)
	at ch.guru_bazar.test.booking.tempSpec.cleanup(tempSpec.groovy:23)
```

## Java/JDK
```
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```

## Groovy version
`Groovy Version: 2.4.6 JVM: 1.8.0_111 Vendor: Oracle Corporation OS: Linux`

### Gradle
`Gradle 2.12`

## Operating System
Linux, Ubuntu 16.04

### Gradle/Grails
    compile `org.spockframework:spock-core:1.1-groovy-2.4`

**Comment by leonard84** [comment]
Hi @craffael, this is not a bug mocks can only verify behavior inside a feature method. If you want to test the cleanup behavior then do it in a separate feature method. If your SUT needs defined interactions, then you need to do it inside the `cleanup` block of the method and define the default stubs when you create the mock.

```groovy
class Foo extends Specification {

  List mocked = Mock {
    get(_) >> 'hello'
  }

  def "verify"() {
    when:
    def result = mocked.get(1)

    then:
    1 * mocked.get(_) >> 'world'
    result == 'world'

    cleanup:
    assert mocked.get(1) == 'hello'
  }
}
```
