### ISSUE TITLE
Documentation should offer anchors for subsections

### ISSUE THREAD

**Issue by bmuschko** [spockframework/spock#806]
At the moment it's hard to provide someone with a link to a subsection in the documentation. For example there's no way I could point someone directly to "Syntactic Variations" under ["Data Driven Testing"](http://spockframework.org/spock/docs/1.1/data_driven_testing.html).

It would be great if you could scroll to a subsection and click on an anchor symbol to retrieve the direct link. The [documentation for JUnit 5](http://junit.org/junit5/docs/current/user-guide) does this pretty effectively already (e.g. see paragraph icon whenever you hover with your mouse left to the title).

**Comment by leonard84** [comment]
Use the [Single Page Version](http://spockframework.org/spock/docs/1.1/all_in_one.html) and take the link from the index.
But if you want you can create a PR that sets the appropriate asciidoctor option, for the section links.

**Comment by bmuschko** [comment]
PR created.
