### ISSUE TITLE
Update Build to use JDK9+ with release option

### ISSUE THREAD

**Issue by leonard84** [spockframework/spock#808]
Java 7 has been EOL for a long time and due to an openjdk bug (https://github.com/spockframework/spock/commit/722106bc519ac05ecf2266c71dddb1dac4d6a0fc), Spock is using a deprecated runner on travis-ci that still offers oraclejdk7.

Starting with JDK9 there is the option to (correctly) compile for a previous Java version using the `release` parameter.

For compatibility reasons Spock 1.x will stay on Java 7 level. Spock 2.x will require Java 8, since that will be the new baseline for the foreseeable future. 

There is some refactoring necessary to make the current buildscripts work with this new mode. The JUnit build setup can be used as an example https://github.com/junit-team/junit5.

**Comment by bartoszwalacik** [comment]
Hi @leonard84, I'm a Spock power-user, I love Spock.
We want to migrate our projects to from Java8 to Java10, but since we have all tests written in Spock, we can't do it as I guess. What are your plans for  Spock 2.0 release? Or maybe there is some workaround for us?

**Comment by leonard84** [comment]
@bartoszwalacik see #842
