### ISSUE TITLE
SpringMockTestExecutionListener initializes @Lazy beans

### ISSUE THREAD

**Issue by jiallombardo** [spockframework/spock#823]
# Issue description
Beans marked as @Lazy are inadvertedly initialized when running spock-spring tests. I suspect the culprit is SpringMockTestExecutionListener:54. @Lazy autowiring works fine, however, classes and @Beans, annotated with @Lazy, are loaded due to the invocation of `applicationContext.getBean(...)`

# How to reproduce
I've uploaded a small project that has this issue reproduced in tests:
https://github.com/jiallombardo/test-spock-spring

When running LazyBeanInitializedSpec, you will notice an "I AM INITIALIZED" message in console log.
When running LazyBeanNotInitializedSpec (which is a regular, non spring spock test), this message won't appear.

# Additional Environment information
## Java/JDK
`java -version` 8

## Groovy version
`groovy -version` 2.4.4

### Gradle
`gradle -version` 3.1

## Operating System
> Windows

## IDE
> IntelliJ

### Gradle/Grails
    compile("org.springframework.boot:spring-boot-starter-actuator:1.5.10.RELEASE")
    compile("org.springframework.boot:spring-boot-starter-aop:1.5.10.RELEASE")
    compile("org.springframework.boot:spring-boot-starter-jetty:1.5.10.RELEASE")
    compile("org.springframework.boot:spring-boot-starter-web:1.5.10.RELEASE") {
        exclude(group: "org.springframework.boot", module: "spring-boot-starter-tomcat")
    }

    testCompile("cglib:cglib-nodep:3.2.4")
    testCompile("org.codehaus.groovy:groovy-all:2.4.4")
    testCompile("org.springframework.boot:spring-boot-starter-test:1.5.10.RELEASE")
    testCompile("org.spockframework:spock-core:1.1-groovy-2.4")
    testCompile("org.spockframework:spock-spring:1.1-groovy-2.4")

**Comment by dkhamitov** [comment]
Just a test which is expected to pass as per Spring semantics
```java
@ContextConfiguration(classes = SpringConfig)
class SpringSpockSpec extends Specification {
    @Autowired
    Foo foo

    def "foo#bar shouldn't be initialized"() {
        expect:
        foo.bar == null
    }
}

@Configuration
class SpringConfig {
    @Bean
    Foo foo() {
        new Foo()
    }

    @Lazy
    @Bean
    Object bar(Foo foo) {
        foo.bar = new Object()
        foo.bar
    }
}

class Foo {
    Object bar
}
```
