### ISSUE TITLE
PollingConditions with overridable or enhanceable failure messages

### ISSUE THREAD

**Issue by cohen990** [spockframework/spock#824]
When using `PollingConditions` and running the `eventually()` or `within()`, the failure message is unmodifiable.
e.g. I am trying to create a file on a remote server. That file requires some processing before being made available. So I write something like this:

```groovy
    when: "I drop a file into FTP"
        dropFileOnFtp()
    then: "The file is available on that FTP"
        new PollingConditions(timeout: 150, initialDelay: 1).eventually {
            response = getFileFromFtp()
            assert response.status == 200
        }
```
If this fails, the error I get looks like this.
```
Condition not satisfied after 150.00 seconds and 1365 attempts
    at spock.util.concurrent.PollingConditions.within(PollingConditions.java:164)
    ...
```

I would like to be able to enhance this failure reporting so that I can give more context for the person running the test. e.g.

```
Unable to find the post-processed file on the FTP

Condition not satisfied after 150.00 seconds and 1365 attempts
    at spock.util.concurrent.PollingConditions.within(PollingConditions.java:164)
    ...
```

From a quick look at the code, the change would need to be made at this line:
https://github.com/spockframework/spock/blob/7869f1b4d3418079618b7afcb998e2122eed345a/spock-core/src/main/java/spock/util/concurrent/PollingConditions.java#L163

And the method signature could look something like this:
```groovy
def failureMessage = "Unable to find the post-processed file on the FTP"
new PollingConditions(timeout: 150, initialDelay: 1m, message: failureMessage).eventually { ... }
```
or - and this one is probably preferable because the same conditions could then be used with different failure messages
```groovy
def conditions = { ... }
def failureMessage = "Unable to find the post-processed file on the FTP"
new PollingConditions(timeout: 150, initialDelay: 1).eventually (conditions, failureMessage)
```

and for `within`:
```groovy
def conditions = { ... }
def failureMessage = "Unable to find the post-processed file on the FTP"
new PollingConditions(initialDelay: 1).within(150, conditions, failureMessage)
```

Groovy isn't my primary language and spock isn't my best known framework so I may have missed a more idiomatic approach

**Comment by kwangomango** [comment]
This is already achieved by providing a custom assertion error message to the assert statement:

```
response = getFileFromFtp()
assert response.status == 200 : "Unable to find the post-processed file on the FTP"
```

If your response.status ==200 condition is not met, you should see the following stack trace:

```
Condition not satisfied after 1.00 seconds and 2 attempts

	at spock.util.concurrent.PollingConditions.within(PollingConditions.java:164)
	at ....
	at ....
	at ....
Caused by: Condition not satisfied:

response.status == 200

Unable to find the post-processed file on the FTP
```

**Comment by cohen990** [comment]
Oh you're totally right - the output is pretty clustered together so I never noticed
