### ISSUE TITLE
[Feature Request] Split up parameterised tests in test results

### ISSUE THREAD

**Issue by dylan-chong** [spockframework/spock#831]
# Issue Description

As a developer , i would like to see to see the results for individual parameterised test iterations, so that i can properly see what cases the tests are failing on. (All iterations of the test should be run even if the first one fails so i can see all of the results)

**Comment by Bolerr** [comment]
That is what the @Unroll annotation does when you use it with a parameterized test.

http://spockframework.org/spock/javadoc/1.0/spock/lang/Unroll.html

**Comment by dylan-chong** [comment]
Ah, didn't see that. Thanks
