### ISSUE TITLE
Groovy 2.5 support

### ISSUE THREAD

**Issue by chrylis** [spockframework/spock#833]
I know that support for forward Groovy versions was discussed in #708, but as far as I know Spock currently only supports up to 2.4. As Groovy 2.5 just went RC, is there any information on when Spock will run with 2.5?

**Comment by oreissig** [comment]
Support for a Groovy 2.5 variant is being worked on with #840

**Comment by leonard84** [comment]
Implemented with 53ca9f1cd7672f5359002eb12b3cc602ac606b07
