### ISSUE TITLE
isJava9() in spock.util.environment.Jvm returns false negative

### ISSUE THREAD

**Issue by msgilligan** [spockframework/spock#835]
# Issue description

When running Spock on Java9:
spock.util.environment.Jvm.getCurrent().getJavaSpecificationVersion() returns "9"
spock.util.environment.Jvm.getCurrent().isJava9() returns false

This is because isJava9() expects to see `"1.9"`
https://github.com/spockframework/spock/blob/5157299cb5aac34d2070ed5aac10a449b06156ab/spock-core/src/main/java/spock/util/environment/Jvm.java#L97

# How to reproduce

On a Java9 VM:
`assert spock.util.environment.Jvm.getCurrent().isJava9()`
will fail.

# Additional Environment information

I'm using Groovy 2.5.0-rc-1 from Gradle 4.6 on Mac OS X, but I doubt this matters.

**Comment by msgilligan** [comment]
The workaround is to use `jvm.getJavaSpecificationVersion() == "9"`

**Comment by ddemott** [comment]
In the test, you could check to see if a decimal is present.  If a decimal is not present then treat the version as an Integer.

**Comment by msgilligan** [comment]
It gets tricker than that because there are sometimes decimals present, e.g. `10.0.1`.

**Comment by ddemott** [comment]
Your code is going to have to deal w/the new naming standards.  It seems as though 1.0 through 1.8 follow the old standard.  The new naming standards for versioning seems to now be 9.x.x, 10.x.x etc.  Your major, minor and micro versions will have to take that into account when checking against the compatibility.
