### ISSUE TITLE
Add @Pending annotation to support pending tests

### ISSUE THREAD

**Issue by leonard84** [spockframework/spock#84]
RSpec has both `skip` and `pending` to exclude not implemented or failing tests, while `skip` is equal to `@Ignore` the equivalent to `pending` is not yet supported by spock.

`pending` tests are actually executed but are marked as skipped when they fail. However, when the test passes it will be a test failure, because a passing test should not be pending any more. This is especially helpful when you write a bunch of tests in the beginning or if you have to disable some integration tests due to external problems. This way you get notified when you can re-enable those tests.

@pniederw if you would be open to include it into spock, I would write the code and open a pull request.

**Comment by pniederw** [comment]
You can use Groovy’s `@NotYetImplemented` for this, which works fine with Spock.

**Comment by Derbeth** [comment]
So maybe documentation for "Extensions" should include `@NotYetImplemented`?

**Comment by leonard84** [comment]
@Derbeth yes it should be documented

@pniederw I've created a pull request to add some documentation for `@NotYetImplemented` then we could close this issue.

**Comment by leonard84** [comment]
There is one issue with `@NotYetImplemented` which is already described in https://code.google.com/p/spock/issues/detail?id=361

The problem is with data driven tests, currently `@NotYetImplemented` will raise an AssertionError when even a single iteration works, this might be undesirable in some cases.

Quote @pniederw from issue 361
> Technically speaking, this works as expected. The semantics that you are proposing seem more useful, but to realize them, we'd have to implement our own version of Groovy's @NotYetImplemented. Therefore I've changed this to a feature request. Thanks for the report!

> Note to myself: @PlannedFeature might be a good name for our version of @NotYetImplemented. This is in contrast to @PendingSpec, which would also be a worthwhile addition.

**Comment by leonard84** [comment]
Another thing that I noticed is that `@NotYetImplemented` will mark a test as passed. I would rather mark it as skipped so that it is more obvious in the reports that it is not really tested, otherwise someone might get the wrong impression.

**Comment by chrylis** [comment]
Definitely second the request for skipped.
