### ISSUE TITLE
Requirement for Java 11 compatibility

### ISSUE THREAD

**Issue by raphw** [spockframework/spock#843]
Java 11 is going to be the first LTS version of Java and it will remove support for `sun.misc.Unsafe::defineClass` which is currently used by both Byte Buddy and cglib.

As of Java 11, this loading approach does no longer work but since Byte Buddy 1.8 there is a new way of loading classes that unfortunately requires some code changes in Spock as method handle lookups are call site sensitive: https://mydailyjava.blogspot.no/2018/04/jdk-11-and-proxies-in-world-past.html 

You need to invoke the `load` method in `ProxyBasedMockFactory` to use a class loading strategy that depends on the current JVM's capabilities. The code looks like the following: 

```java
ClassLoadingStrategy<ClassLoader> strategy;
if (ClassInjector.UsingLookup.isAvailable()) {
  Class<?> methodHandles = Class.forName("java.lang.invoke.MethodHandles");
  Object lookup = methodHandles.getMethod("lookup").invoke(null);
  Method privateLookupIn = methodHandles.getMethod("privateLookupIn", 
      Class.class, 
      Class.forName("java.lang.invoke.MethodHandles$Lookup"));
  Object privateLookup = privateLookupIn.invoke(null, targetClass, lookup);
  strategy = ClassLoadingStrategy.UsingLookup.of(privateLookup);
} else if (ClassInjector.UsingReflection.isAvailable()) {
  strategy = ClassLoadingStrateg.Default.INJECTION;
} else {
  throw new IllegalStateException(“No code loading strategy available”);
}
```

The `Method` and the base `lookup` instance should be reused to avoid an overhead if the `lookup` strategy is available.

Also, using this strategy, you probably need to change the naming strategy for `java.*` types as you cannot define classes in a random package. Instead, put those types into a dedicated package that contains another class that you own and resolve the private lookup against this class. The class can for example be `org.spockframework.loading.Hook` and then name classes that start with `java.*` by `org.spockframework.loading`.

I am currently on parental leave without too much time. I will send you a PR if I get a quite moment but its not a big change, so maybe you can find the time to do it yourself.

**Comment by tburny** [comment]
Currently looking into it.

**Comment by raphw** [comment]
As for the Spring related test: You cannot normally define classes in JVM packages as a package needs to be opened to the Spock module (or the unnamed module) to allow definition within it. I would therefore recommend you to use `ClassLoadingStrategy.Default.WRAPPER` if the mock is in the `java.*` package. This looses you the ability to mock package-private types and to mock package-private methods of these classes but I assume that only few if any rely on this.

**Comment by MartyIX** [comment]
@tburny I added 

```
    // To fix java.lang.NoClassDefFoundError: javax/annotation/PostConstruct in org.spockframework.tapestry.ServiceInjection test
    compile("org.jboss.spec:jboss-javaee-6.0:3.0.3.Final")
```

to build.gradle file and the `java.lang.NoClassDefFoundError: javax/annotation/PostConstruct` exception was fixed. But it's just a hack..

**Comment by MartyIX** [comment]
@tburny I added PR #862. Maybe you have already done some work to improve it further or the other way around.

**Comment by tburny** [comment]
@MartyIX This is a great start!
I saw that you changed a lot of stuff along the way like updating versions of stuff - where some probably isn't necessary to archive Java 11 compatibility. Some of the stuff fixes really nasty problems, others look more unrelated to me and might accidentelly break stuff.
The path I chose was to change the absolute minimum of things, so the compromise would be to handle these cases in a seperate pull request :+1: 

I found out that it is easy to go the "lets refactor a bit here, change a bit there" path along the way, but it does make the changes (and the pull request) more complicated and confusing.
For instance I'd love to refactor the mocking proxy code a lot, as it is quite confusing. Still - I won't do that in this issue :)

**Comment by MartyIX** [comment]
@tburny I fully agree. I'm still in the phase of "making it work".

**Comment by oehme** [comment]
Just adding my +1 here, since the Gradle team currently can't verify whether Gradle fully works on Java 11 because some of our tests use proxying and fail because of the missing Java 11 support.

**Comment by MartyIX** [comment]
@tburny I have cleaned up the commit a bit. :-)

**Comment by tburny** [comment]
@MartyIX great work! I had a chat with @leonard84 some time ago and as it seems Java 7 should still be supported as long as possible (Spock 2 will support Java 8 and I hope JUnit 5).

**Comment by MartyIX** [comment]
@tburny Yes, that's my goal. It's not that easy. :-)

**Comment by MartyIX** [comment]
(I've just added https://github.com/spockframework/spock/pull/885 PR to see how many tests fail with WRAPPER strategy)

**Comment by raphw** [comment]
As described, if you resolve the method handle lookup against a class in this package, this is fully possible. It just requires that the class is opened to Spock. This is achieved via the `privateLookupIn` method.

**Comment by leonard84** [comment]
@raphw could we chat in gitter or the spock slack channel?
