### ISSUE TITLE
first failing feature marks entire spec as 'skipped'?

### ISSUE THREAD

**Issue by rosemead** [spockframework/spock#844]
Hi.
Question. Given this spec:
```
@Stepwise
class StepwiseSpec extends Specification {
    def stepA() {
        expect: true
    }
    def stepB() {
        expect: false
    }
}
```
I would expect this, when reported, to present a success rate of 50%: stepA passes, stepB fails.
Yet spock-reports reports such a run as having 100% success rate.
If I am not mistaken `StepwiseExtension::skipFeaturesAfterFirstFailingFeature` marks **all** features as skipped, when a feature in a stepwise spec fails. That would eventually lead spock reports to spit-out a skewed result. Shouldn't we count an executed feature, even if it failed/resulted in an error?
Thanks,

**Comment by leonard84** [comment]
Please provide some more information about your environment. Running this in Intellij correctly reports 1 failed/1 skipped of 2 tests

**Comment by tilmanginzel** [comment]
HI @leonard84, while IntelliJ is correctly reporting 1 failed/1 skipped of 2 tests, libraries like spock-reports are accessing the [SpecElementInfo.isSkipped()](https://github.com/spockframework/spock/blob/5157299cb5aac34d2070ed5aac10a449b06156ab/spock-core/src/main/java/org/spockframework/runtime/model/SpecElementInfo.java#L35) method, which is falsely reporting each feature as skipped.

It indeed seems like the StepwiseExtension is marking each feature as [skipped](https://github.com/spockframework/spock/blob/5157299cb5aac34d2070ed5aac10a449b06156ab/spock-core/src/main/java/org/spockframework/runtime/extension/builtin/StepwiseExtension.java#L59), as soon as one fails. Is there a specific reason for it?

Do you know if it is possible to only mark all following features as skipped?

**Comment by tilmanginzel** [comment]
Something like this would do the trick:

```java
private void skipFeaturesAfterFirstFailingFeature(final SpecInfo spec) {
    spec.getBottomSpec().addListener(new AbstractRunListener() {
        @Override
        public void error(ErrorInfo error) {
            // @Stepwise only affects class that carries the annotation,
            // but not sub- and super classes
            if (!error.getMethod().getParent().equals(spec)) return;

            // get index of failed feature and mark all subsequent features as skipped
            int indexOfFailedFeature = spec.getFeatures().indexOf(error.getMethod().getFeature());
            for (int i = indexOfFailedFeature + 1; i < spec.getFeatures().size(); i++) {
                spec.getFeatures().get(i).setSkipped(true);
            }
        }
    });
}
```

Would you accept a pull request for this @leonard84?

**Comment by leonard84** [comment]
Yes, but when you do please use local variables instead of always retrieving the value anew.

**Comment by tilmanginzel** [comment]
Hi @leonard84, thanks for the reply! I will do so in the coming week. :)
