### ISSUE TITLE
SPOCK on JAVA 10 ?

### ISSUE THREAD

**Issue by ShunmugamAiyappan** [spockframework/spock#846]
Will spock work on JAVA 10,  If so what is the stable version to be used to load the Jar using Maven ?

**Comment by tunaranch** [comment]
1.1-groovy-2.4 works with java 10.

**Comment by MartyIX** [comment]
We use Java 10 and I added the following dependencies to my project https://github.com/spockframework/spock/pull/842/files and it works fine.

**Comment by marcphilipp** [comment]
@tunaranch What are the issues with running Spock 1.0 on Java 10?

**Comment by leonard84** [comment]
With ab48b3c3506f3ffe66625d9f1aaf554df83211b1 and groovy-2.5 53ca9f1cd7672f5359002eb12b3cc602ac606b07 there should be no problems.

**Comment by marcphilipp** [comment]
So, if I understood you correctly, Spock 1.0 runs on JDK 10 and above as long as the code it handles has been compiled with target 1.8 or less, right?
