### ISSUE TITLE
Inactive Spock project admins

### ISSUE THREAD

**Issue by henrik242** [spockframework/spock#850]
There are a lot of unhandled and unanswered PR's and issues in Spock.  Releases are unfrequent, and sorely missed.

Could the Spock maintainers consider adding more admins to the project, to increase adoption, activity and release rates?

Cc: @ldaley @leonard84 @sbglasius @pniederw

**Comment by huehnerlady** [comment]
I agree, there is work on the project and there seem to be fixes which are very nice to have, but no release for over a year. So would there be the possibility of giving some feedback and maybe some reasons of why there is so much silence?

**Comment by jason-edstrom** [comment]
I have started resorting to forking the repos and making the needed changes due to the consistent lack of momentum that revisions are reviewed and merged.

**Comment by sbglasius** [comment]
I think it would be better to invite those who wants to contribute to this repo. Forking off will bring confustion to the community. I for one would like to see a momentum going forward

**Comment by jason-edstrom** [comment]
I agree 100%.  I was forking out of personal use and necessity because I needed to make some progress on some of my big issues rather than waiting for unknown ETR.

**Comment by tburny** [comment]
Regarding the popularity of spock I think that being very conservative with changes is a good thing.

However there are a few upcoming challenges that should be tackled in the near future:

- Someone to sort through and label open issues and pull requests
- Patch releases: Fixing obvious bugs in a way that does not break the existing API
- Compatibility with new Java and Groovy versions (so the project keeps its momentum and people do not turn away)

In the more distant future I think that JUnit 5 support is one of the most important aspects that we as a community should try to put together.

Although I'd love to see stable improvements for Spock, maintaining an FOSS project for a long time can be quite tedious and time consuming so it is fairly understandable if a maintainer is not always reacting instantly.

**Comment by MartyIX** [comment]
@tburny I agree. The thing is, the admins do not react at all. Not having time is understandable and fine, but no answer for months is worrisome.

**Comment by sbglasius** [comment]
I try to squeeze in as much time as I can, but my deeper knowledge of the build process and code base limits me to being active here and not merging pull requests or building the code. 

I'll see if I can get a reaction from the other admins.

Cc: @ldaley @leonard84 @sbglasius @pniederw

**Comment by milanov** [comment]
Completely agree with what's been said up to now. We all realise that working on a side-project is not always easy, but leaving things as they currently are and not merging/releasing is not a solution. I'm pretty sure there will be volunteers that might help with the actual development (with at least some guidance or reviews from the core admins).

**Comment by nvonop** [comment]
Happy to help if developers or documentation writers are needed!

**Comment by huehnerlady** [comment]
Same here, although not very experienced in open source work I am more than happy to help out :)

**Comment by tburny** [comment]
I'd volunteer for sifting through all the pull requests and open tickets to at least categorize (priorize) them.

**Comment by szpak** [comment]
@tburny I remember we (with @sbglasius and some volunteers) did it at Gr8Conf Europe 2016 to make the release of Spock 1.1 possible (with a good result in the end ;) ). It's definitely a good idea (to close duplicates and ensure something is still a problem in master) and maybe @sbglasius as a contributor could be helpful here - there is also a [Gitter](https://gitter.im/spockframework/spock) which were used to synchronize the activities.

**Comment by leonard84** [comment]
Sorry I've been absent these last 4 month due to private reasons. I'll try build momentum again. That being said I was essentially the only active (now again ;) ) member which contributed a bit to the fatigue. Having more people willing to help by reviewing PRs, improving documentation, or testing the current SNAPSHOT builds on as many projects as possible will definitely help to improve motivation. If you are seriously interested in helping out you can join gitter spock channel and message me.

**Comment by sbglasius** [comment]
@leonard84 good to see you back. I'll pitch in where I can, but probably most with cheers and encouragements. Let me know what I can do besides that.

**Comment by leonard84** [comment]
For the others who want to help you can check out the https://github.com/spockframework/spock/labels/help%20wanted label.

**Comment by leonard84** [comment]
For the others who want to help you can check out the https://github.com/spockframework/spock/labels/help%20wanted label.
