### ISSUE TITLE
verify no more interactions with mocks

### ISSUE THREAD

**Issue by musketyr** [spockframework/spock#860]
# Issue description
When I'm testing existing code I would like to be sure that I cover all the mock interactions during the tested method execution. Currently, I can add `0 * _._(*_)` to verify this. It might look better if there will be a method which will be doing the same. Let's call it `noMoreInteractions()`. Ideally on top of current functionality the method `noMoreInteractions()` would not stop on the first unexpected call of the mock method but it would show all unmatched interactions at the end of `when` block execution.

**Comment by leonard84** [comment]
Please see [strict mocking](http://spockframework.org/spock/docs/1.1/all_in_one.html#_strict_mocking) the shortest syntax is `0 * _`.

**Comment by musketyr** [comment]
Ok, thanks

Dne čt 19. čvc 2018 13:15 uživatel Leonard Brünings <
notifications@github.com> napsal:
