### ISSUE TITLE
Soft assertions should use accept a list

### ISSUE THREAD

**Issue by OdysseusLives** [spockframework/spock#863]
# Issue description
Soft assertions with `verifyAll` should be able to accept a list.

This would be most useful with parameterized tests, where only some assertions are applicable, yet the test setup and actions are the same.

# Ideal example
```
def assertions = [1 == 1, 1 == 2, 2 == 3]
verifyAll {
    assertions.each {
        it
    }
}
```

as opposed to defining each assertion in a separate line in the verifyAll block: 
```
verifyAll {
    1 == 1
    1 == 2
    2 == 3
}
```

**Comment by leonard84** [comment]
It is highly unlikely that this will be added, spock power assertios are implemented using AST transformations during compile time. For that to work, spock needs to know precisely which statement needs to be transformed, this will not work some random list. So what you basically have is a list of booleans.

**Comment by tburny** [comment]
How about

```
assertions.every { it }
```

**Comment by leonard84** [comment]
What could be possible would be something like this:

```groovy
verifyAll(Iterable<Closure>);

// note explicit assert statements are neccessary
def assertions = [{assert 1 == 1}, {assert 1 == 2}, {assert 2 == 3}]

verifyAll(assertions)
```

But you could easily implement this yourself

```groovy
void customAsssert(Iterable<Closure> assertions) {
 def result = assertions.collect {
    try {
      it()
      return null
    } catch (AssertionError e)
      return e
    }
  }.findAll()
  if (result) {
    throw new MultipleFailureException(result)
  }
}
```
