### ISSUE TITLE
Global mocking not working when receiving null on methods with many signatures 

### ISSUE THREAD

**Issue by fogrizovic** [spockframework/spock#871]
Hi,

I'm trying to stub a static method from Java class, which has more than one signature. Like this

```
def "test stubbing"() {
       given:
       GroovySpy(Foo, global: true)
       Foo.generate(_) >>  "bla"
       when:
       def res = Foo.generate((Obj1) null)
       then:
       res == "bla"
   }
```
Foo is a java class with mehtod "generate" defined as:

```
public static String generate(Obj1 obj) {
// somehting
}

public static String generate(Obj2 obj) {
// somehting
}
```
Then I'm getting:
```
groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method Foo#generate.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
[Obj1]
[Obj2]
```
Is this the expected behaviour? How can I call generate with "null" value?

**Comment by postapczuk** [comment]
You cannot stub two methods in one stub. You need to precise which signature you are stubbing. Use `Foo.generate(_ as Obj1) >> "bla1"` and `Foo.generate(_ as Obj2) >> " bla2"` .

**Comment by FatCash** [comment]
+1 Neither calling with `generate(_ as Obj1) ` or `generate((Obj1) _)` works :(
Have you found any workaround to test with null argument when there is a method/constructor with more than one signature?

**Comment by postapczuk** [comment]
What are you testing in your test?

It doesn't make sense:

First you're stubing:
`Foo.generate(_) >> "bla"`

And then you test this stub:
'def res = Foo.generate((Obj1) null)'

If you're testing the static method, you shouldn't do the stub. 

If you're testing some class that is use Foo's static method you should change 'when' section to use method from that class, not from Foo.

**Comment by slyns** [comment]
@fogrizovic , actually `Foo.generate((Obj1) null)` will not help Groovy to choose proper method. This might be more specific to Groovy itself, not Spock, see https://stackoverflow.com/questions/26037514/groovy-method-overloading-selection-of-method-prefers-interfaces-over-subclasse

**Comment by ssrinathraju** [comment]
I think You can't use GroovyMock for testing the Java static method.

The methods under MockingApi like GroovyMock, GroovySpy are specific to Groovy

Please refer the same in the Spock doc: http://spockframework.org/spock/docs/1.0/interaction_based_testing.html (Groovy Mocks (New in 0.7)

**Comment by Vampire** [comment]
@ssrinathraju it depends.
The point is the code that is "calling" the mock, not the class that is mocked.
If the code that is tested calls a static method on a Java class, a GroovyMock can be used to mock this call.
And in this - I guess simplified - example the code that is tested is inlined in the feature method as `Foo.generate((Obj1) null)`.
Imagine this line is in some Groovy file and that Groovy file is tested here, then the expectation of OP is fine.
If you e. g. replace `Foo.generate((Obj1) null)` by `Foo.generate('foo')`, the test is successful as the mock worked.

The problem ist most probably more how the mocks are implemented and that they don't carry over the cast to the method selection or something similar.
