### ISSUE TITLE
@Retry should be declarable on the spec class level

### ISSUE THREAD

**Issue by marcphilipp** [spockframework/spock#874]
Currently, `@Retry` can only be used to annotate (feature) methods. Thus, if you wanted to configure the same retries for all feature methods in a spec class or class hierarchy, you'd have to copy the same annotation including it's arguments to every feature method. That's repetitive and easy to forget when adding new tests.

Instead, similar to `@Timeout` it should be possible to declare `@Retry` on a spec class which would mean that the retries are applied to every feature method. If a feature method declares its own `@Retry` annotation, it will override the class-level one. The `@Retry` annotation should be inherited to subclasses which should also be able to override it by declaring their own annotation.

There are two alternatives what a `@Retry` annotation on a subclass would mean. Let's look at an example:

```groovy
@Retry(count = 1)
abstract class Foo extends Specification {
  def foo() {
    expect:
    false
  }
}

@Retry(count = 2)
class Bar extends Foo {
  def bar() {
    expect:
    false
  }
}
```

How often would `Bar.foo()` be retried? One option would be to use the original config from the `@Retry` annotation on `Foo`. Another would be to use the `@Retry` annotation on `Bar`.

Thoughts?

**Comment by wolfs** [comment]
What happens for `@Timeout`? I think it should be consistent to `@Retry`.

I would expect the retry count for `Bar.foo()` to be `2`, i.e. to use the `@Retry` annotation on `Bar`. If `Foo.foo()` would have a `@Retry` annotation then I would expect that to take precedence.

**Comment by leonard84** [comment]
`@Timeout` is not inherited, it will apply to all features in the annotated spec but not to parent or sub specs.

**Comment by marcphilipp** [comment]
Here's a PR for option (1): #875.

**Comment by marcphilipp** [comment]
Based on the feedback I got from coworkers, I decided to go with option (2) in #879.
