### ISSUE TITLE
Mockito.verify don't work in 'then:' block

### ISSUE THREAD

**Issue by stanislav3316** [spockframework/spock#883]
Hello, cannot verify
`Mockito.verify(spyService, Mockito.times(2)).checkOrder(ArgumentMatchers.any(OrderDto.class))`
in `then:` block. Works in `when:` block correctly.

**Comment by stanislav3316** [comment]
create a Spy with @SpyBean annotation to inject it into Spring application context.

**Comment by leonard84** [comment]
Usage of mockito is discuraged. Please use Spocks own mock objects. See http://spockframework.org/spock/docs/1.2-RC1/all_in_one.html#_annotation_driven
