### ISSUE TITLE
Support 2.5 operators

### ISSUE THREAD

**Issue by chrylis** [spockframework/spock#891]
I'm running `1.2-RC1-groovy-2.5` with 2.5.2, and it's working beautifully. However, it seems that some Groovy 2.5 features aren't supported yet, and I'm getting a compile error when trying to use `===` (i.e., the new `is` operator) or `!in` in a `then:` block. This is a request to add support for the new operators.

**Comment by leonard84** [comment]
I can't find any reference to `===` in the [docs](http://groovy-lang.org/operators.html), also nothing about `!in`. `!(a in b)` works fine as well as `a.is(b)`. Could you please provide some sample code.

**Comment by chrylis** [comment]
I was reading too many docs at once and got confused. This is a feature in Groovy 3, not 2.5.
