### ISSUE TITLE
Spock exhausts the Iterable dataprovider by calling 'size'

### ISSUE THREAD

**Issue by rtretyak** [spockframework/spock#894]
My setup:
Maven, Groovy 2.4.15, Spock 1.1-groovy-2.4

The exact problem is on this line 
https://github.com/spockframework/spock/blob/master/spock-core/src/main/java/org/spockframework/runtime/ParameterizedSpecRunner.java#L123
where SpecRunner runs 'size' method on the provided Iterable.
Running 'size' on the Iterable object (not a Collection) actually exhausts it, causing Spock to throw `org.spockframework.runtime.SpockExecutionException: Data provider has no data` exception afterwards.
I see that it tries to overcome this by checking `prov instanceof Iterator` on line 118 but it actually should check `instance of Iterable`, not `Iterator`, which actually makes no sense (I expect `prov` to always be `Iterable` at that point)
As a workaround it is possible to add a stub 'size()' method to the dataprovider that will return any non-zero integer, but this is not documented anywhere.
This actually took me quite some time to understand why my dataprovider keeps throwing at me =(

Here is some code:
```
    @Unroll
    def "My test #sw"() {
        expect: "this sketch to work"

        where:
        sw << new MyDataProvider()
    }

    @Slf4j
    class MyDataProvider implements Iterable<String> {
        protected int counter = 0

        @Override
        Iterator iterator() {
            return new Iterator() {
                @Override
                boolean hasNext() {
                    return counter++ < 5
                }

                @Override
                String next() {
                    "next$counter"
                }
            }
        }
    }
```
which ends up with `org.spockframework.runtime.SpockExecutionException: Data provider has no data`
Works fine if I add size() inside MyDataProvider
```
int size() {
    return 1
}
```

Am I doing something wrong? Looks like a defect to me. At least it is not documented that I should provide a 'size()' implementation

**Comment by rtretyak** [comment]
Oh, it works fine if I implement `Iterator` instead of `Iterable`. It also works fine if I implement 'Iterable' with  with size. The doc clearly states that dataprovider should be implementing the `Iterable` contract.

**Comment by leonard84** [comment]
AFAIK is the contract for [Iterable](https://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html) to return a **fresh** `Iterator` each time `iterator()` is called. Your `MyDataProvider ` violates this by not really returning a fresh `Iterator`, since it relies on a shared counter.

**Comment by rtretyak** [comment]
That's true, thanks
