### ISSUE TITLE
jsonBody' error code

### ISSUE THREAD

**Issue by bmjames** [spockframework/spock#91]
The documentation for `Web.Spock.Shared.jsonBody'` says:

> Parse the request body as json and fails with 500 status code on error

500 seems like the wrong status code, for most use cases. If I am expecting JSON from the client, and it provides a request body that is not valid JSON, that should be a client error (4xx), not a server error.

**Comment by leonard84** [comment]
@bmjames could you be more specific, I could not find anything related to `jsonBody` in the spock sources and documentation.

**Comment by bmjames** [comment]
Sorry, I opened this issue on the wrong repository... :)
