### ISSUE TITLE
Error while Mocking EntityManager

### ISSUE THREAD

**Issue by simbuatgit** [spockframework/spock#914]
# Issue description

java.lang.SecurityException: class "javax.persistence.EntityManager"'s signer information does not match signer information of other classes in the same package

# How to reproduce
Mocking EntityManger creating this problem. javax.persistence-2.2.0.jar and eclipselink-2.7.1.jar is being used

## Link to a gist or similar (optional)

# Additional Environment information
Jdk8,

## Java/JDK
java version "1.8.0_151"

## Groovy version
2.4.9

### Gradle
Gradle 4.10

## Operating System
 Windows

## IDE
 Eclipse

### Gradle/Grails
     testCompile(group: 'org.spockframework', name: 'spock-core', version:'1.1-groovy-2.4')

**Comment by leonard84** [comment]
Please try  `spock-1.2-RC3`
