### ISSUE TITLE
assert with message disables power assertion output

### ISSUE THREAD

**Issue by kriegaex** [spockframework/spock#922]
With a feature method like this

```
def one() {
	expect:
	("one".capitalize() * 3).toUpperCase() == "OneOneOne"
}
```

we get an error message like that:
```
Condition not satisfied:

("one".capitalize() * 3).toUpperCase() == "OneOneOne"
       |            |    |             |
       One          |    ONEONEONE     false
                    OneOneOne          6 differences (33% similarity)
                                       O(NE)O(NE)O(NE)
                                       O(ne)O(ne)O(ne)

Expected :OneOneOne

Actual   :ONEONEONE
```

The same is true if we explicitly use `assert` at the beginning of the condition. So far, so good.

Now this is what happens when using `assert` with an additional error message:

```
def one() {
	expect:
	assert ("one".capitalize() * 3).toUpperCase() == "OneOneOne", "My custom message"
}
```

The very helpful power assert output vanishes.
```
Condition not satisfied:

("one".capitalize() * 3).toUpperCase() == "OneOneOne"

My custom message
```

What I would like to see instead is the custom message prepended to the power assert output like this:

```
My custom message

Condition not satisfied:

("one".capitalize() * 3).toUpperCase() == "OneOneOne"
       |            |    |             |
       One          |    ONEONEONE     false
                    OneOneOne          6 differences (33% similarity)
                                       O(NE)O(NE)O(NE)
                                       O(ne)O(ne)O(ne)

Expected :OneOneOne

Actual   :ONEONEONE
```

Would it be possible to add a corresponding AST transformation for that kind of syntax?

**Comment by leonard84** [comment]
Yes it is possible, take a look at:
* `org.spockframework.compiler.ConditionRewriter#rewriteExplicitCondition` 
* `org.spockframework.compiler.ConditionRewriter#rewriteOtherCondition`
* `org.spockframework.compiler.ConditionRewriter#rewriteMethodCondition`
* `org.spockframework.compiler.ConditionRewriter#rewriteStaticMethodCondition`

FYI the syntax is slightly different `assert expression [ : message ] `

The question should be if it should?
Adding a custom message currently completely removes the recording of arguments.
This behavior might be helpful. Furthermore, if will break tests that rely on the specific message (although they should be few)

/polls 'Keep existing behavior' 'Change to custom message plus power-assert'

**Comment by kriegaex** [comment]
As for the syntax `assert expression [ : message ]`, yes, it works like that. But the syntax `assert expression [,: message ]` seems to be equivalent. At least it yields the exact same result in my test case. I was also surprised.

My vote is for a breaking change because I think it is what a Spock user probably expects: Spock power assertion features, no matter whether he parametrises the `assert` or not. Two different behaviours are rather unexpected IMO.

**Comment by paulk-asert** [comment]
Spock behavior doesn't have to mirror vanilla Groovy, but in vanilla Groovy when adding our simplified power assert we wanted a way to disable the generated message. You might have expressions that contain objects with sensitive data or self-recursive data-structures or believe you have a better way to present the information. We decided that if the optional additional message was supplied, that would disable the generated content. We tried thinking of a way to make the generated message available to be incorporated manually, e.g. if the supplied additional message was a GString but never found a solution we were happy with.

**Comment by leonard84** [comment]
@kriegaex what do you think about #923, would this be a viable alternative for you?

@paulk-asert thanks for the information, I was thinking along the same lines.

**Comment by kriegaex** [comment]
@paulk-asert, I cannot follow your reasoning because if this was the intention and important enough to implement the "feature" that way, why is it [undocumented](http://spockframework.org/spock/docs/1.1/all_in_one.html)? I am sure there must be a way to make it configurable to **not** have power assert output if someone does not want it. An annotation-driven extension, `SpockConfig.groovy` or a combination of both, default config plus override per spec or feature method. Maybe even an override per (block of) condition(s) via `with(SomeCategory)` would be possible, but I am not the implementation expert here.

Apart from the technology discussion, why would test data ever be sensitive enough not to print it? And if it was self-recursive, the printing problem would also apply to normal power asserts and should be solved within the framework, not by forcing users to disable power assert with a rather strange trick, documented or not.

@leonard84, #923 is not a solution for me. Of course I also came up with a workaround long ago, but it is ugly:

    package de.scrum_master.testing
    
    import org.spockframework.runtime.ConditionNotSatisfiedError
    import spock.lang.Specification
    
    /**
     * This is an ugly workaround for https://github.com/spockframework/spock/issues/922
     */
    class EnhancedPowerAssertionTest extends Specification {
      static class PowerAssertionEnhancer {
        private static final String DASHED_LINE = "=" * 60
    
        static boolean specialAssert(String extraMessage, Closure assertion) {
          try { assertion() }
          catch(ConditionNotSatisfiedError e) {
            System.err.println DASHED_LINE
            System.err.println extraMessage
            System.err.println DASHED_LINE
            throw e
          }
          true
        }
      }
    
      def setupSpec() {
        getClass().mixin PowerAssertionEnhancer
      }
    
      def "Power-assert output for unparametrised 'assert'"() {
        expect:
        assert ("one".capitalize() * 3).toUpperCase() == "OneOneOne"
      }
    
      def "Power-assert output for implicit Spock-style 'assert'"() {
        expect:
        ("one".capitalize() * 3).toUpperCase() == "OneOneOne"
      }
    
      def "No power-assert output for parametrised 'assert'"() {
        expect:
        assert ("one".capitalize() * 3).toUpperCase() == "OneOneOne" :
          "This is some additional info about the error"
      }
    
      def "Combine power-assert output with extra failure log output"() {
        expect:
        specialAssert "This is some additional info about the error", {
          assert ("one".capitalize() * 3).toUpperCase() == "OneOneOne"
        }
      }
    }

**Comment by leonard84** [comment]
I still see the need to be able to suppress a message, especially if we are using a third-party library, that provides its own exception messages.

```java
 resultActions.andExpect(status().isOk())
                .andExpect(view().name('login'))
                .andExpect(content().string(
                CoreMatchers.allOf(
                        containsString('<input type="hidden" name="service" value="foo" />'),
                        containsString('<input type="hidden" name="successURL" value="https:/login/success?kmsi=false" />'),
                        containsString('<input type="hidden" name="loginFailedURL" value="https:/login?failed=true&amp;login_hint=username@web.de" />'),
                        containsString('<input type="hidden" name="loginErrorURL" value="https:/login/error" />'),
                        containsString('<input type="hidden" name="statistics" value="foo" />'),
                        containsString('<input type="hidden" name="username" value="username@web.de" />'),
                        matcher
                )))
```

renders as

```
Condition failed with Exception:

resultActions.andExpect(status().isOk()) .andExpect(view().name('login')) .andExpect(content().string( CoreMatchers.allOf( containsString('<input type="hidden" name="service" value="foo" />'), containsString('<input type="hidden" name="successURL" value="https:/login/success?kmsi=false" />'), containsString('<input type="hidden" name="loginFailedURL" value="https:/login?failed=true&amp;login_hint=username@web.de" />'), containsString('<input type="hidden" name="loginErrorURL" value="https:/login/error" />'), containsString('<input type="hidden" name="statistics" value="foo" />'), containsString('<input type="hidden" name="username" value="username@web.de" />'), matcher )))
|             |         |        |        |         |      |
|             |         |        |        |         |      <org.springframework.test.web.servlet.result.ViewResultMatchers$$Lambda$382/219130824@77f4038c arg$1=login>
|             |         |        |        |         <org.springframework.test.web.servlet.result.ViewResultMatchers@27a90ce5>
|             |         |        |        java.lang.AssertionError: No ModelAndView found
|             |         |        <org.springframework.test.web.servlet.result.StatusResultMatchers$$Lambda$381/1314050802@51869ad6 arg$1=200>
|             |         <org.springframework.test.web.servlet.result.StatusResultMatchers@36511772>
|             <org.springframework.test.web.servlet.MockMvc$1@795faad val$mvcResult=org.springframework.test.web.servlet.DefaultMvcResult@1eb9d69a this$0=org.springframework.test.web.servlet.MockMvc@73385d3f>
<org.springframework.test.web.servlet.MockMvc$1@795faad val$mvcResult=org.springframework.test.web.servlet.DefaultMvcResult@1eb9d69a this$0=org.springframework.test.web.servlet.MockMvc@73385d3f>
```
The spring exception message is listed as cause.

with `assert <expectation> : 'MVC Expectation Failed'`  we get
```
Condition failed with Exception:

resultActions.andExpect(status().isOk()) .andExpect(view().name('login')) .andExpect(content().string( CoreMatchers.allOf( containsString('<input type="hidden" name="service" value="foo" />'), containsString('<input type="hidden" name="successURL" value="https:/login/success?kmsi=false" />'), containsString('<input type="hidden" name="loginFailedURL" value="https:/login?failed=true&amp;login_hint=username@web.de" />'), containsString('<input type="hidden" name="loginErrorURL" value="https:/login/error" />'), containsString('<input type="hidden" name="statistics" value="foo" />'), containsString('<input type="hidden" name="username" value="username@web.de" />'), matcher )))

MVC Expectation Failed
```

I would argue it would be event better to hide the complete expression. So if we change `assert exp : message` then we need something for this, any ideas?

**Comment by kriegaex** [comment]
Well, that's why my last sentence was:

> Please consider implementing it and making it the default behaviour - _**with an option to deactivate it**_ if you think it is necessary.

So providing an option to users to override the default behaviour (power-assert output) is, as I said, completely fine with me - not that you need my approval. ;-)

The sample log output you just showed might be a case in which a user would want to avoid power assert output, even though I think that it is rather exotic to use an extra libraries for assertions even though Spock provides its nice condition auto-assert which is no less expressive and easy to use. BTW, I would still like to have the power assert output if I could have the additional text I want. Why? The first line is identical anyway, but looks way uglier than it would using Spock conditions. Now we cannot even clearly see which of the many assertions failed. The power assert output at least helps a bit here, indicating that `.andExpect(view().name('login'))` failed with `java.lang.AssertionError: No ModelAndView found`. So actually it is a case for wanting power assert, not for avoiding it. It helps me more than the general information "MVC expectation failed". Of course it did, the power assert output tells me already.

As for how to implement the feature, I wrote something about it in a previous comment, too:

> I am sure there must be a way to make it configurable to **not** have power assert output if someone does not want it. An annotation-driven extension, `SpockConfig.groovy` or a combination of both, default config plus override per spec or feature method. Maybe even an override per (block of) condition(s) via `with(SomeCategory)` would be possible, but I am not the implementation expert here.

The idea that was mentioned above about different behaviour for `String` vs. `GString` would be quite counter-intuitive, I think we should not go that way. Another similar option might be a syntax like `assert condition : ["Additional message"]` which could be used like `assert condition : ["First paragraph", "Second paragraph"]`. I.e. if there was some kind of collection or array as an argument, Spock could use power assert output. It feels a bit ugly and definitely would need explicit documentation, but so would all other options.

I am just thinking aloud here and am really open to other ways of implementing or using this. Even if it was just a workaround like `powerAssert condition , "message"` it would be better than now because at least I could use it. I still would be happier with making power assert the default and providing ways to disable it, see my quote above.

**Comment by leonard84** [comment]
I don't want a config switch. First, it adds hidden information to the behavior of Spock, so a reviewer would also have to know about that. Second, it would be global so you couldn't mix it. Third, this needs to be known at compile time not test runtime, which is also confusing for the users.

> even though I think that it is rather exotic to use an extra libraries for assertions even though Spock provides its nice condition auto-assert which is no less expressive and easy to use. 

That depends, I agree it doesn't make sense to add standalone assertion libraries. However, if the framework you are working with (e.g., Spring MVC) provides test support then it is a valid scenario.

Spring MockMVC does output more than a page on system.out with additional information. So I would actually remove the whole condition rendering as well as the power assertions. It does not have to be `assert` at all, maybe we could use something better to indicate that the method we are calling provides its own diagnostics.

**Comment by kriegaex** [comment]
> I don't want a config switch. First, it adds hidden information to the behavior of Spock, so a reviewer would also have to know about that. Second, it would be global so you couldn't mix it. Third, this needs to be known at compile time not test runtime, which is also confusing for the users.

I suggested a combination of global config + annotation-driven extension. The former would have the advantage that I could set the desired default behaviour for a whole project and not just class by class or method by method. The latter would enable developers to override on a case-by-case basis. But if you dislike the idea of a global switch, I can also live with the annotation-driven extension only or any of the other approaches I suggested.

> It does not have to be `assert` at all, maybe we could use something better to indicate that the method we are calling provides its own diagnostics.

Yes, see above. It would be fantastic if assert + parameter would use power-assert output but the user would still have the ability to indicate she does not want it in certain cases.

@leonard84, to me is looks as though we are talking "past each other". Most of the issues you keep mentioning I have already addressed in my previous suggestions. I am really trying to be constructive here. Please tell me if you need more input. :-)

**Comment by timyates** [comment]
Was there a flag added to stop this (or power asserts in general)?  We have a test with thousands of objects being serialised through a mock and we check that the method was called with `{ it.size() == thousands }`... 

Obviously this blows up the error report somewhat 😬   Passing the mock conditional to an external private method doesn't hide it, as it shows the method call parameters in the power assert

I guess this isn't the place for this, but I was just wondering... Ta 😄
