### ISSUE TITLE
Improve failure output for Set comparison

### ISSUE THREAD

**Issue by masooh** [spockframework/spock#924]
When two sets are compared I would like to see the mutual exclusive values in the output. See new lines 'excl: ...'
```
Condition not satisfied:

oneSet == anotherSet
|      |  |
|      |  [3, 6, 4, 5]
|      |  excl: [6]
|      false
[4, 3, 1, 5, 2]
excl: [1,2]
```

Used sample feature:
```groovy
def "sets are equal"() {
    given:
    Set oneSet = [4,3,1,5,1,4,2]
    Set anotherSet = [3,6,4,3,5]

    expect:
    oneSet == anotherSet
}
```

**Comment by masooh** [comment]
Here's another approach for rendering the differences (like in String comparison):

```
oneSet == anotherSet
|      |  |
|      |  [3, 6, 4, 5]
|      false
|      3 differences (2 only in actual, 1 only in expected)
|      [(1),(2),3,4,5,(-)]
|      [(-),(-),3,4,5,(6)]
[4, 3, 1, 5, 2]
```

This would require to sort the sets for rendering.

**Comment by leonard84** [comment]
Interesting suggestion, another possibility could be:
```
oneSet == anotherSet
|      |  |
|      |  [3, 6, 4, 5]
|      false
|      3 differences (2 missing, 1 extra)
|      missing: 1, 2
|      extra: 6
[4, 3, 1, 5, 2]
```

The relevant code is located here `org.spockframework.runtime.ExpressionInfoValueRenderer#doRenderValue`.

**Comment by tylerbenson** [comment]
💯 This would be awesome!  Could potentially be useful for other types of collections too (lists and maps).

**Comment by leonard84** [comment]
@tylerbenson lists and maps will are more difficult, since order or values are relevant as well.
