### ISSUE TITLE
@Unroll is not working in maven test with Spock 1.2 and Groovy 2.5

### ISSUE THREAD

**Issue by pavelber** [spockframework/spock#945]
We switched to Java 11 and we figured out that we need upgrade Spock to 1.2 and Groovy to 2.5, otherwise tests are not running on Java 11

But now, with the latest Spock, maven counts each @Unroll test as a single test and not according to the number of different parameters.

Java 11, Groovy 2.5.3, Spock 1.2, Maven 3.5.4

**Comment by oshai** [comment]
I think this is an issue with groovy 2.5. when I downgraded to 2.4.16 the issue was solved.

**Comment by szpak** [comment]
Guys, please provide [SSCCE/MWE](https://en.wikipedia.org/wiki/Minimal_working_example).

**Comment by oshai** [comment]
I checked it with this library (actually a fork we have): https://github.com/outbrain/prometheus-client
When I upgraded spok to 1.2 and groovy to 2.5.5 there were fewer tests reported. when I reverted back to 2.4.16 I saw back all tests reported.

**Comment by leonard84** [comment]
Try Spock-1.3

**Comment by fabiominelli** [comment]
I am seeing what might be the same issue when passing from Groovy 2.4.7/Spock 1.2 to Groovy 2.5.8/Spock 1.3:

- Methods annotated with @Unroll are executed by Surefire but not included in test total count, neither in the console output nor in generated XML test reports (if executing @Unroll tests only, surefire says "Tests run: 0, Failures: 0, Errors: 0, Skipped: 0")

- Implementing a Spock IRunListener, I can see that the events beforeFeature, beforeIteration, afterIteration and afterFeature are all correctly invoked

I am using Maven 3.6.1 and Surefire plugin 2.22.2

**Comment by esmiralhaibm** [comment]
any news on this issue?

**Comment by Vampire** [comment]
I'd guess this is soon obsolete, as Spock 2.0 is no longer based on JUnit 4, but JUnit platform (JUnit 5) and there it is built-in that you can dynamically add tests during test execution. So I'd expect that there should not be a problem then. You could try with Spock 2.0-M2, but it will probably increase your test count, as now all tests are unrolled by default. (while the naming is not yet properly implemented and there is no way to rollup yet, but it is in the works)
