### ISSUE TITLE
Allow assigning to @Shared fields in then: block

### ISSUE THREAD

**Issue by chrylis** [spockframework/spock#946]
I am writing some `@Stepwise` Geb specs (testing whole Web workflows), and as part of the tests I want to save values obtained in feature method N for use in feature method N+1. The most straightforward way to do this is to assign the values to an `@Shared` field, but `expect/then` blocks do not permit any assignments except initialization.

I suggest that it would make sense to be able to assign in an assertion block under these conditions:

- the assignment is to a field/property on this class
- the field is annotated with `@Shared`
- (maybe) the class is annotated with `@Stepwise`

I would also be interested if there's another proposal for an idiom that accomplishes this same task, but the workarounds I tried (such as using inline closures) didn't do what I needed.

**Comment by rtretyak** [comment]
The quickest workaround I can think of is just to call an auto-generated setter:
```
@Shared def myVar
def test() {
  expect:
  setMyVar("myValue")
  myVar == "myValue"
}
```

You should agree that this is not a common case. Often this feature prevents you from accidentally putting `=` instead of `==`. While spock users don't have to explicitly put an `assert` keyword, such mistake can slip through unnoticed

**Comment by leonard84** [comment]
Yes, assignments (other than to a new variable) in blocks with implicit assertions are forbidden for the expressed purpose of preventing the common mistake of forgetting one `=` for an equality check, and this will not be changed.

What you can do however is to (ab)use the `cleanup` block to set you shared vars, or do it in the `when` block before.
