### ISSUE TITLE
IllegalAccessError & NoClassDefFoundError when using spock with groovy 2.5.3 and jdk 11

### ISSUE THREAD

**Issue by visha-r** [spockframework/spock#948]
# Issue description
After upgrading to Java 11, running spock (1.2-groovy-2.5) with groovy 2.5.3 fail some tests with the following errors:

java.lang.IllegalAccessError: Update to static final field com.abc.trial.InformationBuilder.$const$0 attempted from a different method (__$swapInit) than the initializer method <clinit> 

	at java.base/java.lang.Class.forName(Class.java:398)
        at com.abc.trial.InformationBuilderTest.$spock_initializeFields
------------------------------------------------------------------------------------------------------
java.lang.NoClassDefFoundError: Could not initialize class com.abc.trial.InformationBuilder

	at java.base/java.lang.Class.forName(Class.java:398)
	at com.abc.trial.InformationBuilderTest.$spock_initializeFields

# How to reproduce

Setting double value causes IllegalAccessError error. E.g. object.setMyDouble(1.11)
Setting long to any value with more than 10 digits throws IllegalAccessError E.g. object.setMyLong(10000000001) throws error while  object.setMyLong(1000000000) works good.

# Additional Environment information

## Java/JDK
jdk-11.0.1

## Groovy version
2.5.3

### Apache Maven
3.5.2

## Operating System
Mac

## IDE
IntelliJ

### Apache Maven
    <dependency>
      <groupId>org.spockframework</groupId>
      <artifactId>spock-core</artifactId>
      <version>1.2-groovy-2.5</version>
    </dependency>

**Comment by leonard84** [comment]
Same root cause as in #911 so close it
