### ISSUE TITLE
GroovyCastException while two tests share same variable name and data pipe is used

### ISSUE THREAD

**Issue by vtajzich** [spockframework/spock#957]
# Issue description

When two tests share variable name and second test use data pipe to feed variable with different values, then GroovyCastException is thrown.

```
def "should consume 1"() {

        given:

        consumer = new Consumer()

        NullPointerException exception = new NullPointerException('test NPE')

        when:

        boolean result = consumer.consume(exception)

        then:

        !result
    }

    def "should consume 2"() {


        given:

        consumer = new Consumer()

        when:

        boolean result = consumer.consume(exception)

        then:

        !result

        where:

        exception << [new RuntimeException(), new AlreadyBoundException()]
    }
```

Variable exception is casted to NullPointerException type even it shouldn't be. With Groovy 2.4.x and Spock 1.1 it works correctly.

In order to reproduce the issue take a look on github repository.

## Link to a gist or similar (optional)

https://github.com/vtajzich/spock-groovy-cast-exception

# Additional Environment information

## Java/JDK
1.8

## Groovy version
2.5.x

### Gradle
4.10.2

## Operating System
Mac, Windows

## IDE
IntelliJ Idea

### Gradle
compile group: 'org.codehaus.groovy', name: 'groovy', version: '2.5.4'
testCompile group: 'org.spockframework', name: 'spock-core', version: '1.2-groovy-2.5'

**Comment by leonard84** [comment]
Thanks for reporting this issue, this duplicates #880 please add any comments there.
