### ISSUE TITLE
Unroll parameterized features/tests by default - feature proposal

### ISSUE THREAD

**Issue by szpak** [spockframework/spock#967]
## Description

In most of the cases parameterized features/tests are more readable while unrolled. Even if the `@Unroll` annotation is placed at the specification/class level it's still boiler plate code to write. Following the common use cases it would be more natural to unroll all parameterized tests by default (with an option to disable it on per test or class basis).

## Possible implementation

Starting with Spock 2.0 all parameterized tests would be unrolled by default. There would be still an ability to provide custom messages with the `@Unroll("...")` annotation. If desired the unrolling would be possible to disable for a test or the whole class with a dedicated annotation - `@Roll`).

## Solutions for 1.x

There is the [spock-global-unroll](https://github.com/szpak/spock-global-unroll) (global) extension which once added to classpath automatically unroll all parameterized tests in the whole projects. There is no need to add any extra code or annotation - all (parameter-less) `@Unroll` annotations can be removed.

It can be used as a preparation for Spock 2.0 with similar behavior available out-of-box.

## Open topics

Feel free to leave comment in that issue.

**Comment by ifqthenp** [comment]
Personally, I do not use `@Unroll` every time I run parametrized tests. Actually, last time I used `@Unroll` feature long time ago only to show to my colleague how cool Spock framework is.

I do not need to see detailed output for every test as long as tests run green. But when tests fail, Spock provides enough details to find failed test quickly even without `@Unroll` feature. For those willing to use `@Unroll` for every parametrized test I would recommend create some sort of live template or snippet in their favourite IDE or text editor.

My suggestion is to leave it as it is, there's no need to introduce breaking change for that.

**Comment by leonard84** [comment]
Unrolled tests will be the default for spock 2.0, I'm not sure if we will provide an `@Rollup` extension.

**Comment by ddimtirov** [comment]
In some of our PBT tests we run thousands of simple tests per method. Without `@Rollup` this would overwhelm the reporting infrastructure. 

In particular IDEA's test reporting window becomes unresponsive when the number of tests goes into tens of thousands. Other tools may have the same issue too.

**Comment by szpak** [comment]
It's implemented in Spock 2.0-M3 (#1101) with a possibility to disable globally or rolling up on demand. Closing.
