### ISSUE TITLE
Extension to override feature methods in parent specifications

### ISSUE THREAD

**Issue by musketyr** [spockframework/spock#969]
# Issue description
There is currently no simple way how to override feature method in a subclass. Both the feature method from subclass and the method from superclass are executed.

## Link to a gist or similar
You can see the implemented extension in following Gist. I don't know which branch is ideal to address:
https://gist.github.com/musketyr/3aa85f2cb51dc13f001f05b4140353e7

### Gradle/Grails
    compile 'org.spockframework:spock-core:1.2-groovy-2.5'

**Comment by leonard84** [comment]
@musketyr you can publish your extensension, then we can link to it https://github.com/spockframework/spock/wiki/Third-Party-Extensions

**Comment by musketyr** [comment]
ok done.
