### ISSUE TITLE
Argument capture and return value in 1.3-RC1

### ISSUE THREAD

**Issue by henrik242** [spockframework/spock#970]
In the [1.3-RC1 release docs](https://github.com/spockframework/spock/blob/master/docs/release_notes.adoc#code-argument-constraints-are-treated-as-implicit-assertions), this breaking change is announced:
```
def extern = null
1 * mock.foo( { extern = it; it.size() > 0 })  // old
1 * mock.foo( { it.size() > 0 }) >> { extern = it[0] } // new
```

What if I have ...
```
def extern = null
def bar = new Bar()
1 * mock.foo({ extern = it }) >> bar
```
... how does that translate to the new format?

/cc: @leonard84

**Comment by leonard84** [comment]
Just return `bar` from the closure

```
def extern = null
def bar = new Bar()
1 * mock.foo(_) >> { extern = it[0] ; bar }
```
