### ISSUE TITLE
@SpringSpy doesn't work

### ISSUE THREAD

**Issue by pchudzik** [spockframework/spock#971]
# Issue description
@SpringSpy annotations doesn't work when verifying interactions with spies.

Spy is generated and proxied properly: TwoRepository$SpockMock$1035038003$$EnhancerBySpringCGLIB$$11ccc6b0

Looks like a naming problem or something?
```
Too few invocations for:
1 * twoRepository.getTwo()   (0 invocations)
Unmatched invocations (ordered by similarity):
1 * TwoRepository.getTwo()
```

# How to reproduce
Test case: https://github.com/blog-pchudzik-examples/blog-example-spock-spring/blob/master/src/test/groovy/com/pchudzik/springmock/samples/springboot2/spock/SpockSamplesApplicationTest.groovy
```
@SpringBootTest(classes = Springboot2Application)
class SpockSamplesApplicationTest extends Specification {
    @SpringBean
    AddOne addOneTranslator = Mock()

    @SpringSpy
    TwoRepository twoRepository

    @Autowired
    MyService myService

    def "should calculate values"() {
        given:
        final inputA = 1
        final translatedA = 10
        final expectedResult = translatedA + TWO
        addOneTranslator.addOne(inputA) >> translatedA

        when:
        final result = myService.calculate(inputA)

        then:
        1 * twoRepository.getTwo()
        result == expectedResult
    }
}
```

and inside MyService (https://github.com/blog-pchudzik-examples/blog-example-spock-spring/tree/master/src/main/java/com/pchudzik/springmock/samples/springboot2/spock):
```
public int calculate(int a) {
        return addOne.addOne(a) + twoRepository.getTwo();
    }
```

Results:
```
Too few invocations for:

1 * twoRepository.getTwo()   (0 invocations)

Unmatched invocations (ordered by similarity):

1 * TwoRepository.getTwo()
```

Ignore package names. That's something I hacked quickly just to test @SpringSpy and @SpringBean annotations

Complete project https://github.com/blog-pchudzik-examples/blog-example-spock-spring

# Additional Environment information
Complete build log: https://travis-ci.org/blog-pchudzik-examples/blog-example-spock-spring/builds/488647237

## Java/JDK
```
$ java -Xmx32m -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
$ javac -J-Xmx32m -version
javac 1.8.0_151
```

## Groovy version
2.5
```
testCompile('org.spockframework:spock-core:1.2-groovy-2.5')
testCompile('org.spockframework:spock-spring:1.2-groovy-2.5')
```

### Gradle
`gradle -version`
4.8.1

**Comment by leonard84** [comment]
@pchudzik could you try updating to 1.3 that release has increased debugging output for unmatched invocations.

**Comment by pchudzik** [comment]
After upgrade to:
```
testCompile('org.spockframework:spock-core:1.3-groovy-2.5')
testCompile('org.spockframework:spock-spring:1.3-groovy-2.5')
```

Test output is as follows:
```

Too few invocations for:

1 * twoRepository.getTwo()   (0 invocations)

Unmatched invocations (ordered by similarity):

1 * TwoRepository.getTwo()
instance == target
|        |  |
|        |  com.pchudzik.springmock.samples.springboot2.spock.TwoRepository$SpockMock$1366440991@57c6feea
|        false
|        0 differences (100% similarity)
|        com.pchudzik.springmock.samples.springboot2.spock.TwoRepository$SpockMock$1366440991@57c6feea
|        com.pchudzik.springmock.samples.springboot2.spock.TwoRepository$SpockMock$1366440991@57c6feea
com.pchudzik.springmock.samples.springboot2.spock.TwoRepository$SpockMock$1366440991@57c6feea




	at org.spockframework.mock.runtime.InteractionScope.verifyInteractions(InteractionScope.java:98)
	at org.spockframework.mock.runtime.MockController.leaveScope(MockController.java:77)
	at com.pchudzik.springmock.samples.springboot2.spock.SpockSamplesApplicationTest.should calculate values(SpockSamplesApplicationTest.groovy:31)
```

https://travis-ci.org/blog-pchudzik-examples/blog-example-spock-spring/builds/528658547

What's the difference between twoRepository.getTwo() and TwoRepository.getTwo()?

**Comment by k0staa** [comment]
I have a similar problem and I analyzed it for a while and it looks like that in the `TargetConstraint` class the `isSatisfiedBy` method returns false. The problem is that the comparison takes place in the `MockObject` class as follows: 
```
boolean match = global? matchGlobal (target): instance == target;
```

and unfortunately it does not pass because the bean wrapped by Spring is compared with pure mock instance.

**Comment by leonard84** [comment]
This also asked on [Stackoverflow](https://stackoverflow.com/questions/60181621/how-to-use-spock-springspy-with-a-jparepository)

The problem is, that there is no class for Spock to spy on, only an interface for which spring-data will create a proxy. In short you can't spy on a Spring Data Repository, but you can create a mock.

**Comment by unxia** [comment]
but how to use spock spring to verify  cached method, which should not called twice

**Comment by leonard84** [comment]
@unxia https://github.com/spockframework/spock/blob/master/spock-spring/src/test/groovy/org/spockframework/spring/mock/imported/SpringSpyWithAopProxyTests.groovy but this should probably be a question on Stackoverflow and not hijacking a closed thread.

**Comment by javiersolisguzman** [comment]
> This was also asked on [Stackoverflow](https://stackoverflow.com/questions/60181621/how-to-use-spock-springspy-with-a-jparepository)
> 
> The problem is, that there is no class for Spock to spy on, only an interface for which spring-data will create a proxy. In short you can't spy on a Spring Data Repository, but you can create a mock.

In the comments, they said that you can use @UnwrapAopProxy, it works for me, but my bean was no a Repository

```
    @SpringSpy
    @UnwrapAopProxy
    var MyService myService
```

**Comment by javiersolisguzman** [comment]
You could try with this, to avoid _

https://github.com/spockframework/spock/issues/971#issuecomment-1706039103
