### ISSUE TITLE
IntelliJ should show "<Click to see difference>" in stack trace

### ISSUE THREAD

**Issue by zatziky** [spockframework/spock#972]
# Issue description
Jetbrains IDEs provide a neat way how to compare results of assertEquals( ) in a very human readable form.

![image](https://user-images.githubusercontent.com/2794365/52325822-c5d81380-29e6-11e9-91e5-a8ef1f74b8a3.png)

We are using Intellij IDE, Grails/Gradle project and Spock. We have big request which are hard to compare. See for yourself:
![image](https://user-images.githubusercontent.com/2794365/52325851-e2744b80-29e6-11e9-8423-aaa6ccb7d350.png)

Adding the Jetbrains "click to see difference" hyperlink would really give speed up the testing.

**Comment by leonard84** [comment]
Spock supports this already, if you are using the spock native comparison, e.g. `'foo' == 'bar'`

**Comment by leonard84** [comment]
@vanta yes 
<img width="877" alt="image" src="https://user-images.githubusercontent.com/1151511/133606169-dbbe1c61-35be-4c8e-aec8-848659808835.png">
