### ISSUE TITLE
Code constraint in interactions verifyAll/with

### ISSUE THREAD

**Issue by michalgebauer** [spockframework/spock#973]
# Issue description
Code constraint in interactions is not working as expected

taken from documentation:
`1 * list.add({
  verifyAll(it, Person) {
    firstname == 'William'
    lastname == 'Kirk'
    age == 45
  }
})`

problem is (my assumption), that if there is no assertion error verifyAll/with returns void, which in turn means the result is false and method invocation is not counted.

my workaround (return true):
`
1 * list.add({
  verifyAll(it, Person) {
    firstname == 'William'
    lastname == 'Kirk'
    age == 45
  }
  true
})
`

# How to reproduce
described above

## Link to a gist or similar (optional)

# Additional Environment information
spock version: 1.2-groovy-2.4

## Java/JDK
1.8

## Groovy version
2.4.15

`groovy -version`

### Gradle
`gradle -version`

### Apache Maven
3.3.9

## Operating System
Windows

## IDE
> IntelliJ

**Comment by leonard84** [comment]
This is implemented in spock-1.3-RC1
