### ISSUE TITLE
Unroll with a groovy compilation error excludes the whole test

### ISSUE THREAD

**Issue by FatCash** [spockframework/spock#976]
Having the @Unroll annotation on a test which has a groovy compilation error in where clause results in the test being excluded and **not marked as failed**. Really dangerous! :small_red_triangle:

Bug appears (ie as if test never existed):
* IntelliJ: Running the test by package, even if only one class with one test in that package.
* IntelliJ: Running all unit tests (probably same as above)
* Gradle: Always, even if you -Ptest.include only a single class/test

Bug does not appear (ie test is marked as failed):
* IntelliJ: Running the particular test (right-clicking green arrow on right -> run)
* IntelliJ: Running the test by running all tests in class (by green arrow as above)
* IntelliJ: Removing the @Unroll

Imagine, you've done some refactoring and introduced compilation errors in the tests.
You run all your groovy tests in IntelliJ and all is false-positively green.
You run gradle tests and all is green. You run your Jenkins pipeline and all is green.

**Update: I found that this bug only appears with junit-jupiter all versions** 
Perhaps the exception thrown by spock is swallowed silently by jupiter

# How to reproduce
Add a java class that you want to test, say User.java in a package.
Create a test for User.java annotated with @Unroll
Initialise the User in the test wrongly by constructor in where clause
Run the tests by package
User.java
```
public class User {

    public String id;

    public User(String id) {
        this.id = id;
    }
}
```
UserTest.groovy
```
import spock.lang.Specification
import spock.lang.Unroll

class UserTest extends Specification {

    @Unroll
    def "testRevealingUnrollBug"() {
        when:
        def nothing = "here"

        then:
        user.id == user_id

        where:
        user                    || user_id
        new User("id")          || "id"
        new User("id", "extra") || "id"
    }

}
```
## Java/JDK
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
(Tried java jdk1.8.0_162 as well)

## Groovy version
2.5.6

### Gradle
Gradle 4.10.3

## IDE
IntelliJ 2018.3.4

## Spock version
spock-core:1.2-groovy-2.5
spock-spring:1.2-groovy-2.5

**Comment by lsikora** [comment]
Hi. I have encountered a similar issue. Please see https://github.com/lsikora/spock-unroll-junit5. 
When running Spock atop JUnit 4 all test cases are visible. When running Spock atop JUnit 5 Vintage engine. Completely different things are displayed in IntelliJ test tree and output window. There is also a difference when using embedded IntelliJ test runner and running Gradle task. This seems related to #617.

**Comment by leonard84** [comment]
@marcphilipp correct me if I'm wrong, I noticed something similar in the spock-2.0 branch. My guess is that any exceptions in the discovery phase of jupiter will simply exclude the whole class.

**Comment by marcphilipp** [comment]
That sounds bad. Could you please raise an issue in the junit5 repo?

**Comment by marcphilipp** [comment]
Nevermind, I raised an issue myself: https://github.com/junit-team/junit5/issues/1845.

**Comment by marcphilipp** [comment]
This issue will be fixed in JUnit Vintage 5.4.2.

**Comment by pkurczyna** [comment]
I have the same issue for Junit4, does anybody know the fix around it?

**Comment by pkurczyna** [comment]
@FatCash I guess my problem is the same as yours, have you managed to fix that?

**Comment by Vampire** [comment]
He wrote it only appears with JUnit Jupiter, so I guess he meant Vintage, as Spock tests do not run on Jupiter. That means it does not happen for him with JUnit 4. I suggest you open a separate issue with a minimal reproducer project.

**Comment by FatCash** [comment]
No, we actually removed all Unroll annotations in that project because we haven't bump the test dependencies there yet 😳. Still on, where it does not work:
"org.junit:junit-bom:5.4.2"
"org.spockframework:spock-bom:1.3-groovy-2.5"
Try bumping everything to latest version and it should work as described in the fix by @marcphilipp
