### ISSUE TITLE
the task in 'stop' method of GlobalExtension does not complete when the jvm shutdown.

### ISSUE THREAD

**Issue by WenRui13** [spockframework/spock#977]
# Issue description
 I custom GlobalExtension to collect my test reslut and push to our report platform, but the 'stop' method in my extension does not work correctly, the task in it does not run completely then the JVM shutdown and spockframework stoped.

# How to reproduce
```java
    @Override
    public void stop() {
        //上报天书
//        ExecutorService exec = Executors.newFixedThreadPool(1);
//        Future<String> future = exec.submit(() -> testResultCollector.push2platfrom());
//        try {
//            String result = future.get(10, TimeUnit.MINUTES);
//            System.out.println(result);
//        } catch (InterruptedException e) {
//            e.printStackTrace();
//        } catch (ExecutionException e) {
//            e.printStackTrace();
//        } catch (TimeoutException e) {
//            e.printStackTrace();
//        } finally {
//            exec.shutdown();
//        }


//        Runtime.getRuntime().addShutdownHook(new Thread(() -> testResultCollector.push2platfrom()));


        testResultCollector.push2platfrom();
    }
```

# Additional Environment information
> Version of your build tool(if used), Java, Groovy, IDE, OS etc

## Java/JDK
`jdk1.8`

## versions
```xml
 <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.4.10</version>
        </dependency>

        <dependency>
            <groupId>org.spockframework</groupId>
            <artifactId>spock-core</artifactId>
            <version>1.1-groovy-2.4</version>
            <!--<scope>test</scope>-->
        </dependency>


        <dependency>
            <groupId>com.athaydes</groupId>
            <artifactId>spock-reports</artifactId>
            <version>1.6.1</version>
        </dependency>


```

**Comment by rtretyak** [comment]
This looks related to my problem in #966

**Comment by WenRui13** [comment]
@rtretyak dig into the source code to see what happened. I think that may be relate to thread.  how complicated it is.

**Comment by WenRui13** [comment]
@rtretyak problem may occur in this code，the 'stop' method's invoke chain is bellow:
![image](https://user-images.githubusercontent.com/6370420/53695596-71169580-3df8-11e9-82db-f0de84f39a06.png)

**Comment by leonard84** [comment]
Yeah in 1.x this method is best effort and may not be called at all or the jvm may terminate before completion if you try to do some long running stuff. The reason is that the JUnit 4 Framework does not offer a hook for Spock, so we are using a ShutdownHook as a workaround, with all its limitations.

**Comment by WenRui13** [comment]
@leonard84 how to solve this problem ? tks !

**Comment by leonard84** [comment]
This is fixed in Spock 2.x, but beware that the stop method can be called more than once.
