### ISSUE TITLE
how to mock the parent class method

### ISSUE THREAD

**Issue by ThinkCats** [spockframework/spock#982]
# Issue description
I can't mock the parent class method

# How to reproduce
```java
class Bar {

  def method1(parm1){
      //Method actions
  }
}


class Foo extends Bar {

   def method2(param1, param2) {          
       //Method actions
       super.method1(param1)
   }
}

```
I want to mock 'super.method1(param1)', but I dont know how to do it. 

## Link to a gist or similar (optional)
https://stackoverflow.com/questions/24481973/mocking-a-superclass-in-spock

Thanks a lot.

**Comment by leonard84** [comment]
Hi, as you have already provided the SO link check out the answer here https://stackoverflow.com/a/24483664/2145769

**Comment by ThinkCats** [comment]
> Hi, as you have already provided the SO link check out the answer here https://stackoverflow.com/a/24483664/2145769

Thanks, but that is not what I want . 
I am trying to test `Foo` ,  and this is  my test:

```java
def "testFoo"() {
given:
def param1 = "hello"
def param2 = "world"
//here, I want to mock  'method1(parm1)' of the Bar class
when:
def foo = new Foo()
then:
foo.method2(param1,param2) == 'result'
}
```
So, how to mock 'method1(parm1)' ? Thanks for any help .

**Comment by leonard84** [comment]
```groovy
  def "testFoo"() {
    given:
    def foo = Spy(Foo)
    def param1 = "hello"
    def param2 = "world"

    when:
    def result = foo.method2(param1,param2)

    then:
    result == 'result'
    1 * foo.'super$2$method1'(param1) >> 'result'
 }
```
works for me. However, this type of mocking should be avoided if possible.

**Comment by zhangfanghui8** [comment]
> ```groovy
>   def "testFoo"() {
>     given:
>     def foo = Spy(Foo)
>     def param1 = "hello"
>     def param2 = "world"
> 
>     when:
>     def result = foo.method2(param1,param2)
> 
>     then:
>     result == 'result'
>     1 * foo.'super$2$method1'(param1) >> 'result'
>  }
> ```
> 
> works for me. However, this type of mocking should be avoided if possible.

this way can work?

什么意思

what do you mean about foo.'super$2$method1'

**Comment by zhangfanghui8** [comment]
> ```groovy
>   def "testFoo"() {
>     given:
>     def foo = Spy(Foo)
>     def param1 = "hello"
>     def param2 = "world"
> 
>     when:
>     def result = foo.method2(param1,param2)
> 
>     then:
>     result == 'result'
>     1 * foo.'super$2$method1'(param1) >> 'result'
>  }
> ```
> 
> works for me. However, this type of mocking should be avoided if possible.


what do you mean about foo.'super$2$method1'
