### ISSUE TITLE
spring test @Sql for setupSpec() not work

### ISSUE THREAD

**Issue by ThoreauZZ** [spockframework/spock#983]
## versions
* spock-spring: 1.3-groovy-2.4.jar
* spring-boot: 2.0.1
* h2: 1.4.119

## test db
```
@Import([UserDao.class])
@MybatisTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
class UserDaoSpec extends Specification {

    @Autowired
    private UserDao userDao

    @Sql(value = "classpath:init-db.sql")
    def setupSpec() {

    }

    def "create user"() {
        given: "give a user"
        def user = new User(id: 1, nick: "df")

        when:
        userDao.createUser(user)

        then:
        noExceptionThrown()
    }
}
```
> failed

```
@Sql(value = "classpath:init-db.sql")
    def "create user"() {
        given: "give a user"
        def user = new User(id: 1, nick: "df")

        when:
        userDao.createUser(user)

        then:
        noExceptionThrown()
    }
```
> work, @Sql must on test method

**Comment by rtretyak** [comment]
Unfortunately Spock's setupSpec (as well as JUnit's `@BeforeSpec`) is run before Spring injections happen. See this thread https://github.com/spockframework/spock/issues/76.

**Comment by ThoreauZZ** [comment]
> Unfortunately Spock's setupSpec (as well as JUnit's `@BeforeSpec`) is run before Spring injections happen. See this thread #76.

Thanks，this case , I can put schma.sql to test/resources dir

**Comment by leonard84** [comment]
@ThoreauZZ as you have a working solution can you close this?
