### ISSUE TITLE
Stubbing  with Data Tables not work ?

### ISSUE THREAD

**Issue by TarikChrouki** [spockframework/spock#985]
# Issue description
Test faild with Stubbing with Data tables

# How to reproduce
Run exemple below 

```java
class Publisher {
    def subscriber

    def send(event) {
        subscriber.receive(event)
    }
}

interface Subscriber {
    def receive(event)
}

 class PublisherSpec extends Specification {


    def "Stubbing"() {

        given:
        def pub = new Publisher()
        pub.subscriber = Mock(Subscriber)
        pub.subscriber.receive(_) >>> ["ok", "ko"]

        when:
        def result = pub.send("event1")

        then:
        result == expected

        where:
        expected | msg
        "ok"     | "event1"
        "ko"     | "event2"
    }
}
```

# Result 
```
Condition not satisfied:

result == expected
|      |  |
ok     |  ko
       false
       2 differences (0% similarity)
       (o)k(-)
       (-)k(o)
```

**Comment by robmorning** [comment]
Think the 'given' block is executed once per test (in where block) .. So each invocation in where block is effectively returning first element in list on each call  ..  

If you change .. 

    def "Stubbing"() {

        given:
        def pub = new Publisher()
        println "new publisher created  .."
        pub.subscriber = Mock(Subscriber)
        pub.subscriber.receive(_) >>> ["ok", "ko"]

        when:
        def result = pub.send("event1")

        then:
        result == expected

        where:
        expected | msg
        "ok"     | "event1"
        "ko"     | "event2"
    }

You will see
 
new publisher .. 
new publisher .. 

Condition not satisfied:

result == expected
|      |  |
ok     |  ko
       false
       2 differences (0% similarity)
       (o)k(-)
       (-)k(o)

So you are redefining the subscriber.receive on each iteration ..

**Comment by leonard84** [comment]
@robmorning is correct, this is not a bug.
