### ISSUE TITLE
Enhancement: alternatives for "then" label: "still" and "now"

### ISSUE THREAD

**Issue by pauxus** [spockframework/spock#995]
# Issue description
In more complex specifications, I often encounter situations where a condition is first checked multiple times and finally changes to something else:

```groovy
when:
List<String> names = []

then:
names.isEmpty()

when:
addValidNames(names, "invalid")

then: "still"
names.isEmpty()

when:
addValidNames(names, "valid")

then: "now"
"valid" in names
```

I think this could be easily made more readable by allowing some more synonyms for "then" or "and" in "then" scope:

```groovy
when:
List<String> names = []

then:
names.isEmpty()

when:
addValidNames(names, "invalid")

still:
names.isEmpty()

when:
addValidNames(names, "valid")

now:
"valid" in names
```

One could even add "butWhen" as synonym to "when":

```groovy
when:
List<String> names = []

then:
names.isEmpty()

when:
addValidNames(names, "invalid")

still:
names.isEmpty()

butWhen:
addValidNames(names, "valid")

now:
"valid" in names
```

**Comment by rtretyak** [comment]
You are free to add string descriptions to each block, this is so easy. Do you really find 
```
when:
addValidNames(names, "invalid")

still:
names.isEmpty()
```
to be more readable than
```
when: "try adding invalid name"
addValidNames(names, "invalid")

then: "names list is still empty"
names.isEmpty()
```
?
The `still` and `now` blocks look completely misleading to me. I strongly disagree that this should be part of the core framework, since these literals are not related to classic given-when-then technique. GWT approach is understood by the majority of people, while these new blocks promote some unconventional design for a test case. 
Any other opinions?

**Comment by leonard84** [comment]
I agree with @rtretyak having a fixed set of labels makes it easy for everybody to understand instead of having to guess what an alias means. Use descriptions if you want to tell the story.

**Comment by pauxus** [comment]
Ok, point taken. I am not that big fan of descriptions, because IMHO as with any documentation they tend to become stale more often than actual semantics.

@rtretyak Actually, I do find it more readable, but I see your point. There are already some aliases (and, setup/given), so it seemed a good idea (as said, this scenario comes up quite often), but I agree that it might be confusing.

Perhaps a better approach would be to allow project specific custom aliases to existing blocks, either defined by configuration file / system properties or by an extension. This should actually be easy to implement. I will open another issue for that one and have a try at them implementation.

Thanks for your input.
